ALTER TABLE "business_experiment_assignments" DROP CONSTRAINT "business_experiment_assignments_content_check";--> statement-breakpoint
ALTER TABLE "business_experiment_completions" DROP CONSTRAINT "business_experiment_completions_content_check";--> statement-breakpoint
ALTER TABLE "business_experiment_executions" DROP CONSTRAINT "business_experiment_executions_content_check";--> statement-breakpoint
ALTER TABLE "business_experiment_exposures" DROP CONSTRAINT "business_experiment_exposures_content_check";--> statement-breakpoint
ALTER TABLE "business_experiment_executions" DROP CONSTRAINT "business_experiment_executions_review_fk";
--> statement-breakpoint
ALTER TABLE "business_experiment_transitions" ADD CONSTRAINT "business_experiment_transitions_tenant_uq" UNIQUE("company_id","experiment_id","version_id","id");
--> statement-breakpoint
ALTER TABLE "business_experiment_executions" ADD CONSTRAINT "business_experiment_executions_review_fk" FOREIGN KEY ("company_id","experiment_id","version_id","review_transition_id") REFERENCES "public"."business_experiment_transitions"("company_id","experiment_id","version_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "business_experiment_assignments" ADD CONSTRAINT "business_experiment_assignments_content_check" CHECK ("business_experiment_assignments"."arm" in ('control','treatment') and ("business_experiment_assignments"."unit_type"='issue' and "business_experiment_assignments"."issue_id" is not null and "business_experiment_assignments"."issue_id"="business_experiment_assignments"."unit_id" and "business_experiment_assignments"."project_id" is null or "business_experiment_assignments"."unit_type"='project' and "business_experiment_assignments"."project_id" is not null and "business_experiment_assignments"."project_id"="business_experiment_assignments"."unit_id" and "business_experiment_assignments"."issue_id" is null) and "business_experiment_assignments"."source_hash" ~ '^[0-9a-f]{64}$' and "business_experiment_assignments"."receipt_hash" ~ '^[0-9a-f]{64}$' and "business_experiment_assignments"."signature" ~ '^decision-spec-v1[.][0-9a-f]{64}$' and jsonb_typeof("business_experiment_assignments"."source_snapshot_json")='object' and jsonb_typeof("business_experiment_assignments"."invariant_receipts_json")='array');--> statement-breakpoint
ALTER TABLE "business_experiment_completions" ADD CONSTRAINT "business_experiment_completions_content_check" CHECK ("business_experiment_completions"."reason" in ('fixed_horizon','emergency_safety_stop','cancelled') and jsonb_typeof("business_experiment_completions"."concurrent_change_review_json")='object' and "business_experiment_completions"."concurrent_change_review_json"->>'assessment' in ('none_identified','material_or_unknown') and length(btrim("business_experiment_completions"."concurrent_change_review_json"->>'rationale')) between 10 and 2000 and length(btrim("business_experiment_completions"."rationale")) between 10 and 2000 and "business_experiment_completions"."receipt_hash" ~ '^[0-9a-f]{64}$' and "business_experiment_completions"."signature" ~ '^decision-spec-v1[.][0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "business_experiment_executions" ADD CONSTRAINT "business_experiment_executions_content_check" CHECK ("business_experiment_executions"."mode"='recording_only_human_attested_native_process' and "business_experiment_executions"."assignment_key_fingerprint" ~ '^[0-9a-f]{64}$' and "business_experiment_executions"."receipt_hash" ~ '^[0-9a-f]{64}$' and "business_experiment_executions"."signature" ~ '^decision-spec-v1[.][0-9a-f]{64}$' and length(btrim("business_experiment_executions"."rationale")) between 10 and 2000);--> statement-breakpoint
ALTER TABLE "business_experiment_exposures" ADD CONSTRAINT "business_experiment_exposures_content_check" CHECK ("business_experiment_exposures"."arm" in ('control','treatment') and "business_experiment_exposures"."status" in ('applied','not_applied') and "business_experiment_exposures"."provenance"='human_attestation' and ("business_experiment_exposures"."status"='applied')=("business_experiment_exposures"."asserted_applied_at" is not null) and ("business_experiment_exposures"."asserted_applied_at" is null or "business_experiment_exposures"."asserted_applied_at"<="business_experiment_exposures"."recorded_at") and "business_experiment_exposures"."receipt_hash" ~ '^[0-9a-f]{64}$' and "business_experiment_exposures"."signature" ~ '^decision-spec-v1[.][0-9a-f]{64}$' and length(btrim("business_experiment_exposures"."rationale")) between 10 and 2000);