import { causalClaimDefinitionSchema,type CausalClaimDefinition,type NativeCausalSource,type NativeCausalResult } from "@paperclipai/shared";
import { nativeSha256 } from "../native-runtime/canonical.js";
/** Reuse the exact source-owner-qualified registered result. This provider
 * cannot identify observational designs or invent refutations/telemetry. */
export function evaluateNativeCausalClaim(raw:CausalClaimDefinition,source:NativeCausalSource|null):NativeCausalResult {
  const definition=causalClaimDefinitionSchema.parse(raw),analysis=source?.analysis,result=analysis?.result;
  const assumed=Object.values(definition.assumptions).every(a=>a.status==="assumed");
  const guards=result?.metrics.filter(m=>m.role==="guardrail")??[];
  const output:NativeCausalResult={engineVersion:"aw-native-causal-registered-primary-v1",definitionHash:nativeSha256(definition),inputHash:nativeSha256({sourceHash:source?.sourceHash??null}),status:"inconclusive",evidenceGrade:source?"randomized_experiment":"descriptive_only",stages:["question","human_model_and_assumptions","identification","estimation_or_abstention","robustness","conditional_interpretation"],
    identification:{status:"unsupported",strategy:definition.identificationStrategy,conditions:[]},estimate:null,
    robustness:{assignmentRatio:result?.diagnostics.srm?result.diagnostics.srm.mismatch?"failed":"passed":"unavailable",registeredBaselineBalance:analysis?analysis.qualityGates.baselineBalance?"passed":"failed":"unavailable",completeOutcomeAndExposureReceipts:analysis?analysis.qualityGates.assignmentReceipts&&analysis.qualityGates.exposureReports&&analysis.qualityGates.identityJoins&&analysis.qualityGates.finalOutcomeCapture==="complete"?"passed":"failed":"unavailable",guardrails:guards.length===0?"unavailable":guards.some(g=>g.interpretation==="harm_detected")?"harm_detected":guards.every(g=>g.interpretation==="harm_excluded")?"excluded_within_registered_bounds":"uncertain",assumptions:assumed?"human_assumed":"unknown_or_violated",sensitivity:"unknown",providerRefutations:"not_run"},
    language:"causal_reliance_withheld",executionAuthority:"advisory_only",reasons:[],limitations:["This claim interprets the exact preregistered primary endpoint retrospectively; the causal question/graph is a separately reviewed human model.","Allocation and native outcome receipts do not prove intervention delivery, business impact, absence of interference or complete confounder measurement.","Human exposure and concurrent-change assessments remain attestations. No independent provider refutation or sensitivity analysis has run.","The outcome is native status at one common final capture after the window, not a reconstructed period-end state or verified business/task outcome.","Any support is conditional on the registered randomization, native proxy definition and explicitly stated human assumptions; no execution authority is granted."]};
  if(definition.identificationStrategy!=="registered_randomized_assignment"||!source){output.reasons.push("identification_unsupported_without_qualified_design_and_data");return output;}
  const assignment=definition.graph.nodes.find(n=>n.role==="randomized_assignment")!,outcome=definition.graph.nodes.find(n=>n.role==="outcome")!;
  const reachable=new Set([assignment.key]);for(let i=0;i<definition.graph.nodes.length;i++)for(const e of definition.graph.edges)if(reachable.has(e.from))reachable.add(e.to);
  if(definition.graph.edges.some(e=>e.to===assignment.key)||!reachable.has(outcome.key)){output.reasons.push("human_graph_does_not_admit_randomized_assignment_identification");return output;}
  const reference=definition.experimentEvidence;
  if(!reference||reference.id!==analysis!.id||reference.experimentId!==analysis!.experimentId||reference.versionId!==analysis!.versionId||reference.interpretationId!==source.interpretationId){output.reasons.push("exact_experiment_analysis_interpretation_pin_mismatch");return output;}
  const protocol=source.definition,primary=protocol.primaryMetric;
  if(definition.outcomeMetricId!==primary.metricId||definition.outcomeMetricVersionId!==primary.metricVersionId||definition.horizon.from!==protocol.sampleOrDurationPlan.from||definition.horizon.until!==protocol.sampleOrDurationPlan.until||nativeSha256(definition.population.scope)!==nativeSha256(protocol.scope)||definition.population.unit!==protocol.population.randomizationUnit||definition.estimand.beneficialDirection!==primary.beneficialDirection||definition.estimand.minimumMeaningfulEffect!==primary.minimumMeaningfulEffect){output.reasons.push("claim_does_not_match_exact_registered_primary_estimand_population_and_horizon");return output;}
  if(!assumed){output.identification.status="assumptions_not_admitted";output.reasons.push("human_assumptions_unknown_or_violated");return output;}
  const selected=result!.metrics.find(m=>m.role==="primary"&&m.key===primary.key);
  if(analysis!.currentQualification!=="current"||analysis!.causalAuthority!=="conditional_on_registered_randomization_and_human_attestations"||!result!.numericallyQualified||!selected?.interval||analysis!.qualityGates.finalOutcomeCapture!=="complete"||!analysis!.qualityGates.concurrentReviewAdmitted||output.robustness.assignmentRatio!=="passed"||output.robustness.registeredBaselineBalance!=="passed"||output.robustness.completeOutcomeAndExposureReceipts!=="passed"){output.identification.status="source_not_qualified";output.reasons.push("registered_source_quality_or_current_authority_does_not_admit_estimation");return output;}
  output.identification={status:"conditional_identified",strategy:definition.identificationStrategy,conditions:["Secret-key registered individual randomization and exact native receipt identity.","Complete intention-to-treat primary outcomes under the frozen endpoint/period.","Registered SRM/pretreatment diagnostic gates plus human-assumed interference/measurement/population conditions."]};
  output.estimate={effect:selected.effect,interval:selected.interval,unit:"fraction_difference",estimand:"assignment_intention_to_treat_native_binary_outcome",derivedFromRegisteredAnalysis:true};
  output.language="conditional_assignment_effect_on_native_proxy";
  if(selected.interpretation==="threshold_met"&&result!.status==="pass"&&output.robustness.guardrails==="excluded_within_registered_bounds"){output.status="supported";output.reasons.push("registered_meaningful_primary_and_safety_bounds_conditionally_supported");}
  else if(selected.interpretation==="threshold_not_met"){output.status="refuted";output.reasons.push("registered_minimum_meaningful_primary_benefit_not_supported_within_bounds");}
  else output.reasons.push("registered_primary_or_safety_bounds_do_not_support_a_positive_claim");
  return output;
}
