import { causalClaimDefinitionSchema,type NativeCausalSource,type BusinessExperimentAnalysisView } from "@paperclipai/shared";
import { experimentDefinition } from "./business-experiment-fixture.js";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const rationale="Explicit synthetic software fixture; no collected trial or verified business outcome.";
export function causalClaimFixture(){
 const protocol=experimentDefinition(id(1),[2,4,6].map(n=>({id:id(n),versionId:id(n+1)}))),analysisId=id(9),experimentId=id(10),versionId=id(11),interpretationId=id(12);
 const assumption={status:"assumed" as const,rationale};
 const definition=causalClaimDefinitionSchema.parse({name:"Conditional assignment effect",question:rationale,humanHypothesis:rationale,ownerUserId:"local-board",outcomeMetricId:protocol.primaryMetric.metricId,outcomeMetricVersionId:protocol.primaryMetric.metricVersionId,
  population:{scope:protocol.scope,unit:"issue",eligibilityStatement:rationale,externalValidityLimits:rationale},horizon:{from:protocol.sampleOrDurationPlan.from,until:protocol.sampleOrDurationPlan.until},estimand:{kind:"assignment_intention_to_treat_native_binary_outcome",beneficialDirection:"increase",minimumMeaningfulEffect:0.1},identificationStrategy:"registered_randomized_assignment",
  graph:{nodes:[{key:"assignment",label:"Randomized assignment",role:"randomized_assignment"},{key:"outcome",label:"Native binary outcome",role:"outcome"}],edges:[{from:"assignment",to:"outcome",authority:"human_assumption",rationale}]},assumptions:{noInterference:assumption,stableOutcomeMeasurement:assumption,registeredPopulationValidity:assumption},experimentEvidence:{type:"experiment_analysis",id:analysisId,experimentId,versionId,interpretationId},interpretationBoundary:"conditional_native_proxy_advisory_only",purpose:"management_intelligence",sensitivity:"internal",governanceObligationRefs:[id(1)],retentionDays:30});
 const analysis:BusinessExperimentAnalysisView={id:analysisId,companyId:id(13),experimentId,versionId,definitionHash:"a".repeat(64),qualityGates:{assignmentReceipts:true,exposureReports:true,finalOutcomeCapture:"complete",identityJoins:true,baselineBalance:true,concurrentReviewAdmitted:true},invariantDiagnostics:[],exposureProvenance:"human_attestation",outcomeTimeSemantics:"created_in_window_current_state_at_common_final_capture",concurrentChangeReview:{assessment:"none_identified",rationale},causalAuthority:"conditional_on_registered_randomization_and_human_attestations",analyzedAt:new Date(Date.parse(protocol.sampleOrDurationPlan.until)+1000).toISOString(),analyzedBy:"local-board",receiptHash:"b".repeat(64),currentQualification:"current",
  result:{engineVersion:"aw-native-business-experiment-v1",definitionHash:"a".repeat(64),inputHash:"c".repeat(64),status:"pass",numericallyQualified:true,reasons:[],diagnostics:{assigned:100,control:50,treatment:50,exposed:100,srm:{method:"exact_binomial_probability_ordering_v1",expectedTreatmentProbability:0.5,pValue:1,threshold:0.001,mismatch:false}},metrics:[{key:"primary",role:"primary",control:{units:50,successes:10,rate:0.2},treatment:{units:50,successes:40,rate:0.8},effect:0.6,interval:{lower:0.2,upper:0.8,method:"bonferroni_clopper_pearson_difference_v1",familywiseCoverage:0.95},interpretation:"threshold_met"},{key:"harm",role:"guardrail",control:{units:50,successes:0,rate:0},treatment:{units:50,successes:0,rate:0},effect:0,interval:{lower:-0.09,upper:0.09,method:"bonferroni_clopper_pearson_difference_v1",familywiseCoverage:0.95},interpretation:"harm_excluded"}],limitations:[rationale]}};
 const source:NativeCausalSource={definition:protocol,analysis,sourceHash:"d".repeat(64),interpretationId};
 return {definition,source};
}
