import { z } from "zod";
import * as sharedSchemas from "@paperclipai/shared";

// Mounted V5 operations. Bodies reuse the validators enforced by each route.
export const v5ApiPaths: Array<{ method: "get" | "post" | "put" | "patch" | "delete"; path: string; body?: z.ZodTypeAny; successStatus: number }> = [
  { method: "get", path: "/api/companies/{companyId}/agent-identities", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agent-identities", body: sharedSchemas.createAgentIdentitySchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/agent-identities/{identityId}", successStatus: 200 },
  { method: "patch", path: "/api/companies/{companyId}/agent-identities/{identityId}", body: sharedSchemas.updateAgentIdentitySchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agent-identities/{identityId}/presences", body: sharedSchemas.addAgentPresenceSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/agent-identities/{identityId}/rehome", body: sharedSchemas.rehomeAgentIdentitySchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding", body: sharedSchemas.createProviderBindingSchema, successStatus: 201 },
  { method: "put", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding", body: sharedSchemas.attachProviderBindingSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding/discover", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding/conformance", body: sharedSchemas.providerConformanceInputSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding/revalidate", body: sharedSchemas.revalidateProviderBindingSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/provider-binding/{bindingId}/acknowledge-shared", body: sharedSchemas.acknowledgeSharedRuntimeSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/agents/{agentId}/runtime/execute", body: sharedSchemas.createExecutionScopeRequestSchema, successStatus: 202 },
  { method: "post", path: "/api/companies/{companyId}/runs/{runId}/scoped-actions", body: sharedSchemas.scopedRuntimeActionSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/runs/{runId}/execution-manifest", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/runtime/capabilities", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/runs/{runId}/skills/{skillId}/body", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/runs/{runId}/skill-usage", body: sharedSchemas.skillUsageInputSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/cross-company/policy", successStatus: 200 },
  { method: "put", path: "/api/companies/{companyId}/cross-company/policy", body: sharedSchemas.crossCompanyPolicySchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/cross-company/preview", body: sharedSchemas.agentExecutionScopeSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/cross-company/context", body: sharedSchemas.crossCompanyContextRequestSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/relationships", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/relationships", body: sharedSchemas.createCompanyRelationshipSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/relationships/{relationshipId}/transition", body: sharedSchemas.transitionCompanyRelationshipSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/org-units", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/org-units", body: sharedSchemas.createOrgUnitSchema, successStatus: 201 },
  { method: "patch", path: "/api/companies/{companyId}/org-units/{unitId}", body: sharedSchemas.updateOrgUnitSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/org-units/{unitId}/memberships", successStatus: 200 },
  { method: "put", path: "/api/companies/{companyId}/org-units/{unitId}/memberships", body: sharedSchemas.setOrgUnitMembershipSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/playbooks", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/playbooks", body: sharedSchemas.createPlaybookSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/playbooks/{id}", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/playbooks/{id}/revisions/{revisionId}", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/playbooks/{id}/export", successStatus: 200 },
  { method: "patch", path: "/api/companies/{companyId}/playbooks/{id}/draft", body: sharedSchemas.playbookDraftSchema, successStatus: 200 },
  { method: "patch", path: "/api/companies/{companyId}/playbooks/{id}/metadata", body: sharedSchemas.updatePlaybookMetadataSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/playbooks/{id}/review", body: sharedSchemas.reviewPlaybookSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/playbooks/{id}/proposals", body: sharedSchemas.proposePlaybookSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/playbooks/{id}/proposals/{proposalId}/review", body: sharedSchemas.reviewPlaybookProposalSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/playbooks/{id}/skill-links", body: sharedSchemas.linkPlaybookSkillSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/playbooks/{id}/compile-skill-candidate", body: sharedSchemas.projectPlaybookSkillSchema, successStatus: 201 },
  { method: "post", path: "/api/portfolio/summary", body: sharedSchemas.portfolioRequestSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/portfolio-capabilities", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/portfolio-capabilities/publications", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/portfolio-capabilities/publications", body: sharedSchemas.publishPortfolioCapabilitySchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/portfolio-capabilities/publications/{id}/withdraw", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/portfolio-capabilities/subscriptions", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/portfolio-capabilities/install", body: sharedSchemas.installPortfolioCapabilitySchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/portfolio-capabilities/subscriptions/{id}/prepare-upgrade", body: sharedSchemas.preparePortfolioCapabilityUpgradeSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/portfolio-capabilities/{id}", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/projects/{projectId}/roadmap", successStatus: 200 },
  { method: "put", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/policy", body: sharedSchemas.roadmapPolicySchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/milestones", body: sharedSchemas.createMilestoneSchema, successStatus: 201 },
  { method: "patch", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/milestones/{milestoneId}", body: sharedSchemas.updateMilestoneSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/baselines", body: sharedSchemas.createRoadmapBaselineSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/proposals", body: sharedSchemas.roadmapProposalSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/proposals/{proposalId}/review", body: sharedSchemas.reviewRoadmapProposalSchema, successStatus: 200 },
  { method: "patch", path: "/api/companies/{companyId}/projects/{projectId}/roadmap/tasks/{issueId}/forecast", body: sharedSchemas.taskForecastPatchSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/role-packs", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/role-packs/catalog", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/role-packs", body: sharedSchemas.createRolePackSchema, successStatus: 201 },
  { method: "put", path: "/api/companies/{companyId}/role-packs/assignments", body: sharedSchemas.assignRolePackSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/role-packs/resolve/{agentId}", successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/role-packs/{id}", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/role-packs/{id}/versions", body: sharedSchemas.rolePackVersionInputSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/role-packs/{id}/versions/{versionId}", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/role-packs/{id}/versions/{versionId}/publish", body: sharedSchemas.publishRolePackSchema, successStatus: 200 },
  { method: "get", path: "/api/companies/{companyId}/skills/{skillId}/evaluations", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/evaluations/suites", body: sharedSchemas.createSkillEvalSuiteSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/skills/{skillId}/evaluations/suites/{suiteId}", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/evaluations/suites/{suiteId}/replace", body: sharedSchemas.replaceSkillEvalSuiteSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/evaluations/runs", body: sharedSchemas.createSkillEvalRunSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/evaluations/runs/{evalRunId}/observations", body: sharedSchemas.attachSkillEvalObservationSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/governed-drafts", body: sharedSchemas.createGovernedSkillSchema, successStatus: 201 },
  { method: "get", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle", successStatus: 200 },
  { method: "patch", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/governance", body: sharedSchemas.updateSkillGovernanceSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/candidates", body: sharedSchemas.skillCandidateInputSchema, successStatus: 201 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/candidates/{versionId}/submit", successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/candidates/{versionId}/overlap-review", body: sharedSchemas.reviewSkillOverlapSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/transition", body: sharedSchemas.skillLifecycleTransitionSchema, successStatus: 200 },
  { method: "post", path: "/api/companies/{companyId}/skills/{skillId}/lifecycle/promote", body: sharedSchemas.skillPromotionInputSchema, successStatus: 200 },
];
