import { z } from "zod";
import * as shared from "@paperclipai/shared";

/** Explicit contracts, independently compared with mounted route handlers.
 * A listed operation grants no permissions or rollout qualification. */
export interface V7ApiOperation {
  method: "get" | "post" | "patch" | "put" | "delete";
  path: string;
  summary: string;
  successStatus: number;
  auth: "native" | "board" | "operator" | "publisher" | "owner" | "host";
  body?: z.ZodType;
  query?: z.ZodType;
  headers?: z.ZodType;
  description?: string;
}
const company = "/api/companies/{companyId}";
const hostHeaders = z.object({
  "x-aw-host-id": shared.runtimeHostProofSchema.shape.hostId,
  "x-aw-host-epoch": shared.runtimeHostProofSchema.shape.epoch,
  "x-aw-host-timestamp": shared.runtimeHostProofSchema.shape.timestamp,
  "x-aw-host-nonce": shared.runtimeHostProofSchema.shape.nonce,
  "x-aw-host-signature": shared.runtimeHostProofSchema.shape.signature,
});
const accountQuery = z.object({ expectedUserId: z.string().optional() });
const version = z
  .object({ expectedVersion: z.number().int().positive() })
  .strict();
const op = (
  method: V7ApiOperation["method"],
  path: string,
  summary: string,
  body?: z.ZodType,
  successStatus = 200,
  auth: V7ApiOperation["auth"] = "native",
  query?: z.ZodType,
): V7ApiOperation => ({
  method,
  path,
  summary,
  body,
  successStatus,
  auth,
  query,
});

export const v7ApiPaths: V7ApiOperation[] = [
  op(
    "get",
    "/api/agent-packages",
    "List current qualified package releases",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    "/api/agent-packages/{packageKey}",
    "List current releases for a package",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    "/api/agent-packages/releases",
    "Publish a qualified package release",
    shared.packageReleaseSchema,
    201,
    "publisher",
    accountQuery,
  ),
  op(
    "post",
    "/api/agent-packages/releases/{id}/revoke",
    "Revoke a package release",
    undefined,
    200,
    "publisher",
    accountQuery,
  ),
  op(
    "get",
    `${company}/agent-package-options`,
    "List authorized package installation choices",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/agent-package-installations`,
    "List company package installations",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/agent-package-installations/{id}`,
    "Inspect an authorized package installation",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/agent-packages/{packageKey}/preview`,
    "Preview a package without activation",
    shared.packageInstallSchema,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/agent-packages/{packageKey}/install`,
    "Install a package draft without granting access",
    shared.packageInstallSchema,
    201,
    "board",
    accountQuery,
  ),
  ...(["activate", "suspend"] as const).map((action) =>
    op(
      "post",
      `${company}/agent-package-installations/{id}/${action}`,
      `${action} a company package installation`,
      shared.packageDecisionSchema,
      200,
      "board",
      accountQuery,
    ),
  ),
  op(
    "delete",
    `${company}/agent-package-installations/{id}`,
    "Uninstall a package while retaining customer state",
    shared.packageDecisionSchema,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/agent-package-installations/{id}/update`,
    "Propose an explicit package update",
    shared.packageUpdateSchema,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/agent-package-update-proposals`,
    "List package update proposals",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/agent-package-update-proposals/{id}/review`,
    "Review a package update explicitly",
    z.object({ decision: z.enum(["accept", "reject"]) }).passthrough(),
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/agent-package-evaluations`,
    "Evaluate a qualified specialist candidate without hiring",
    shared.specialistEvaluationSchema,
    200,
    "board",
    accountQuery,
  ),

  op(
    "get",
    `${company}/ai-use-case-deployment-targets`,
    "List authorized AI deployment targets",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/ai-use-cases`,
    "List company AI use cases",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/ai-use-cases`,
    "Create a governed AI use case",
    shared.createUseCaseSchema,
    201,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/ai-use-cases/{id}`,
    "Inspect a governed AI use case",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "patch",
    `${company}/ai-use-cases/{id}`,
    "Revise an AI use case purpose",
    shared.updateUseCaseSchema,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/ai-use-cases/{id}/assessments`,
    "Record an AI use case assessment",
    shared.useCaseAssessmentSchema,
    201,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/ai-use-cases/{id}/deployments`,
    "Bind an authorized deployment to an AI use case",
    shared.useCaseDeploymentSchema,
    201,
    "board",
    accountQuery,
  ),
  ...(["approve", "suspend", "retire"] as const).map((action) =>
    op(
      "post",
      `${company}/ai-use-cases/{id}/${action}`,
      `${action} an AI use case`,
      shared.useCaseDecisionSchema,
      200,
      "board",
      accountQuery,
    ),
  ),
  op(
    "get",
    `${company}/ai-use-cases/{id}/evidence-pack`,
    "Export authorized governance evidence without asserting legal compliance",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/human-oversight-profiles`,
    "List human oversight profiles",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/human-oversight-profiles`,
    "Create a human oversight profile",
    shared.oversightProfileSchema,
    201,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/governance-obligations`,
    "List company governance obligations",
    undefined,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/governance-obligations`,
    "Record a company governance obligation",
    shared.governanceObligationSchema,
    201,
    "board",
    accountQuery,
  ),

  op(
    "get",
    `${company}/memory/cognitive/status`,
    "Inspect cognitive Memory status",
  ),
  op(
    "post",
    `${company}/memory/cognitive/bindings`,
    "Create an authorized cognitive Memory binding",
    shared.cognitiveBindingSchema,
    201,
    "board",
  ),
  op(
    "post",
    `${company}/memory/cognitive/reconcile`,
    "Reconcile a cognitive Memory binding",
    shared.cognitiveReconcileSchema,
    200,
    "board",
  ),
  op(
    "get",
    `${company}/memory/observations`,
    "List visible derived observations",
  ),
  op(
    "post",
    `${company}/memory/observations`,
    "Create a sourced observation proposal",
    shared.createObservationSchema,
    201,
  ),
  op(
    "get",
    `${company}/memory/observations/{id}`,
    "Inspect an observation with current source access",
  ),
  ...(["accept", "reject", "revoke"] as const).map((action) =>
    op(
      "post",
      `${company}/memory/observations/{id}/${action}`,
      `${action} an observation`,
      shared.derivedReviewSchema,
      200,
      "board",
    ),
  ),
  op("get", `${company}/memory/models`, "List visible derived Memory models"),
  op(
    "post",
    `${company}/memory/models`,
    "Create a sourced Memory model proposal",
    shared.createMemoryModelSchema,
    201,
  ),
  op(
    "get",
    `${company}/memory/models/{id}`,
    "Inspect a Memory model with current source access",
  ),
  ...(["accept", "revoke"] as const).map((action) =>
    op(
      "post",
      `${company}/memory/models/{id}/${action}`,
      `${action} a Memory model`,
      shared.derivedReviewSchema,
      200,
      "board",
    ),
  ),
  op(
    "post",
    `${company}/memory/models/{id}/rebuild`,
    "Queue a bounded Memory model rebuild",
    shared.rebuildMemoryModelSchema,
    202,
    "board",
  ),

  op(
    "post",
    `${company}/foundation/bootstrap`,
    "Start bounded Foundation discovery as a native Task",
    shared.startFoundationBootstrapSchema,
    201,
    "board",
  ),
  op(
    "get",
    `${company}/foundation/bootstrap/{runId}`,
    "Inspect Foundation discovery",
  ),
  op(
    "get",
    `${company}/foundation/bootstrap/{runId}/sources`,
    "List currently authorized Foundation discovery sources",
  ),
  op(
    "post",
    `${company}/foundation/bootstrap/{runId}/candidates`,
    "Submit Foundation candidates without approval",
    shared.submitBootstrapCandidatesSchema,
  ),
  op(
    "post",
    `${company}/foundation/bootstrap/{runId}/answer`,
    "Answer a Foundation discovery question",
    shared.answerBootstrapSchema,
    200,
    "board",
  ),
  op(
    "post",
    `${company}/foundation/bootstrap/{runId}/create-proposals`,
    "Create Foundation proposals for human review",
    shared.bootstrapTransitionSchema,
    200,
    "board",
  ),

  op(
    "post",
    `${company}/learning/prepare-change`,
    "Validate and hash a learning change",
    shared.learningChangeSchema,
    200,
    "board",
  ),
  op("get", `${company}/learning/cycles`, "List authorized learning cycles"),
  op(
    "get",
    `${company}/learning/policy-proposals`,
    "List learning policy proposals",
  ),
  op(
    "post",
    `${company}/learning/cycles`,
    "Create a bounded learning cycle",
    shared.learningCycleSchema,
    201,
  ),
  op("get", `${company}/learning/cycles/{id}`, "Inspect a learning cycle"),
  op(
    "post",
    `${company}/learning/cycles/{id}/hypotheses`,
    "Add a learning hypothesis",
    shared.learningHypothesisSchema,
    201,
  ),
  op(
    "post",
    `${company}/learning/hypotheses/{id}/evaluations`,
    "Record a learning evaluation",
    shared.learningEvaluationSchema,
    201,
    "board",
  ),
  op(
    "post",
    `${company}/learning/hypotheses/{id}/propose-change`,
    "Propose a governed learning change",
    shared.proposeLearningChangeSchema,
    201,
    "board",
  ),
  op(
    "post",
    `${company}/learning/policy-proposals/{id}/review`,
    "Review a learning policy proposal",
    shared.reviewLearningPolicySchema,
    200,
    "board",
  ),
  op(
    "post",
    `${company}/learning/cycles/{id}/finish`,
    "Finish a learning cycle",
    shared.finishLearningCycleSchema,
    200,
    "board",
  ),

  op(
    "get",
    `${company}/orchestration/plans`,
    "List authorized orchestration plans",
  ),
  op(
    "get",
    `${company}/orchestration/plans/{id}`,
    "Inspect an orchestration plan",
  ),
  op(
    "post",
    `${company}/orchestration/plans`,
    "Create a bounded orchestration plan",
    shared.createOrchestrationPlanSchema,
    201,
    "board",
  ),
  op(
    "post",
    `${company}/orchestration/plans/{id}/decisions`,
    "Apply an explicit orchestration decision",
    shared.orchestrationDecisionSchema,
    200,
    "board",
  ),
  op(
    "get",
    `${company}/orchestration/plans/{id}/supervision`,
    "Inspect current supervision state",
  ),
  op(
    "get",
    `${company}/orchestration/plans/{id}/signals`,
    "List supervision signals",
  ),
  op(
    "post",
    `${company}/orchestration/plans/{id}/intervene`,
    "Request a governed intervention without claiming physical Stop",
    shared.supervisionInterventionSchema,
    200,
    "board",
  ),
  op(
    "get",
    `${company}/orchestration/plans/{id}/verification-packet`,
    "Read the current authorized verification packet",
    undefined,
    200,
    "native",
    z.object({ workerId: z.string().optional() }),
  ),
  op(
    "get",
    `${company}/orchestration/plans/{id}/verifications`,
    "List human reviews and non-authorizing model assessments",
  ),
  op(
    "post",
    `${company}/orchestration/plans/{id}/verify`,
    "Record a current human verification decision",
    shared.verificationReviewSchema,
    200,
    "board",
  ),
  op(
    "post",
    `${company}/orchestration/plans/{id}/trajectory-reviews`,
    "Record a current human trajectory review",
    shared.trajectoryReviewSchema,
    200,
    "board",
  ),

  op(
    "get",
    `${company}/core-stewards`,
    "Inspect bounded Core Steward state",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "get",
    `${company}/readiness/requirements`,
    "List mandatory and company readiness requirements",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "post",
    `${company}/readiness/requirements`,
    "Publish a company readiness requirement",
    shared.createReadinessRequirementSchema,
    201,
    "board",
    accountQuery,
  ),
  op(
    "get",
    `${company}/readiness/overview`,
    "Inspect current actor readiness",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "get",
    `${company}/readiness/findings`,
    "List current actor readiness findings",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "post",
    `${company}/readiness/findings/{id}/resolve`,
    "Review a readiness finding",
    shared.resolveReadinessFindingSchema,
    200,
    "board",
    accountQuery,
  ),
  op(
    "post",
    `${company}/readiness/assess`,
    "Create an actor-bound readiness assessment",
    shared.assessReadinessSchema,
    201,
    "native",
    accountQuery,
  ),
  op(
    "get",
    `${company}/readiness/assessments`,
    "List current actor readiness assessments",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "get",
    `${company}/readiness/assessments/{id}`,
    "Inspect a current actor readiness assessment",
    undefined,
    200,
    "native",
    accountQuery,
  ),

  op(
    "get",
    `${company}/work-signals`,
    "List authorized work signals",
    undefined,
    200,
    "board",
  ),
  op(
    "post",
    `${company}/work-signals/extract`,
    "Extract bounded signals from an authorized Task",
    shared.workSignalExtractSchema,
    201,
  ),
  ...(["apply", "ignore", "review"] as const).map((action) =>
    op(
      "post",
      `${company}/work-signals/{id}/${action}`,
      `${action} a work signal`,
      shared.workSignalDecisionSchema,
      200,
      "board",
    ),
  ),

  op(
    "get",
    `${company}/runtime-cells/{id}/execution-posture`,
    "Inspect observed execution posture",
    undefined,
    200,
    "native",
    accountQuery,
  ),
  op(
    "get",
    `${company}/runtime-sandboxes`,
    "List native sandbox bindings",
    undefined,
    200,
    "operator",
  ),
  op(
    "post",
    `${company}/runtime-sandboxes`,
    "Create a sandbox binding without workload admission",
    shared.sandboxBindingCreateSchema,
    201,
    "operator",
  ),
  op(
    "get",
    `${company}/runtime-sandboxes/{id}`,
    "Inspect a native sandbox binding",
    undefined,
    200,
    "operator",
  ),
  op(
    "post",
    `${company}/runtime-sandboxes/{id}/qualify`,
    "Probe the actual sandbox boundary; unsupported controls remain inconclusive",
    version,
    200,
    "operator",
  ),
  op(
    "post",
    `${company}/runtime-sandboxes/{id}/reconcile`,
    "Reconcile current sandbox authority and observations",
    version,
    200,
    "operator",
  ),
  op(
    "post",
    `${company}/runtime-sandboxes/{id}/policy`,
    "Compile a version-bound sandbox policy",
    shared.sandboxCompileSchema,
    201,
    "operator",
  ),

  {
    ...op(
      "get",
      `${company}/portability/v7`,
      "Export company-owned V7 state without commercial or rollout restrictions",
      undefined,
      200,
      "owner",
      accountQuery,
    ),
    description:
      "Requires current company owner authority and current source permissions. Billing and feature rollback do not restrict portability. No credentials, activation grants or approvals are exported.",
  },
  op(
    "get",
    `${company}/enterprise/security-events`,
    "Inspect the company security export configuration",
    undefined,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "put",
    `${company}/enterprise/security-events`,
    "Configure bounded, default-off security export",
    shared.securityEventExportConfigurationSchema,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "get",
    `${company}/enterprise/identity`,
    "Inspect enterprise identity policy",
    undefined,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "put",
    `${company}/enterprise/identity`,
    "Configure an enterprise identity policy without activation",
    shared.enterpriseIdentityPolicySchema,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "post",
    `${company}/enterprise/identity/qualify`,
    "Record a source-bound enterprise identity qualification",
    shared.enterpriseQualificationSchema,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "get",
    `${company}/enterprise/identity/subjects`,
    "List native enterprise subject bindings",
    undefined,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "post",
    `${company}/enterprise/identity/subjects`,
    "Bind an exact enterprise subject without granting company authority",
    shared.enterpriseSubjectBindingSchema,
    201,
    "owner",
    accountQuery,
  ),
  op(
    "delete",
    `${company}/enterprise/identity/subjects/{bindingId}`,
    "Revoke an enterprise subject binding",
    undefined,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "post",
    `${company}/enterprise/identity/scim-credential`,
    "Rotate a company-scoped SCIM credential; secret returned once",
    shared.enterpriseCredentialRotationSchema,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "post",
    `${company}/enterprise/identity/scim-decommission`,
    "Decommission the company SCIM projection",
    shared.enterprisePolicyDecisionSchema,
    200,
    "owner",
    accountQuery,
  ),
  op(
    "post",
    `${company}/enterprise/identity/suspend`,
    "Suspend an enterprise identity policy",
    shared.enterprisePolicyDecisionSchema,
    200,
    "owner",
    accountQuery,
  ),

  {
    ...op(
      "post",
      "/api/internal/runtime/hosts/{hostId}/sandbox-commands/claim",
      "Claim a bounded native sandbox host command",
      undefined,
      200,
      "host",
    ),
    headers: hostHeaders,
  },
  {
    ...op(
      "post",
      "/api/internal/runtime/hosts/{hostId}/sandbox-commands/{commandId}/complete",
      "Complete a leased generation-bound sandbox host command",
      shared.sandboxHostCompletionSchema,
      200,
      "host",
    ),
    headers: hostHeaders,
  },
];
