import {managementAnalyticalFixture} from "./helpers/management-analytical-fixture.js";
import {disableV8Rollout} from "./helpers/v8-rollout.js";
import {randomUUID} from "node:crypto";
import express from "express";
import request from "supertest";
import {afterAll,beforeAll,beforeEach,describe,expect,it} from "vitest";
import {and,eq} from "drizzle-orm";
import {agents,authUsers,companyMemberships,heartbeatRuns,issues,issueComments,decisions,decisionCausalPins,decisionContexts,decisionContextVersions,decisionEvidenceLinks,decisionCriteria,decisionExpectedOutcomes,analyticalLineageManifests,companies,projects,causalClaims,causalClaimVersions,causalClaimReviews,causalAnalysisRuns,createDb} from "@paperclipai/db";
import {decisionContextDefinitionSchema,causalClaimDefinitionSchema,businessMetricDefinitionSchema,type CausalAnalysisEvidenceReference} from "@paperclipai/shared";
import {decisionService} from "../services/decisions.js";
import {decisionIntelligenceService} from "../services/decision-intelligence.js";
import {causalClaimService} from "../services/causal-claims/service.js";
import {causalClaimRoutes} from "../routes/causal-claims.js";
import {errorHandler} from "../middleware/index.js";
import {businessMetricService} from "../services/business-metrics/service.js";
import {aiGovernanceService} from "../services/ai-governance/governance-service.js";
import {instanceSettingsService} from "../services/instance-settings.js";
import {lockMemoryPrivacy} from "../services/memory/memory-privacy.js";
import {eraseAnalyticalSourcesUnderMemory} from "../services/analytical-source-erasure.js";
import {purgeCompanyContent} from "../services/saas/company-purge.js";
import {analyticalPurpose,metricDefinition} from "./helpers/business-metric-fixture.js";
import {causalClaimFixture} from "./helpers/causal-claim-fixture.js";
import {getEmbeddedPostgresTestSupport,startEmbeddedPostgresTestDatabase} from "./helpers/embedded-postgres.js";
const support=await getEmbeddedPostgresTestSupport(),suite=support.supported?describe:describe.skip;
const actor={type:"board" as const,source:"local_implicit" as const},rationale="Explicit synthetic human model review, not collected causal or business evidence";
const flags={analytical_lineage_v8:true,business_metrics_v8:true,business_experiments_v8:true,causal_claims_v8:true,decision_intelligence_v8:true,enableDecisions:true,ai_use_cases_v7:true,governance_evidence_v7:true,causal_provider_dowhy_v8:false};
suite("Native causal model/review/source owner on migrated PostgreSQL",()=>{
 let database:Awaited<ReturnType<typeof startEmbeddedPostgresTestDatabase>>,db:ReturnType<typeof createDb>,companyId:string,otherId:string,policyId:string;
 beforeAll(async()=>{process.env.PAPERCLIP_DECISION_SIGNING_SECRET="0123456789abcdef0123456789abcdef";database=await startEmbeddedPostgresTestDatabase("aw-v8-causal-owner-");db=createDb(database.connectionString);});afterAll(async()=>database?.cleanup());
 beforeEach(async()=>{await instanceSettingsService(db,{runtimeEnv:{}}).updateExperimental(flags);companyId=randomUUID();otherId=randomUUID();await db.insert(companies).values([{id:companyId,name:"Native causal fixture",issuePrefix:randomUUID()},{id:otherId,name:"Foreign causal fixture",issuePrefix:randomUUID()}]);const policy=analyticalPurpose();policy.analyticalPurpose!.capabilities=["metrics","causal","decision"];policyId=(await aiGovernanceService(db).obligation(actor,companyId,policy)).id;});
 const service=()=>causalClaimService(db);
 async function proposal(projectId:string|null=null){const definition=metricDefinition(policyId);if(projectId&&definition.calculation.kind==="native_ratio"){definition.calculation.numerator.projectId=projectId;definition.calculation.denominator.projectId=projectId;}const metric=await businessMetricService(db).create(companyId,actor,{key:`metric_${randomUUID().replaceAll("-","")}`,definition:businessMetricDefinitionSchema.parse(definition)});await businessMetricService(db).publish(companyId,actor,metric.metric.id,{expectedRevision:1,versionId:metric.version.id});const seed=causalClaimFixture().definition;const model=causalClaimDefinitionSchema.parse({...seed,outcomeMetricId:metric.metric.id,outcomeMetricVersionId:metric.version.id,experimentEvidence:null,population:{...seed.population,scope:projectId?{type:"project",id:projectId}:{type:"company",id:null}},governanceObligationRefs:[policyId]});return {model,metric};}
 const create=(model:ReturnType<typeof causalClaimDefinitionSchema.parse>)=>service().create(companyId,actor,{key:`claim_${randomUUID().replaceAll("-","")}`,definition:model});
 async function reviewed(){const f=await proposal(),d=await create(f.model),claim=await service().review(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true});return {...f,...d,claim};}
 function app(){const a=express();a.use(express.json());a.use((req,_res,next)=>{req.actor={...actor,userId:"local-board"};next();});a.use("/api",causalClaimRoutes(db));a.use(errorHandler);return a;}
  async function nativeDecision() {
    await db.insert(authUsers).values({id:"local-board",name:"Local fixture human",email:"experiment-decision@example.test",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();
    await db.insert(companyMemberships).values({companyId,principalType:"user",principalId:"local-board",membershipRole:"member",status:"active"}).onConflictDoNothing();
    const [agent]=await db.insert(agents).values({companyId,name:"Native fixture proposer",role:"engineer",status:"active",adapterType:"codex_local"}).returning();
    const [origin]=await db.insert(issues).values({companyId,title:"Native decision origin",status:"done",responsibleUserId:"local-board"}).returning();
    const [target]=await db.insert(issues).values({companyId,title:"Native decision target",status:"todo",responsibleUserId:"local-board"}).returning();
    const [run]=await db.insert(heartbeatRuns).values({companyId,agentId:agent.id,status:"running",responsibleUserId:"local-board",contextSnapshot:{issueId:origin.id}}).returning();
    const owner=decisionService(db,{wakeOriginAgent:async()=>{}});
    const decision=await owner.create({companyId,actor,agentId:agent.id,runId:run.id,title:"Consider this exact retained experiment?",body:rationale,options:[{id:"proceed",label:"Proceed",effects:[{type:"comment_on_issue",targetIssueId:target.id,staleness:"lenient",bodyMarkdown:"Separate human native choice"}]},{id:"defer",label:"Defer",effects:[]}]});
    return {decision,target,owner};
  }
  function causalContext(source:CausalAnalysisEvidenceReference) {
    return decisionContextDefinitionSchema.parse({question:"Should this conditional causal evidence inform a separate option?",objective:rationale,ownerUserId:"local-board",scope:{type:"company",id:null},timeHorizon:{from:new Date().toISOString(),until:new Date(Date.now()+86400000).toISOString()},uncertaintySummary:rationale,revisitAt:null,sensitivity:"internal",purpose:"management_intelligence",governanceObligationRefs:[policyId],retentionDays:1,evidence:[{key:"causal",source,relationship:"causal_result",optionId:null,criterionKey:null,rationale}],assumptions:[],criteria:[{key:"judgment",name:"Human consideration",description:rationale,type:"qualitative",priority:"high",evidenceKey:null}],expectedOutcomes:[{kind:"qualitative",optionId:"proceed",statement:rationale,reviewAt:new Date(Date.now()+2*86400000).toISOString(),uncertaintySummary:rationale}]});
  }
  async function causalEvidence(projectId:string|null=null){const f=await proposal(projectId),d=await create(f.model);await service().review(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true});const analyzed=await service().analyze(companyId,actor,d.claim.id,{expectedRevision:2,versionId:d.version.id}),detail=await service().detail(companyId,actor,d.claim.id);return {...f,...d,analyzed,ref:{type:"causal_analysis" as const,id:analyzed.run.id,claimId:d.claim.id,versionId:d.version.id,reviewId:detail.versions[0].review!.id}};}
 it("pins exact causal abstention and human review before a separate native decision choice, with immutable/deferred source material",async()=>{
  const c=await causalEvidence(),native=await nativeDecision(),owner=decisionIntelligenceService(db),definition=causalContext(c.ref),view=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition}),pin=view.versions[0];
  expect(pin.evidence[0].causal!.run.result).toEqual(c.analyzed.run.result);expect(pin.evidence[0].causal!.run.result.estimate).toBeNull();expect((await native.owner.get(native.decision.id))!.status).toBe("open");expect(await db.select().from(issueComments).where(eq(issueComments.issueId,native.target.id))).toHaveLength(0);
  expect(await db.select().from(decisionCausalPins).where(eq(decisionCausalPins.contextVersionId,pin.id))).toMatchObject([{runId:c.ref.id,reviewId:c.ref.reviewId,claimId:c.ref.claimId,claimVersionId:c.ref.versionId}]);await expect(db.delete(decisionCausalPins).where(eq(decisionCausalPins.contextVersionId,pin.id))).rejects.toMatchObject({cause:{code:"23514"}});
  const [stored]=await db.select().from(decisionContextVersions).where(eq(decisionContextVersions.id,pin.id)),[manifest]=await db.select().from(analyticalLineageManifests).where(eq(analyticalLineageManifests.id,stored.lineageManifestId));
  await expect(db.transaction(async raw=>{const tx=raw as unknown as typeof db,versionId=randomUUID(),manifestId=randomUUID();await tx.insert(analyticalLineageManifests).values({...manifest,id:manifestId,analysisRef:versionId});await tx.insert(decisionContextVersions).values({...stored,id:versionId,revision:2,lineageManifestId:manifestId});const fields={companyId,decisionId:native.decision.id,contextVersionId:versionId};await tx.insert(decisionEvidenceLinks).values(definition.evidence.map(payload=>({...fields,key:payload.key,payload})));await tx.insert(decisionCriteria).values(definition.criteria.map(payload=>({...fields,key:payload.key,payload})));await tx.insert(decisionExpectedOutcomes).values(definition.expectedOutcomes.map((payload,i)=>({...fields,key:String(i),payload})));})).rejects.toMatchObject({code:"23514",message:expect.stringContaining("decision_causal_material_incomplete")});
  await owner.prepare(companyId,actor,native.decision.id,{expectedRevision:1,versionId:pin.id,rationale});const chosen=await native.owner.decide({id:native.decision.id,optionId:"proceed",decidedByUserId:"local-board",userActor:actor});expect(chosen.status).toBe("decided");expect(await db.select().from(issueComments).where(eq(issueComments.issueId,native.target.id))).toHaveLength(1);
 });
 it("rejects altered run/review/version and cross-tenant causal references before any context is created",async()=>{
  const c=await causalEvidence(),native=await nativeDecision(),owner=decisionIntelligenceService(db);for(const source of [{...c.ref,id:randomUUID()},{...c.ref,reviewId:randomUUID()},{...c.ref,versionId:randomUUID()},{...c.ref,claimId:randomUUID()}])await expect(owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(source)})).rejects.toMatchObject({status:404});
  await expect(owner.propose(otherId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(c.ref)})).rejects.toMatchObject({status:404});expect(await db.select().from(decisionContexts).where(eq(decisionContexts.decisionId,native.decision.id))).toHaveLength(0);
 });
 it("preserves original causal context bytes after human model amendment while requiring explicit revalidation",async()=>{
  const c=await causalEvidence(),native=await nativeDecision(),owner=decisionIntelligenceService(db),view=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(c.ref)}),pin=view.versions[0];
  const management=await managementAnalyticalFixture(db,companyId,[c.ref]);expect(management.original.sources[0].grade).toBe("conditional_causal");expect(management.original.sources[0].analytical!.causal!.definition).toEqual(c.model);
  await service().revise(companyId,actor,c.claim.id,{expectedRevision:3,definition:{...c.model,question:"A changed human causal question requires a new separate review"},rationale});const retained=await owner.detail(companyId,actor,native.decision.id);expect(retained.versions[0].contentHash).toBe(pin.contentHash);expect(retained.versions[0].evidence).toEqual(pin.evidence);expect(retained.versions[0].revalidationRequiredEvidenceKeys).toEqual(["causal"]);await expect(owner.prepare(companyId,actor,native.decision.id,{expectedRevision:1,versionId:pin.id,rationale})).rejects.toMatchObject({status:409});expect((await native.owner.get(native.decision.id))!.status).toBe("open");
  const history=await management.read();expect(history.currentQualification).toBe("needs_revalidation");expect(history.sources).toEqual(management.original.sources);expect(history.packet).toEqual(management.original.packet);await expect(management.publish()).rejects.toMatchObject({status:409});await expect(management.recapture()).rejects.toMatchObject({status:409});
 });
 it("retains authorized original causal history when its declared human owner leaves, while refusing new reliance",async()=>{
  const ownerId=randomUUID();await db.insert(authUsers).values({id:ownerId,name:"Former human model owner",email:`${ownerId}@example.test`,createdAt:new Date(),updatedAt:new Date()});await db.insert(companyMemberships).values({companyId,principalType:"user",principalId:ownerId,membershipRole:"member",status:"active"});const f=await proposal(),d=await create({...f.model,ownerUserId:ownerId});await service().review(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true});const result=await service().analyze(companyId,actor,d.claim.id,{expectedRevision:2,versionId:d.version.id}),detail=await service().detail(companyId,actor,d.claim.id),native=await nativeDecision(),owner=decisionIntelligenceService(db),ref={type:"causal_analysis" as const,id:result.run.id,claimId:d.claim.id,versionId:d.version.id,reviewId:detail.versions[0].review!.id},view=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(ref)});
  await db.delete(companyMemberships).where(and(eq(companyMemberships.companyId,companyId),eq(companyMemberships.principalId,ownerId)));const retained=await owner.detail(companyId,actor,native.decision.id);expect(retained.versions[0].contentHash).toBe(view.versions[0].contentHash);expect(retained.versions[0].revalidationRequiredEvidenceKeys).toEqual(["causal"]);await expect(owner.prepare(companyId,actor,native.decision.id,{expectedRevision:1,versionId:view.versions[0].id,rationale})).rejects.toMatchObject({status:409});
 });
 it("revoking the causal source blocks a prepared choice before canonical effects run",async()=>{
  const c=await causalEvidence(),native=await nativeDecision(),owner=decisionIntelligenceService(db),view=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(c.ref)});await owner.prepare(companyId,actor,native.decision.id,{expectedRevision:1,versionId:view.versions[0].id,rationale});await service().revoke(companyId,actor,c.claim.id,{expectedRevision:3,rationale});await expect(native.owner.decide({id:native.decision.id,optionId:"proceed",decidedByUserId:"local-board",userActor:actor})).rejects.toMatchObject({status:404});expect((await db.select().from(decisions).where(eq(decisions.id,native.decision.id)))[0].status).toBe("open");expect(await db.select().from(issueComments).where(eq(issueComments.issueId,native.target.id))).toHaveLength(0);
  const retained=await owner.detail(companyId,actor,native.decision.id);expect(retained.versions[0].revalidationRequiredEvidenceKeys).toEqual(["causal"]);expect(retained.versions[0].evidence[0].causal!.run.result).toEqual(c.analyzed.run.result);
  const replacement=causalContext(c.ref);replacement.evidence=[];const revised=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:2,definition:replacement});expect(revised.versions[0].evidence).toEqual([]);await owner.prepare(companyId,actor,native.decision.id,{expectedRevision:3,versionId:revised.versions[0].id,rationale});
 });
 it("erases complete causal-derived context prose while retaining an already chosen canonical decision and effects with V8 rollout off",async()=>{
  const [source]=await db.insert(projects).values({companyId,name:"Causal-only source scope",status:"in_progress"}).returning(),c=await causalEvidence(source.id),native=await nativeDecision(),owner=decisionIntelligenceService(db),view=await owner.propose(companyId,actor,native.decision.id,{expectedRevision:0,definition:causalContext(c.ref)});await owner.prepare(companyId,actor,native.decision.id,{expectedRevision:1,versionId:view.versions[0].id,rationale});await native.owner.decide({id:native.decision.id,optionId:"proceed",decidedByUserId:"local-board",userActor:actor});
  await disableV8Rollout(db);await db.update(companies).set({status:"paused"}).where(eq(companies.id,companyId));await db.transaction(async raw=>{const tx=raw as unknown as typeof db;await lockMemoryPrivacy(tx,companyId);await eraseAnalyticalSourcesUnderMemory(tx,companyId,"project",[source.id]);});expect(await db.select().from(decisionContextVersions).where(eq(decisionContextVersions.decisionId,native.decision.id))).toHaveLength(0);expect(await db.select().from(decisionCausalPins).where(eq(decisionCausalPins.decisionId,native.decision.id))).toHaveLength(0);expect(await db.select().from(causalClaims).where(eq(causalClaims.id,c.claim.id))).toHaveLength(0);expect((await db.select().from(decisions).where(eq(decisions.id,native.decision.id)))[0].chosenOptionId).toBe("proceed");expect(await db.select().from(issueComments).where(eq(issueComments.issueId,native.target.id))).toHaveLength(1);
 });
 it("persists a human question, separates review and abstains without an identified dataset instead of inventing effects",async()=>{
  const f=await proposal(),d=await create(f.model);expect(d.claim).toMatchObject({status:"hypothesis",revision:1,reviewedVersionId:null,latestRunId:null});await expect(service().analyze(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id})).rejects.toMatchObject({status:409});
  const reviewed=await service().review(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true});const result=await service().analyze(companyId,actor,d.claim.id,{expectedRevision:reviewed.revision,versionId:d.version.id});expect(result).toMatchObject({claim:{status:"inconclusive",revision:3},run:{result:{status:"inconclusive",evidenceGrade:"descriptive_only",identification:{status:"unsupported"},estimate:null,executionAuthority:"advisory_only"}}});
  const detail=await service().detail(companyId,actor,d.claim.id);expect(detail.versions[0].run).toEqual(result.run);expect(JSON.stringify(detail)).not.toContain('"signature"');await expect(service().analyze(companyId,actor,d.claim.id,{expectedRevision:3,versionId:d.version.id})).rejects.toMatchObject({status:409});
 });
 it("retains immutable versions/receipts and resets review on explicit amendment with CAS",async()=>{
  const d=await reviewed();const attempts=await Promise.allSettled([1,2].map(()=>service().revise(companyId,actor,d.claim.id,{expectedRevision:2,definition:{...d.model,question:"Which explicit native causal question should be investigated?"},rationale})));expect(attempts.filter(a=>a.status==="fulfilled")).toHaveLength(1);const detail=await service().detail(companyId,actor,d.claim.id);expect(detail.claim).toMatchObject({status:"hypothesis",revision:3,reviewedVersionId:null,latestRunId:null});expect(detail.versions).toHaveLength(2);
  await expect(db.update(causalClaimVersions).set({contentHash:"f".repeat(64)}).where(eq(causalClaimVersions.id,d.version.id))).rejects.toMatchObject({cause:{code:"23514"}});await expect(db.delete(causalClaimReviews).where(eq(causalClaimReviews.claimId,d.claim.id))).rejects.toMatchObject({cause:{code:"23514"}});await expect(service().review(companyId,actor,d.claim.id,{expectedRevision:3,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true})).rejects.toMatchObject({status:409});
 });
 it("requires causal purpose and current human/company authority without borrowing metric permission",async()=>{
  const f=await proposal(),policy=analyticalPurpose();policy.citation="Metric-only fixture purpose";const metricsOnly=await aiGovernanceService(db).obligation(actor,companyId,policy);await expect(create({...f.model,governanceObligationRefs:[metricsOnly.id]})).rejects.toMatchObject({status:409});expect(await db.select().from(causalClaims).where(eq(causalClaims.companyId,companyId))).toHaveLength(0);
  const d=await create(f.model);await expect(service().detail(otherId,actor,d.claim.id)).rejects.toMatchObject({status:404});await expect(service().detail(companyId,{type:"agent",agentId:randomUUID(),runId:null},d.claim.id)).rejects.toMatchObject({status:403});
 });
 it("deferred material proof rejects an empty claim and SQL cannot promote an unreviewed model to support",async()=>{
  await expect(db.transaction(async raw=>{const tx=raw as unknown as typeof db;await tx.insert(causalClaims).values({companyId,key:`bare_${randomUUID().replaceAll("-","")}`,createdBy:"local-board",createdAt:new Date(),updatedAt:new Date()});})).rejects.toMatchObject({code:"23514",message:expect.stringContaining("causal_initial_material_incomplete")});
  const f=await proposal(),d=await create(f.model);await expect(db.update(causalClaims).set({revision:2,status:"supported"}).where(eq(causalClaims.id,d.claim.id))).rejects.toMatchObject({cause:{code:"23514"}});expect((await service().detail(companyId,actor,d.claim.id)).claim.status).toBe("hypothesis");
 });
 it("erases source-owned causal question, review, run and prose with rollout off and company paused",async()=>{
  const [project]=await db.insert(projects).values({companyId,name:"Causal governed source scope",status:"in_progress"}).returning(),f=await proposal(project.id),d=await create(f.model);
  await service().review(companyId,actor,d.claim.id,{expectedRevision:1,versionId:d.version.id,rationale,graphAndAssumptionsAcknowledged:true});await service().analyze(companyId,actor,d.claim.id,{expectedRevision:2,versionId:d.version.id});
  await disableV8Rollout(db);await db.update(companies).set({status:"paused"}).where(eq(companies.id,companyId));await db.transaction(async raw=>{const tx=raw as unknown as typeof db;await lockMemoryPrivacy(tx,companyId);await eraseAnalyticalSourcesUnderMemory(tx,companyId,"project",[project.id]);});
  for(const table of [causalClaims,causalClaimVersions,causalClaimReviews,causalAnalysisRuns])expect(await db.select().from(table).where(eq(table.companyId,companyId))).toHaveLength(0);
 });
 it("preserves immutable analysis and permits explicit revocation independently of rollout/source disclosure",async()=>{
  const d=await reviewed(),result=await service().analyze(companyId,actor,d.claim.id,{expectedRevision:2,versionId:d.version.id});await expect(db.delete(causalAnalysisRuns).where(eq(causalAnalysisRuns.id,result.run.id))).rejects.toMatchObject({cause:{code:"23514"}});await expect(db.update(causalAnalysisRuns).set({sourceHash:"f".repeat(64)}).where(eq(causalAnalysisRuns.id,result.run.id))).rejects.toMatchObject({cause:{code:"23514"}});
  await disableV8Rollout(db);await db.update(companies).set({status:"paused"}).where(eq(companies.id,companyId));const revoked=await service().revoke(companyId,actor,d.claim.id,{expectedRevision:3,rationale});expect(revoked).toMatchObject({status:"revoked",revision:4});expect((await db.select().from(causalAnalysisRuns).where(eq(causalAnalysisRuns.id,result.run.id)))[0].result).toEqual(result.run.result);await expect(service().revoke(companyId,actor,d.claim.id,{expectedRevision:4,rationale})).rejects.toMatchObject({status:409});
 });
 it("returns bounded minimal revocation metadata with flags off and company paused, without source admission",async()=>{
  const d=await reviewed();await disableV8Rollout(db);await db.update(companies).set({status:"paused"}).where(eq(companies.id,companyId));
  await expect(service().detail(companyId,actor,d.claim.id)).rejects.toMatchObject({status:404});
  const controls=await service().controls(companyId,actor);expect(controls.items).toEqual([{id:d.claim.id,companyId,revision:2,status:"hypothesis"}]);expect(controls.coverage).toBe("bounded_native_revocation_metadata");
  const response=await request(app()).get(`/api/companies/${companyId}/causal-claims/controls?expectedUserId=local-board`).expect(200);expect(response.headers["cache-control"]).toBe("no-store");expect(response.body.items).toEqual(controls.items);
  await request(app()).get(`/api/companies/${companyId}/causal-claims/controls?includeProse=true`).expect(400);await request(app()).get(`/api/companies/${companyId}/causal-claims/controls?expectedUserId=other`).expect(409);
  await service().revoke(companyId,actor,d.claim.id,{expectedRevision:2,rationale});expect((await service().controls(companyId,actor)).items).toHaveLength(0);
 });
 it("native company purge clears causal descendants with flags off and preserves a foreign tenant",async()=>{
  const d=await reviewed();await service().analyze(companyId,actor,d.claim.id,{expectedRevision:2,versionId:d.version.id});await disableV8Rollout(db);await purgeCompanyContent(db,companyId,{operationId:randomUUID()});for(const table of [causalClaims,causalClaimVersions,causalClaimReviews,causalAnalysisRuns])expect(await db.select().from(table).where(eq(table.companyId,companyId))).toHaveLength(0);expect(await db.select().from(companies).where(eq(companies.id,otherId))).toHaveLength(1);
 });
 it.runIf(!!process.env.PAPERCLIP_DOWHY_PYTHON)("optional provider metadata is current-account/company-bound, strict and disabled by default",async()=>{
  const base=`/api/companies/${companyId}/causal-claims/provider-profile`;
  await request(app()).get(base).expect(404);await instanceSettingsService(db,{runtimeEnv:{}}).updateExperimental({...flags,causal_provider_dowhy_v8:true});
  const response=await request(app()).get(base+"?expectedUserId=local-board").expect(200);expect(response.headers["cache-control"]).toBe("no-store");expect(response.body).toMatchObject({provider:"dowhy",version:"0.14",python:"3.12.14",bundleHash:expect.stringMatching(/^[0-9a-f]{64}$/),conformanceHash:expect.stringMatching(/^[0-9a-f]{64}$/)});
  await request(app()).get(base+"?expectedUserId=changed-account").expect(409);await request(app()).get(base+"?graph=arbitrary").expect(400);await expect(service().providerProfile(randomUUID(),actor)).rejects.toMatchObject({status:404});
 });
 it("public commands are strict, account-bound and no-store without accepting caller effects or quality flags",async()=>{
  const f=await proposal(),api=app(),base=`/api/companies/${companyId}/causal-claims`;const valid={key:"native_api_claim",definition:f.model};await request(api).post(base).send({...valid,result:{status:"supported",effect:1}}).expect(400);await request(api).post(base).send({...valid,definition:{...f.model,confidence:0.99}}).expect(400);await request(api).post(base+"?expectedUserId=changed-account").send(valid).expect(409);
  const response=await request(api).post(base+"?expectedUserId=local-board").send(valid).expect(201);expect(response.headers["cache-control"]).toBe("no-store");await request(api).get(base+"?includePrivate=true").expect(400);const detail=await request(api).get(base+"/"+response.body.claim.id+"?expectedUserId=local-board").expect(200);expect(detail.headers["cache-control"]).toBe("no-store");expect(detail.body.versions[0].run).toBeNull();expect(detail.body.versions[0].review).toBeNull();
 });
});
