import { randomUUID } from "node:crypto";
import express from "express";
import request from "supertest";
import { and, eq, sql } from "drizzle-orm";
import { analyticalLineageManifests, companies, goals, issues, projects, managementReviewSnapshots, managementReviewEvents, managementReviewSourceLinks, memoryBindings, memoryRecords, memoryEvidence, type Db, createDb } from "@paperclipai/db";
import { managementReviewDefinitionSchema, type ManagementReviewDefinition } from "@paperclipai/shared";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { managementReviewService } from "../services/management-reviews/service.js";
import { managementReviewRoutes } from "../routes/management-reviews.js";
import { instanceSettingsService } from "../services/instance-settings.js";
import { aiGovernanceService } from "../services/ai-governance/governance-service.js";
import { businessMetricService } from "../services/business-metrics/service.js";
import { analyticalPurpose, metricDefinition } from "./helpers/business-metric-fixture.js";
import { disableV8Rollout } from "./helpers/v8-rollout.js";
import { getEmbeddedPostgresTestSupport, startEmbeddedPostgresTestDatabase } from "./helpers/embedded-postgres.js";
import { eraseAnalyticalSourcesUnderMemory } from "../services/analytical-source-erasure.js";
import { lockMemoryPrivacy } from "../services/memory/memory-privacy.js";
import { learningService } from "../services/learning/learning-service.js";
import { purgeMemoryRecords } from "../services/memory/memory-privacy.js";
import { purgeCompanyContent } from "../services/saas/company-purge.js";
import { errorHandler } from "../middleware/index.js";
const support = await getEmbeddedPostgresTestSupport(), actor = { type: "board" as const, source: "local_implicit" as const }, rationale = "Synthetic native management software qualification; no business-impact or collected outcome claim";
describe.skipIf(!support.supported)("Native historical management review owner on PostgreSQL", () => {
  let database: Awaited<ReturnType<typeof startEmbeddedPostgresTestDatabase>>, db: Db, companyId: string, otherId: string, policyId: string;
  beforeAll(async () => { process.env.PAPERCLIP_DECISION_SIGNING_SECRET = "0123456789abcdef0123456789abcdef"; database = await startEmbeddedPostgresTestDatabase("aw-v8-management-reviews-"); db = createDb(database.connectionString); });
  afterAll(async () => { await database?.cleanup(); });
  beforeEach(async () => { await instanceSettingsService(db, { runtimeEnv: {} }).updateExperimental({ enableFoundationV1: true, project_roadmap_v5: true, analytical_lineage_v8: true, business_metrics_v8: true, management_reviews_v8: true, ai_use_cases_v7: true, governance_evidence_v7: true }); companyId = randomUUID(); otherId = randomUUID(); await db.insert(companies).values([{ id: companyId, name: "Synthetic native management", issuePrefix: randomUUID() }, { id: otherId, name: "Foreign native source", issuePrefix: randomUUID() }]); const policy = analyticalPurpose(); policy.analyticalPurpose!.capabilities = ["metrics", "reviews"]; policyId = (await aiGovernanceService(db).obligation(actor, companyId, policy)).id; });
  async function fixture() { const [goal] = await db.insert(goals).values({ companyId, title: "Native source goal", status: "planned" }).returning(); const now = new Date(), from = new Date(now.getTime() - 86400000).toISOString(), until = now.toISOString(); const definition = managementReviewDefinitionSchema.parse({ name: "Human cited leadership review", reviewType: "weekly_leadership", period: { from, until }, purpose: "management_intelligence", sensitivity: "internal", retentionDays: 1, governanceObligationRefs: [policyId], sources: [{ key: "goal", source: { kind: "canonical", reference: { type: "goal", id: goal!.id } } }], agenda: [{ key: "inspect", category: "INVESTIGATE", ownerUserId: "local-board", dueAt: new Date(now.getTime() + 86400000).toISOString(), sourceKeys: ["goal"], nextAction: rationale, hypothesis: "Human suspects a constraint; this remains an unverified hypothesis" }] }); return { goal: goal!, definition }; }
  const publish = (id: string, hash: string, supersedesId: string | null = null) => managementReviewService(db).publish(companyId, actor, id, { expectedContentHash: hash, rationale, evidenceAndUncertaintyAcknowledged: true, supersedesId });
  it("captures immutable cited native state without changing a Goal or dispatching a task", async () => { const f = await fixture(), result = await managementReviewService(db).create(companyId, actor, f.definition), detail = await managementReviewService(db).detail(companyId, actor, result.id); expect(detail.status).toBe("draft"); expect(detail.currentQualification).toBe("current"); expect(detail.packet.claims[0]!.facts.status).toBe("planned"); expect(detail.packet.agenda[0]!.hypothesisAuthority).toBe("human_hypothesis"); expect(detail.packet.executionAuthority).toBe("read_only_historical_review"); expect((await db.select().from(goals).where(eq(goals.id, f.goal.id)))[0]!.status).toBe("planned"); });
  it("requires exact current content and one separate human publication under concurrent review", async () => { const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition); await expect(publish(created.id, "0".repeat(64))).rejects.toMatchObject({ status: 409 }); const outcomes = await Promise.allSettled([publish(created.id, created.contentHash), publish(created.id, created.contentHash)]); expect(outcomes.filter(outcome => outcome.status === "fulfilled")).toHaveLength(1); expect(outcomes.filter(outcome => outcome.status === "rejected")).toHaveLength(1); expect((await managementReviewService(db).detail(companyId, actor, created.id)).status).toBe("published"); });
  it("preserves original state after source change and blocks publication until a fresh capture", async () => { const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition), original = (await managementReviewService(db).detail(companyId, actor, created.id)).packet; await db.update(goals).set({ status: "in_progress", updatedAt: new Date() }).where(eq(goals.id, f.goal.id)); const detail = await managementReviewService(db).detail(companyId, actor, created.id); expect(detail.currentQualification).toBe("needs_revalidation"); expect(detail.packet).toEqual(original); expect(detail.packet.claims[0]!.facts.status).toBe("planned"); await expect(publish(created.id, created.contentHash)).rejects.toMatchObject({ status: 409 }); });
  it("supersedes an explicitly selected published packet without rewriting its historical material", async () => { const f = await fixture(), first = await managementReviewService(db).create(companyId, actor, f.definition); await publish(first.id, first.contentHash); const old = await managementReviewService(db).detail(companyId, actor, first.id); const second = await managementReviewService(db).create(companyId, actor, f.definition); await publish(second.id, second.contentHash, first.id); const retained = await managementReviewService(db).detail(companyId, actor, first.id); expect(retained.status).toBe("superseded"); expect(retained.packet).toEqual(old.packet); expect(retained.sources).toEqual(old.sources); });
  it("rejects direct material rewrites and records only bounded explicit human event reports", async () => { const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition); await expect(db.update(managementReviewSnapshots).set({ definition: { ...f.definition, name: "Rewritten historical prose" } }).where(eq(managementReviewSnapshots.id, created.id))).rejects.toMatchObject({ cause: { code: "23514" } }); await publish(created.id, created.contentHash); const event = await managementReviewService(db).recordEvent(companyId, actor, created.id, { expectedContentHash: created.contentHash, itemKey: "inspect", event: "false_alarm", rationale }); expect(event.interpretation).toBe("human_reported_event"); expect((await managementReviewService(db).detail(companyId, actor, created.id)).events[0]!.interpretation).toBe("human_reported_event"); await expect(db.update(managementReviewEvents).set({ rationale: "Changed" }).where(eq(managementReviewEvents.id, event.id))).rejects.toMatchObject({ cause: { code: "23514" } }); await expect(managementReviewService(db).recordEvent(companyId, actor, created.id, { expectedContentHash: created.contentHash, itemKey: "unknown", event: "acted_on", rationale })).rejects.toMatchObject({ status: 409 }); });
  it("erases the whole historical review and copied event prose through native primitive erasure while flags are off and company paused", async () => { const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition); await publish(created.id, created.contentHash); await managementReviewService(db).recordEvent(companyId, actor, created.id, { expectedContentHash: created.contentHash, itemKey: "inspect", event: "opened", rationale }); await disableV8Rollout(db); await db.update(companies).set({ status: "paused" }).where(eq(companies.id, companyId)); await db.transaction(async raw => { const tx = raw as unknown as Db; await lockMemoryPrivacy(tx, companyId); await eraseAnalyticalSourcesUnderMemory(tx, companyId, "goal", [f.goal.id]); }); expect(await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.id, created.id))).toHaveLength(0); expect(await db.select().from(managementReviewEvents).where(eq(managementReviewEvents.reviewId, created.id))).toHaveLength(0); expect(await db.select().from(goals).where(eq(goals.id, f.goal.id))).toHaveLength(1); });
  it("inherits an exact native observation and cascades whole-review erasure from its original manifest", async () => { const f = await fixture(), metric = await businessMetricService(db).create(companyId, actor, { key: "review_metric", definition: metricDefinition(policyId) }); await businessMetricService(db).publish(companyId, actor, metric.metric.id, { expectedRevision: metric.metric.revision, versionId: metric.version.id }); const observation = await businessMetricService(db).query(companyId, actor, { metricId: metric.metric.id, versionId: metric.version.id, from: f.definition.period.from, until: f.definition.period.until, dimensions: [], maxRows: 5000 }); f.definition.sources.push({ key: "actual", source: { kind: "analytical", reference: { type: "metric_observation", id: observation.id, metricId: observation.metricId, metricVersionId: observation.versionId } } }); f.definition.agenda[0]!.sourceKeys.push("actual"); const created = await managementReviewService(db).create(companyId, actor, f.definition), detail = await managementReviewService(db).detail(companyId, actor, created.id); expect(detail.sources.find(source => source.key === "actual")!.facts.value).toBe(observation.value); await db.delete(analyticalLineageManifests).where(and(eq(analyticalLineageManifests.companyId, companyId), eq(analyticalLineageManifests.id, observation.lineageManifestId))); expect(await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.id, created.id))).toHaveLength(0); });
  it("reauthorizes every original project task before disclosing retained aggregate facts", async () => { const f = await fixture(), [project] = await db.insert(projects).values({ companyId, name: "Native current Roadmap source" }).returning(), [task] = await db.insert(issues).values({ companyId, projectId: project!.id, title: "Retained task source", status: "todo", responsibleUserId: "local-board" }).returning(); f.definition.sources.push({ key: "roadmap", source: { kind: "canonical", reference: { type: "project", id: project!.id } } }); const created = await managementReviewService(db).create(companyId, actor, f.definition); expect((await managementReviewService(db).detail(companyId, actor, created.id)).currentQualification).toBe("current"); await db.update(issues).set({ hiddenAt: new Date() }).where(eq(issues.id, task!.id)); await expect(managementReviewService(db).detail(companyId, actor, created.id)).rejects.toMatchObject({ status: 404 }); });
  it("binds strict HTTP/account inputs and exposes only independent native metadata with disabled rollout", async () => { const f = await fixture(), app = express(); app.use(express.json()); app.use((req, _res, next) => { req.actor = { ...actor, userId: "operator" }; next(); }); app.use(managementReviewRoutes(db)); app.use(errorHandler); const base = `/companies/${companyId}/management-reviews`; const bad = await request(app).post(`${base}?expectedUserId=other`).send(f.definition); expect(bad.status).toBe(409); expect((await request(app).post(base).send({ ...f.definition, facts: { favorable: 1 } })).status).toBe(400); const created = await request(app).post(`${base}?expectedUserId=operator`).send(f.definition); expect(created.status, JSON.stringify(created.body)).toBe(201); expect(created.headers["cache-control"]).toBe("no-store"); expect((await request(app).get(`${base}/${created.body.id}?unexpected=1`)).status).toBe(400); await disableV8Rollout(db); expect((await request(app).get(`${base}/${created.body.id}`)).status).toBe(404); const controls = await request(app).get(`${base}/controls?expectedUserId=operator`); expect(controls.status).toBe(200); expect(JSON.stringify(controls.body)).not.toContain(f.definition.name); expect(Object.keys(controls.body.items[0]).sort()).toEqual(["createdAt", "expiresAt", "id", "status"]); });
  it("rejects agent authors and cross-company source pins without inserting review prose", async () => { const f = await fixture(), [foreign] = await db.insert(goals).values({ companyId: otherId, title: "Foreign hidden source" }).returning(); await expect(managementReviewService(db).create(companyId, { type: "agent", agentId: randomUUID(), source: "agent_jwt" }, f.definition)).rejects.toMatchObject({ status: 403 }); f.definition.sources[0]!.source = { kind: "canonical", reference: { type: "goal", id: foreign!.id } }; await expect(managementReviewService(db).create(companyId, actor, f.definition)).rejects.toMatchObject({ status: 404 }); expect(await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.companyId, companyId))).toHaveLength(0); });
  it("inherits surviving verified native Learning roots and erases the entire copied review when a Memory root is purged", async () => {
    const f = await fixture(); await instanceSettingsService(db).updateExperimental({ enableContextEngineV1: true, skill_lifecycle_v5: true, playbooks_v5: true, enableCollectiveMemoryV1: true, cognitive_memory_v7: true, memory_observations_v7: true, learning_engine_v7: true });
    const [task] = await db.insert(issues).values({ companyId, title: "Synthetic verified Task software fixture", status: "done", completedAt: new Date(), responsibleUserId: "local-board" }).returning();
    const [binding] = await db.insert(memoryBindings).values({ companyId, key: "management_source", name: "Native verified source fixture", providerKey: "local" }).returning();
    const [memory] = await db.insert(memoryRecords).values({ companyId, bindingId: binding!.id, providerKey: "local", memoryType: "outcome", scopeType: "company", content: "Synthetic verified native Task root for software qualification only", reviewState: "accepted", verificationState: "human_verified", observedAt: new Date(), createdByActorType: "system", createdByActorId: "fixture" }).returning();
    await db.insert(memoryEvidence).values({ companyId, memoryRecordId: memory!.id, sourceClass: "task", sourceProvider: "august_works_tasks", sourceType: "issue", sourceRef: `issue://${task!.id}`, sourceVersion: "1", observedAt: new Date(), excerptHash: "a".repeat(64), citationJson: { label: "Synthetic native fixture" }, trustLevel: "high", supportsOrContradicts: "supports" });
    const cycle = await learningService(db).create(actor, companyId, { scope: { type: "company", id: null }, purpose: "native_task_execution", trigger: rationale, memoryRecordIds: [memory!.id] });
    f.definition.sources.push({ key: "learning", source: { kind: "learning_cycle", id: cycle.id, expectedVersion: cycle.version } });
    const created = await managementReviewService(db).create(companyId, actor, f.definition), detail = await managementReviewService(db).detail(companyId, actor, created.id);
    expect(detail.sources.find(source => source.key === "learning")!.grade).toBe("native_learning_cycle");
    await disableV8Rollout(db); await db.update(companies).set({ status: "paused" }).where(eq(companies.id, companyId));
    await db.transaction(async raw => { const tx = raw as unknown as Db; await lockMemoryPrivacy(tx, companyId); await purgeMemoryRecords(tx, companyId, [memory!.id]); });
    expect(await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.id, created.id))).toHaveLength(0);
    expect((await db.select().from(issues).where(eq(issues.id, task!.id)))[0]!.status).toBe("done");
  });
  it("purges published review/event content with disabled rollout and a paused company while preserving a foreign Goal", async () => {
    const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition); await publish(created.id, created.contentHash);
    await managementReviewService(db).recordEvent(companyId, actor, created.id, { expectedContentHash: created.contentHash, itemKey: "inspect", event: "opened", rationale });
    const [foreign] = await db.insert(goals).values({ companyId: otherId, title: "Foreign surviving canonical Goal" }).returning();
    await disableV8Rollout(db); await db.update(companies).set({ status: "paused" }).where(eq(companies.id, companyId));
    await purgeCompanyContent(db, companyId);
    expect(await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.companyId, companyId))).toHaveLength(0);
    expect(await db.select().from(managementReviewEvents).where(eq(managementReviewEvents.companyId, companyId))).toHaveLength(0);
    expect(await db.select().from(goals).where(eq(goals.id, foreign!.id))).toHaveLength(1);
  });

  it("rejects a copied valid proof attached to a different native snapshot identity", async () => {
    const f = await fixture(), created = await managementReviewService(db).create(companyId, actor, f.definition);
    const [row] = await db.select().from(managementReviewSnapshots).where(eq(managementReviewSnapshots.id, created.id));
    const [manifest] = await db.select().from(analyticalLineageManifests).where(eq(analyticalLineageManifests.id, row!.lineageManifestId));
    const fakeId = randomUUID(), fakeManifestId = randomUUID();
    await db.transaction(async tx => {
      await tx.insert(analyticalLineageManifests).values({ ...manifest!, id: fakeManifestId, analysisRef: fakeId });
      await tx.execute(sql`insert into analytical_lineage_edges(company_id,manifest_id,input_type,input_ref,input_hash,relationship) select company_id,${fakeManifestId}::uuid,input_type,input_ref,input_hash,relationship from analytical_lineage_edges where company_id=${companyId}::uuid and manifest_id=${manifest!.id}::uuid`);
      await tx.insert(managementReviewSnapshots).values({ ...row!, id: fakeId, lineageManifestId: fakeManifestId });
      const links = await tx.select().from(managementReviewSourceLinks).where(eq(managementReviewSourceLinks.reviewId, created.id));
      await tx.insert(managementReviewSourceLinks).values(links.map(link => ({ ...link, reviewId: fakeId })));
    });
    await expect(managementReviewService(db).detail(companyId, actor, fakeId)).rejects.toMatchObject({ status: 404 });
    await expect(publish(fakeId, created.contentHash)).rejects.toMatchObject({ status: 404 });
  });

});
