import { describe, expect, it } from "vitest";
import { managementReviewDefinitionSchema, type CapturedManagementSource, type BusinessMetricResult } from "@paperclipai/shared";
import { composeManagementReview } from "../services/management-reviews/kernel.js";
const id = "00000000-0000-4000-8000-000000009901", asOf = "2026-10-07T12:00:00Z";
function fixture() {
  const source = { kind: "canonical" as const, reference: { type: "project" as const, id } };
  const definition = managementReviewDefinitionSchema.parse({ name: "Synthetic cited review", reviewType: "ad_hoc", period: { from: "2026-10-01T00:00:00Z", until: asOf }, purpose: "management_intelligence", sensitivity: "internal", retentionDays: 1, governanceObligationRefs: [id], sources: [{ key: "roadmap", source }], agenda: [{ key: "inspect", category: "INVESTIGATE", ownerUserId: "human", dueAt: asOf, sourceKeys: ["roadmap"], nextAction: "Inspect the admitted project constraints", hypothesis: "Human suspects an unresolved capacity condition" }] });
  const captured: CapturedManagementSource = { key: "roadmap", source, sourceHash: "a".repeat(64), capturedAt: asOf, expiresAt: "2026-10-08T12:00:00Z", grade: "native_current_state", facts: { health: "unknown", completionVarianceDays: null }, limitations: ["Synthetic software fixture only; no verified business impact"] };
  return { definition, captured };
}
describe("Deterministic cited management skeleton", () => {
  it("preserves unknown facts, explicit human hypotheses and the selected coverage without quota invention", () => { const { definition, captured } = fixture(), result = composeManagementReview(definition, [captured], asOf); expect(result.claims).toHaveLength(1); expect(result.claims[0].facts.completionVarianceDays).toBeNull(); expect(result.agenda[0].hypothesisAuthority).toBe("human_hypothesis"); expect(result.agenda[0].interpretation).toBe("human_declared_agenda"); expect(result.executionAuthority).toBe("read_only_historical_review"); expect(result.limitations.join(" ")).toContain("no facts are invented"); });
  it("rejects missing, duplicated or mismatched native pins and unsupported citations", () => { const { definition, captured } = fixture(); expect(() => composeManagementReview(definition, [], asOf)).toThrow(); expect(() => composeManagementReview(definition, [{ ...captured, source: { kind: "canonical", reference: { type: "goal", id } } }], asOf)).toThrow("Exact unique"); expect(() => composeManagementReview(definition, [captured, captured], asOf)).toThrow(); expect(managementReviewDefinitionSchema.safeParse({ ...definition, agenda: [{ ...definition.agenda[0], sourceKeys: ["missing"] }] }).success).toBe(false); });
  it("rejects expired/future source captures and nonfinite or oversized scalar facts", () => { const { definition, captured } = fixture(); for (const patch of [{ expiresAt: asOf }, { capturedAt: "2026-10-08T12:00:00Z" }, { facts: { value: NaN } }, { facts: { text: "x".repeat(4001) } }]) expect(() => composeManagementReview(definition, [{ ...captured, ...patch }], asOf)).toThrow(); });
  it("keeps forecasts conditional and prevents a caller from relabeling them as observations", () => { const { definition, captured } = fixture(), source = { kind: "analytical" as const, reference: { type: "forecast_run" as const, id, specId: id, versionId: id, pointIndex: 0 } }; definition.sources[0].source = source; const forecast: CapturedManagementSource = { ...captured, source, grade: "predictive", facts: { value: 3, intervalLower: null, calibration: "not_assessed" } }; expect(composeManagementReview(definition, [forecast], asOf).claims[0].grade).toBe("predictive"); expect(() => composeManagementReview(definition, [{ ...forecast, grade: "native_observation" }], asOf)).toThrow("cannot be relabeled"); });
  it("keeps historical bytes unchanged after caller mutation and computes stable hashes", () => { const { definition, captured } = fixture(), original = JSON.stringify({ definition, captured }), result = composeManagementReview(definition, [captured], asOf); expect(JSON.stringify({ definition, captured })).toBe(original); expect(composeManagementReview(definition, [captured], asOf).contentHash).toBe(result.contentHash); captured.facts.health = "changed"; definition.agenda[0].nextAction = "Different human action"; expect(result.claims[0].facts.health).toBe("unknown"); expect(result.agenda[0].nextAction).toBe("Inspect the admitted project constraints"); });
  it("preserves explicit human agenda order without a score and bounds source/agenda cardinality", () => { const { definition, captured } = fixture(); definition.agenda.push({ ...definition.agenda[0], key: "second", category: "NO_ACTION", hypothesis: null }); const result = composeManagementReview(definition, [captured], asOf); expect(result.agenda.map(item => item.key)).toEqual(["inspect", "second"]); expect(result.agenda[1].hypothesisAuthority).toBe("none"); expect(managementReviewDefinitionSchema.safeParse({ ...definition, agenda: Array.from({ length: 11 }, (_, i) => ({ ...definition.agenda[0], key: `item_${i}` })) }).success).toBe(false); expect(managementReviewDefinitionSchema.safeParse({ ...definition, content: "unsupported prose" }).success).toBe(false); });
  function metricPair() {
    const { definition, captured } = fixture();
    const actual: BusinessMetricResult = { id, companyId: id, metricId: id, versionId: id, from: "2026-10-01T00:00:00Z", until: "2026-10-02T00:00:00Z", asOf, expiresAt: captured.expiresAt, status: "observed", value: 0.4, reason: null, groups: [], inputHash: "1".repeat(64), definitionHash: "2".repeat(64), engineVersion: "fixture-only", lineageManifestId: id, sourceWatermark: asOf };
    const observation: CapturedManagementSource = { ...captured, key: "actual", source: { kind: "analytical", reference: { type: "metric_observation", id, metricId: id, metricVersionId: id } }, grade: "native_observation", facts: { value: 0.4 }, metric: { observation: actual, unit: "ratio", timeSemantics: "created_in_window_current_state" } };
    const target: CapturedManagementSource = { ...captured, key: "target", source: { kind: "canonical", reference: { type: "metric_target", id, versionId: id } }, facts: { threshold: 0.5 }, target: { id, versionId: id, definition: { metricId: id, metricVersionId: id, scope: { type: "company" }, periodStart: actual.from, periodEnd: actual.until, criterion: { kind: "at_least", value: 0.5 }, rationale: "Human approved synthetic threshold", assumptions: ["Native status is not impact"], ownerUserId: "human" } } };
    definition.sources = [{ key: "target", source: target.source }, { key: "actual", source: observation.source }]; definition.agenda[0].sourceKeys = ["target", "actual"]; definition.comparisons = [{ key: "commitment", kind: "target_actual", leftSourceKey: "target", rightSourceKey: "actual" }];
    return { definition, observation, target, actual };
  }
  it("compares an exact owner observation with an approved commitment while preserving both citations", () => { const f = metricPair(), result = composeManagementReview(f.definition, [f.target, f.observation], asOf); expect(result.claims.at(-1)).toMatchObject({ sourceKeys: ["target", "actual"], grade: "native_observation", facts: { status: "not_met", observedValue: 0.4 } }); expect(result.claims.at(-1)!.limitations.join(" ")).toContain("does not establish the cause"); f.target.target!.definition.periodEnd = "2026-10-08T00:00:00Z"; f.actual.until = f.target.target!.definition.periodEnd; expect(composeManagementReview(f.definition, [f.target, f.observation], asOf).claims.at(-1)!.facts.status).toBe("period_in_progress"); });
  it("keeps target comparison unknown for a wrong window or missing actual and rejects private identity substitution", () => { const f = metricPair(); f.actual.from = "2026-10-01T01:00:00Z"; expect(composeManagementReview(f.definition, [f.target, f.observation], asOf).claims.at(-1)!.facts).toMatchObject({ status: "unknown", observedValue: null, reason: "observation_definition_or_period_mismatch" }); f.actual.from = f.target.target!.definition.periodStart; f.actual.status = "undefined"; f.actual.value = null; expect(composeManagementReview(f.definition, [f.target, f.observation], asOf).claims.at(-1)!.facts.status).toBe("unknown"); f.actual.id = "00000000-0000-4000-8000-000000009902"; expect(() => composeManagementReview(f.definition, [f.target, f.observation], asOf)).toThrow("exact original"); });
  it("compares only consecutive equal windows and retains zero-baseline relative change as unknown", () => { const f = metricPair(), laterId = "00000000-0000-4000-8000-000000009902", earlier = { ...f.observation, key: "before" }, later = structuredClone(f.observation); later.key = "after"; later.source = { kind: "analytical", reference: { type: "metric_observation", id: laterId, metricId: id, metricVersionId: id } }; later.metric!.observation = { ...f.actual, id: laterId, from: f.actual.until, until: "2026-10-03T00:00:00Z", value: 0.6 }; earlier.metric!.observation.value = 0;
    f.definition.sources = [earlier, later].map(source => ({ key: source.key, source: source.source })); f.definition.agenda[0].sourceKeys = ["before", "after"]; f.definition.comparisons = [{ key: "change", kind: "metric_change", leftSourceKey: "before", rightSourceKey: "after" }];
    expect(composeManagementReview(f.definition, [earlier, later], asOf).claims.at(-1)!.facts).toMatchObject({ status: "observed_change", absoluteChange: 0.6, relativeChangeFraction: null, direction: "increase" }); later.metric!.observation.from = "2026-10-02T01:00:00Z"; expect(composeManagementReview(f.definition, [earlier, later], asOf).claims.at(-1)!.facts).toMatchObject({ status: "unknown", absoluteChange: null, reason: "windows_not_consecutive_and_equal" });
  });
  it("rejects a forecast or undeclared citation used as an actual comparison", () => { const f = metricPair(); f.definition.sources[1].source = { kind: "analytical", reference: { type: "forecast_run", id, specId: id, versionId: id, pointIndex: 0 } }; expect(managementReviewDefinitionSchema.safeParse(f.definition).success).toBe(false); const valid = metricPair(); valid.definition.comparisons![0].rightSourceKey = "missing"; expect(managementReviewDefinitionSchema.safeParse(valid.definition).success).toBe(false); });
});
