import { describe, expect, it } from "vitest";
import { managementReviewDefinitionSchema, type CapturedManagementSource } from "@paperclipai/shared";
import { composeManagementReview } from "../services/management-reviews/kernel.js";
const id = "00000000-0000-4000-8000-000000009901", asOf = "2026-10-07T12:00:00Z";
function fixture() {
  const source = { kind: "canonical" as const, reference: { type: "project" as const, id } };
  const definition = managementReviewDefinitionSchema.parse({ name: "Synthetic cited review", reviewType: "ad_hoc", period: { from: "2026-10-01T00:00:00Z", until: asOf }, purpose: "management_intelligence", sensitivity: "internal", retentionDays: 1, governanceObligationRefs: [id], sources: [{ key: "roadmap", source }], agenda: [{ key: "inspect", category: "INVESTIGATE", ownerUserId: "human", dueAt: asOf, sourceKeys: ["roadmap"], nextAction: "Inspect the admitted project constraints", hypothesis: "Human suspects an unresolved capacity condition" }] });
  const captured: CapturedManagementSource = { key: "roadmap", source, sourceHash: "a".repeat(64), capturedAt: asOf, expiresAt: "2026-10-08T12:00:00Z", grade: "native_current_state", facts: { health: "unknown", completionVarianceDays: null }, limitations: ["Synthetic software fixture only; no verified business impact"] };
  return { definition, captured };
}
describe("Deterministic cited management skeleton", () => {
  it("preserves unknown facts, explicit human hypotheses and the selected coverage without quota invention", () => { const { definition, captured } = fixture(), result = composeManagementReview(definition, [captured], asOf); expect(result.claims).toHaveLength(1); expect(result.claims[0].facts.completionVarianceDays).toBeNull(); expect(result.agenda[0].hypothesisAuthority).toBe("human_hypothesis"); expect(result.agenda[0].interpretation).toBe("human_declared_agenda"); expect(result.executionAuthority).toBe("read_only_historical_review"); expect(result.limitations.join(" ")).toContain("no facts are invented"); });
  it("rejects missing, duplicated or mismatched native pins and unsupported citations", () => { const { definition, captured } = fixture(); expect(() => composeManagementReview(definition, [], asOf)).toThrow(); expect(() => composeManagementReview(definition, [{ ...captured, source: { kind: "canonical", reference: { type: "goal", id } } }], asOf)).toThrow("Exact unique"); expect(() => composeManagementReview(definition, [captured, captured], asOf)).toThrow(); expect(managementReviewDefinitionSchema.safeParse({ ...definition, agenda: [{ ...definition.agenda[0], sourceKeys: ["missing"] }] }).success).toBe(false); });
  it("rejects expired/future source captures and nonfinite or oversized scalar facts", () => { const { definition, captured } = fixture(); for (const patch of [{ expiresAt: asOf }, { capturedAt: "2026-10-08T12:00:00Z" }, { facts: { value: NaN } }, { facts: { text: "x".repeat(4001) } }]) expect(() => composeManagementReview(definition, [{ ...captured, ...patch }], asOf)).toThrow(); });
  it("keeps forecasts conditional and prevents a caller from relabeling them as observations", () => { const { definition, captured } = fixture(), source = { kind: "analytical" as const, reference: { type: "forecast_run" as const, id, specId: id, versionId: id, pointIndex: 0 } }; definition.sources[0].source = source; const forecast: CapturedManagementSource = { ...captured, source, grade: "predictive", facts: { value: 3, intervalLower: null, calibration: "not_assessed" } }; expect(composeManagementReview(definition, [forecast], asOf).claims[0].grade).toBe("predictive"); expect(() => composeManagementReview(definition, [{ ...forecast, grade: "native_observation" }], asOf)).toThrow("cannot be relabeled"); });
  it("keeps historical bytes unchanged after caller mutation and computes stable hashes", () => { const { definition, captured } = fixture(), original = JSON.stringify({ definition, captured }), result = composeManagementReview(definition, [captured], asOf); expect(JSON.stringify({ definition, captured })).toBe(original); expect(composeManagementReview(definition, [captured], asOf).contentHash).toBe(result.contentHash); captured.facts.health = "changed"; definition.agenda[0].nextAction = "Different human action"; expect(result.claims[0].facts.health).toBe("unknown"); expect(result.agenda[0].nextAction).toBe("Inspect the admitted project constraints"); });
  it("preserves explicit human agenda order without a score and bounds source/agenda cardinality", () => { const { definition, captured } = fixture(); definition.agenda.push({ ...definition.agenda[0], key: "second", category: "NO_ACTION", hypothesis: null }); const result = composeManagementReview(definition, [captured], asOf); expect(result.agenda.map(item => item.key)).toEqual(["inspect", "second"]); expect(result.agenda[1].hypothesisAuthority).toBe("none"); expect(managementReviewDefinitionSchema.safeParse({ ...definition, agenda: Array.from({ length: 11 }, (_, i) => ({ ...definition.agenda[0], key: `item_${i}` })) }).success).toBe(false); expect(managementReviewDefinitionSchema.safeParse({ ...definition, content: "unsupported prose" }).success).toBe(false); });
});
