// @vitest-environment jsdom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { instanceExperimentalSettingsSchema,type Issue } from "@paperclipai/shared";
import { BusinessExperiments } from "./BusinessExperiments";
import { businessExperimentsApi } from "@/api/business-experiments";
import { businessMetricsApi } from "@/api/business-metrics";
import { instanceSettingsApi } from "@/api/instanceSettings";
import { issuesApi } from "@/api/issues";
import { experimentFixture } from "../../storybook/stories/business-experiment-fixtures";
const identity=vi.hoisted(()=>({companyId:"00000000-0000-4000-8000-000000000001",userId:"reviewer",settled:true,failed:false,breadcrumbs:vi.fn()}));
vi.mock("@/context/CompanyContext",()=>({useCompany:()=>({selectedCompanyId:identity.companyId})}));
vi.mock("@/api/companies-query",()=>({useAccountIdentity:()=>identity}));
vi.mock("@/context/BreadcrumbContext",()=>({useBreadcrumbs:()=>({setBreadcrumbs:identity.breadcrumbs})}));
vi.mock("@/lib/router",()=>({Link:({to,children}:{to:string;children:React.ReactNode})=><a href={to}>{children}</a>}));
vi.mock("@/api/instanceSettings",()=>({instanceSettingsApi:{getExperimental:vi.fn()}}));
vi.mock("@/api/business-experiments",()=>({businessExperimentsApi:{list:vi.fn(),detail:vi.fn(),create:vi.fn(),amend:vi.fn(),transition:vi.fn(),start:vi.fn(),assign:vi.fn(),exposure:vi.fn(),stop:vi.fn(),receipts:vi.fn(),analyze:vi.fn(),interpret:vi.fn(),safetyControls:vi.fn()}}));
vi.mock("@/api/business-metrics",()=>({businessMetricsApi:{list:vi.fn(),detail:vi.fn()}}));
vi.mock("@/api/ai-governance",()=>({aiGovernanceApi:{obligations:vi.fn(async()=>[experimentFixture().policy])}}));
vi.mock("@/api/projects",()=>({projectsApi:{list:vi.fn(async()=>[])}}));
vi.mock("@/api/issues",()=>({issuesApi:{list:vi.fn(async()=>[])}}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const flush=async()=>{await act(async()=>{await new Promise(r=>setTimeout(r,30));});};
async function mount(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),container=document.createElement("div");document.body.append(container);const root=createRoot(container);const render=async()=>{await act(async()=>root.render(<QueryClientProvider client={client}><BusinessExperiments/></QueryClientProvider>));await flush();};await render();return {client,container,render,cleanup:async()=>{await act(async()=>root.unmount());client.clear();container.remove();}};}
async function click(container:HTMLElement,label:string){const find=()=>[...container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label);for(let i=0;i<20&&(!find()||find()!.disabled);i++)await flush();expect(find(),label).toBeDefined();expect(find()!.disabled,label).toBe(false);await act(async()=>find()!.click());await flush();}
async function select(container:HTMLElement,label:string,value:string){ const ready = () => { const field = container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`); return field && !field.disabled && [...field.options].some(option => option.value === value); }; for (let attempt = 0; attempt < 40 && !ready(); attempt++) await flush(); expect(ready(), label).toBeTruthy(); await act(async()=>{const input=container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(input,label).toBeDefined();input.value=value;input.dispatchEvent(new Event("change",{bubbles:true}));});await flush();}
async function text(container:HTMLElement,label:string,value:string){await act(async()=>{const input=container.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;expect(input,label).toBeDefined();Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));});await flush();}
function responses(state:Parameters<typeof experimentFixture>[0]="draft",status:Parameters<typeof experimentFixture>[1]="inconclusive"){
 const f=experimentFixture(state,status);vi.mocked(businessExperimentsApi.list).mockResolvedValue({items:[{experiment:f.experiment,version:f.version}],nextCursor:null,coverage:"bounded_current_authorized_page"});vi.mocked(businessExperimentsApi.detail).mockResolvedValue({experiment:f.experiment,versions:[f.version],transitions:[],coverage:"bounded_recent_versions_and_transitions"});vi.mocked(businessExperimentsApi.receipts).mockResolvedValue(f.receipts);return f;
}
function sourceIssue(f:ReturnType<typeof experimentFixture>,unitId:string):Issue{return {id:unitId,companyId:f.companyId,projectId:null,projectWorkspaceId:null,goalId:null,parentId:null,title:"Authorized synthetic native unit",description:null,status:"todo",workMode:"standard",priority:"medium",reviewPolicy:null,assigneeAgentId:null,assigneeUserId:null,responsibleUserId:null,checkoutRunId:null,executionRunId:null,executionAgentNameKey:null,executionLockedAt:null,createdByAgentId:null,createdByUserId:null,issueNumber:1,identifier:"AW-1",requestDepth:0,billingCode:null,assigneeAdapterOverrides:null,executionWorkspaceId:null,executionWorkspacePreference:null,executionWorkspaceSettings:null,startedAt:null,completedAt:null,cancelledAt:null,hiddenAt:null,labels:[],labelIds:[],createdAt:new Date(Date.parse(f.version.definition.sampleOrDurationPlan.from)+1000),updatedAt:new Date()};}
beforeEach(()=>{vi.clearAllMocks();const f=responses();identity.companyId=f.companyId;identity.userId=f.userId;identity.settled=true;identity.failed=false;vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({analytical_lineage_v8:true,business_metrics_v8:true,business_experiments_v8:true,ai_use_cases_v7:true,governance_evidence_v7:true}));vi.mocked(businessExperimentsApi.safetyControls).mockResolvedValue({items:[],nextCursor:null,coverage:"bounded_active_recording_control_metadata"});vi.mocked(businessMetricsApi.list).mockResolvedValue({items:f.measurements.map(m=>m.metric),nextCursor:null});vi.mocked(businessMetricsApi.detail).mockImplementation(async(_companyId,id)=>{const m=f.measurements.find(m=>m.metric.id===id)!;return {metric:m.metric,versions:[m.version]};});vi.mocked(issuesApi.list).mockResolvedValue([]);});
describe("Native business experiment operator boundaries",()=>{
 it("amends only the exact unstarted protocol with a human reason and current native pins, without approval or recording",async()=>{
  const f=responses();vi.mocked(businessExperimentsApi.amend).mockResolvedValue({experiment:f.experiment,version:f.version});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await click(app.container,"Amend unstarted protocol");await text(app.container,"Hypothesis","Explicit changed hypothesis for this unstarted source-owned experiment");await text(app.container,"Amendment rationale","Human has reviewed the intended change before recording or approval");await click(app.container,"Save experiment proposal");expect(businessExperimentsApi.amend).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:1,reason:"Human has reviewed the intended change before recording or approval",definition:expect.objectContaining({primaryMetric:expect.objectContaining({metricId:f.measurements[0].metric.id,metricVersionId:f.measurements[0].version.id}),diagnostics:expect.objectContaining({invariantMetricRefs:[f.measurements[2].metric.id]}),analysisPlan:expect.objectContaining({finalCaptureMaxDelaySeconds:3600})})},f.userId);expect(businessExperimentsApi.start).not.toHaveBeenCalled();expect(businessExperimentsApi.transition).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("constructs a reasoned new proposal through native pickers with no pasted data or authority booleans",async()=>{
  const f=responses();vi.mocked(businessExperimentsApi.create).mockResolvedValue({experiment:f.experiment,version:f.version});const app=await mount();try{await click(app.container,"Preregister an experiment");await text(app.container,"Experiment reference","review_timing");await text(app.container,"Experiment name","Review timing process test");
   for(const label of ["Hypothesis","Decision question","Eligible population and exclusions","When a unit becomes eligible","Limits on applying results elsewhere","Treatment","Control","Primary metric success definition","Guardrail 1 success definition","Sample size and power rationale","Concurrent experiments and interference plan","Exposure, telemetry and identity plan","Novelty, seasonality and carryover limits","Emergency safety stop rule","Human ship decision policy","Rollback policy","Affected population and no-personal-impact rationale","Legal basis rationale","Fairness constraints"])await text(app.container,label,"Explicit human synthetic rationale for this registered software qualification proposal");
   await select(app.container,"Primary metric measure",f.measurements[0].metric.id);await select(app.container,"Guardrail 1 measure",f.measurements[1].metric.id);await select(app.container,"Pretreatment invariant 1",f.measurements[2].metric.id);await select(app.container,"Approved experiment purpose",f.policy.id);await text(app.container,"Recording start (UTC)",f.version.definition.sampleOrDurationPlan.from.replace(/Z$/,""));await text(app.container,"Fixed horizon end (UTC)",f.version.definition.sampleOrDurationPlan.until.replace(/Z$/,""));await click(app.container,"Save experiment proposal");const call=vi.mocked(businessExperimentsApi.create).mock.calls[0];expect(call[2]).toBe(f.userId);expect(call[1].definition).toMatchObject({ownerUserId:f.userId,primaryMetric:{metricId:f.measurements[0].metric.id,metricVersionId:f.measurements[0].version.id},ethics:{personImpact:"none",requiresConsent:false,changesMaterialAiDecisions:false}});expect(call[1]).not.toHaveProperty("result");expect(call[1]).not.toHaveProperty("integrity");expect(app.container.querySelector('[aria-label*="JSON"]')).toBeNull();expect(businessExperimentsApi.start).not.toHaveBeenCalled();
  }finally{await app.cleanup();}
 });
 it("requires explicit human preregistration approval and does not start on approval",async()=>{
  const f=responses("in_review");vi.mocked(businessExperimentsApi.transition).mockResolvedValue({...f.experiment,state:"ready",revision:3});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await text(app.container,"Human action rationale","Human reviewed this exact preregistered question and all safety bounds");await click(app.container,"Approve this preregistration");expect(businessExperimentsApi.transition).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:2,versionId:f.version.id,state:"ready",rationale:expect.any(String)},f.userId);expect(businessExperimentsApi.start).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("starts only the explicit reviewed recording mode with exact revision and human rationale",async()=>{
  const f=responses("ready");vi.mocked(businessExperimentsApi.start).mockResolvedValue({...f.experiment,state:"running",revision:4});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await text(app.container,"Human action rationale","Human records this exact approved business-object protocol");await click(app.container,"Start recording this protocol");expect(businessExperimentsApi.start).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:3,versionId:f.version.id,mode:"recording_only_human_attested_native_process",rationale:expect.any(String)},f.userId);expect(businessExperimentsApi.assign).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("attests not-applied exposure on its native assignment without accepting a caller-selected arm",async()=>{
  const f=responses("running"),assignment=f.receipts.assignments[0];f.receipts.exposures=[];vi.mocked(issuesApi.list).mockResolvedValue([sourceIssue(f,assignment.unitId)]);vi.mocked(businessExperimentsApi.exposure).mockResolvedValue(experimentFixture("running").receipts.exposures[0]);const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await select(app.container,"Assigned native unit",assignment.unitId);await text(app.container,"Human action rationale","Human confirms the described treatment was not applied to this unit");await click(app.container,"Save human exposure receipt");expect(businessExperimentsApi.exposure).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:4,versionId:f.version.id,assignmentId:assignment.id,exposure:{status:"not_applied",rationale:expect.any(String)}},f.userId);expect(vi.mocked(businessExperimentsApi.exposure).mock.calls[0][2]).not.toHaveProperty("arm");}finally{await app.cleanup();}
 });
 it("submits one final analysis with identities and CAS only",async()=>{
  const f=responses("completed");vi.mocked(businessExperimentsApi.analyze).mockResolvedValue({experiment:{...f.experiment,state:"analyzing",revision:6},analysis:f.analysis});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await click(app.container,"Capture and analyze once");expect(businessExperimentsApi.analyze).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:5,versionId:f.version.id},f.userId);expect(businessExperimentsApi.interpret).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("keeps conditional numerical evidence and explicit human interpretation separate from execution",async()=>{
  const f=responses("analyzing","pass");vi.mocked(businessExperimentsApi.interpret).mockResolvedValue({experiment:{...f.experiment,state:"decided",revision:7},interpretation:{id:"interpretation",analysisId:f.analysis.id,conclusion:"ship_candidate",rationale:"Human advisory decision rationale",executionAuthority:"advisory_only",receiptHash:"d".repeat(64),interpretedBy:f.userId,interpretedAt:f.analysis.analyzedAt}});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);expect(app.container.textContent).toContain("Registered benefit and safety bounds met");expect(app.container.textContent).toContain("human attestations");expect(app.container.textContent).toContain("percentage points");await select(app.container,"Human conclusion","ship_candidate");await text(app.container,"Human action rationale","Human reviewed the registered bounds and all conditional source limitations");await act(async()=>app.container.querySelector<HTMLInputElement>('[aria-label="Acknowledge result limitations and advisory authority"]')!.click());await flush();await click(app.container,"Save human interpretation");expect(businessExperimentsApi.interpret).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:6,versionId:f.version.id,analysisId:f.analysis.id,conclusion:"ship_candidate",rationale:expect.any(String),limitationsAcknowledged:true,executionAuthority:"advisory_only"},f.userId);}finally{await app.cleanup();}
 });
 it("withholds ship candidates for invalid evidence and explains absent effects",async()=>{
  const f=responses("analyzing","invalid"),app=await mount();try{await select(app.container,"Experiment",f.experiment.id);expect(app.container.textContent).toContain("Evidence does not meet the registered quality gates");expect(app.container.textContent).toContain("Causal reliance is withheld");const choices=app.container.querySelector<HTMLSelectElement>('[aria-label="Human conclusion"]')!;expect([...choices.options].map(o=>o.value)).toEqual(["abstain"]);expect(app.container.querySelector('[aria-label="Primary, guardrail and exploratory results"]')).toBeNull();}finally{await app.cleanup();}
 });
 it("account revalidation immediately withholds dependent result and controls",async()=>{
  const f=responses("analyzing","pass"),app=await mount();try{await select(app.container,"Experiment",f.experiment.id);expect(app.container.textContent).toContain("Registered benefit and safety bounds met");identity.settled=false;await app.render();expect(app.container.textContent).toContain("Verifying current account");expect(app.container.textContent).not.toContain(f.version.definition.hypothesis);expect(app.container.querySelector('[aria-label="Human conclusion"]')).toBeNull();}finally{await app.cleanup();}
 });
 it("Memory revocation clears sensitive protocol drafts and resets native source namespaces",async()=>{
  const f=responses(),app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await click(app.container,"Amend unstarted protocol");await text(app.container,"Hypothesis","Sensitive source-dependent draft that must be cleared");vi.mocked(businessExperimentsApi.list).mockResolvedValue({items:[],nextCursor:null,coverage:"bounded_current_authorized_page"});await act(async()=>window.dispatchEvent(new Event("memory-access-changed")));await flush();expect(app.container.textContent).not.toContain("Sensitive source-dependent draft");expect(app.container.querySelector('[aria-label="Experiment preregistration proposal"]')).toBeNull();expect(app.client.getQueryCache().findAll({queryKey:["experiment-definition-sources",f.companyId,f.userId]})).toHaveLength(0);}finally{await app.cleanup();}
 });
 it("does not rebind a retained primary to a changed published source version",async()=>{
  const f=responses(),m=f.measurements[0];vi.mocked(businessMetricsApi.detail).mockImplementation(async(_company,id)=>{const metric=f.measurements.find(m=>m.metric.id===id)!;return id===m.metric.id?{metric:{...m.metric,publishedVersionId:"00000000-0000-4000-8000-000000000799"},versions:[m.version,{...m.version,id:"00000000-0000-4000-8000-000000000799",revision:2}]}:{metric:metric.metric,versions:[metric.version]};});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);await click(app.container,"Amend unstarted protocol");await text(app.container,"Amendment rationale","Human must explicitly review changed native metric semantics");expect(app.container.textContent).toContain("published definition changed");const save=[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Save experiment proposal")!;expect(save.disabled).toBe(true);expect(businessExperimentsApi.amend).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("withholds dependent result and protocol controls when a receipt response has another tenant identity",async()=>{
  const f=responses("analyzing","pass");vi.mocked(businessExperimentsApi.receipts).mockResolvedValue({...f.receipts,analysis:{...f.analysis,companyId:"00000000-0000-4000-8000-000000000799"}});const app=await mount();try{await select(app.container,"Experiment",f.experiment.id);expect(app.container.textContent).not.toContain(f.version.definition.hypothesis);expect(app.container.textContent).not.toContain("Registered benefit and safety bounds met");expect(app.container.querySelector('[aria-label="Human result interpretation"]')).toBeNull();expect(businessExperimentsApi.interpret).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
 it("disabled rollout admits only exact human stopping metadata and cancellation",async()=>{
  const f=responses("running");vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({}));vi.mocked(businessExperimentsApi.safetyControls).mockResolvedValue({items:[{id:f.experiment.id,companyId:f.companyId,versionId:f.version.id,revision:4,state:"running"}],nextCursor:null,coverage:"bounded_active_recording_control_metadata"});vi.mocked(businessExperimentsApi.stop).mockResolvedValue({...f.experiment,state:"cancelled",revision:5});const app=await mount();try{expect(businessExperimentsApi.list).not.toHaveBeenCalled();expect(app.container.textContent).not.toContain(f.version.definition.hypothesis);await select(app.container,"Active recording",f.experiment.id);await text(app.container,"Stopping rationale","Human stops the active recording while rollout remains disabled");await click(app.container,"Cancel this active recording");expect(businessExperimentsApi.stop).toHaveBeenCalledWith(f.companyId,f.experiment.id,{expectedRevision:4,versionId:f.version.id,state:"cancelled",rationale:expect.any(String),completion:null},f.userId);expect(businessExperimentsApi.start).not.toHaveBeenCalled();}finally{await app.cleanup();}
 });
});
