// @vitest-environment jsdom
import {act} from "react";
import {createRoot} from "react-dom/client";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {BusinessForecasts} from "./BusinessForecasts";
import {businessForecastingApi} from "@/api/business-forecasting";
import {businessMetricsApi} from "@/api/business-metrics";
import {forecastFixture} from "../../storybook/stories/business-forecast-fixtures";
const identity=vi.hoisted(()=>({companyId:"00000000-0000-4000-8000-000000000001",userId:"reviewer",settled:true,failed:false,breadcrumbs:vi.fn()}));
vi.mock("@/context/CompanyContext",()=>({useCompany:()=>({selectedCompanyId:identity.companyId})}));
vi.mock("@/api/companies-query",()=>({useAccountIdentity:()=>identity}));
vi.mock("@/context/BreadcrumbContext",()=>({useBreadcrumbs:()=>({setBreadcrumbs:identity.breadcrumbs})}));
vi.mock("@/lib/router",()=>({Link:({to,children}:{to:string;children:React.ReactNode})=><a href={to}>{children}</a>}));
vi.mock("@/api/instanceSettings",()=>({instanceSettingsApi:{getExperimental:vi.fn(async()=>({analytical_lineage_v8:true,business_metrics_v8:true,business_forecasting_v8:true,ai_use_cases_v7:true,governance_evidence_v7:true}))}}));
vi.mock("@/api/business-forecasting",()=>({businessForecastingApi:{list:vi.fn(),detail:vi.fn(),create:vi.fn(),revise:vi.fn(),backtest:vi.fn(),publish:vi.fn(),run:vi.fn(),retire:vi.fn(),artifacts:vi.fn(),artifact:vi.fn()}}));
vi.mock("@/api/business-metrics",()=>({businessMetricsApi:{list:vi.fn(),detail:vi.fn(),observations:vi.fn()}}));
vi.mock("@/api/ai-governance",()=>({aiGovernanceApi:{obligations:vi.fn(async()=>[forecastFixture().policy])}}));
vi.mock("@/api/projects",()=>({projectsApi:{list:vi.fn(async()=>[])}}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const flush=async()=>{await act(async()=>{await new Promise(resolve=>setTimeout(resolve,30));});};
async function mount() {const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),container=document.createElement("div");document.body.append(container);const root=createRoot(container);const render=async()=>{await act(async()=>root.render(<QueryClientProvider client={client}><BusinessForecasts/></QueryClientProvider>));await flush();};await render();return {client,container,render,cleanup:async()=>{await act(async()=>root.unmount());client.clear();container.remove();}};}
async function click(container:HTMLElement,label:string) {const find=()=>[...container.querySelectorAll<HTMLButtonElement>("button")].find(value=>value.textContent===label);for(let attempt=0;attempt<20&&(!find()||find()!.disabled);attempt++) await flush();expect(find(),label).toBeDefined();expect(find()!.disabled,label).toBe(false);await act(async()=>find()!.click());await flush();}
async function select(container:HTMLElement,label:string,value:string) { const ready = () => { const field = container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`); return field && !field.disabled && [...field.options].some(option => option.value === value); }; for (let attempt = 0; attempt < 40 && !ready(); attempt++) await flush(); expect(ready(), label).toBeTruthy(); await act(async()=>{const input=container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`)!;input.value=value;input.dispatchEvent(new Event("change",{bubbles:true}));});await flush();}
async function text(container:HTMLElement,label:string,value:string) {await act(async()=>{const input=container.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));});await flush();}
beforeEach(()=>{vi.clearAllMocks();identity.userId="reviewer";identity.companyId=forecastFixture().companyId;identity.settled=true;identity.failed=false;const f=forecastFixture();vi.mocked(businessForecastingApi.list).mockResolvedValue({items:[f.spec],nextCursor:null,coverage:"bounded_current_authorized_page"});vi.mocked(businessForecastingApi.detail).mockResolvedValue({spec:f.spec,versions:[f.version]});vi.mocked(businessForecastingApi.artifacts).mockImplementation(async(_company,_id,kind)=>({items:kind==="backtest"?[f.backtest]:[],nextCursor:null,coverage:"bounded_current_authorized_page"}));vi.mocked(businessForecastingApi.artifact).mockImplementation(async(_company,_id,_artifact,kind)=>kind==="backtest"?f.backtest:f.run);vi.mocked(businessMetricsApi.list).mockResolvedValue({items:[f.metric],nextCursor:null});vi.mocked(businessMetricsApi.detail).mockResolvedValue({metric:f.metric,versions:[f.metricVersion]});vi.mocked(businessMetricsApi.observations).mockResolvedValue({items:f.observations,nextCursor:null,coverage:"bounded_current_authorized_page"});});
describe("Native business forecast operator authority",()=>{
 it("saves a human proposal with exact published metric pins without implicitly publishing or running",async()=>{
  const f=forecastFixture();vi.mocked(businessForecastingApi.create).mockResolvedValue({spec:f.spec,version:f.version});const app=await mount();try {await click(app.container,"Define a forecast");await text(app.container,"Forecast key","capacity_review");await text(app.container,"Forecast name","Native workload review");await text(app.container,"Business question","What workload should the capacity review consider?");await text(app.container,"Decision use","Support the separate human capacity planning decision");await text(app.container,"Known failure modes (one per line)","Current throughput does not establish useful business outcomes");await select(app.container,"Published native metric",f.metric.id);await select(app.container,"Approved forecast purpose",f.policy.id);await click(app.container,"Save forecast proposal");expect(businessForecastingApi.create).toHaveBeenCalledWith(f.companyId,{key:"capacity_review",definition:expect.objectContaining({metricId:f.metric.id,metricVersionId:f.metricVersion.id,ownerUserId:"reviewer",provider:"aw_native",baselines:[{kind:"naive"}]})},"reviewer");expect(businessForecastingApi.publish).not.toHaveBeenCalled();expect(businessForecastingApi.run).not.toHaveBeenCalled();} finally {await app.cleanup();}
 });
 it("captures only native observation identities with the expected specification revision",async()=>{
  const f=forecastFixture();vi.mocked(businessForecastingApi.backtest).mockResolvedValue(f.backtest);const app=await mount();try {await select(app.container,"Forecast specification",f.spec.id);await click(app.container,"Choose observation history");const minute=new Date().toISOString().slice(0,16);await text(app.container,"Forecast cutoff (UTC)",minute);await click(app.container,"Use loaded observations");await click(app.container,"Backtest this history");expect(businessForecastingApi.backtest).toHaveBeenCalledWith(f.companyId,f.spec.id,{expectedRevision:1,versionId:f.version.id,observationIds:f.observations.map(value=>value.id),cutoff:`${minute}:00.000Z`},"reviewer");expect(businessForecastingApi.publish).not.toHaveBeenCalled();expect(businessForecastingApi.run).not.toHaveBeenCalled();} finally {await app.cleanup();}
 });
 it("publishes only the reviewed exact backtest and current revision without running or changing commitments",async()=>{
  const f=forecastFixture();vi.mocked(businessForecastingApi.publish).mockResolvedValue(forecastFixture(true).spec);const app=await mount();try {await select(app.container,"Forecast specification",f.spec.id);await select(app.container,"Retained backtest",f.backtest.id);await text(app.container,"Human review rationale","Explicit human approval of this exact retained backtest");await click(app.container,"Publish this forecast version");expect(businessForecastingApi.publish).toHaveBeenCalledWith(f.companyId,f.spec.id,{expectedRevision:1,versionId:f.version.id,backtestId:f.backtest.id,rationale:"Explicit human approval of this exact retained backtest"},"reviewer");expect(businessForecastingApi.run).not.toHaveBeenCalled();} finally {await app.cleanup();}
 });
 it("requires a human rationale and qualified selected backtest; stale historical math cannot publish",async()=>{
  const f=forecastFixture(),stale={...f.backtest,currentQualification:"needs_revalidation" as const,reviewReason:"Native measurement history changed"};vi.mocked(businessForecastingApi.artifact).mockResolvedValue(stale);const app=await mount();try {await select(app.container,"Forecast specification",f.spec.id);await select(app.container,"Retained backtest",f.backtest.id);await text(app.container,"Human review rationale","Human review of a changed measurement history");const button=[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(value=>value.textContent==="Publish this forecast version")!;expect(button.disabled).toBe(true);expect(app.container.textContent).toContain("Native measurement history changed");expect(app.container.textContent).toContain("Prediction intervals: unavailable");expect(businessForecastingApi.publish).not.toHaveBeenCalled();} finally {await app.cleanup();}
 });
 it("hides retained facts during reauthorization and after denial instead of showing cached success",async()=>{
  const f=forecastFixture();const app=await mount();try {await select(app.container,"Forecast specification",f.spec.id);await select(app.container,"Retained backtest",f.backtest.id);expect(app.container.textContent).toContain("Recorded calculation: qualified");let reject!:(error:Error)=>void;vi.mocked(businessForecastingApi.artifact).mockImplementation(()=>new Promise((_resolve,denied)=>{reject=denied;}));let pending!:Promise<unknown>;await act(async()=>{pending=app.client.refetchQueries({queryKey:["business-forecasts",f.companyId,f.userId,"backtest",f.spec.id,f.backtest.id]});});await flush();expect(app.container.textContent).not.toContain("Recorded calculation: qualified");await act(async()=>{reject(new Error("Current source access denied"));await pending;});await flush();expect(app.container.textContent).not.toContain("Recorded calculation: qualified");expect(app.container.textContent).toContain("Current source access denied");} finally {await app.cleanup();}
 });
 it("clears private facts and unsaved proposals on native Memory events and account changes",async()=>{
  const f=forecastFixture();const app=await mount();try {await select(app.container,"Forecast specification",f.spec.id);await click(app.container,"Propose a forecast revision");await text(app.container,"Business question","Unsaved private forecast question for this account");await act(async()=>window.dispatchEvent(new Event("memory-access-changed")));await flush();expect(app.container.querySelector('form[aria-label="Forecast definition proposal"]')).toBeNull();vi.mocked(businessForecastingApi.list).mockResolvedValue({items:[],nextCursor:null,coverage:"bounded_current_authorized_page"});identity.userId="other-account";await app.render();expect(app.container.textContent).not.toContain("Daily delivery volume");expect(businessForecastingApi.list).toHaveBeenLastCalledWith(f.companyId,undefined,"other-account");} finally {await app.cleanup();}
 });
});
