// @vitest-environment jsdom
import {act} from "react";
import {createRoot} from "react-dom/client";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {instanceExperimentalSettingsSchema} from "@paperclipai/shared";
import {CausalClaims} from "./CausalClaims";
import {causalClaimsApi} from "@/api/causal-claims";
import {businessExperimentsApi} from "@/api/business-experiments";
import {businessMetricsApi} from "@/api/business-metrics";
import {aiGovernanceApi} from "@/api/ai-governance";
import {instanceSettingsApi} from "@/api/instanceSettings";
import {causalFixture} from "../../storybook/stories/causal-claim-fixtures";
const identity=vi.hoisted(()=>({companyId:"company",userId:"reviewer",settled:true,failed:false,breadcrumbs:vi.fn()}));
vi.mock("@/context/CompanyContext",()=>({useCompany:()=>({selectedCompanyId:identity.companyId})}));
vi.mock("@/api/companies-query",()=>({useAccountIdentity:()=>identity}));
vi.mock("@/context/BreadcrumbContext",()=>({useBreadcrumbs:()=>({setBreadcrumbs:identity.breadcrumbs})}));
vi.mock("@/api/instanceSettings",()=>({instanceSettingsApi:{getExperimental:vi.fn()}}));
vi.mock("@/api/causal-claims",()=>({causalClaimsApi:{list:vi.fn(),detail:vi.fn(),create:vi.fn(),revise:vi.fn(),review:vi.fn(),analyze:vi.fn(),revoke:vi.fn(),controls:vi.fn()}}));
vi.mock("@/api/business-experiments",()=>({businessExperimentsApi:{list:vi.fn(),detail:vi.fn(),receipts:vi.fn()}}));
vi.mock("@/api/business-metrics",()=>({businessMetricsApi:{list:vi.fn(),detail:vi.fn()}}));
vi.mock("@/api/ai-governance",()=>({aiGovernanceApi:{obligations:vi.fn()}}));
vi.mock("@/api/projects",()=>({projectsApi:{list:vi.fn(async()=>[])}}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const flush=async()=>{await act(async()=>{await new Promise(r=>setTimeout(r,30));});};
async function mount(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),container=document.createElement("div");document.body.append(container);const root=createRoot(container);const render=async()=>{await act(async()=>root.render(<QueryClientProvider client={client}><CausalClaims/></QueryClientProvider>));await flush();};await render();return {client,container,render,cleanup:async()=>{await act(async()=>root.unmount());client.clear();container.remove();}};}
async function click(container:HTMLElement,label:string){const find=()=>[...container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label);for(let i=0;i<20&&(!find()||find()!.disabled);i++)await flush();expect(find(),label).toBeDefined();expect(find()!.disabled,label).toBe(false);await act(async()=>find()!.click());await flush();}
async function select(container:HTMLElement,label:string,value:string){ const ready = () => { const field = container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`); return field && !field.disabled && [...field.options].some(option => option.value === value); }; for (let attempt = 0; attempt < 40 && !ready(); attempt++) await flush(); expect(ready(), label).toBeTruthy(); await act(async()=>{const input=container.querySelector<HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(input,label).toBeDefined();input.value=value;input.dispatchEvent(new Event("change",{bubbles:true}));});await flush();}
async function text(container:HTMLElement,label:string,value:string){await act(async()=>{const input=container.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;expect(input,label).toBeDefined();Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));});await flush();}
function responses(state:Parameters<typeof causalFixture>[0]="draft",stale=false){
 const f=causalFixture(state,stale);vi.mocked(causalClaimsApi.list).mockResolvedValue({items:[{claim:f.claim,version:f.causalVersion,run:f.claim.latestRunId?f.run:null}],nextCursor:null,coverage:"bounded_current_authorized_page"});vi.mocked(causalClaimsApi.detail).mockResolvedValue({claim:f.claim,versions:[{version:f.causalVersion,review:f.review,run:f.claim.latestRunId?f.run:null}],coverage:"bounded_recent_native_versions"});
 vi.mocked(businessExperimentsApi.list).mockResolvedValue({items:[{experiment:f.experiment,version:f.version}],nextCursor:null,coverage:"bounded_current_authorized_page"});vi.mocked(businessExperimentsApi.detail).mockResolvedValue({experiment:f.experiment,versions:[f.version],transitions:[],coverage:"bounded_recent_versions_and_transitions"});vi.mocked(businessExperimentsApi.receipts).mockResolvedValue(f.causalReceipts);
 vi.mocked(aiGovernanceApi.obligations).mockResolvedValue([f.policy]);vi.mocked(businessMetricsApi.list).mockResolvedValue({items:f.measurements.map(m=>m.metric),nextCursor:null});vi.mocked(businessMetricsApi.detail).mockImplementation(async(_company,id)=>{const m=f.measurements.find(m=>m.metric.id===id)!;return {metric:m.metric,versions:[m.version]};});return f;
}
beforeEach(()=>{vi.clearAllMocks();const f=responses();identity.companyId=f.companyId;identity.userId=f.userId;identity.settled=true;identity.failed=false;vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({analytical_lineage_v8:true,business_metrics_v8:true,business_experiments_v8:true,causal_claims_v8:true,ai_use_cases_v7:true,governance_evidence_v7:true}));vi.mocked(causalClaimsApi.controls).mockResolvedValue({items:[],nextCursor:null,coverage:"bounded_native_revocation_metadata"});});
describe("Human causal operator boundaries",()=>{
 it("starts a new human model with unknown assumptions and pins the exact interpreted source explicitly",async()=>{const f=responses();vi.mocked(causalClaimsApi.create).mockResolvedValue({claim:f.claim,version:f.causalVersion});const app=await mount();try{await click(app.container,"Record a causal question");expect(app.container.querySelector<HTMLSelectElement>('[aria-label="Interference between units"]')!.value).toBe("unknown");await text(app.container,"Claim key","review_completion");await text(app.container,"Claim name","Conditional process review");for(const label of ["Causal question","Human hypothesis","Arrow 1 human rationale","Assumption 1 rationale","Assumption 2 rationale","Assumption 3 rationale"])await text(app.container,label,"Explicit human software qualification rationale, with no collected causal evidence");await select(app.container,"Source experiment",f.experiment.id);const save=()=>[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Save human causal model")!;expect(save().disabled).toBe(true);await click(app.container,"Pin exact interpreted analysis");await select(app.container,"Approved causal purpose",f.policy.id);await click(app.container,"Save human causal model");expect(causalClaimsApi.create).toHaveBeenCalledWith(f.companyId,{key:"review_completion",definition:expect.objectContaining({experimentEvidence:f.causalVersion.definition.experimentEvidence,horizon:f.causalVersion.definition.horizon,assumptions:{noInterference:expect.objectContaining({status:"unknown"}),stableOutcomeMeasurement:expect.objectContaining({status:"unknown"}),registeredPopulationValidity:expect.objectContaining({status:"unknown"})}})},f.userId);expect(causalClaimsApi.review).not.toHaveBeenCalled();expect(causalClaimsApi.analyze).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("withholds a selected experiment whose human interpretation has the wrong analysis identity",async()=>{const f=responses();vi.mocked(businessExperimentsApi.receipts).mockResolvedValue({...f.causalReceipts,interpretation:{...f.causalReceipts.interpretation,analysisId:f.run.id}});const app=await mount();try{await click(app.container,"Record a causal question");await select(app.container,"Source experiment",f.experiment.id);await flush();expect(app.container.textContent).toContain("no current, exact human-interpreted analysis");expect([...app.container.querySelectorAll("button")].some(b=>b.textContent==="Pin exact interpreted analysis")).toBe(false);expect(causalClaimsApi.create).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("retains changed-source history while withholding new analysis and suppresses revoked results",async()=>{const f=responses("supported",true);const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);expect(app.container.textContent).toContain("retained result requires explicit source revalidation");expect([...app.container.querySelectorAll("button")].some(b=>b.textContent==="Interpret registered evidence once")).toBe(false);responses("revoked");await act(async()=>{await app.client.invalidateQueries({queryKey:["causal-claims",f.companyId,f.userId]});});await flush();expect(app.container.textContent).toContain("claim is revoked");expect(app.container.querySelector('[aria-label="Conditional causal result"]')).toBeNull();}finally{await app.cleanup();}});
 it("clears dependent source prose and proposal drafts after an authorization failure",async()=>{const f=responses("supported");const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);await click(app.container,"Revise human model and reset review");await text(app.container,"Human hypothesis","Private draft that must disappear after source denial");vi.mocked(causalClaimsApi.detail).mockRejectedValue(new Error("Source authority lost"));await act(async()=>{await app.client.invalidateQueries({queryKey:["causal-claims",f.companyId,f.userId]});});await flush();expect(app.container.textContent).not.toContain("Private draft");expect(app.container.querySelector('[aria-label="Conditional causal result"]')).toBeNull();expect(app.container.textContent).toContain("withheld");}finally{await app.cleanup();}});
 it("clears drafts and cached source namespaces on Memory access change",async()=>{const f=responses();const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);await click(app.container,"Revise human model and reset review");await text(app.container,"Human hypothesis","Sensitive causal proposal retained only under current Memory access");await act(async()=>window.dispatchEvent(new Event("memory-access-changed")));await flush();expect(app.container.textContent).not.toContain("Sensitive causal proposal");expect(app.client.getQueriesData({queryKey:["causal-definition-sources",f.companyId,f.userId]})).toHaveLength(0);expect(app.client.getQueriesData({queryKey:["experiment-definition-sources",f.companyId,f.userId]})).toHaveLength(0);}finally{await app.cleanup();}});
 it("disabled rollout exposes only independent exact human revocation controls",async()=>{const f=responses();vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({}));vi.mocked(causalClaimsApi.controls).mockResolvedValue({items:[{id:f.claim.id,companyId:f.companyId,revision:1,status:"hypothesis"}],nextCursor:null,coverage:"bounded_native_revocation_metadata"});vi.mocked(causalClaimsApi.revoke).mockResolvedValue({...f.claim,status:"revoked",revision:2});const app=await mount();try{expect(causalClaimsApi.list).not.toHaveBeenCalled();expect(app.container.textContent).not.toContain(f.causalVersion.definition.question);await select(app.container,"Claim control reference",f.claim.id);await text(app.container,"Revocation rationale","Human withdraws this causal claim while full rollout is disabled");await click(app.container,"Revoke this causal claim");expect(causalClaimsApi.revoke).toHaveBeenCalledWith(f.companyId,f.claim.id,{expectedRevision:1,rationale:expect.any(String)},f.userId);expect(causalClaimsApi.analyze).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("account switching removes the old company model and source drafts",async()=>{const f=responses();const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);await click(app.container,"Revise human model and reset review");await text(app.container,"Human hypothesis","Old account draft must be removed after account change");identity.userId="different-human";vi.mocked(causalClaimsApi.list).mockResolvedValue({items:[],nextCursor:null,coverage:"bounded_current_authorized_page"});await app.render();expect(app.container.textContent).not.toContain("Old account draft");expect(app.container.querySelector('[aria-label="Human causal model proposal"]')).toBeNull();expect(causalClaimsApi.list).toHaveBeenLastCalledWith(f.companyId,undefined,"different-human");}finally{await app.cleanup();}});
 it("requires a human rationale and explicit acknowledgment before exact model review",async()=>{const f=responses();vi.mocked(causalClaimsApi.review).mockResolvedValue({...f.claim,revision:2,reviewedVersionId:f.causalVersion.id});const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);const button=[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Record human model review")!;expect(button.disabled).toBe(true);await text(app.container,"Human review rationale","Human independently reviews this graph, source and conditional boundary");expect(button.disabled).toBe(true);await act(async()=>app.container.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await click(app.container,"Record human model review");expect(causalClaimsApi.review).toHaveBeenCalledWith(f.companyId,f.claim.id,{expectedRevision:1,versionId:f.causalVersion.id,rationale:expect.any(String),graphAndAssumptionsAcknowledged:true},f.userId);expect(causalClaimsApi.analyze).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("interprets only the separately reviewed current model without copied estimates or authority",async()=>{const f=responses("reviewed");vi.mocked(causalClaimsApi.analyze).mockResolvedValue({claim:{...f.claim,revision:3,status:"supported",latestRunId:f.run.id},run:f.run});const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);await click(app.container,"Interpret registered evidence once");expect(causalClaimsApi.analyze).toHaveBeenCalledWith(f.companyId,f.claim.id,{expectedRevision:2,versionId:f.causalVersion.id},f.userId);expect(causalClaimsApi.review).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("revises an exact source-pinned model with human rationale and refuses cyclic or duplicate arrows",async()=>{const f=responses();vi.mocked(causalClaimsApi.revise).mockResolvedValue({claim:f.claim,version:f.causalVersion});const app=await mount();try{await select(app.container,"Causal claim",f.claim.id);await click(app.container,"Revise human model and reset review");await text(app.container,"Model revision rationale","Human has reconsidered the exact causal graph and its assumptions");const save=()=>[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Save human causal model")!;for(let i=0;i<15&&save().disabled;i++)await flush();expect(save().disabled).toBe(false);expect(app.container.querySelector<HTMLSelectElement>('[aria-label="Causal outcome measure"]')!.disabled).toBe(true);await click(app.container,"Add assumed arrow");await text(app.container,"Arrow 2 human rationale","Explicit synthetic rationale for a second graph arrow");expect(save().disabled).toBe(true);await select(app.container,"Arrow 2 from","outcome");await select(app.container,"Arrow 2 to","assignment");expect(save().disabled).toBe(true);await click(app.container,"Remove arrow 2");await click(app.container,"Save human causal model");expect(causalClaimsApi.revise).toHaveBeenCalledWith(f.companyId,f.claim.id,{expectedRevision:1,rationale:expect.any(String),definition:expect.objectContaining({experimentEvidence:f.causalVersion.definition.experimentEvidence,horizon:f.causalVersion.definition.horizon,estimand:f.causalVersion.definition.estimand})},f.userId);expect(causalClaimsApi.analyze).not.toHaveBeenCalled();}finally{await app.cleanup();}});
});
