import { useCallback, useEffect, useState } from "react";
import { useInfiniteQuery, useIsFetching, useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { crossProjectPlanningProfileSchema, v7FeatureEnabled, v8FeatureEnabled, type CrossProjectPlanningProfile } from "@paperclipai/shared";
import { crossProjectPlanningApi, type JointPlanningPreview } from "@/api/cross-project-planning";
import { adaptivePlanningApi } from "@/api/adaptive-planning";
import { instanceSettingsApi } from "@/api/instanceSettings";
import { useAccountIdentity } from "@/api/companies-query";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { queryKeys } from "@/lib/queryKeys";
import { Link } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ProjectPlanningForm } from "@/components/ProjectPlanningForm";
import { ProjectPlanningResult } from "@/components/ProjectPlanningResult";
import { ProjectPlanningBasis } from "@/components/ProjectPlanningBasis";
const selectStyle = "w-full min-w-0 rounded-md border border-input bg-background p-2";
export function CrossProjectPlanning() {
  const { selectedCompanyId } = useCompany(), { userId, settled, failed } = useAccountIdentity(), { setBreadcrumbs } = useBreadcrumbs();
  const verifying = useIsFetching({ queryKey: queryKeys.auth.session }) > 0;
  const flags = useQuery({ queryKey: [...queryKeys.instance.experimentalSettings, "joint-planning", userId], queryFn: () => instanceSettingsApi.getExperimental(), enabled: !!selectedCompanyId && settled && !failed && !verifying, retry: false });
  useEffect(() => setBreadcrumbs([{ label: "Cross-project planning" }]), [setBreadcrumbs]);
  if (failed) return <p role="alert">Your account could not be verified. Reload this page.</p>;
  if (!settled || verifying) return <p role="status">Verifying current account…</p>;
  if (!selectedCompanyId) return <p>Select a company to inspect a joint planning proposal.</p>;
  const enabled = !flags.isFetching && !flags.isError && !!flags.data && v8FeatureEnabled(flags.data, "planning_optimizer_v8") && v7FeatureEnabled(flags.data, "governance_evidence_v7");
  return <CrossProjectPlanningWorkspace key={`${selectedCompanyId}:${userId}`} companyId={selectedCompanyId} userId={userId} enabled={enabled} />;
}
export function CrossProjectPlanningWorkspace({ companyId, userId, enabled }: { companyId: string; userId: string | null; enabled: boolean }) {
  const cache = useQueryClient(), key = ["cross-project-planning", companyId, userId];
  const [ids, setIds] = useState<string[]>([]), [search, setSearch] = useState(""), [id, setId] = useState(""), [editing, setEditing] = useState(false), [lost, setLost] = useState(false), [epoch, setEpoch] = useState(0), [now, setNow] = useState(Date.now());
  const [preview, setPreview] = useState<{ profile: CrossProjectPlanningProfile; response: JointPlanningPreview; sourceKey: string } | null>(null), [reason, setReason] = useState(""), [rationale, setRationale] = useState(""), [ack, setAck] = useState(false);
  const controls = useInfiniteQuery({ queryKey: [...key, "controls"], initialPageParam: undefined as string | undefined, queryFn: ({ pageParam }) => crossProjectPlanningApi.controls(companyId, pageParam, userId), getNextPageParam: page => page.nextCursor ?? undefined, retry: false });
  const choices = useQuery({ queryKey: [...key, "choices", search], queryFn: () => crossProjectPlanningApi.sourceOptions(companyId, search, userId), enabled: enabled && !lost, retry: false, refetchInterval: editing ? false : 30000 });
  const detail = useQuery({ queryKey: [...key, "detail", id], queryFn: () => crossProjectPlanningApi.detail(companyId, id, userId), enabled: !!id && enabled && !lost, retry: false, refetchInterval: editing ? false : 30000 });
  const purgeCaches = useCallback(() => { for (const owner of ["detail", "source", "choices"]) cache.removeQueries({ queryKey: ["cross-project-planning", companyId, userId, owner] }); cache.removeQueries({ queryKey: ["planning-definition-sources", companyId, userId] }); cache.removeQueries({ queryKey: ["decision-evidence", companyId, userId] }); }, [cache, companyId, userId]);
  const clear = useCallback(() => { setIds([]); setId(""); setEditing(false); setPreview(null); setReason(""); setRationale(""); setAck(false); purgeCaches(); }, [purgeCaches]);
  const revoke = useCallback(() => { setLost(true); clear(); }, [clear]);
  const rows = !controls.isFetching && !controls.isError ? controls.data?.pages.flatMap(page => page.items) ?? [] : [], selected = rows.find(row => row.id === id);
  const retained = enabled && !lost && !controls.isFetching && !controls.isError && !detail.isFetching && !detail.isError && detail.data?.companyId === companyId && detail.data.id === id && Date.parse(detail.data.context.expiresAt) > Math.max(now, Date.now()) ? detail.data : undefined;
  const sourceIds = ids.length ? ids : retained?.context.profile.projects.map(project => project.id) ?? [];
  const sources = useQueries({ queries: sourceIds.map(projectId => ({ queryKey: [...key, "source", projectId], queryFn: () => adaptivePlanningApi.source(companyId, projectId, userId), enabled: enabled && !lost, retry: false, refetchInterval: editing ? false as const : 30000 })) });
  const currentSources = sources.length >= 2 && sources.every((source, index) => !source.isFetching && !source.isError && source.data?.companyId === companyId && source.data.projectId === sourceIds[index]) ? sources.map(source => source.data!) : [];
  const sourceKey = JSON.stringify(currentSources.map(source => [source.projectId, source.projectUpdatedAt, source.policy, source.tasks.map(task => [task.id, task.updatedAt])]));
  const labels = Object.fromEntries(currentSources.flatMap(source => source.tasks.map(task => [task.id, `${source.projectName} · ${task.title}`])));
  const dirty = useCallback(() => { setPreview(null); setReason(""); setAck(false); }, []);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); window.addEventListener("memory-access-changed", revoke); return () => { window.clearInterval(timer); window.removeEventListener("memory-access-changed", revoke); purgeCaches(); }; }, [revoke, purgeCaches]);
  useEffect(() => { if (controls.isError || choices.isError || detail.isError || sources.some(source => source.isError)) revoke(); }, [controls.isError, choices.isError, detail.isError, sources.some(source => source.isError), revoke]);
  useEffect(() => { if (!enabled) { setEditing(false); dirty(); setRationale(""); } }, [enabled, dirty]);
  const inspect = useMutation({ mutationFn: (input: { profile: CrossProjectPlanningProfile; sourceKey: string }) => crossProjectPlanningApi.preview(companyId, input.profile, userId), onSuccess: (response, input) => { setPreview({ response, ...input }); setReason(""); }, onError: revoke });
  const propose = useMutation({ mutationFn: () => crossProjectPlanningApi.propose(companyId, preview!.profile, preview!.response.snapshotHash, reason, userId), onSuccess: result => { setEditing(false); dirty(); setId(result.id); setRationale(""); setAck(false); void cache.invalidateQueries({ queryKey: [...key, "controls"] }); }, onError: revoke });
  const review = useMutation({ mutationFn: (action: "begin_review" | "accept" | "reject" | "cancel") => crossProjectPlanningApi.review(companyId, id, selected!.revision, action, rationale, userId), onSuccess: () => { clear(); void cache.invalidateQueries({ queryKey: [...key, "controls"] }); void cache.invalidateQueries({ queryKey: ["v5-roadmap", companyId] }); }, onError: revoke });
  const busy = inspect.isPending || propose.isPending || review.isPending, reviewValid = rationale.trim().length >= 10 && rationale.trim().length <= 4000;
  const shownPreview = currentSources.length && preview?.sourceKey === sourceKey && Date.parse(preview.response.expiresAt) > Math.max(now, Date.now()) ? preview : null;
  const options = !choices.isFetching && !choices.isError && enabled && !lost ? choices.data?.items.filter(item => item.source.kind === "canonical" && item.source.reference.type === "project") ?? [] : [];
  const canApply = !!retained && retained.currentQualification === "current" && !!selected && selected.revision === retained.revision && ack && reviewValid;
  return <div className="min-w-0 space-y-6"><header className="space-y-2"><h1 className="text-xl font-semibold">Cross-project planning</h1><p>Plan across projects using shared capacity and dependencies, then review the proposed Task dates before applying them.</p></header>
    {lost && <p role="alert">Current planning sources or access could not be confirmed. Refresh access before continuing.</p>}
    {!enabled && <p role="status">Joint planning disclosure and application are unavailable. Existing proposal references can still be rejected or cancelled.</p>}
    <Button variant="ghost" disabled={busy} onClick={() => { clear(); setLost(false); void cache.invalidateQueries({ queryKey: key }); }}>Refresh joint planning authority</Button>
    {enabled && !lost && !editing && <section aria-label="Native joint planning project choices" className="space-y-3"><h2 className="font-semibold">Select native projects</h2><label className="block space-y-2">Project name search<Input aria-label="Joint planning project search" maxLength={120} value={search} onChange={event => { setSearch(event.target.value); setIds([]); dirty(); }} /></label><p>Search project names to find more choices. Select two to twenty projects.</p>{choices.isFetching && <p role="status">Rechecking native project choices…</p>}{options.map(item => { const projectId = item.source.kind === "canonical" && item.source.reference.type === "project" ? item.source.reference.id : ""; return <label className="flex items-start gap-2" key={projectId}><input type="checkbox" checked={ids.includes(projectId)} disabled={busy || ids.length >= 20 && !ids.includes(projectId)} onChange={event => { setIds(old => event.target.checked ? [...old, projectId].sort() : old.filter(value => value !== projectId)); dirty(); }} />{item.title}</label>; })}<Button variant="outline" disabled={busy || ids.length < 2 || currentSources.length < 2 || currentSources.some(source => source.policy.fieldOwnership.plannedDates !== "internal")} onClick={() => { setId(""); setEpoch(old => old + 1); setEditing(true); dirty(); }}>Declare shared project constraints</Button></section>}
    {sources.some(source => source.isFetching) && <p role="status">Rechecking complete native Roadmap Sources…</p>}
    {editing && currentSources.length >= 2 && <section className="space-y-3"><h2 className="font-semibold">Declare joint planning assumptions</h2><ProjectPlanningForm key={`${sourceKey}:${epoch}`} roadmap={{ companyId, tasks: currentSources.flatMap(source => source.tasks.map(task => ({ ...task, title: labels[task.id] }))) }} scopeLabel="the selected projects" userId={userId} busy={busy} onPreview={profile => inspect.mutate({ profile: crossProjectPlanningProfileSchema.parse({ ...profile, projects: currentSources.map(source => ({ id: source.projectId, expectedUpdatedAt: source.projectUpdatedAt })) }), sourceKey })} onDirty={dirty} onCancel={() => { setEditing(false); dirty(); }} onAuthorityLost={revoke} /></section>}
    {shownPreview && <section className="space-y-3"><h2 className="font-semibold">Joint planning preview</h2><ProjectPlanningResult result={shownPreview.response.result} horizonStart={shownPreview.profile.horizon.start} taskLabels={labels} />{shownPreview.response.result.status === "feasible_best_known" && <><label className="block space-y-2">Reason for the joint planning proposal<Textarea aria-label="Joint planning proposal reason" minLength={20} maxLength={4000} value={reason} onChange={event => setReason(event.target.value)} /></label><Button disabled={busy || reason.trim().length < 20 || reason.trim().length > 4000} onClick={() => propose.mutate()}>Create joint planning proposal</Button></>}</section>}
    <section aria-label="Native joint proposal controls" className="space-y-3"><h2 className="font-semibold">Joint proposal controls</h2>{controls.isError && <p role="alert">Current native control authority could not be established.</p>}<label className="block space-y-2">Joint proposal reference<select aria-label="Joint proposal reference" className={selectStyle} value={id} disabled={busy || controls.isFetching} onChange={event => { setId(event.target.value); setIds([]); setEditing(false); dirty(); setRationale(""); }}>{rows.map(row => <option key={row.id} value={row.id}>{row.status.replaceAll("_", " ")} · revision {row.revision} · {row.id}</option>)}<option value="">Choose exact native joint proposal</option></select></label>{controls.hasNextPage && <Button variant="outline" disabled={busy || controls.isFetching} onClick={() => void controls.fetchNextPage()}>Load more joint controls</Button>}
      {detail.isFetching && <p role="status">Rechecking retained joint Source authority…</p>}
      {retained && <div className="space-y-4"><p>{retained.reason}</p><ProjectPlanningResult result={retained.context.result} horizonStart={retained.context.profile.horizon.start} taskLabels={labels} current={retained.currentQualification === "current"} /><ProjectPlanningBasis detail={retained} taskLabels={labels} />{retained.appliedRoadmapRefs.length > 0 && <ul className="list-disc pl-5">{retained.appliedRoadmapRefs.map(ref => <li key={ref.projectId}><Link className="underline" to={`/projects/${ref.projectId}`}>Open original project Roadmap</Link></li>)}</ul>}</div>}
      {selected && ["proposed", "under_review"].includes(selected.status) && <section aria-label="Separate Human joint review" className="space-y-3"><label className="block space-y-2">Separate Human joint review rationale<Textarea aria-label="Joint planning review rationale" minLength={10} maxLength={4000} value={rationale} onChange={event => { setRationale(event.target.value); setAck(false); }} /></label>{retained && <label className="flex items-start gap-2"><input type="checkbox" checked={ack} onChange={event => setAck(event.target.checked)} />I reviewed this exact joint Source, complete native Task population, declared shared capacity and proposed UTC dates.</label>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || !reviewValid} onClick={() => review.mutate("reject")}>Reject joint proposal</Button><Button variant="ghost" disabled={busy || !reviewValid} onClick={() => review.mutate("cancel")}>Cancel joint proposal</Button>{retained && <Button disabled={busy || !canApply} onClick={() => review.mutate(selected.status === "proposed" ? "begin_review" : "accept")}>{selected.status === "proposed" ? "Begin separate joint review" : "Approve joint committed dates"}</Button>}</div></section>}
    </section>
  </div>;
}
