import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { EVIDENCE_SENSITIVITIES, v7FeatureEnabled } from "@paperclipai/shared";
import { CognitivePurposeSelector } from "@/components/CognitivePurposeSelector";
import { DerivedMemoryEvidence } from "@/components/DerivedMemoryEvidence";
import { derivedMemoryApi } from "@/api/derivedMemory";
import { memoryApi } from "@/api/memory";
import { instanceSettingsApi } from "@/api/instanceSettings";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { MarkdownBody } from "@/components/MarkdownBody";
import { Link } from "@/lib/router";
export function DerivedMemory() {
  const { selectedCompanyId: companyId } = useCompany(), { setBreadcrumbs } = useBreadcrumbs();
  const [kind, setKind] = useState<"observations" | "models">("observations"), [selected, setSelected] = useState<string[]>([]);
  const [purpose, setPurpose] = useState("native_task_execution"), [content, setContent] = useState(""), [name, setName] = useState(""), [query, setQuery] = useState(""), [sensitivity, setSensitivity] = useState("internal"), [reason, setReason] = useState("");
  useEffect(() => setBreadcrumbs([{ label: "Memory", href: "/memory" }, { label: "Derived intelligence" }]), [setBreadcrumbs]);
  useEffect(() => { setSelected([]); setContent(""); setName(""); setQuery(""); setReason(""); }, [companyId]);
  const flags = useQuery({ queryKey: ["derived-flags"], queryFn: () => instanceSettingsApi.getExperimental() });
  const modelsEnabled = v7FeatureEnabled(flags.data ?? {}, "memory_models_v7");
  const sources = useQuery({ queryKey: ["derived-source-memory", companyId], queryFn: () => memoryApi.listRecords(companyId!, { reviewState: "accepted", limit: 100 }), enabled: Boolean(companyId) });
  const observations = useQuery({ queryKey: ["derived-observations", companyId], queryFn: () => derivedMemoryApi.observations(companyId!), enabled: Boolean(companyId) });
  const models = useQuery({ queryKey: ["derived-models", companyId], queryFn: () => derivedMemoryApi.models(companyId!), enabled: Boolean(companyId && modelsEnabled) });
  const refresh = () => { void observations.refetch(); if (modelsEnabled) void models.refetch(); };
  const create = useMutation({ mutationFn: async () => kind === "observations" ? derivedMemoryApi.createObservation(companyId!, { content, purpose, sensitivity, recordIds: selected }) : derivedMemoryApi.createModel(companyId!, { name, purpose, query, recordIds: selected }), onSuccess: () => { setContent(""); setName(""); refresh(); } });
  const review = useMutation({ mutationFn: (input: { kind: "observations" | "models"; id: string; decision: "accept" | "reject" | "revoke"; version: number }) => derivedMemoryApi.review(companyId!, input.kind, input.id, input.decision, input.version, reason), onSuccess: refresh });
  const rebuild = useMutation({ mutationFn: (input: { id: string; version: number }) => derivedMemoryApi.rebuild(companyId!, input.id, input.version, selected), onSuccess: refresh });
  const eligible = sources.data?.filter((record) => record.scopeType === "company" && record.retentionState === "active" && !record.deletedAt && !record.revokedAt && !record.supersededByRecordId) ?? [];
  return <div className="space-y-6"><h1 className="text-xl font-semibold">Derived intelligence</h1><p className="text-muted-foreground">Observations describe reviewed patterns. Mental models collect evidence for repeated questions. Both remain derived and require human review before influencing Context.</p>
    {!companyId ? <p>Select a company first.</p> : <><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><div className="flex gap-2"><Button type="button" variant={kind === "observations" ? "default" : "outline"} onClick={() => setKind("observations")}>Observation</Button>{modelsEnabled ? <Button type="button" variant={kind === "models" ? "default" : "outline"} onClick={() => setKind("models")}>Mental model</Button> : null}</div>
      <CognitivePurposeSelector id="derived-purpose" value={purpose} onChange={setPurpose} />
      {kind === "observations" ? <><div className="space-y-2"><label htmlFor="observation-content">Proposed pattern</label><textarea id="observation-content" className="w-full rounded-md border border-input bg-background p-2" value={content} onChange={(event) => setContent(event.target.value)} required maxLength={64000} /></div><div className="space-y-2"><label htmlFor="observation-sensitivity">Sensitivity</label><select id="observation-sensitivity" className="rounded-md border border-input bg-background p-2" value={sensitivity} onChange={(event) => setSensitivity(event.target.value)}>{EVIDENCE_SENSITIVITIES.map((value) => <option key={value}>{value}</option>)}</select></div></> : <><div className="space-y-2"><label htmlFor="model-name">Model name</label><Input id="model-name" value={name} onChange={(event) => setName(event.target.value)} required maxLength={240} /></div><div className="space-y-2"><label htmlFor="model-question">Repeated question</label><Input id="model-question" value={query} onChange={(event) => setQuery(event.target.value)} required maxLength={500} /></div></>}
      <fieldset className="space-y-2"><legend>Accepted company Memory</legend>{eligible.map((record) => <label className="flex items-start gap-2" key={record.id}><input type="checkbox" checked={selected.includes(record.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, record.id].slice(0, 32) : selected.filter((id) => id !== record.id))} /><span>{record.title ?? record.summary ?? record.content.slice(0, 120)} <span className="text-muted-foreground">· {record.sensitivityLabel}</span> <Link to={`/memory/${record.id}`}>Review source</Link></span></label>)}{sources.isPending ? <p role="status">Loading sources…</p> : eligible.length === 0 ? <p>No accepted company Memory is available yet.</p> : null}</fieldset>
      <div className="flex items-center justify-between"><Link to="/memory">Back to Memory</Link><Button type="submit" disabled={create.isPending || selected.length < (kind === "observations" ? 2 : 1)}>Prepare candidate</Button></div></form>
      <div className="space-y-2"><label htmlFor="derived-review-reason">Review reason</label><Input id="derived-review-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={1000} /></div>
      {observations.data?.map((row) => <section className="space-y-2" key={row.id}><h2 className="font-medium">Observation</h2><DerivedMemoryEvidence key={`${companyId}:${row.id}`} companyId={companyId} kind="observations" id={row.id} /><Badge variant="outline">{row.status.replaceAll("_", " ")}</Badge>{row.content ? <MarkdownBody>{row.content}</MarkdownBody> : <p>Source evidence changed. Content is withheld until reviewed again.</p>}<p className="text-sm text-muted-foreground">{row.purpose === "native_task_execution" ? "Assigned agent tasks" : row.purpose === "foundation_bootstrap" ? "Company knowledge drafts" : "Internal reasoning"} · {row.supportCount} supports · {row.contradictionCount} contradictions · {row.independentSourceCount} independent sources · {row.sensitivity}</p><div className="flex gap-2">{row.status === "candidate" ? <Button disabled={!reason.trim() || review.isPending} onClick={() => review.mutate({ kind: "observations", id: row.id, decision: "accept", version: row.version })}>Accept observation</Button> : null}{!["revoked", "rejected", "superseded", "expired"].includes(row.status) ? <Button variant="outline" disabled={!reason.trim() || review.isPending} onClick={() => review.mutate({ kind: "observations", id: row.id, decision: row.status === "accepted" ? "revoke" : "reject", version: row.version })}>{row.status === "accepted" ? "Revoke" : "Reject"}</Button> : null}</div></section>)}
      {modelsEnabled ? models.data?.map((row) => <section className="space-y-2" key={row.id}><h2 className="font-medium">{row.name}</h2><DerivedMemoryEvidence key={`${companyId}:${row.id}`} companyId={companyId} kind="models" id={row.id} /><Badge variant="outline">{row.status.replaceAll("_", " ")}</Badge><p>Version {row.version} · {row.sensitivity}</p>{row.content ? <MarkdownBody>{row.content}</MarkdownBody> : <p>Source evidence changed. Select current Memory above to request a rebuild.</p>}<div className="flex gap-2">{row.status === "candidate" ? <Button disabled={!reason.trim() || review.isPending} onClick={() => review.mutate({ kind: "models", id: row.id, decision: "accept", version: row.version })}>Activate reviewed model</Button> : null}{row.status !== "revoked" ? <><Button variant="outline" disabled={!selected.length || rebuild.isPending} onClick={() => rebuild.mutate({ id: row.id, version: row.version })}>Rebuild from selected Memory</Button><Button variant="outline" disabled={!reason.trim() || review.isPending} onClick={() => review.mutate({ kind: "models", id: row.id, decision: "revoke", version: row.version })}>Revoke</Button></> : null}</div></section>) : null}
      {rebuild.data ? <p role="status">Rebuild queued. <Link to="/memory">Follow the Memory job</Link>; review the resulting candidate before activation.</p> : null}</>}
    {[flags, sources, observations, models, create, review, rebuild].filter((state) => state.isError).map((state, index) => <p role="alert" key={index}>{state.error instanceof Error ? state.error.message : "Operation failed"}</p>)}
  </div>;
}
