// @vitest-environment jsdom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { instanceExperimentalSettingsSchema } from "@paperclipai/shared";
import { ManagementReviews } from "./ManagementReviews";
import { managementReviewsApi } from "@/api/management-reviews";
import { instanceSettingsApi } from "@/api/instanceSettings";
import { aiGovernanceApi } from "@/api/ai-governance";
import { managementFixture } from "../../storybook/stories/management-review-fixtures";
const identity = vi.hoisted(() => ({ userId: "human", settled: true, failed: false }));
const company = vi.hoisted(() => ({ selectedCompanyId: "" }));
const breadcrumbs = vi.hoisted(() => ({ setBreadcrumbs: vi.fn() }));
vi.mock("@/api/companies-query", () => ({ useAccountIdentity: () => identity }));
vi.mock("@/context/CompanyContext", () => ({ useCompany: () => company }));
vi.mock("@/context/BreadcrumbContext", () => ({ useBreadcrumbs: () => breadcrumbs }));
vi.mock("@/api/management-reviews", () => ({ managementReviewsApi: { controls: vi.fn(), detail: vi.fn(), create: vi.fn(), publish: vi.fn(), event: vi.fn(), sourceOptions: vi.fn() } }));
vi.mock("@/api/instanceSettings", () => ({ instanceSettingsApi: { getExperimental: vi.fn() } }));
vi.mock("@/api/ai-governance", () => ({ aiGovernanceApi: { obligations: vi.fn() } }));
(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const flush = async () => { await act(async () => { await new Promise(resolve => setTimeout(resolve, 30)); }); };
async function mount() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }), container = document.createElement("div"); document.body.append(container); const root = createRoot(container), render = async () => { await act(async () => root.render(<QueryClientProvider client={client}><ManagementReviews /></QueryClientProvider>)); await flush(); await flush(); }; await render(); return { client, container, render, cleanup: async () => { await act(async () => root.unmount()); client.clear(); container.remove(); } }; }
const button = (node: HTMLElement, label: string) => [...node.querySelectorAll<HTMLButtonElement>("button")].find(button => button.textContent === label)!;
async function click(node: HTMLElement, label: string) { for (let i = 0; i < 20 && (!button(node, label) || button(node, label).disabled); i++) await flush(); expect(button(node, label), label).toBeDefined(); expect(button(node, label).disabled, label).toBe(false); await act(async () => button(node, label).click()); await flush(); }
async function field(node: HTMLElement, label: string, value: string) { await act(async () => { const input = node.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[aria-label="${label}"]`)!; expect(input, label).toBeDefined(); if (input instanceof HTMLSelectElement) { input.value = value; input.dispatchEvent(new Event("change", { bubbles: true })); } else { Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, "value")!.set!.call(input, value); input.dispatchEvent(new Event("input", { bubbles: true })); } }); await flush(); }
async function selectReview(node: HTMLElement) { await field(node, "Review reference", managementFixture().id); }
async function fillDraft(node: HTMLElement) { const f = managementFixture(); await click(node, "Prepare a cited management review"); await field(node, "Review name", "Human onboarding review"); await field(node, "Review period start (UTC)", "2026-10-01T00:00:00"); await field(node, "Review period end (UTC)", "2026-10-07T00:00:00"); await field(node, "Source 1 canonical native source", JSON.stringify(f.definition.sources[0].source.kind === "canonical" ? f.definition.sources[0].source.reference : null)); await field(node, "Agenda 1 due date (UTC)", "2099-10-08T00:00:00"); await field(node, "Agenda 1 proposed next action", "Human investigates these exact cited sources before any canonical change"); await field(node, "Approved review purpose", f.policy.id); }
beforeEach(() => { vi.resetAllMocks(); const f = managementFixture(); identity.userId = f.userId; identity.settled = true; identity.failed = false; company.selectedCompanyId = f.companyId; vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(f.flags); vi.mocked(managementReviewsApi.controls).mockResolvedValue(f.controls); vi.mocked(managementReviewsApi.detail).mockResolvedValue(f.review); vi.mocked(managementReviewsApi.create).mockResolvedValue({ id: f.id, companyId: f.companyId, status: "draft", contentHash: f.review.packet.contentHash }); vi.mocked(managementReviewsApi.publish).mockResolvedValue({ id: f.id, companyId: f.companyId, status: "published", contentHash: f.review.packet.contentHash }); vi.mocked(managementReviewsApi.event).mockResolvedValue({ id: f.id, reviewId: f.id, ordinal: 2, event: "acted_on", interpretation: "human_reported_event" }); vi.mocked(aiGovernanceApi.obligations).mockResolvedValue([f.policy]); vi.mocked(managementReviewsApi.sourceOptions).mockResolvedValue({ items: [{ source: f.definition.sources[0].source, title: f.goal.title }], coverage: "bounded_authorized_native_choices" }); });
describe("Native Management operator authority", () => {
  it("requests account-bound choices and clears a draft when current source-menu authority is lost", async () => { const f = managementFixture(), app = await mount(); try { await fillDraft(app.container); expect(managementReviewsApi.sourceOptions).toHaveBeenCalledWith(f.companyId, { kind: "goal", q: undefined, parentId: undefined }, f.userId); vi.mocked(managementReviewsApi.sourceOptions).mockRejectedValue(new Error("Current source role denied")); await act(async () => { await app.client.invalidateQueries({ queryKey: ["management-definition-sources", f.companyId, f.userId, "options"] }); }); await flush(); expect(app.container.querySelector('[aria-label="Cited management review proposal"]')).toBeNull(); expect(managementReviewsApi.create).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("selects an exact native governance pin with account binding and keeps control effectiveness unverified", async () => { const f = managementFixture(), source = { kind: "governance_obligation" as const, id: f.policy.id, contentHash: f.policy.obligationHash }, app = await mount(); try { await fillDraft(app.container); vi.mocked(managementReviewsApi.sourceOptions).mockResolvedValue({ items: [{ source, title: "Human declared native governance risk" }], coverage: "bounded_authorized_native_choices" }); await field(app.container, "Source 1 domain", "governance_obligation"); await field(app.container, "Source 1 retained source", JSON.stringify(source)); await click(app.container, "Capture management review draft"); expect(managementReviewsApi.sourceOptions).toHaveBeenCalledWith(f.companyId, { kind: "governance_obligation", q: undefined, parentId: undefined }, f.userId); expect(vi.mocked(managementReviewsApi.create).mock.calls[0][1].sources).toEqual([{ key: "source_1", source }]); expect(managementReviewsApi.publish).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("renders original outcome explanations and all six independent judgments without mounting outcome mutations", async () => { const f = managementFixture(), source = f.review.sources[0], judgment = { kind: "human_judgment" as const, assessment: "unknown" as const, explanation: "Human explicitly retains incomplete evidence", evidenceKeys: [] }; source.source = { kind: "decision_outcome", decisionId: f.id, reviewId: f.id, revision: 1 }; source.grade = "native_outcome_review"; source.outcome = { id: f.id, companyId: f.companyId, decisionId: f.id, contextVersionId: f.id, contextHash: "c".repeat(64), optionId: "proceed", revision: 1, status: "inconclusive", reviewDueAt: f.review.createdAt, reviewedAt: f.review.createdAt, reviewedByUserId: f.userId, causalClaimRef: null, learningCycleId: null, receipts: [{ revision: 1, action: "finish", fromState: "in_review", toState: "inconclusive", rationale: "Synthetic original native outcome presentation", recordedBy: f.userId, recordedAt: f.review.createdAt, contextHash: "c".repeat(64), contentHash: "d".repeat(64), expiresAt: f.review.expiresAt, actualEvidence: [], comparisons: [], nativeExecution: { status: "succeeded", capturedAt: f.review.createdAt }, assessment: { expectedRevision: 1, result: "inconclusive", lessonSummary: "A result alone does not determine the quality of the decision", assessments: { decisionProcessQuality: { ...judgment, assessment: "supported" }, assumptionAccuracy: judgment, executionFidelity: judgment, externalChange: judgment, observedOutcome: judgment, causalConfidence: { assessment: "not_assessed", explanation: "No identified native causal claim exists" } }, actualMetrics: [], metricOutcomes: [], qualitativeOutcomes: [], assumptionOutcomes: [] } }] }; vi.mocked(managementReviewsApi.detail).mockResolvedValue(f.review); const app = await mount(); try { await selectReview(app.container); const details = [...app.container.querySelectorAll("details")].find(node => node.textContent?.includes("Original outcome judgments"))!; expect(details).toBeDefined(); expect(details.textContent).toContain("Decision process quality"); expect(details.textContent).toContain("Assumption accuracy"); expect(details.textContent).toContain("Execution fidelity"); expect(details.textContent).toContain("External change"); expect(details.textContent).toContain("Observed outcome"); expect(details.textContent).toContain("Causal confidence"); expect(details.textContent).toContain("Human explicitly retains incomplete evidence"); expect(details.querySelectorAll("button,textarea,input")).toHaveLength(0); } finally { await app.cleanup(); } });
  it("captures native pins and a cited human agenda without auto-publication or copied facts", async () => { const f = managementFixture(), app = await mount(); try { await fillDraft(app.container); await field(app.container, "Agenda 1 human hypothesis", "Human suspects timing; this remains an explicitly unverified hypothesis"); await click(app.container, "Capture management review draft"); expect(managementReviewsApi.create).toHaveBeenCalledWith(f.companyId, expect.objectContaining({ sources: [{ key: "source_1", source: f.definition.sources[0].source }], agenda: [expect.objectContaining({ sourceKeys: ["source_1"], hypothesis: expect.any(String), ownerUserId: f.userId })] }), f.userId); const input = vi.mocked(managementReviewsApi.create).mock.calls[0][1]; expect(JSON.stringify(input)).not.toContain("measuredEffect"); expect(managementReviewsApi.publish).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("requires separate exact evidence acknowledgement and human rationale before publication", async () => { const f = managementFixture(), app = await mount(); try { await selectReview(app.container); expect(button(app.container, "Publish this reviewed packet").disabled).toBe(true); await field(app.container, "Publication rationale", "Human reviews the complete original cited packet and retained uncertainty"); expect(button(app.container, "Publish this reviewed packet").disabled).toBe(true); await act(async () => app.container.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click()); await click(app.container, "Publish this reviewed packet"); expect(managementReviewsApi.publish).toHaveBeenCalledWith(f.companyId, f.id, { expectedContentHash: f.review.packet.contentHash, rationale: expect.any(String), evidenceAndUncertaintyAcknowledged: true, supersedesId: null }, f.userId); } finally { await app.cleanup(); } });
  it("retains original facts and citation links while withholding changed-source publication", async () => { const f = managementFixture(true); vi.mocked(managementReviewsApi.detail).mockResolvedValue(f.review); const app = await mount(); try { await selectReview(app.container); expect(app.container.textContent).toContain("Retained historical review"); expect(app.container.textContent).toContain(f.goal.title); expect(app.container.textContent).toContain("Unknown / not established"); expect(app.container.textContent).toContain("Human hypothesis, unverified"); expect(button(app.container, "Publish this reviewed packet").disabled).toBe(true); const link = app.container.querySelector<HTMLAnchorElement>('a[href="#management-source-source_1"]')!; expect(app.container.querySelector(link.hash)).not.toBeNull(); } finally { await app.cleanup(); } });
  it("records acted-on as a signed human report against the original agenda", async () => { const f = managementFixture(false, true); vi.mocked(managementReviewsApi.controls).mockResolvedValue(f.controls); vi.mocked(managementReviewsApi.detail).mockResolvedValue(f.review); const app = await mount(); try { await selectReview(app.container); expect(app.container.textContent).toContain("do not verify an intervention"); await field(app.container, "Original agenda item", "agenda_1"); await field(app.container, "Reported event", "acted_on"); await field(app.container, "Human event rationale", "Human reports an investigation, without claiming a verified effect"); await click(app.container, "Record human event report"); expect(managementReviewsApi.event).toHaveBeenCalledWith(f.companyId, f.id, { expectedContentHash: f.review.packet.contentHash, itemKey: "agenda_1", event: "acted_on", rationale: expect.any(String) }, f.userId); expect(managementReviewsApi.publish).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("exposes metadata with rollout disabled without reading source content", async () => { vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({})); const app = await mount(); try { await selectReview(app.container); expect(managementReviewsApi.detail).not.toHaveBeenCalled(); expect(app.container.textContent).not.toContain(managementFixture().goal.title); expect(button(app.container, "Prepare a cited management review")).toBeUndefined(); } finally { await app.cleanup(); } });
  it("removes human drafts and sensitive source caches on Memory access loss", async () => { const f = managementFixture(), app = await mount(); try { await fillDraft(app.container); await field(app.container, "Agenda 1 human hypothesis", "Private hypothesis must disappear when authority changes"); app.client.setQueryData(["decision-evidence", f.companyId, f.userId, "private"], { text: "private source" }); await act(async () => window.dispatchEvent(new Event("memory-access-changed"))); await flush(); expect(app.container.querySelector('[aria-label="Cited management review proposal"]')).toBeNull(); expect(app.container.textContent).not.toContain("Private hypothesis"); expect(app.client.getQueriesData({ queryKey: ["decision-evidence", f.companyId, f.userId] })).toHaveLength(0); } finally { await app.cleanup(); } });
  it("withholds cached content when the current native detail request loses authority", async () => { const f = managementFixture(), app = await mount(); try { await selectReview(app.container); vi.mocked(managementReviewsApi.detail).mockRejectedValue(new Error("Source permission lost")); await act(async () => { await app.client.invalidateQueries({ queryKey: ["management-reviews", f.companyId, f.userId] }); }); await flush(); expect(app.container.textContent).not.toContain(f.goal.title); expect(app.container.querySelector('[aria-label="Cited management review"]')).toBeNull(); } finally { await app.cleanup(); } });
  it("removes the old account review when the verified account changes", async () => { const f = managementFixture(), app = await mount(); try { await selectReview(app.container); identity.userId = "another-human"; vi.mocked(managementReviewsApi.controls).mockRejectedValue(new Error("Current actor denied")); await app.render(); expect(app.container.textContent).not.toContain(f.goal.title); expect(app.container.querySelector('[aria-label="Separate human review publication"]')).toBeNull(); } finally { await app.cleanup(); } });
  it("invalidates saving when the human removes the only cited source from the agenda", async () => { const app = await mount(); try { await fillDraft(app.container); expect(button(app.container, "Capture management review draft").disabled).toBe(false); await act(async () => app.container.querySelector<HTMLInputElement>('[aria-label="Declared human review agenda"] input[type="checkbox"]')!.click()); await flush(); expect(button(app.container, "Capture management review draft").disabled).toBe(true); expect(managementReviewsApi.create).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("requires exact declared source pairs for an optional comparison and never treats a Goal as a measurement", async () => { const app = await mount(); try { await fillDraft(app.container); await click(app.container, "Add cited metric comparison"); expect(button(app.container, "Capture management review draft").disabled).toBe(true); expect(app.container.querySelector<HTMLSelectElement>('[aria-label="Comparison 1 right source"]')!.options).toHaveLength(1); await click(app.container, "Remove comparison 1"); expect(button(app.container, "Capture management review draft").disabled).toBe(false); expect(managementReviewsApi.create).not.toHaveBeenCalled(); } finally { await app.cleanup(); } });
  it("renders a derived comparison with both citations without replacing or duplicating original source anchors", async () => { const f = managementFixture(), source = { ...f.review.sources[0], key: "actual", source: { kind: "analytical" as const, reference: { type: "metric_observation" as const, id: f.id, metricId: f.id, metricVersionId: f.id } }, grade: "native_observation" as const, facts: { value: 0.5 } }; f.review.sources[0].source = { kind: "canonical", reference: { type: "metric_target", id: f.id, versionId: f.id } }; f.review.definition.sources[0].source = f.review.sources[0].source; f.review.definition.sources.push({ key: source.key, source: source.source }); f.review.definition.comparisons = [{ key: "commitment", kind: "target_actual", leftSourceKey: "source_1", rightSourceKey: "actual" }]; f.review.sources.push(source); f.review.packet.claims.push({ key: "claim_actual", sourceKeys: ["actual"], grade: source.grade, facts: source.facts, limitations: source.limitations }, { key: "comparison_commitment", sourceKeys: ["source_1", "actual"], grade: "native_observation", facts: { status: "not_met", observedValue: 0.5 }, limitations: ["Synthetic software display only; no business impact."] }); vi.mocked(managementReviewsApi.detail).mockResolvedValue(f.review); const app = await mount(); try { await selectReview(app.container); expect(app.container.querySelectorAll("#management-source-source_1")).toHaveLength(1); const comparison = app.container.querySelector("#management-claim-comparison_commitment")!; expect(comparison.textContent).toContain("not met"); expect(comparison.querySelectorAll("a")).toHaveLength(2); for (const link of comparison.querySelectorAll<HTMLAnchorElement>("a")) expect(app.container.querySelector(link.hash)).not.toBeNull(); } finally { await app.cleanup(); } });
});
