import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { LearningEvaluationInput, LearningChange } from "@paperclipai/shared";
import { learningApi } from "@/api/learning";
import { memoryApi } from "@/api/memory";
import { foundationApi } from "@/api/foundation";
import { issuesApi } from "@/api/issues";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { CognitivePurposeSelector } from "@/components/CognitivePurposeSelector";
import { LearningPolicyReview } from "@/components/LearningPolicyReview";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Link } from "@/lib/router";
type Case = LearningEvaluationInput["cases"][number];
const unreviewed = () => ({ correctness: false, safety: false, policy: false, businessOutcome: 0, reliability: 0, latencyMs: null, costCents: null });
const emptyCase = (): Case => ({ baselineTaskId: "", challengerTaskId: "", baseline: unreviewed(), challenger: unreviewed(), invariantResults: [false], rationale: "" });
export function OrganizationalLearning() {
  const { selectedCompanyId: companyId } = useCompany(), { setBreadcrumbs } = useBreadcrumbs();
  const [cycleId, setCycleId] = useState(""), [selected, setSelected] = useState<string[]>([]), [purpose, setPurpose] = useState("native_task_execution"), [trigger, setTrigger] = useState("");
  const [targetId, setTargetId] = useState(""), [body, setBody] = useState(""), [claim, setClaim] = useState(""), [effect, setEffect] = useState(""), [invariant, setInvariant] = useState(""), [rollback, setRollback] = useState(""), [reason, setReason] = useState("");
  const [hypothesisId, setHypothesisId] = useState(""), [prepared, setPrepared] = useState<LearningChange | null>(null), [cases, setCases] = useState<Case[]>([emptyCase(), emptyCase()]), [limitations, setLimitations] = useState(""), [closeRationale, setCloseRationale] = useState("");
  useEffect(() => setBreadcrumbs([{ label: "Memory", href: "/memory" }, { label: "Organizational Learning" }]), [setBreadcrumbs]);
  useEffect(() => { setCycleId(""); setSelected([]); setTargetId(""); setBody(""); setClaim(""); setEffect(""); setReason(""); setInvariant(""); setRollback(""); setTrigger(""); setPrepared(null); setHypothesisId(""); setCases([emptyCase(), emptyCase()]); setLimitations(""); setCloseRationale(""); }, [companyId]);
  const cycles = useQuery({ queryKey: ["learning-cycles", companyId], queryFn: () => learningApi.list(companyId!), enabled: Boolean(companyId) });
  const detail = useQuery({ queryKey: ["learning-cycle", companyId, cycleId], queryFn: () => learningApi.get(companyId!, cycleId), enabled: Boolean(companyId && cycleId) });
  const sources = useQuery({ queryKey: ["learning-roots", companyId], queryFn: () => memoryApi.listRecords(companyId!, { reviewState: "accepted", limit: 100 }), enabled: Boolean(companyId) });
  const foundation = useQuery({ queryKey: ["learning-foundation", companyId], queryFn: () => foundationApi.list(companyId!), enabled: Boolean(companyId) });
  const tasks = useQuery({ queryKey: ["learning-outcomes", companyId], queryFn: () => issuesApi.list(companyId!, { status: "done" }), enabled: Boolean(companyId) });
  const refresh = () => { void cycles.refetch(); void detail.refetch(); };
  const create = useMutation({ mutationFn: () => learningApi.create(companyId!, { scope: { type: "company", id: null }, purpose, trigger, memoryRecordIds: selected }), onSuccess: (row) => { setCycleId(row.id); refresh(); } });
  const hypothesis = useMutation({ mutationFn: async () => {
    const target = foundation.data?.find((row) => row.id === targetId); if (!target?.latestRevisionId || !detail.data) throw new Error("Select a current Foundation document and cycle.");
    const proposal = await learningApi.prepare(companyId!, { targetDomain: "foundation", baseRevisionId: target.latestRevisionId, proposedBody: body, reason });
    const row = await learningApi.hypothesis(companyId!, cycleId, { expectedCycleVersion: detail.data.version, claim, predictedEffect: effect, targetDomain: "foundation", targetId, riskClass: "material",
      evaluationContract: { expectedImprovement: effect, protectedInvariants: [invariant], baselineRef: `foundation://${targetId}/${target.latestRevisionId}`, challengerHash: proposal.hash, minimumCases: 2, minimumQuality: 0.8, minimumImprovement: 0.05, rollbackPath: rollback } });
    setPrepared(proposal.change); return row;
  }, onSuccess: (row) => { setHypothesisId(row.id); refresh(); } });
  const chosen = detail.data?.hypotheses.find((row) => row.id === hypothesisId);
  const restoreDraft = useMutation({ mutationFn: async () => {
    const target = foundation.data?.find((row) => row.id === chosen?.targetId);
    if (!chosen || chosen.targetDomain !== "foundation" || !target?.latestRevisionId) throw new Error("Select a Foundation hypothesis and re-enter its pinned draft and reason.");
    const proposal = await learningApi.prepare(companyId!, { targetDomain: "foundation", baseRevisionId: target.latestRevisionId, proposedBody: body, reason });
    if (proposal.hash !== chosen.evaluationContract.challengerHash) throw new Error("The entered draft differs from the evaluated change. Restore the original draft or evaluate a new hypothesis.");
    return proposal.change;
  }, onSuccess: setPrepared });
  const evaluate = useMutation({ mutationFn: () => {
    if (!chosen) throw new Error("Select a hypothesis first.");
    return learningApi.evaluate(companyId!, chosen.id, { expectedHypothesisVersion: chosen.version, method: "manual_review", cases, limitations: [limitations] });
  }, onSuccess: refresh });
  const propose = useMutation({ mutationFn: () => {
    const passed = detail.data?.evaluations.find((row) => row.hypothesisId === hypothesisId && row.result === "passed");
    if (!chosen || !passed || !prepared) throw new Error("A retained passing review of this prepared change is required.");
    return learningApi.propose(companyId!, chosen.id, { expectedHypothesisVersion: chosen.version, evaluationId: passed.id, change: prepared });
  }, onSuccess: refresh });
  const finish = useMutation({ mutationFn: (decision: "complete" | "cancel") => {
    if (!detail.data) throw new Error("Select a current cycle.");
    return learningApi.finish(companyId!, cycleId, { expectedVersion: detail.data.version, decision, rationale: closeRationale });
  }, onSuccess: () => { setCloseRationale(""); refresh(); } });
  const setCase = (index: number, patch: Partial<Case>) => setCases((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));
  const eligible = sources.data?.filter((row) => row.scopeType === "company" && row.retentionState === "active" && !row.revokedAt && !row.deletedAt && !row.supersededByRecordId) ?? [];
  const errors = [cycles, detail, sources, foundation, tasks, create, hypothesis, restoreDraft, evaluate, propose, finish].filter((state) => state.isError);
  return <div className="space-y-6"><h1 className="text-xl font-semibold">Organizational Learning</h1><p className="text-muted-foreground">Use reviewed work outcomes to test a hypothesis. Safety, correctness and policy come before cost. Passing a comparison prepares a domain proposal for its normal human review.</p>
    {!companyId ? <p>Select a company first.</p> : <><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><h2 className="font-medium">Start from real outcomes</h2><CognitivePurposeSelector id="learning-purpose" value={purpose} onChange={setPurpose} /><label className="block space-y-2">Observed problem<Input value={trigger} onChange={(event) => setTrigger(event.target.value)} minLength={10} maxLength={1000} required /></label>
      <fieldset className="space-y-2"><legend>Accepted company Memory with verified completed Task evidence</legend>{eligible.map((row) => <label key={row.id} className="flex gap-2"><input type="checkbox" checked={selected.includes(row.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, row.id].slice(0, 32) : selected.filter((id) => id !== row.id))} /><span>{row.title ?? row.summary ?? row.content.slice(0, 100)} · <Link to={`/memory/${row.id}`}>Inspect evidence</Link></span></label>)}</fieldset><div className="flex items-center justify-between"><Link to="/memory">Back to Memory</Link><Button disabled={!selected.length || create.isPending}>Start bounded cycle</Button></div></form>
      <label className="block space-y-2">Learning cycle<select className="rounded-md border border-input bg-background p-2" value={cycleId} onChange={(event) => { setCycleId(event.target.value); setPrepared(null); setHypothesisId(""); }}><option value="">Select a cycle</option>{cycles.data?.map((row) => <option key={row.id} value={row.id}>{row.trigger} · {row.status}</option>)}</select></label>
      {detail.data ? <><p>Hypothesis budget: {detail.data.hypotheses.length}/{detail.data.maxHypotheses} · Evaluation budget: {detail.data.evaluations.length}/{detail.data.maxEvaluations}</p>
        <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); hypothesis.mutate(); }}><h2 className="font-medium">Prepare a Foundation hypothesis</h2><label className="block space-y-2">Target document<select className="rounded-md border border-input bg-background p-2" value={targetId} onChange={(event) => setTargetId(event.target.value)} required><option value="">Select a current document</option>{foundation.data?.filter((row) => row.latestRevisionId).map((row) => <option value={row.id} key={row.id}>{row.title ?? row.foundationKey} · {row.sensitivity}</option>)}</select></label>
          {[{ label: "Hypothesis", value: claim, set: setClaim }, { label: "Expected improvement", value: effect, set: setEffect }, { label: "Protected invariant", value: invariant, set: setInvariant }, { label: "Rollback path", value: rollback, set: setRollback }, { label: "Reason for changing the document", value: reason, set: setReason }].map((field) => <label key={field.label} className="block space-y-2">{field.label}<Input value={field.value} onChange={(event) => field.set(event.target.value)} required minLength={20} maxLength={2000} /></label>)}<label className="block space-y-2">Proposed document body<textarea className="w-full rounded-md border border-input bg-background p-2" value={body} onChange={(event) => setBody(event.target.value)} required maxLength={100000} /></label><div className="flex items-center justify-between"><span>Minimum two comparisons · Quality floor 80% · Improvement 5 percentage points</span><Button disabled={hypothesis.isPending || !targetId}>Pin hypothesis and challenger</Button></div></form>
        {detail.data.hypotheses.map((row) => <section key={row.id} className="space-y-2"><h3 className="font-medium">{row.claim}</h3><Badge variant="outline">{row.status.replaceAll("_", " ")}</Badge><p>{row.predictedEffect}</p><p className="text-muted-foreground">{row.targetDomain} · {row.riskClass} · {row.evaluationContract.protectedInvariants.join("; ")}</p><Button variant="outline" onClick={() => { if (hypothesisId !== row.id) setPrepared(null); setHypothesisId(row.id); setCases([emptyCase(), emptyCase()].map((item) => ({ ...item, invariantResults: row.evaluationContract.protectedInvariants.map(() => false) }))); }}>Review paired outcomes</Button></section>)}
        {chosen ? <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); evaluate.mutate(); }}><h2 className="font-medium">Human review: {chosen.claim}</h2><p>This comparison records your judgement. It does not establish causation.</p>{cases.map((item, index) => <fieldset key={index} className="space-y-3 rounded-md border border-border p-4"><legend>Comparison {index + 1}</legend>{(["baseline", "challenger"] as const).map((arm) => <div key={arm} className="space-y-2"><label className="block">{arm === "baseline" ? "Baseline outcome" : "Challenger outcome"}<select className="rounded-md border border-input bg-background p-2" value={arm === "baseline" ? item.baselineTaskId : item.challengerTaskId} onChange={(event) => setCase(index, arm === "baseline" ? { baselineTaskId: event.target.value } : { challengerTaskId: event.target.value })} required><option value="">Select a completed Task</option>{tasks.data?.filter((row) => row.completedAt).map((row) => <option key={row.id} value={row.id}>{row.identifier} · {row.title}</option>)}</select></label>
          <div className="flex flex-wrap gap-4">{(["correctness", "safety", "policy"] as const).map((key) => <label key={key}><input type="checkbox" checked={item[arm][key]} onChange={(event) => setCase(index, { [arm]: { ...item[arm], [key]: event.target.checked } })} /> {key}</label>)}</div>{(["businessOutcome", "reliability"] as const).map((key) => <label key={key} className="block">{key === "businessOutcome" ? "Business outcome quality (0–1)" : "Reliability (0–1)"}<Input type="number" min={0} max={1} step={0.01} value={item[arm][key]} onChange={(event) => setCase(index, { [arm]: { ...item[arm], [key]: Number(event.target.value) } })} /></label>)}</div>)}
          {chosen.evaluationContract.protectedInvariants.map((text, i) => <label className="block" key={i}><input type="checkbox" checked={item.invariantResults[i] ?? false} onChange={(event) => setCase(index, { invariantResults: item.invariantResults.map((value, n) => n === i ? event.target.checked : value) })} /> Preserved: {text}</label>)}<label className="block space-y-2">Evidence and rationale<Input value={item.rationale} onChange={(event) => setCase(index, { rationale: event.target.value })} required minLength={20} maxLength={2000} /></label></fieldset>)}<label className="block space-y-2">Limitations<Input value={limitations} onChange={(event) => setLimitations(event.target.value)} required minLength={10} maxLength={1000} /></label><div className="flex items-center justify-between"><Button type="button" variant="outline" disabled={cases.length >= 32} onClick={() => setCases([...cases, { ...emptyCase(), invariantResults: chosen.evaluationContract.protectedInvariants.map(() => false) }])}>Add comparison</Button><Button disabled={evaluate.isPending || chosen.status === "proposal_created"}>Record human evaluation</Button></div></form> : null}
        {detail.data.evaluations.map((row) => <section className="space-y-2" key={row.id}><Badge variant="outline">{row.result}</Badge><p>Reviewed by {row.reviewedBy} · {new Date(row.createdAt).toLocaleString()}</p>{row.limitations.map((text, index) => <p className="text-muted-foreground" key={index}>{text}</p>)}</section>)}
        {chosen?.status === "supported" && prepared ? <Button disabled={propose.isPending} onClick={() => propose.mutate()}>Create reviewed domain proposal</Button> : null}
        {chosen?.status === "supported" && chosen.targetDomain === "foundation" && !prepared ? <div className="space-y-2"><p>Re-enter the evaluated document body and change reason above to restore the pinned draft.</p><Button disabled={!body.trim() || reason.trim().length < 20 || restoreDraft.isPending} onClick={() => restoreDraft.mutate()}>Restore evaluated draft</Button></div> : null}
        {detail.data.candidates.map((row) => <p key={row.id}>{row.erasedAt || row.invalidatedAt ? "Evidence requires revalidation" : row.promotionReceipt ? "Native domain promotion observed" : "Proposal created; separate domain approval remains required"} · <Link to={row.targetDomain === "foundation" ? `/foundation/${row.targetId}` : row.targetDomain === "skill" ? `/skills/${row.targetId}/governance` : row.targetDomain === "project" ? `/projects/${row.targetId}` : ["workflow", "automation_artifact"].includes(row.targetDomain) ? `/workflows/${row.targetId}` : row.targetDomain === "role_pack" ? "/role-packs" : "/memory"}>Open {row.targetDomain.replaceAll("_", " ")}</Link></p>)}
        {!["completed", "cancelled", "failed"].includes(detail.data.status) ? <section className="space-y-3"><h2 className="font-medium">Close the cycle</h2><p className="text-muted-foreground">Completion checks the native domain's current promotion receipt for every proposal. Cancellation is available before a domain candidate is created.</p><label className="block space-y-2">Closure rationale<Input value={closeRationale} onChange={event => setCloseRationale(event.target.value)} minLength={20} maxLength={2000} /></label><div className="flex items-center justify-between"><Button variant="outline" disabled={detail.data.candidates.length > 0 || closeRationale.trim().length < 20 || finish.isPending} onClick={() => finish.mutate("cancel")}>Cancel unpromoted cycle</Button><Button disabled={closeRationale.trim().length < 20 || finish.isPending} onClick={() => finish.mutate("complete")}>Check promotion and complete</Button></div></section> : null}
      </> : null}<LearningPolicyReview key={companyId} companyId={companyId} /></>}{errors.map((state, index) => <p role="alert" key={index}>{state.error instanceof Error ? state.error.message : "Learning operation failed"}</p>)}
  </div>;
}
