import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ORG_UNIT_TYPES, COMPANY_RELATIONSHIP_TYPES, type OrgUnit, type CompanyRelationship } from "@paperclipai/shared";
import { api } from "@/api/client";
import { agentsApi } from "@/api/agents";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { V5Error } from "@/components/V5Gate";

export function OrgUnits() {
  const { selectedCompanyId } = useCompany(), cid = selectedCompanyId!, { setBreadcrumbs } = useBreadcrumbs(), cache = useQueryClient(), base = `/companies/${cid}/org-units`;
  const units = useQuery({ queryKey: ["v5-org-units", cid], queryFn: () => api.get<OrgUnit[]>(base) }), agents = useQuery({ queryKey: ["v5-org-agents", cid], queryFn: () => agentsApi.list(cid) });
  const [selected, setSelected] = useState(""), [name, setName] = useState(""), [slug, setSlug] = useState(""), [type, setType] = useState("team"), [parentId, setParentId] = useState(""), [principalId, setPrincipalId] = useState(""), [humanId, setHumanId] = useState(""), [role, setRole] = useState("member");
  const members = useQuery({ queryKey: ["v5-org-members", cid, selected], queryFn: () => api.get<Array<{ id: string; principalType: string; principalId: string; role: string; status: string }>>(`${base}/${selected}/memberships`), enabled: Boolean(selected) });
  const mutate = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["v5-org-units", cid] }); await cache.invalidateQueries({ queryKey: ["v5-org-members", cid] }); } });
  useEffect(() => { setBreadcrumbs([{ label: "Organization units" }]); }, [setBreadcrumbs]);
  const row = units.data?.find((u) => u.id === selected);
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Organization units</h1><p className="text-sm text-muted-foreground">Company-local teams and reporting context. Membership and leadership grant no permissions.</p></div><V5Error error={units.error ?? members.error ?? agents.error ?? mutate.error} /><Card><CardHeader><CardTitle>{row ? `Edit ${row.name}` : "Create unit"}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{units.data?.map((u) => <Button key={u.id} variant={selected === u.id ? "secondary" : "outline"} onClick={() => { setSelected(u.id); setName(u.name); setSlug(u.slug); setType(u.type); setParentId(u.parentId ?? ""); }}>{u.name} · {u.status}</Button>)}<Button variant="outline" onClick={() => { setSelected(""); setName(""); setSlug(""); setParentId(""); }}>New unit</Button></div><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); mutate.mutate(async () => { const input = { name, slug, type, parentId: parentId || null }; if (selected) await api.patch(`${base}/${selected}`, input); else { const result = await api.post<{ id: string }>(base, input); setSelected(result.id); } }); }}><div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-sm"><span className="block">Name</span><Input value={name} onChange={(e) => setName(e.target.value)} required /></label><label className="space-y-1 text-sm"><span className="block">Stable slug</span><Input value={slug} onChange={(e) => setSlug(e.target.value)} pattern="[a-z0-9]+(-[a-z0-9]+)*" required /></label><label className="space-y-1 text-sm"><span className="block">Type</span><select className="w-full rounded-md border bg-background p-2" value={type} onChange={(e) => setType(e.target.value)}>{ORG_UNIT_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Parent unit</span><select className="w-full rounded-md border bg-background p-2" value={parentId} onChange={(e) => setParentId(e.target.value)}><option value="">Root unit</option>{units.data?.filter((u) => u.id !== selected && u.status === "active").map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><div className="flex items-center justify-between gap-3"><Button variant="outline" type="button" onClick={() => setSelected("")}>Cancel</Button><Button disabled={mutate.isPending}>Save unit</Button></div></form>{row && <div className="flex justify-end"><Button variant={row.status === "active" ? "destructive" : "outline"} disabled={mutate.isPending} onClick={() => mutate.mutate(() => api.patch(`${base}/${selected}`, { status: row.status === "active" ? "archived" : "active" }))}>{row.status === "active" ? "Archive unit" : "Restore unit"}</Button></div>}</CardContent></Card>
    {row && <Card><CardHeader><CardTitle>Local memberships</CardTitle></CardHeader><CardContent className="space-y-4">{members.data?.map((m) => <div key={m.id} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm"><span>{m.principalType === "agent" ? agents.data?.find((a) => a.id === m.principalId)?.name ?? m.principalId : m.principalId} · {m.principalType} · {m.role}</span><Badge variant="outline">{m.status}</Badge><Button variant="ghost" size="sm" disabled={mutate.isPending || m.status !== "active"} onClick={() => mutate.mutate(() => api.put(`${base}/${selected}/memberships`, { principalType: m.principalType, principalId: m.principalId, role: m.role, status: "archived" }))}>Remove membership</Button></div>)}<div className="flex flex-wrap items-end gap-3"><label className="space-y-1 text-sm"><span className="block">Local agent</span><select className="rounded-md border bg-background p-2" value={principalId} onChange={(e) => setPrincipalId(e.target.value)}><option value="">Select agent</option>{agents.data?.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Unit role</span><select className="rounded-md border bg-background p-2" value={role} onChange={(e) => setRole(e.target.value)}><option value="member">Member</option><option value="lead">Lead</option></select></label><Button disabled={mutate.isPending || !principalId || row.status !== "active"} onClick={() => mutate.mutate(() => api.put(`${base}/${selected}/memberships`, { principalType: "agent", principalId, role, status: "active" }))}>Add agent membership</Button></div><div className="flex items-end gap-3"><label className="flex-1 space-y-1 text-sm"><span className="block">Active company member ID</span><Input value={humanId} onChange={(e) => setHumanId(e.target.value)} /></label><Button variant="outline" disabled={mutate.isPending || !humanId || row.status !== "active"} onClick={() => mutate.mutate(() => api.put(`${base}/${selected}/memberships`, { principalType: "user", principalId: humanId, role, status: "active" }))}>Add human membership</Button></div></CardContent></Card>}
  </main>;
}

export function CompanyRelationships() {
  const { selectedCompanyId, companies } = useCompany(), cid = selectedCompanyId!, { setBreadcrumbs } = useBreadcrumbs(), base = `/companies/${cid}/relationships`;
  const query = useQuery({ queryKey: ["v5-relationships", cid], queryFn: () => api.get<CompanyRelationship[]>(base) });
  const [target, setTarget] = useState(""), [type, setType] = useState("portfolio_company");
  const mutate = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: () => query.refetch() });
  useEffect(() => { setBreadcrumbs([{ label: "Company relationships" }]); }, [setBreadcrumbs]);
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Company relationships</h1><p className="text-sm text-muted-foreground">Explicit relationships require acceptance by the destination company and grant no access.</p></div><V5Error error={query.error ?? mutate.error} /><Card><CardHeader><CardTitle>Propose a relationship</CardTitle></CardHeader><CardContent><form className="flex flex-wrap items-end gap-3" onSubmit={(e) => { e.preventDefault(); mutate.mutate(() => api.post(base, { targetCompanyId: target, relationshipType: type })); }}><label className="space-y-1 text-sm"><span className="block">Target company</span><select className="rounded-md border bg-background p-2" value={target} onChange={(e) => setTarget(e.target.value)} required><option value="">Select company</option>{companies.filter((c) => c.id !== cid).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Relationship type</span><select className="rounded-md border bg-background p-2" value={type} onChange={(e) => setType(e.target.value)}>{COMPANY_RELATIONSHIP_TYPES.map((t) => <option key={t} value={t}>{t.replaceAll("_", " ")}</option>)}</select></label><Button disabled={mutate.isPending || !target}>Propose for acceptance</Button></form></CardContent></Card><div className="space-y-3">{query.data?.map((r) => <Card key={r.id}><CardContent className="space-y-3 pt-6"><p className="text-sm font-medium">{companies.find((c) => c.id === r.sourceCompanyId)?.name ?? "Source company"} → {companies.find((c) => c.id === r.targetCompanyId)?.name ?? "Target company"} · {r.relationshipType.replaceAll("_", " ")}</p><Badge variant="outline">{r.status}</Badge><div className="flex justify-end gap-2">{r.status === "proposed" && r.targetCompanyId === cid && <><Button variant="outline" disabled={mutate.isPending} onClick={() => mutate.mutate(() => api.post(`${base}/${r.id}/transition`, { action: "reject" }))}>Reject</Button><Button disabled={mutate.isPending} onClick={() => mutate.mutate(() => api.post(`${base}/${r.id}/transition`, { action: "accept" }))}>Accept relationship</Button></>}{r.status === "active" && <Button variant="destructive" disabled={mutate.isPending} onClick={() => mutate.mutate(() => api.post(`${base}/${r.id}/transition`, { action: "revoke" }))}>Revoke relationship</Button>}</div></CardContent></Card>)}</div></main>;
}
