import { useEffect, useState } from "react";
import { PlaybookMetadata } from "@/components/PlaybookMetadata";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { v5Api } from "@/api/v5";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { Link, useNavigate, useParams } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { MarkdownBody } from "@/components/MarkdownBody";
import { V5Error } from "@/components/V5Gate";

export function Playbooks() {
  const { selectedCompanyId } = useCompany(), cid = selectedCompanyId!, { playbookId } = useParams(), navigate = useNavigate(), cache = useQueryClient();
  const { setBreadcrumbs } = useBreadcrumbs();
  const [synchronizationNotice, setSynchronizationNotice] = useState("");
  const [creating, setCreating] = useState(false), [editing, setEditing] = useState(false), [key, setKey] = useState(""), [title, setTitle] = useState(""), [body, setBody] = useState(""), [reason, setReason] = useState(""), [revisionId, setRevisionId] = useState<string | null>(null), [skillId, setSkillId] = useState(""), [baseVersion, setBaseVersion] = useState(""), [procedure, setProcedure] = useState(""), [syncPolicy, setSyncPolicy] = useState<"manual" | "notify_on_change" | "auto_generate_candidate">("notify_on_change");
  const list = useQuery({ queryKey: ["v5-playbooks", cid], queryFn: () => v5Api.playbooks(cid) });
  const detail = useQuery({ queryKey: ["v5-playbook", cid, playbookId], queryFn: () => v5Api.playbook(cid, playbookId!), enabled: Boolean(playbookId) });
  const viewRevision = revisionId ?? detail.data?.approvedRevisionId ?? detail.data?.document.latestRevisionId;
  const revision = useQuery({ queryKey: ["v5-playbook-revision", cid, playbookId, viewRevision], queryFn: () => v5Api.revision(cid, playbookId!, viewRevision!), enabled: Boolean(playbookId && viewRevision) });
  useEffect(() => { setBreadcrumbs([{ label: "Playbooks", href: "/playbooks" }, ...(detail.data ? [{ label: detail.data.document.title ?? detail.data.key }] : [])]); }, [setBreadcrumbs, detail.data]);
  useEffect(() => { setEditing(false); setCreating(false); setRevisionId(null); setReason(""); setSynchronizationNotice(""); }, [playbookId, cid]);
  const mutation = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: async () => { setEditing(false); setCreating(false); await cache.invalidateQueries({ queryKey: ["v5-playbooks", cid] }); await cache.invalidateQueries({ queryKey: ["v5-playbook", cid] }); await cache.invalidateQueries({ queryKey: ["v5-playbook-revision", cid] }); } });
  const row = detail.data, busy = mutation.isPending;
  return <main className="mx-auto max-w-6xl space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{row?.document.title ?? "Playbooks"}</h1><p className="text-sm text-muted-foreground">Canonical organizational procedures with reviewed revisions and Skill links.</p></div>{playbookId ? <Link to="/playbooks" className="text-primary underline">All Playbooks</Link> : <Button disabled={busy} onClick={() => { setCreating(true); setTitle(""); setBody(""); setKey(""); }}>New Playbook</Button>}</div>
    <V5Error error={list.error ?? detail.error ?? revision.error ?? mutation.error} />
    {synchronizationNotice && <p role="status" className="rounded-md border bg-muted p-3 text-sm">{synchronizationNotice}</p>}
    {(list.isPending || (playbookId && detail.isPending)) && <p role="status">Loading Playbooks…</p>}
    {!playbookId && !creating && <div className="grid gap-4 md:grid-cols-2">{list.data?.map((p) => <Card key={p.id}><CardHeader><CardTitle><Link to={`/playbooks/${p.id}`} className="hover:underline">{p.title ?? p.key}</Link></CardTitle></CardHeader><CardContent className="space-y-2"><div className="flex flex-wrap gap-2"><Badge variant="outline">{p.status}</Badge><Badge variant="secondary">{p.sensitivity}</Badge>{p.overdue && <Badge variant="destructive">Review overdue</Badge>}</div><p className="text-sm text-muted-foreground">{p.category} · review every {p.reviewFrequencyDays} days</p></CardContent></Card>)}{list.data?.length === 0 && <p className="text-muted-foreground">No Playbooks yet. Create a draft and review it before use.</p>}</div>}
    {(creating || editing) && <form className="space-y-4 rounded-lg border p-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(async () => { if (creating) { const created = await v5Api.createPlaybook(cid, { key, title, markdown: body }); navigate(`/playbooks/${created.id}`); } else if (row && playbookId) await v5Api.draftPlaybook(cid, playbookId, { expectedRevisionId: row.document.latestRevisionId, title, markdown: body, changeSummary: reason }); }); }}>
      {creating && <label className="block space-y-1"><span className="text-sm font-medium">Stable key</span><Input value={key} onChange={(e) => setKey(e.target.value)} pattern="[a-z0-9][a-z0-9_-]*" maxLength={100} required /></label>}
      <label className="block space-y-1"><span className="text-sm font-medium">Title</span><Input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={200} required /></label>
      <label className="block space-y-1"><span className="text-sm font-medium">Procedure in Markdown</span><Textarea rows={16} value={body} onChange={(e) => setBody(e.target.value)} required /></label>
      {!creating && <label className="block space-y-1"><span className="text-sm font-medium">Change summary</span><Input value={reason} onChange={(e) => setReason(e.target.value)} required /></label>}
      <div className="flex items-center justify-between gap-3"><Button type="button" variant="outline" onClick={() => { setCreating(false); setEditing(false); }}>Cancel</Button><Button disabled={busy} type="submit">Save draft</Button></div>
    </form>}
    {row && !editing && <>
      <PlaybookMetadata key={`${cid}:${row.id}:${row.updatedAt}`} companyId={cid} playbook={row} busy={busy} onSave={(input) => mutation.mutate(() => v5Api.updatePlaybookMetadata(cid, row.id, input))} />
      <div className="flex flex-wrap items-center gap-2"><Badge>{row.status}</Badge><Badge variant="outline">{row.sensitivity}</Badge>{row.overdue && <Badge variant="destructive">Review overdue</Badge>}<span className="text-sm text-muted-foreground">Review due: {row.nextReviewAt ? new Date(row.nextReviewAt).toLocaleDateString() : "Not reviewed"}</span><Button disabled={busy} variant="outline" onClick={() => { setTitle(row.document.title ?? ""); setBody(row.document.latestBody); setReason(""); setEditing(true); }}>Edit draft</Button><a className="text-sm text-primary underline" href={`/api/companies/${cid}/playbooks/${playbookId}/export`}>Export canonical Markdown</a></div>
      <label className="flex flex-wrap items-center gap-3"><span className="text-sm font-medium">View revision</span><select className="rounded-md border bg-background p-2 text-sm" value={viewRevision ?? ""} onChange={(e) => setRevisionId(e.target.value)}>{row.revisions.map((r) => <option key={r.id} value={r.id}>Revision {r.revisionNumber}{r.id === row.approvedRevisionId ? " · approved canonical" : r.id === row.document.latestRevisionId ? " · latest draft" : ""} · {r.changeSummary}</option>)}</select></label>
      <Card><CardContent className="pt-6"><MarkdownBody>{revision.data?.body ?? "Loading revision…"}</MarkdownBody></CardContent></Card>
      <Card><CardHeader><CardTitle>Human review</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Review the latest draft before approving it. The current approved revision stays canonical until approval.</p><label className="block space-y-1"><span className="text-sm font-medium">Review rationale</span><Textarea value={reason} onChange={(e) => setReason(e.target.value)} minLength={10} /></label><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={busy || reason.trim().length < 10 || row.status === "archived"} onClick={() => mutation.mutate(() => v5Api.reviewPlaybook(cid, playbookId!, { expectedRevisionId: row.document.latestRevisionId, decision: "request_changes", rationale: reason }))}>Request changes</Button><Button disabled={busy || reason.trim().length < 10 || row.status === "archived"} onClick={() => mutation.mutate(async () => { const reviewed = await v5Api.reviewPlaybook(cid, playbookId!, { expectedRevisionId: row.document.latestRevisionId, decision: "approve", rationale: reason }); setSynchronizationNotice(reviewed.synchronizationFailures.length ? `Playbook approved. ${reviewed.synchronizationFailures.length} Skill projection(s) need attention; use the linked Skill and drift details below. No Skill was activated.` : `Playbook approved. ${reviewed.generatedCandidates.length} new Skill candidate(s) require evaluation before activation.`); })}>Approve latest revision</Button><Button variant="destructive" disabled={busy || reason.trim().length < 10 || row.status === "archived"} onClick={() => mutation.mutate(() => v5Api.reviewPlaybook(cid, playbookId!, { expectedRevisionId: row.document.latestRevisionId, decision: "archive", rationale: reason }))}>Archive</Button></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Skill links and drift</CardTitle></CardHeader><CardContent className="space-y-3">{row.links.length === 0 && <p className="text-sm text-muted-foreground">No projected procedures yet.</p>}{row.links.map((link) => <div key={link.id} className="flex flex-wrap items-center gap-2"><Link to={`/skills/${link.skillId}/governance`} className="text-primary underline">Skill {link.skillId}</Link><Badge variant={link.drifted ? "destructive" : "outline"}>{link.drifted ? "Canonical revision changed" : "Revision aligned"}</Badge><span className="text-xs text-muted-foreground">{link.relationType} · {link.syncPolicy}</span></div>)}
        <details className="space-y-3"><summary className="cursor-pointer text-sm font-medium">Project reviewed Playbook into a Skill candidate</summary><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (row.approvedRevisionId) mutation.mutate(() => v5Api.projectSkill(cid, playbookId!, { approvedRevisionId: row.approvedRevisionId!, skillId, baseActiveVersionId: baseVersion || null, markdown: procedure, summary: reason, syncPolicy })); }}><label className="block">Local Skill ID<Input value={skillId} onChange={(e) => setSkillId(e.target.value)} required /></label><label className="block">Current active Skill version (empty for first candidate)<Input value={baseVersion} onChange={(e) => setBaseVersion(e.target.value)} /></label><label className="block">AI procedure<Textarea rows={8} value={procedure} onChange={(e) => setProcedure(e.target.value)} required /></label><label className="block space-y-1 text-sm"><span>When the canonical procedure changes</span><select className="w-full rounded-md border bg-background p-2" value={syncPolicy} onChange={(event) => setSyncPolicy(event.target.value as typeof syncPolicy)}><option value="manual">Manual synchronization</option><option value="notify_on_change">Show drift for review</option><option value="auto_generate_candidate">Create a new candidate after canonical approval</option></select></label><p className="text-xs text-muted-foreground">New candidates still require evaluation and explicit promotion. This policy never activates a procedure automatically.</p><label className="block">Projection summary<Input value={reason} onChange={(e) => setReason(e.target.value)} minLength={20} required /></label><div className="flex justify-end"><Button disabled={busy || !row.approvedRevisionId || row.overdue}>Create candidate for evaluation</Button></div></form></details>
      </CardContent></Card>
      {row.proposals.length > 0 && <Card><CardHeader><CardTitle>Canonical change proposals</CardTitle></CardHeader><CardContent className="space-y-4">{row.proposals.map((p) => <details key={p.id}><summary className="cursor-pointer">{p.title} · {p.status}</summary><p className="my-2 text-sm">{p.reason}</p><MarkdownBody>{p.markdown}</MarkdownBody>{p.status === "pending" && <div className="mt-3 flex justify-end gap-2"><Button variant="outline" disabled={busy || reason.trim().length < 10} onClick={() => mutation.mutate(() => v5Api.reviewPlaybookProposal(cid, playbookId!, p.id, false, reason))}>Reject</Button><Button disabled={busy || reason.trim().length < 10} onClick={() => mutation.mutate(() => v5Api.reviewPlaybookProposal(cid, playbookId!, p.id, true, reason))}>Accept as draft</Button></div>}</details>)}</CardContent></Card>}
    </>}
  </main>;
}
