import { PortfolioPublication, PortfolioUpgrade } from "@/components/PortfolioPublication";
import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { v5Api } from "@/api/v5";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { Link } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { V5Error } from "@/components/V5Gate";

export function Portfolio() {
  const { companies, selectedCompanyId } = useCompany(), { setBreadcrumbs } = useBreadcrumbs();
  const [selected, setSelected] = useState(() => companies.slice(0, 32).map((c) => c.id));
  const query = useQuery({ queryKey: ["v5-portfolio", [...selected].sort()], queryFn: () => v5Api.portfolio([...selected].sort()), enabled: selected.length > 0 });
  useEffect(() => { setBreadcrumbs([{ label: "August OS portfolio" }]); }, [setBreadcrumbs]);
  const prefix = (cid: string) => `/${companies.find((c) => c.id === cid)?.issuePrefix ?? ""}`;
  return <main className="mx-auto max-w-7xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">August OS</h1><p className="text-sm text-muted-foreground">Company operations, your tasks and approval queues from their canonical sources.</p></div>
    <details className="space-y-3 rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Companies in this view ({selected.length}/32)</summary><div className="flex flex-wrap gap-4">{companies.map((c) => <label key={c.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(c.id)} disabled={!selected.includes(c.id) && selected.length >= 32} onChange={(e) => setSelected((old) => e.target.checked ? [...old, c.id] : old.filter((id) => id !== c.id))} />{c.name}{c.id === selectedCompanyId ? " · current" : ""}</label>)}</div></details>
    <V5Error error={query.error} />{query.isFetching && <p role="status" className="text-sm text-muted-foreground">Refreshing company sources…</p>}{selected.length === 0 && <p>Select at least one company.</p>}
    {query.data?.unavailableCompanyIds.length ? <p role="status" className="rounded-md border p-3 text-sm">{query.data.unavailableCompanyIds.length} selected company source(s) are unavailable under your current access.</p> : null}
    <div className="grid gap-4 lg:grid-cols-2">{query.data?.companies.map((c) => <Card key={c.companyId}><CardHeader><CardTitle><Link to={`${prefix(c.companyId)}/dashboard`} className="hover:underline">{c.name}</Link></CardTitle><p className="text-xs text-muted-foreground">Observed {new Date(c.observedAt).toLocaleString()} · {c.status}</p></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant="outline">{c.dashboard.tasks.open} open tasks</Badge><Badge variant="outline">{c.dashboard.tasks.blocked} blocked</Badge><Badge variant="outline">{c.dashboard.agents.running} running agents</Badge><Badge variant={c.dashboard.budgets.activeIncidents ? "destructive" : "outline"}>{c.dashboard.budgets.activeIncidents} budget incidents</Badge></div><p className="text-sm">Monthly spend {(c.dashboard.costs.monthSpendCents / 100).toFixed(2)} / budget {(c.dashboard.costs.monthBudgetCents / 100).toFixed(2)} · {c.dashboard.costs.monthUtilizationPercent}%</p><div><h2 className="mb-2 text-sm font-semibold">Projects and milestones</h2><ul className="space-y-2 text-sm">{c.projects.map((p) => <li key={p.id}><Link className="text-primary underline" to={`${prefix(c.companyId)}/projects/${p.id}/roadmap`}>{p.name}</Link> · {p.status} · target {p.targetDate ?? "unknown"}</li>)}{c.milestones.map((m) => <li key={m.id}>◆ {m.name} · {m.status} · {m.targetDate ?? "No target"}</li>)}</ul></div><details><summary className="cursor-pointer text-sm font-semibold">Goals ({c.goals.length})</summary><ul className="mt-2 space-y-1 text-sm">{c.goals.map((g) => <li key={g.id}><Link className="text-primary underline" to={`${prefix(c.companyId)}/goals/${g.id}`}>{g.title}</Link> · {g.status}</li>)}</ul></details><div><h2 className="mb-2 text-sm font-semibold">My tasks ({c.myTasks.length})</h2><ul className="space-y-1 text-sm">{c.myTasks.map((t) => <li key={t.id}><Link className="text-primary underline" to={`${prefix(c.companyId)}/issues/${t.identifier ?? t.id}`}>{t.title}</Link> · {t.status}</li>)}</ul></div><Link className="text-sm text-primary underline" to={`${prefix(c.companyId)}/inbox`}>Review queue: {c.myApprovals.length} pending approvals</Link></CardContent></Card>)}</div>
  </main>;
}

export function PortfolioCapabilities() {
  const { selectedCompanyId } = useCompany(), cid = selectedCompanyId!, { setBreadcrumbs } = useBreadcrumbs();
  const releases = useQuery({ queryKey: ["v5-portfolio-releases", cid], queryFn: () => v5Api.releases(cid) }), subscriptions = useQuery({ queryKey: ["v5-portfolio-subscriptions", cid], queryFn: () => v5Api.subscriptions(cid) });
  const [localKey, setLocalKey] = useState(""), [mode, setMode] = useState<"install" | "subscribe" | "fork">("install");
  const install = useMutation({ mutationFn: (id: string) => v5Api.install(cid, id, localKey, mode), onSuccess: () => subscriptions.refetch() });
  useEffect(() => { setBreadcrumbs([{ label: "Portfolio capabilities" }]); }, [setBreadcrumbs]);
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Portfolio capabilities</h1><p className="text-sm text-muted-foreground">Explicit releases shared with this company. Adoption creates a local candidate or draft for review.</p></div><V5Error error={releases.error ?? subscriptions.error ?? install.error} />{install.isSuccess && <p role="status">Adopted locally for evaluation and review.</p>}<div className="flex flex-wrap gap-3"><label className="space-y-1 text-sm"><span className="block">Local asset key</span><Input value={localKey} onChange={(e) => setLocalKey(e.target.value)} placeholder="release-procedure" /></label><label className="space-y-1 text-sm"><span className="block">Adoption mode</span><select className="rounded-md border bg-background p-2" value={mode} onChange={(e) => setMode(e.target.value as typeof mode)}><option value="install">Install pinned copy</option><option value="subscribe">Subscribe to proposed upgrades</option><option value="fork">Independent fork</option></select></label></div><div className="grid gap-4 md:grid-cols-2">{releases.data?.map((r) => <Card key={r.id}><CardHeader><CardTitle>{r.title}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Badge variant="outline">{r.assetType}</Badge><Badge variant="secondary">{r.classification}</Badge></div><p className="text-sm">{r.releaseNotes}</p><p className="break-all text-xs text-muted-foreground">Source company {r.companyId} · version {r.versionId}</p><Button disabled={install.isPending || !/^[a-z0-9][a-z0-9_-]{0,99}$/.test(localKey)} onClick={() => install.mutate(r.id)}>Adopt as local draft</Button></CardContent></Card>)}</div>{releases.data?.length === 0 && <p className="text-muted-foreground">No authorized releases are available.</p>}<Card><CardHeader><CardTitle>Installed assets and subscriptions</CardTitle></CardHeader><CardContent className="space-y-3">{subscriptions.data?.map((s) => <div key={s.id} className="space-y-1 border-b pb-3"><Link className="text-sm text-primary underline" to={s.localSkillId ? `/skills/${s.localSkillId}/governance` : `/playbooks/${s.localPlaybookId}`}>{s.assetType} · {s.mode}</Link><p className="text-xs text-muted-foreground">Pinned source: {s.pinnedSourceVersionId}</p><Badge variant={!s.sourceAvailable ? "destructive" : "outline"}>{!s.sourceAvailable ? "Source unavailable" : s.updateAvailable ? "New release available for review" : "Pinned release current"}</Badge>{s.updateAvailable && <PortfolioUpgrade companyId={cid} subscription={s} onPrepared={() => subscriptions.refetch()} />}</div>)}</CardContent></Card><PortfolioPublication companyId={cid} /></main>;
}
