import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { rolePackItemSchema, ROLE_PACK_ITEM_TYPES, type RolePackItem } from "@paperclipai/shared";
import { api } from "@/api/client";
import { v5Api } from "@/api/v5";
import { agentsApi } from "@/api/agents";
import { useCompany } from "@/context/CompanyContext";
import { useBreadcrumbs } from "@/context/BreadcrumbContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { V5Error } from "@/components/V5Gate";

export function RolePacks() {
  const { selectedCompanyId } = useCompany(), cid = selectedCompanyId!, cache = useQueryClient(), { setBreadcrumbs } = useBreadcrumbs();
  const [selected, setSelected] = useState(""), [selectedVersion, setSelectedVersion] = useState(""), [key, setKey] = useState(""), [name, setName] = useState(""), [items, setItems] = useState<RolePackItem[]>([]), [type, setType] = useState<RolePackItem["type"]>("required_skill"), [ref, setRef] = useState(""), [triggers, setTriggers] = useState(""), [excludes, setExcludes] = useState(""), [load, setLoad] = useState<RolePackItem["loadPoint"]>("task_relevant"), [summary, setSummary] = useState(""), [agentId, setAgentId] = useState(""), [scopeType, setScopeType] = useState<"company" | "agent" | "org_unit">("company"), [unitId, setUnitId] = useState(""), [pin, setPin] = useState(false), [localError, setLocalError] = useState<Error | null>(null);
  const packs = useQuery({ queryKey: ["v5-role-packs", cid], queryFn: () => v5Api.rolePacks(cid) }), catalog = useQuery({ queryKey: ["v5-role-catalog", cid], queryFn: () => v5Api.roleCatalog(cid) });
  const detail = useQuery({ queryKey: ["v5-role-pack", cid, selected], queryFn: () => v5Api.rolePack(cid, selected), enabled: Boolean(selected) });
  const version = useQuery({ queryKey: ["v5-role-version", cid, selected, selectedVersion], queryFn: () => v5Api.roleVersion(cid, selected, selectedVersion), enabled: Boolean(selected && selectedVersion) });
  const units = useQuery({ queryKey: ["v5-role-units", cid], queryFn: () => api.get<Array<{ id: string; name: string; status: string }>>(`/companies/${cid}/org-units`) });
  const agents = useQuery({ queryKey: ["v5-role-agents", cid], queryFn: () => agentsApi.list(cid) });
  useEffect(() => { setBreadcrumbs([{ label: "Role Packs" }]); }, [setBreadcrumbs]);
  useEffect(() => { if (version.data) setItems(version.data.items); }, [version.data]);
  const mutate = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["v5-role-packs", cid] }); await cache.invalidateQueries({ queryKey: ["v5-role-pack", cid] }); await cache.invalidateQueries({ queryKey: ["v5-role-version", cid] }); } });
  const base = `/companies/${cid}/role-packs`, busy = mutate.isPending;
  function addItem() { const result = rolePackItemSchema.safeParse({ type, ref, loadPoint: load, triggerTerms: triggers.split(",").map((v) => v.trim()).filter(Boolean), excludeTerms: excludes.split(",").map((v) => v.trim()).filter(Boolean) }); if (!result.success) { setLocalError(new Error(result.error.issues.map((i) => i.message).join("; "))); return; } setLocalError(null); setItems((current) => [...current.filter((i) => i.type !== type || i.ref !== ref), result.data]); setRef(""); }
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Role Packs</h1><p className="text-sm text-muted-foreground">Versioned role, organizational and agent requirements. Packs preserve governance and grant no permissions.</p></div><V5Error error={packs.error ?? catalog.error ?? detail.error ?? version.error ?? mutate.error ?? localError} />
    <Card><CardHeader><CardTitle>Create company overlay</CardTitle></CardHeader><CardContent><form className="flex flex-wrap items-end gap-3" onSubmit={(e) => { e.preventDefault(); mutate.mutate(async () => { const created = await api.post<{ id: string }>(base, { key, name }); setSelected(created.id); setItems([]); setSelectedVersion(""); setKey(""); setName(""); }); }}><label className="space-y-1 text-sm"><span className="block">Stable key</span><Input value={key} onChange={(e) => setKey(e.target.value)} pattern="[a-z0-9][a-z0-9_-]*" required /></label><label className="space-y-1 text-sm"><span className="block">Name</span><Input value={name} onChange={(e) => setName(e.target.value)} required /></label><Button disabled={busy}>Create pack</Button></form></CardContent></Card>
    <div className="flex flex-wrap gap-3"><label className="space-y-1 text-sm"><span className="block">Company pack</span><select className="rounded-md border bg-background p-2" value={selected} onChange={(e) => { setSelected(e.target.value); setSelectedVersion(""); setItems([]); }}><option value="">Select a pack</option>{packs.data?.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{detail.data && <label className="space-y-1 text-sm"><span className="block">Inspect version</span><select className="rounded-md border bg-background p-2" value={selectedVersion} onChange={(e) => setSelectedVersion(e.target.value)}><option value="">New draft</option>{detail.data.versions.map((v) => <option value={v.id} key={v.id}>Revision {v.revisionNumber} · {v.status}{v.id === detail.data?.publishedVersionId ? " · current" : ""}</option>)}</select></label>}</div>
    {detail.data && <Card><CardHeader><CardTitle>{detail.data.name} requirements</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-xs text-muted-foreground">Changes create a new immutable version. Existing published versions remain unchanged.</p><div className="space-y-2">{items.map((item) => <div key={`${item.type}:${item.ref}`} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-2"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{item.type.replaceAll("_", " ")}</Badge><span className="text-sm">{item.ref}</span><span className="text-xs text-muted-foreground">{item.loadPoint} · triggers: {item.triggerTerms.join(", ") || "task key"}</span></div><Button variant="ghost" size="sm" onClick={() => setItems((current) => current.filter((i) => i !== item))}>Remove from new draft</Button></div>)}</div>
      <div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-sm"><span className="block">Requirement type</span><select className="w-full rounded-md border bg-background p-2" value={type} onChange={(e) => setType(e.target.value as RolePackItem["type"])}>{ROLE_PACK_ITEM_TYPES.map((t) => <option key={t} value={t}>{t.replaceAll("_", " ")}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Local key or reference</span><Input value={ref} onChange={(e) => setRef(e.target.value)} /></label><label className="space-y-1 text-sm"><span className="block">Trigger phrases, comma separated</span><Input value={triggers} onChange={(e) => setTriggers(e.target.value)} /></label><label className="space-y-1 text-sm"><span className="block">Exclusion phrases, comma separated</span><Input value={excludes} onChange={(e) => setExcludes(e.target.value)} /></label><label className="space-y-1 text-sm"><span className="block">Load point</span><select className="w-full rounded-md border bg-background p-2" value={load} onChange={(e) => setLoad(e.target.value as RolePackItem["loadPoint"])}><option value="always">Always</option><option value="task_relevant">When task relevant</option><option value="on_demand">On demand</option></select></label></div><Button variant="outline" onClick={addItem}>Add requirement to draft</Button><label className="block space-y-1 text-sm"><span>Version change summary</span><Input value={summary} onChange={(e) => setSummary(e.target.value)} /></label><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={busy} onClick={() => mutate.mutate(async () => { const draft = await api.post<{ id: string }>(`${base}/${selected}/versions`, { items, summary }); setSelectedVersion(draft.id); })}>Save new version</Button><Button disabled={busy || !selectedVersion || version.data?.status !== "draft"} onClick={() => mutate.mutate(() => api.post(`${base}/${selected}/versions/${selectedVersion}/publish`, { expectedPublishedVersionId: detail.data!.publishedVersionId }))}>Publish inspected version</Button></div>
      <div className="space-y-3 border-t pt-4"><h2 className="text-sm font-semibold">Assign version policy</h2><div className="flex flex-wrap items-end gap-3"><label className="space-y-1 text-sm"><span className="block">Scope</span><select className="rounded-md border bg-background p-2" value={scopeType} onChange={(e) => setScopeType(e.target.value as typeof scopeType)}><option value="company">Company overlay</option><option value="agent">Local agent overlay</option><option value="org_unit">Organizational unit overlay</option></select></label>{scopeType === "org_unit" && <label className="space-y-1 text-sm"><span className="block">Organizational unit</span><select className="rounded-md border bg-background p-2" value={unitId} onChange={(e) => setUnitId(e.target.value)}><option value="">Select unit</option>{units.data?.filter((unit) => unit.status === "active").map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label>}{scopeType === "agent" && <label className="space-y-1 text-sm"><span className="block">Local agent</span><select className="rounded-md border bg-background p-2" value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="">Select agent</option>{agents.data?.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pin} onChange={(e) => setPin(e.target.checked)} />Pin inspected published version</label><Button disabled={busy || !detail.data.publishedVersionId || scopeType === "agent" && !agentId || scopeType === "org_unit" && !unitId || pin && version.data?.status !== "published"} onClick={() => mutate.mutate(() => api.put(`${base}/assignments`, { scopeType, scopeId: scopeType === "company" ? cid : scopeType === "org_unit" ? unitId : agentId, rolePackId: selected, versionPolicy: pin ? "pinned" : "follow_published", pinnedVersionId: pin ? selectedVersion : null }))}>Assign pack</Button></div></div>
    </CardContent></Card>}
    <Card><CardHeader><CardTitle>System role defaults</CardTitle></CardHeader><CardContent className="space-y-3">{catalog.data?.map((p) => <details key={p.key}><summary className="cursor-pointer text-sm font-medium">{p.name} · {p.version}</summary><ul className="mt-2 space-y-1 text-xs text-muted-foreground">{p.items.map((i) => <li key={`${i.type}:${i.ref}`}>{i.type.replaceAll("_", " ")}: {i.ref}</li>)}</ul><Button variant="outline" size="sm" className="mt-2" onClick={() => setItems(p.items)}>Use as new draft</Button></details>)}</CardContent></Card>
  </main>;
}
