import type { BusinessScenarioDefinition, BusinessScenarioDistribution, BusinessScenarioUnit } from "@paperclipai/shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { scenarioUnitLabel } from "./BusinessScenarioResult";
type Assumption = BusinessScenarioDefinition["assumptions"][number];
const selectStyle = "w-full min-w-0 rounded-md border border-input bg-background p-2";
export const scenarioNumber = (value: string) => value.trim() ? Number(value) : NaN;
const numberText = (value: number) => Number.isNaN(value) ? "" : String(value);
export function ScenarioNumericField({ label, value, onChange, min, max, step = "any" }: { label: string; value: number; onChange: (value: number) => void; min?: number; max?: number; step?: string | number }) {
  return <label className="block space-y-2">{label}<Input aria-label={label} type="number" value={numberText(value)} onChange={event => onChange(scenarioNumber(event.target.value))} min={min} max={max} step={step} required /></label>;
}
export function ScenarioUnitFields({ label, value, onChange }: { label: string; value: BusinessScenarioUnit; onChange: (value: BusinessScenarioUnit) => void }) {
  const dimensions = ["issue", "project", "person", "customer", "second", "currency_USD", "currency_EUR", "currency_DKK", "currency_GBP"];
  const entries = Object.entries(value);
  return <fieldset className="min-w-0 space-y-2"><legend className="font-medium">{label} · {scenarioUnitLabel(value)}</legend>
    {entries.map(([dimension, power], index) => <div key={index} className="grid gap-2 sm:grid-cols-3"><label className="space-y-2">Dimension<select aria-label={`${label} dimension ${index + 1}`} className={selectStyle} value={dimension} onChange={event => { const next = { ...value }; delete next[dimension]; next[event.target.value] = power; onChange(next); }}>{[...new Set([...dimensions, dimension])].filter(item => item === dimension || !Object.hasOwn(value, item)).map(item => <option key={item} value={item}>{scenarioUnitLabel({ [item]: 1 })}</option>)}</select></label><ScenarioNumericField label={`${label} power ${index + 1}`} value={power} min={-6} max={6} step={1} onChange={next => onChange({ ...value, [dimension]: next })} /><Button type="button" variant="ghost" onClick={() => { const next = { ...value }; delete next[dimension]; onChange(next); }}>Remove dimension</Button></div>)}
    <p className="text-sm text-muted-foreground">Positive powers multiply the unit; negative powers divide by it. Currency conversions require their own explicit human assumption.</p>
    <Button type="button" variant="outline" disabled={entries.length >= 8 || dimensions.every(item => Object.hasOwn(value, item))} onClick={() => { const dimension = dimensions.find(item => !Object.hasOwn(value, item)); if (dimension) onChange({ ...value, [dimension]: 1 }); }}>Add unit dimension</Button>
  </fieldset>;
}
export function BusinessScenarioAssumptionFields({ value, index, sources, monteCarlo, onChange, onRemove }: { value: Assumption; index: number; sources: BusinessScenarioDefinition["inputs"]; monteCarlo: boolean; onChange: (value: Assumption) => void; onRemove: () => void }) {
  const label = (name: string) => `Assumption ${index + 1} ${name}`;
  const humanEvidence = value.evidence.find(item => item.kind === "human_statement");
  const distribution = value.distribution;
  const setDistribution = (next: BusinessScenarioDistribution | null) => onChange({ ...value, distribution: next });
  return <fieldset className="min-w-0 space-y-3 rounded-md border p-3"><legend className="px-1 font-medium">Explicit numeric assumption {index + 1}</legend>
    <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-2">Reference name<Input aria-label={label("reference name")} value={value.key} onChange={event => onChange({ ...value, key: event.target.value })} maxLength={64} required /></label><label className="space-y-2">Human name<Input aria-label={label("human name")} value={value.name} onChange={event => onChange({ ...value, name: event.target.value })} maxLength={160} required /></label></div>
    <ScenarioUnitFields label={label("unit")} value={value.unit} onChange={unit => onChange({ ...value, unit })} />
    <div className="grid gap-3 sm:grid-cols-3"><ScenarioNumericField label={label("nominal value")} value={value.nominal} onChange={nominal => onChange({ ...value, nominal })} /><ScenarioNumericField label={label("range minimum")} value={value.range.minimum} onChange={minimum => onChange({ ...value, range: { ...value.range, minimum } })} /><ScenarioNumericField label={label("range maximum")} value={value.range.maximum} onChange={maximum => onChange({ ...value, range: { ...value.range, maximum } })} /></div>
    <label className="block space-y-2">Accountable human owner<Input aria-label={label("human owner")} value={value.ownerUserId} onChange={event => onChange({ ...value, ownerUserId: event.target.value })} maxLength={200} required /></label>
    <label className="flex items-center gap-2"><input aria-label={label("controllable")} type="checkbox" checked={value.controllable} onChange={event => onChange({ ...value, controllable: event.target.checked })} />This assumption is controllable for an intervention</label>
    <label className="block space-y-2">Confidence statement<select aria-label={label("confidence statement")} className={selectStyle} value={value.confidence} onChange={event => onChange({ ...value, confidence: event.target.value as Assumption["confidence"] })}><option value="human_asserted">Human assertion</option><option value="evidence_supported">Human assertion with cited source evidence</option></select></label>
    <label className="block space-y-2">Human evidence or rationale<Textarea aria-label={label("human evidence")} value={humanEvidence?.kind === "human_statement" ? humanEvidence.rationale : ""} onChange={event => onChange({ ...value, evidence: [...value.evidence.filter(item => item.kind !== "human_statement"), ...(event.target.value.trim() ? [{ kind: "human_statement" as const, rationale: event.target.value }] : [])] })} maxLength={2000} /></label>
    {sources.length > 0 && <fieldset className="space-y-2"><legend>Supporting source pins</legend>{sources.map(source => <label key={source.key} className="flex items-center gap-2"><input aria-label={`${label("supporting source")} ${source.key}`} type="checkbox" checked={value.evidence.some(item => item.kind === "source_input" && item.inputKey === source.key)} onChange={event => onChange({ ...value, evidence: [...value.evidence.filter(item => item.kind !== "source_input" || item.inputKey !== source.key), ...(event.target.checked ? [{ kind: "source_input" as const, inputKey: source.key }] : [])] })} />{source.key}</label>)}</fieldset>}
    <label className="block space-y-2">Uncertainty and evidence limits<Textarea aria-label={label("uncertainty rationale")} value={value.uncertaintyRationale} onChange={event => onChange({ ...value, uncertaintyRationale: event.target.value })} maxLength={2000} required /></label>
    {monteCarlo && <fieldset className="space-y-3"><legend className="font-medium">Explicit conditional distribution</legend><label className="block space-y-2">Distribution<select aria-label={label("distribution")} className={selectStyle} value={distribution?.kind ?? "none"} onChange={event => setDistribution(event.target.value === "none" ? null : event.target.value === "uniform" ? { kind: "uniform", minimum: value.range.minimum, maximum: value.range.maximum, rationale: "" } : event.target.value === "triangular" ? { kind: "triangular", minimum: value.range.minimum, mode: value.nominal, maximum: value.range.maximum, rationale: "" } : { kind: "discrete", outcomes: [{ value: value.range.minimum, probability: 0.5 }, { value: value.range.maximum, probability: 0.5 }], rationale: "" })}><option value="none">Fixed nominal value</option><option value="uniform">Uniform</option><option value="triangular">Triangular</option><option value="discrete">Explicit discrete probabilities</option></select></label>
      {distribution && distribution.kind !== "discrete" && <div className="grid gap-3 sm:grid-cols-3"><ScenarioNumericField label={label("distribution minimum")} value={distribution.minimum} onChange={minimum => setDistribution({ ...distribution, minimum })} />{distribution.kind === "triangular" && <ScenarioNumericField label={label("distribution mode")} value={distribution.mode} onChange={mode => setDistribution({ ...distribution, mode })} />}<ScenarioNumericField label={label("distribution maximum")} value={distribution.maximum} onChange={maximum => setDistribution({ ...distribution, maximum })} /></div>}
      {distribution?.kind === "discrete" && <div className="space-y-3">{distribution.outcomes.map((outcome, position) => <div key={position} className="grid gap-2 sm:grid-cols-3"><ScenarioNumericField label={label(`outcome ${position + 1} value`)} value={outcome.value} onChange={next => setDistribution({ ...distribution, outcomes: distribution.outcomes.map((item, i) => i === position ? { ...item, value: next } : item) })} /><ScenarioNumericField label={label(`outcome ${position + 1} probability`)} value={outcome.probability} min={0} max={1} onChange={next => setDistribution({ ...distribution, outcomes: distribution.outcomes.map((item, i) => i === position ? { ...item, probability: next } : item) })} /><Button type="button" variant="ghost" disabled={distribution.outcomes.length <= 2} onClick={() => setDistribution({ ...distribution, outcomes: distribution.outcomes.filter((_, i) => i !== position) })}>Remove outcome</Button></div>)}<Button type="button" variant="outline" disabled={distribution.outcomes.length >= 32} onClick={() => setDistribution({ ...distribution, outcomes: [...distribution.outcomes, { value: value.nominal, probability: 0.1 }] })}>Add discrete outcome</Button><p className="text-sm text-muted-foreground">Probabilities must sum to one. They are never silently normalized or treated as measured frequencies.</p></div>}
      {distribution && <label className="block space-y-2">Distribution evidence and rationale<Textarea aria-label={label("distribution rationale")} value={distribution.rationale} onChange={event => setDistribution({ ...distribution, rationale: event.target.value })} maxLength={2000} required /></label>}
    </fieldset>}
    <Button type="button" variant="ghost" onClick={onRemove}>Remove assumption {index + 1}</Button>
  </fieldset>;
}
