import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {businessForecastDefinitionSchema,createBusinessForecastSpecSchema,type BusinessForecastDefinition,type BusinessForecastModel} from "@paperclipai/shared";
import {businessForecastingApi} from "@/api/business-forecasting";
import {businessMetricsApi} from "@/api/business-metrics";
import {aiGovernanceApi} from "@/api/ai-governance";
import {projectsApi} from "@/api/projects";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
export function BusinessForecastDefinitionForm({companyId,userId,initial,specKey,busy,onSave,onCancel,statisticalEnabled=false}:{companyId:string;userId:string|null;initial?:BusinessForecastDefinition;specKey?:string;busy:boolean;onSave:(input:{key:string;definition:BusinessForecastDefinition})=>void;onCancel:()=>void;statisticalEnabled?:boolean}) {
 const [key,setKey]=useState(specKey??""),[name,setName]=useState(initial?.name??""),[question,setQuestion]=useState(initial?.businessQuestion??""),[use,setUse]=useState(initial?.decisionUse??"");
 const [owner,setOwner]=useState(initial?.ownerUserId??userId??"local-board"),[metricId,setMetricId]=useState(initial?.metricId??""),[policyId,setPolicyId]=useState(initial?.governanceObligationRefs[0]??"");
 const [scope,setScope]=useState<BusinessForecastDefinition["scope"]>(initial?.scope??{type:"company",id:null}),[sensitivity,setSensitivity]=useState<BusinessForecastDefinition["sensitivity"]>(initial?.sensitivity??"internal");
 const [frequency,setFrequency]=useState<BusinessForecastDefinition["frequency"]>(initial?.frequency??"daily_utc"),[model,setModel]=useState<BusinessForecastModel["kind"]>(initial?.candidate.kind??"naive");
 const [season,setSeason]=useState(String(initial&&"seasonLength" in initial.candidate?initial.candidate.seasonLength:7)),[windowSize,setWindowSize]=useState(String(initial?.candidate.kind==="moving_average"?initial.candidate.window:3));
 const [horizon,setHorizon]=useState(String(initial?.horizon??1)),[minimumHistory,setMinimumHistory]=useState(String(initial?.minimumHistory??10)),[latency,setLatency]=useState(String(initial?.captureLatencySeconds??3600));
 const [training,setTraining]=useState(String(initial?.backtest.minimumTrainingPoints??3)),[origins,setOrigins]=useState(String(initial?.backtest.minimumOrigins??3)),[gap,setGap]=useState(String(initial?.backtest.gapPeriods??1));
 const [loss,setLoss]=useState(String(initial?.backtest.maximumMAE??1)),[improvement,setImprovement]=useState(String(initial?.backtest.minimumRelativeMAEImprovement??0.05)),[retention,setRetention]=useState(String(initial?.retentionDays??30));
 const [failures,setFailures]=useState(initial?.knownFailureModes.join("\n")??"");
 const account=userId??undefined,queryKey=["forecast-definition-sources",companyId,userId];
 const statistical=useQuery({queryKey:[...queryKey,"statistical-profile"],queryFn:()=>businessForecastingApi.providerProfile(companyId,account),enabled:statisticalEnabled,retry:false,refetchInterval:30000});
 const statisticalProfile=statisticalEnabled&&!statistical.isFetching&&!statistical.isError&&statistical.data?.companyId===companyId?statistical.data.profile:undefined;
 const isStatistical=model==="auto_ets"||model==="auto_arima";
 const metrics=useQuery({queryKey:[...queryKey,"metrics"],queryFn:()=>businessMetricsApi.list(companyId,undefined,account),refetchInterval:30000});
 const metric=useQuery({queryKey:[...queryKey,"metric",metricId],queryFn:()=>businessMetricsApi.detail(companyId,metricId,account),enabled:!!metricId,refetchInterval:30000});
 const policies=useQuery({queryKey:[...queryKey,"purpose"],queryFn:()=>aiGovernanceApi.obligations(companyId,account),refetchInterval:30000});
 const projects=useQuery({queryKey:[...queryKey,"projects"],queryFn:()=>projectsApi.list(companyId),enabled:scope.type==="project",refetchInterval:30000});
 const pin=metric.data?.versions.find(value=>value.id===metric.data?.metric.publishedVersionId);
 const queries=[metrics,policies,...(metricId?[metric]:[]),...(scope.type==="project"?[projects]:[])],unavailable=queries.some(query=>query.isFetching||query.isError);
 const numeric=(value:string)=>value.trim()?Number(value):NaN;
 const candidate:BusinessForecastModel=isStatistical?{kind:model,seasonLength:numeric(season)}:model==="seasonal_naive"?{kind:model,seasonLength:numeric(season)}:model==="moving_average"?{kind:model,window:numeric(windowSize)}:{kind:model};
 const parsed=businessForecastDefinitionSchema.safeParse({name,businessQuestion:question,decisionUse:use,ownerUserId:owner,metricId,metricVersionId:pin?.id,scope,sensitivity,frequency,horizon:numeric(horizon),provider:isStatistical?"statsforecast":"aw_native",...(isStatistical?{providerProfile:statisticalProfile}:{}),candidate,baselines:[{kind:"naive"},...(initial?.baselines.filter(value=>value.kind!=="naive")??[])],minimumHistory:numeric(minimumHistory),captureLatencySeconds:numeric(latency),backtest:{minimumTrainingPoints:numeric(training),minimumOrigins:numeric(origins),gapPeriods:numeric(gap),maximumMAE:numeric(loss),minimumRelativeMAEImprovement:numeric(improvement)},knownFailureModes:failures.split("\n").map(line=>line.trim()).filter(Boolean),purpose:"management_intelligence",governanceObligationRefs:[policyId,...(initial?.governanceObligationRefs.slice(1)??[])],retentionDays:numeric(retention)});
 const valid=!unavailable&&(!isStatistical||!!statisticalProfile)&&pin&&metric.data?.metric.status==="published"&&parsed.success&&createBusinessForecastSpecSchema.safeParse({key,definition:parsed.data}).success;
 return <form aria-label="Forecast definition proposal" className="min-w-0 space-y-4" onSubmit={event=>{event.preventDefault();if(valid&&parsed.success) onSave({key,definition:parsed.data});}}>
  <h2 className="font-semibold">{initial?"Propose a forecast revision":"Define a native business forecast"}</h2>
  <label className="block space-y-2">Forecast key<Input aria-label="Forecast key" value={key} onChange={event=>setKey(event.target.value)} pattern="[a-z][a-z0-9_]{1,79}" disabled={!!specKey||busy} required/></label>
  <label className="block space-y-2">Forecast name<Input aria-label="Forecast name" value={name} onChange={event=>setName(event.target.value)} maxLength={160} required/></label>
  {[{label:"Business question",value:question,set:setQuestion},{label:"Decision use",value:use,set:setUse},{label:"Known failure modes (one per line)",value:failures,set:setFailures}].map(field=><label key={field.label} className="block space-y-2">{field.label}<Textarea aria-label={field.label} value={field.value} onChange={event=>field.set(event.target.value)} required/></label>)}
  <label className="block space-y-2">Human owner<Input aria-label="Human owner" value={owner} onChange={event=>setOwner(event.target.value)} maxLength={200} required/></label>
  <label className="block space-y-2">Published native metric<select aria-label="Published native metric" className={selectStyle} value={metricId} onChange={event=>setMetricId(event.target.value)} required><option value="">Choose a current metric</option>{!unavailable&&metrics.data?.items.filter(value=>value.status==="published").map(value=><option key={value.id} value={value.id}>{value.key}</option>)}</select></label>
  {!unavailable&&pin&&<p className="text-sm">{pin.definition.name} · {pin.definition.unit}. Current published definition version {pin.revision}. Metric freshness/retention must preserve the required history.</p>}
  <label className="block space-y-2">Forecast scope<select aria-label="Forecast scope" className={selectStyle} value={scope.type} onChange={event=>setScope(event.target.value==="company"?{type:"company",id:null}:{type:"project",id:""})}><option value="company">Company</option><option value="project">Project</option></select></label>
  {scope.type==="project"&&<label className="block space-y-2">Scoped project<select aria-label="Scoped project" className={selectStyle} value={scope.id} onChange={event=>setScope({type:"project",id:event.target.value})} required><option value="">Choose a current project</option>{!unavailable&&projects.data?.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label>}
  <p className="text-sm text-muted-foreground">Scope does not change the metric's declared population. Native observations keep that exact definition and unit.</p>
  <label className="block space-y-2">Approved forecast purpose<select aria-label="Approved forecast purpose" className={selectStyle} value={policyId} onChange={event=>setPolicyId(event.target.value)} required><option value="">Choose current company policy</option>{!unavailable&&policies.data?.filter(value=>value.obligation.framework==="company_policy"&&value.obligation.analyticalPurpose?.status==="approved"&&value.obligation.analyticalPurpose.purpose==="management_intelligence"&&value.obligation.analyticalPurpose.capabilities.includes("forecast")).map(value=><option key={value.id} value={value.id}>{value.obligation.citation}</option>)}</select></label>
  <div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-2">Frequency<select aria-label="Frequency" className={selectStyle} value={frequency} onChange={event=>setFrequency(event.target.value as typeof frequency)}><option value="daily_utc">Daily UTC</option><option value="weekly_utc">Weekly UTC</option></select></label><label className="block space-y-2">Sensitivity<select aria-label="Sensitivity" className={selectStyle} value={sensitivity} onChange={event=>setSensitivity(event.target.value as typeof sensitivity)}><option value="internal">Internal</option><option value="confidential">Confidential</option></select></label></div>
  <label className="block space-y-2">Native candidate model<select aria-label="Native candidate model" className={selectStyle} value={model} onChange={event=>setModel(event.target.value as typeof model)}><option value="naive">Last value</option><option value="seasonal_naive">Explicit seasonal naive</option><option value="moving_average">Moving average</option><option value="drift">Simple drift</option>{statisticalProfile&&<><option value="auto_ets">Statistical AutoETS</option><option value="auto_arima">Statistical AutoARIMA</option></>}{isStatistical&&!statisticalProfile&&<option value={model}>Statistical model requires current verification</option>}</select></label>
  {(model==="seasonal_naive"||isStatistical)&&<label className="block space-y-2">Declared seasonal periods<Input aria-label="Declared seasonal periods" type="number" min={isStatistical?1:2} max={365} value={season} onChange={event=>setSeason(event.target.value)} required/></label>}
  {model==="moving_average"&&<label className="block space-y-2">Moving average periods<Input aria-label="Moving average periods" type="number" min={2} max={60} value={windowSize} onChange={event=>setWindowSize(event.target.value)} required/></label>}
  <p className="text-sm text-muted-foreground">Every candidate is compared with last value using retained rolling-origin folds. A more complex model must improve on that baseline. {isStatistical?"Statistical intervals are model outputs; their empirical coverage on company history is not established.":"Prediction intervals are unavailable for these native point baselines."}</p>
  {isStatistical&&!statisticalProfile&&<p role="status">The exact statistical runtime is unavailable or being rechecked. Reinspect its profile before saving this model.</p>}
  <div className="grid gap-4 sm:grid-cols-2">{[{label:"Forecast horizon (periods)",value:horizon,set:setHorizon,min:1,max:60},{label:"Minimum history (periods)",value:minimumHistory,set:setMinimumHistory,min:4,max:1000},{label:"Capture latency (seconds)",value:latency,set:setLatency,min:0,max:86400},{label:"Earliest training points",value:training,set:setTraining,min:2,max:900},{label:"Minimum rolling origins",value:origins,set:setOrigins,min:3,max:100},{label:"Gap before each test (periods)",value:gap,set:setGap,min:1,max:7},{label:"Maximum MAE in metric units",value:loss,set:setLoss,min:0,max:undefined,step:"any"},{label:"Minimum improvement over last value",value:improvement,set:setImprovement,min:0,max:1,step:"any"},{label:"Retention (days)",value:retention,set:setRetention,min:1,max:3650}].map(field=><label key={field.label} className="space-y-2">{field.label}<Input aria-label={field.label} type="number" value={field.value} onChange={event=>field.set(event.target.value)} min={field.min} max={field.max} step={field.step??1} required/></label>)}</div>
  {!parsed.success&&<p className="text-sm text-muted-foreground">Complete the required fields and ensure history can support training, gap, horizon and all rolling origins.</p>}
  {queries.some(query=>query.isFetching)&&<p role="status">Rechecking native metric and purpose authority…</p>}{queries.some(query=>query.isError)&&<p role="alert">Current forecast source authority could not be verified. Refresh before saving.</p>}
  <div className="flex flex-wrap justify-between gap-2"><Button type="button" variant="outline" disabled={busy} onClick={onCancel}>Cancel</Button><Button type="submit" disabled={busy||!valid}>{busy?"Saving…":"Save forecast proposal"}</Button></div>
 </form>;
}
