import { useEffect, useState } from "react";
import type { BusinessScenarioRunView, BusinessScenarioUnit } from "@paperclipai/shared";
import { Badge } from "@/components/ui/badge";
import { formatNumber } from "@/lib/utils";
export function scenarioUnitLabel(unit: BusinessScenarioUnit): string {
  const names: Record<string, string> = { issue: "issues", project: "projects", person: "people", customer: "customers", second: "seconds" };
  const entries = Object.entries(unit).filter(([, power]) => power !== 0);
  if (!entries.length) return "dimensionless";
  const label = (dimension: string, power: number) => `${names[dimension] ?? dimension.replace("currency_", "")}${Math.abs(power) === 1 ? "" : `^${Math.abs(power)}`}`;
  const numerator = entries.filter(([, power]) => power > 0).map(([dimension, power]) => label(dimension, power)).join(" × ") || "1";
  const denominator = entries.filter(([, power]) => power < 0).map(([dimension, power]) => label(dimension, power)).join(" × ");
  return denominator ? `${numerator} / (${denominator})` : numerator;
}
export function BusinessScenarioResult({ artifact }: { artifact: BusinessScenarioRunView }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  if (Date.parse(artifact.expiresAt) <= Math.max(now, Date.now())) return <p role="status">This scenario evidence has expired. Review current source pins before using it.</p>;
  const result = artifact.result;
  return <section aria-label="Conditional scenario result" className="min-w-0 space-y-4">
    <div className="flex flex-wrap gap-2"><h3 className="font-semibold">Conditional scenario comparison</h3><Badge variant="outline">{artifact.currentQualification.replaceAll("_", " ")}</Badge><Badge variant="outline">{result.status.replaceAll("_", " ")}</Badge></div>
    <p>These outputs describe what the declared model implies if its assumptions hold. A separate human Decision must adopt any organizational commitment.</p>
    {artifact.currentQualification === "needs_revalidation" && <p role="status">Retained arithmetic is historical. Its source definition, measurements or publication changed; review a new version before reuse.</p>}
    {result.reasons.map(reason => <p key={reason} role="status">{reason.replaceAll("_", " ")}</p>)}
    <p className="text-sm text-muted-foreground">{result.uncertainty.method === "deterministic" ? "Nominal calculation only. Declared ranges have not been propagated; uncertainty intervals are unavailable." : `Conditional assumption simulation · ${result.uncertainty.qualification.replaceAll("_", " ")}. Sample quantiles are not calibrated prediction or confidence intervals.`}</p>
    {result.cases.map(scenarioCase => <div key={scenarioCase.key} className="min-w-0 space-y-3 rounded-md border p-3">
      <h4 className="font-medium">{scenarioCase.name} · {scenarioCase.kind}</h4>
      {scenarioCase.changes.length ? <ul className="list-disc space-y-1 pl-5 text-sm">{scenarioCase.changes.map(change => <li key={change.assumptionKey}>{change.assumptionKey}: {formatNumber(change.value)} · {change.kind.replaceAll("_", " ")}. {change.rationale}</li>)}</ul> : <p className="text-sm">Unchanged declared base assumptions.</p>}
      <div role="region" aria-label={`Nominal outputs and declared constraints · ${scenarioCase.name}`} tabIndex={0} className="overflow-x-auto rounded-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><table className="w-full text-sm"><caption className="text-left font-medium">Nominal outputs and declared constraints · {scenarioCase.name}</caption><thead><tr className="text-left">{["Output", "Unit", "Nominal", "Change from base", "Constraint"].map(label => <th key={label} scope="col" className="p-2">{label}</th>)}</tr></thead><tbody>{scenarioCase.outputs.map(output => <tr key={output.key}><th scope="row" className="p-2 text-left font-normal">{output.key}</th><td className="p-2">{scenarioUnitLabel(output.unit)}</td><td className="p-2 font-mono">{formatNumber(output.nominal)}</td><td className="p-2 font-mono">{formatNumber(output.differenceFromBase)}</td><td className="p-2">{output.constraint.replaceAll("_", " ")}</td></tr>)}</tbody></table></div>
      {scenarioCase.outputs.some(output => output.simulation) && <div role="region" aria-label={`Conditional empirical quantiles · ${scenarioCase.name}`} tabIndex={0} className="overflow-x-auto rounded-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><table className="w-full text-sm"><caption className="text-left font-medium">Conditional empirical quantiles · {scenarioCase.name}</caption><thead><tr className="text-left">{["Output", "P10", "Median", "P90", "Constraint violations", "Samples"].map(label => <th key={label} scope="col" className="p-2">{label}</th>)}</tr></thead><tbody>{scenarioCase.outputs.filter(output => output.simulation).map(output => <tr key={output.key}><th scope="row" className="p-2 text-left font-normal">{output.key} · {scenarioUnitLabel(output.unit)}</th><td className="p-2 font-mono">{formatNumber(output.simulation!.p10)}</td><td className="p-2 font-mono">{formatNumber(output.simulation!.median)}</td><td className="p-2 font-mono">{formatNumber(output.simulation!.p90)}</td><td className="p-2">{output.simulation!.constraintViolations === null ? "Not declared" : formatNumber(output.simulation!.constraintViolations!)}</td><td className="p-2 font-mono">{formatNumber(output.simulation!.samples)}</td></tr>)}</tbody></table></div>}
    </div>)}
    {result.uncertainty.unstableOutputs.length > 0 && <section aria-label="Simulation stability diagnostics" className="space-y-2"><h4 className="font-medium">Sample ranges withheld</h4><p>The reported quantiles did not stabilize within the human-declared tolerance. Nominal arithmetic remains conditional.</p>{result.uncertainty.unstableOutputs.map(item => <p key={`${item.caseKey}:${item.outputKey}`} className="text-sm">{item.caseKey} · {item.outputKey}: half-sample difference {formatNumber(item.maximumDifference)} exceeded tolerance {formatNumber(item.tolerance)}.</p>)}</section>}
    {result.calculationArtifact && <p className="break-all text-sm">Validated calculation artifact {result.calculationArtifact.artifactId} · version {result.calculationArtifact.versionId} · content {result.calculationArtifact.contentHash}. Artifact units are a declared schema contract; business calibration has not been inferred.</p>}
    <ul className="list-disc space-y-1 pl-5 text-sm text-muted-foreground">{result.limitations.map((text, index) => <li key={index}>{text}</li>)}</ul>
    <details><summary className="cursor-pointer">Inspect scenario provenance and reproducibility</summary><div className="space-y-2 pt-3 text-sm"><p>Recorded {new Date(artifact.createdAt).toLocaleString()} · retained until {new Date(artifact.expiresAt).toLocaleString()}</p><p>{result.engineVersion} · seed {result.seed === null ? "Not used" : result.seed} · {result.uncertainty.seedAlgorithm ?? "Deterministic arithmetic"}</p><p className="break-all">Definition {artifact.versionId} · {result.definitionHash}</p><p className="break-all">Input {result.inputHash} · result {artifact.contentHash}</p>{result.cases.flatMap(item => item.outputs.filter(output => output.simulation).map(output => <p key={`${item.key}:${output.key}`}>{item.name} · {output.key}: sampled support {formatNumber(output.simulation!.minimum)} to {formatNumber(output.simulation!.maximum)}; half-sample difference {formatNumber(output.simulation!.halfSampleMaximumDifference)} ≤ declared tolerance {formatNumber(output.simulation!.stabilityAbsoluteTolerance)}.</p>))}</div></details>
  </section>;
}
