import {useState,useEffect,useCallback} from "react";
import {useQuery} from "@tanstack/react-query";
import {causalClaimDefinitionSchema,createCausalClaimSchema,type CausalClaimDefinition,type CausalExperimentReference,type BusinessExperimentDefinition} from "@paperclipai/shared";
import {aiGovernanceApi} from "@/api/ai-governance";
import {projectsApi} from "@/api/projects";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Textarea} from "./ui/textarea";
import {BusinessExperimentMetricPicker} from "./BusinessExperimentMetricPicker";
import {CausalExperimentPicker} from "./CausalExperimentPicker";
import {CausalGraphEditor} from "./CausalGraphEditor";
import {emptyCausalClaimDefinition} from "./causal-claim-draft";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
type Definition=CausalClaimDefinition;
function Prose({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block space-y-2">{label}<Textarea aria-label={label} value={value} minLength={10} maxLength={2000} required onChange={e=>onChange(e.target.value)}/></label>;}
type Fields={draft:Definition;update:<K extends keyof Definition>(key:K,value:Definition[K])=>void};
function CausalPopulationFields({draft,update,projects,companyId}:Fields&{projects?:Awaited<ReturnType<typeof projectsApi.list>>;companyId:string}){
 const p=draft.population,pinned=!!draft.experimentEvidence;
 return <section aria-label="Causal population" className="space-y-3"><h3 className="font-medium">Population and external validity</h3><label className="block space-y-2">Population unit<select aria-label="Population unit" className={selectStyle} value={p.unit} disabled={pinned} onChange={e=>update("population",{...p,unit:e.target.value as "issue"|"project",scope:{type:"company",id:null}})}><option value="issue">Native issue</option><option value="project">Native project</option></select></label><label className="block space-y-2">Population scope<select aria-label="Population scope" className={selectStyle} value={p.scope.type} disabled={pinned} onChange={e=>update("population",{...p,scope:e.target.value==="project"?{type:"project",id:""}:{type:"company",id:null}})}><option value="company">Company</option>{p.unit==="issue"&&<option value="project">Project</option>}</select></label>
 {p.scope.type==="project"&&<label className="block space-y-2">Population project<select aria-label="Population project" className={selectStyle} value={p.scope.id} disabled={pinned} required onChange={e=>update("population",{...p,scope:{type:"project",id:e.target.value}})}><option value="">Choose current project</option>{projects?.filter(x=>x.companyId===companyId&&!x.archivedAt).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 <Prose label="Eligible population and exclusions" value={p.eligibilityStatement} onChange={v=>update("population",{...p,eligibilityStatement:v})}/><Prose label="Limits on applying results elsewhere" value={p.externalValidityLimits} onChange={v=>update("population",{...p,externalValidityLimits:v})}/></section>;
}
function CausalTimingFields({draft,update}:Fields){
 const pinned=!!draft.experimentEvidence,utc=(v:string)=>v&&Number.isFinite(Date.parse(`${v}Z`))?new Date(`${v}Z`).toISOString():"";
 return <section aria-label="Causal estimand and identification" className="space-y-3"><h3 className="font-medium">Estimand and identification</h3><p>Assignment intention-to-treat effect on a native binary outcome. A pinned result retains its original period, primary endpoint and meaningful-effect threshold.</p>
 {(["from","until"] as const).map((k,i)=><label key={k} className="block space-y-2">{i===0?"Horizon start (UTC)":"Horizon end (UTC)"}<Input aria-label={i===0?"Horizon start (UTC)":"Horizon end (UTC)"} type="datetime-local" step="0.001" value={draft.horizon[k].replace(/Z$/,"")} disabled={pinned} required onChange={e=>update("horizon",{...draft.horizon,[k]:utc(e.target.value)})}/></label>)}
 <label className="block space-y-2">Beneficial direction<select aria-label="Beneficial direction" className={selectStyle} value={draft.estimand.beneficialDirection} disabled={pinned} onChange={e=>update("estimand",{...draft.estimand,beneficialDirection:e.target.value as "increase"|"decrease"})}><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label>
 <label className="block space-y-2">Meaningful primary difference (fraction, 0–1)<Input aria-label="Meaningful primary difference (fraction, 0–1)" type="number" min={0} max={1} step="any" required disabled={pinned} value={draft.estimand.minimumMeaningfulEffect} onChange={e=>update("estimand",{...draft.estimand,minimumMeaningfulEffect:e.target.value?Number(e.target.value):NaN})}/></label>
 <label className="block space-y-2">Identification strategy<select aria-label="Identification strategy" className={selectStyle} value={draft.identificationStrategy} onChange={e=>update("identificationStrategy",e.target.value as Definition["identificationStrategy"])}>{(["registered_randomized_assignment","backdoor_adjustment","instrumental_variables","regression_discontinuity","difference_in_differences","association_only"] as const).map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</select></label><p>The native interpreter admits only the exact registered randomized primary analysis. Other strategies record a question and abstain until an independently qualified method is available.</p></section>;
}
export function CausalClaimDefinitionForm({companyId,userId,initial,claimKey,busy,onSave,onCancel,onAuthorityLost=onCancel}:{companyId:string;userId:string|null;initial?:Definition;claimKey?:string;busy:boolean;onSave:(input:{key:string;definition:Definition;rationale:string})=>void;onCancel:()=>void;onAuthorityLost?:()=>void}){
 const [draft,setDraft]=useState(()=>initial?structuredClone(initial):emptyCausalClaimDefinition(userId??"local-board")),[key,setKey]=useState(claimKey??""),[rationale,setRationale]=useState(""),[metricValid,setMetricValid]=useState(false),[experimentValid,setExperimentValid]=useState(false);
 const account=userId??undefined,sourceKey=["causal-definition-sources",companyId,userId];
 const policies=useQuery({queryKey:[...sourceKey,"purpose"],queryFn:()=>aiGovernanceApi.obligations(companyId,account),refetchInterval:30000,retry:false});
 const projects=useQuery({queryKey:[...sourceKey,"projects"],queryFn:()=>projectsApi.list(companyId),enabled:draft.population.scope.type==="project",refetchInterval:30000,retry:false});
 useEffect(()=>{if(policies.isError||projects.isError)onAuthorityLost();},[policies.isError,projects.isError,onAuthorityLost]);
 const unavailable=policies.isFetching||policies.isPending||policies.isError||draft.population.scope.type==="project"&&(projects.isFetching||projects.isPending||projects.isError);
 const approved=!unavailable?policies.data?.filter(p=>p.companyId===companyId&&p.obligation.framework==="company_policy"&&p.obligation.analyticalPurpose?.status==="approved"&&p.obligation.analyticalPurpose.purpose==="management_intelligence"&&p.obligation.analyticalPurpose.capabilities.includes("causal"))??[]:[];
 const valid=!unavailable&&metricValid&&experimentValid&&createCausalClaimSchema.safeParse({key,definition:draft}).success&&draft.governanceObligationRefs.every(id=>approved.some(p=>p.id===id))&&(!initial||rationale.trim().length>=10&&rationale.trim().length<=2000);
 const update=<K extends keyof Definition>(k:K,v:Definition[K])=>setDraft(old=>({...old,[k]:v}));
 const source=useCallback((ref:CausalExperimentReference|null,d?:BusinessExperimentDefinition)=>setDraft(old=>d?{...old,experimentEvidence:ref,outcomeMetricId:d.primaryMetric.metricId,outcomeMetricVersionId:d.primaryMetric.metricVersionId,population:{scope:d.scope,unit:d.population.randomizationUnit,eligibilityStatement:d.population.eligibility,externalValidityLimits:d.population.externalValidityLimits},horizon:{from:d.sampleOrDurationPlan.from,until:d.sampleOrDurationPlan.until},estimand:{...old.estimand,beneficialDirection:d.primaryMetric.beneficialDirection,minimumMeaningfulEffect:d.primaryMetric.minimumMeaningfulEffect},sensitivity:old.sensitivity==="confidential"||d.sensitivity==="confidential"?"confidential":"internal"}:{...old,experimentEvidence:ref}),[]);
 return <form aria-label="Human causal model proposal" className="min-w-0 space-y-6" onSubmit={e=>{e.preventDefault();const parsed=causalClaimDefinitionSchema.safeParse(draft);if(valid&&parsed.success)onSave({key,definition:parsed.data,rationale});}}><fieldset disabled={busy} className="min-w-0 space-y-6"><legend className="text-lg font-semibold">{initial?"Revise human causal model":"Record a human causal question"}</legend>
 <p>Record the question, assumed graph and identification conditions before separate human review. Unknown assumptions stay unknown until you explicitly assess them.</p>
 <label className="block space-y-2">Claim key<Input aria-label="Claim key" value={key} disabled={!!initial} minLength={2} maxLength={64} required onChange={e=>setKey(e.target.value)}/></label>
 <label className="block space-y-2">Claim name<Input aria-label="Claim name" value={draft.name} minLength={3} maxLength={160} required onChange={e=>update("name",e.target.value)}/></label>
 <Prose label="Causal question" value={draft.question} onChange={v=>update("question",v)}/><Prose label="Human hypothesis" value={draft.humanHypothesis} onChange={v=>update("humanHypothesis",v)}/>
 <label className="block space-y-2">Responsible owner<Input aria-label="Responsible owner" value={draft.ownerUserId} required maxLength={200} onChange={e=>update("ownerUserId",e.target.value)}/></label>
 <CausalExperimentPicker companyId={companyId} userId={userId} value={draft.experimentEvidence} onChange={source} onValidity={setExperimentValid} onAuthorityLost={onAuthorityLost}/>
 <CausalPopulationFields draft={draft} update={update} projects={!unavailable?projects.data:undefined} companyId={companyId}/>
 <BusinessExperimentMetricPicker companyId={companyId} userId={userId} label="Causal outcome measure" value={{metricId:draft.outcomeMetricId,metricVersionId:draft.outcomeMetricVersionId}} population={draft.population.unit} scope={draft.population.scope} disabled={!!draft.experimentEvidence} onChange={pin=>setDraft(old=>({...old,outcomeMetricId:pin.metricId,outcomeMetricVersionId:pin.metricVersionId}))} onValidity={setMetricValid} onAuthorityLost={onAuthorityLost}/>
 <CausalTimingFields draft={draft} update={update}/>
 <CausalGraphEditor value={draft.graph} onChange={v=>update("graph",v)}/>
 <section aria-label="Explicit human assumptions" className="space-y-4"><h3 className="font-medium">Explicit human assumptions</h3>{(["noInterference","stableOutcomeMeasurement","registeredPopulationValidity"] as const).map((k,i)=><div key={k} className="space-y-3"><label className="block space-y-2">{["Interference between units","Stable outcome measurement","Registered population validity"][i]}<select aria-label={["Interference between units","Stable outcome measurement","Registered population validity"][i]} className={selectStyle} value={draft.assumptions[k].status} onChange={e=>update("assumptions",{...draft.assumptions,[k]:{...draft.assumptions[k],status:e.target.value as "assumed"|"unknown"|"violated"}})}><option value="unknown">Unknown</option><option value="assumed">Explicitly assumed by human</option><option value="violated">Violated</option></select></label><Prose label={`Assumption ${i+1} rationale`} value={draft.assumptions[k].rationale} onChange={v=>update("assumptions",{...draft.assumptions,[k]:{...draft.assumptions[k],rationale:v}})}/></div>)}</section>
 <label className="block space-y-2">Approved causal purpose<select aria-label="Approved causal purpose" className={selectStyle} value={draft.governanceObligationRefs[0]??""} required onChange={e=>update("governanceObligationRefs",[e.target.value,...draft.governanceObligationRefs.slice(1)])}><option value="">Choose current company policy</option>{approved.map(p=><option key={p.id} value={p.id}>{p.obligation.citation}</option>)}</select></label>
 <label className="block space-y-2">Sensitivity<select aria-label="Sensitivity" className={selectStyle} value={draft.sensitivity} onChange={e=>update("sensitivity",e.target.value as "internal"|"confidential")}><option value="internal">Internal</option><option value="confidential">Confidential</option></select></label>
 <label className="block space-y-2">Retention (days)<Input aria-label="Retention (days)" type="number" min={1} max={3650} required value={draft.retentionDays} onChange={e=>update("retentionDays",e.target.value?Number(e.target.value):NaN)}/></label>
 {initial&&<Prose label="Model revision rationale" value={rationale} onChange={setRationale}/>}</fieldset>
 {unavailable&&<p role="status">Rechecking causal purpose and population authority…</p>}{!valid&&<p>Complete the human model and every rationale, with an exact current metric and approved causal purpose. A selected experiment must be explicitly pinned.</p>}
 <div className="flex flex-wrap gap-2"><Button type="submit" disabled={!valid||busy}>Save human causal model</Button><Button type="button" variant="ghost" disabled={busy} onClick={onCancel}>Cancel model proposal</Button></div></form>;
}
