import type {CausalAnalysisRunView} from "@paperclipai/shared";
import {Card,CardHeader,CardContent} from "./ui/card";
import {formatNumber} from "@/lib/utils";
const words=(v:string)=>v.replaceAll("_"," ");
const points=(v:number)=>`${formatNumber(v*100)} percentage points`;
const reasonLabel:Record<string,string>={identification_unsupported_without_qualified_design_and_data:"The declared method has no qualified design and source data for this question.",human_graph_does_not_admit_randomized_assignment_identification:"The human graph does not admit randomized assignment identification.",exact_experiment_analysis_interpretation_pin_mismatch:"The exact registered analysis and human interpretation do not match this model.",claim_does_not_match_exact_registered_primary_estimand_population_and_horizon:"The question differs from the registered primary estimand, population or horizon.",human_assumptions_unknown_or_violated:"One or more human assumptions remain unknown or are violated.",registered_source_quality_or_current_authority_does_not_admit_estimation:"Source quality or current authority does not admit estimation.",registered_meaningful_primary_and_safety_bounds_conditionally_supported:"The registered meaningful benefit and every safety bound have conditional support.",registered_minimum_meaningful_primary_benefit_not_supported_within_bounds:"The registered minimum meaningful benefit is not supported within these bounds; this does not prove zero effect.",optional_provider_refutations_do_not_admit_causal_reliance:"The fixed DoWhy diagnostics failed or remain unknown; conditional causal reliance is withheld.",registered_primary_or_safety_bounds_do_not_support_a_positive_claim:"The registered primary or safety bounds remain insufficient for a positive claim."};
export function CausalClaimResult({run}:{run:CausalAnalysisRunView}){
 const r=run.result;
 return <section aria-label="Conditional causal result" className="min-w-0 space-y-4"><Card><CardHeader><h2 className="font-semibold">{r.status==="supported"?"Conditional support for the registered benefit":r.status==="refuted"?"Registered benefit is not supported within these bounds":"Causal evidence remains inconclusive"}</h2><p>Evidence design: {words(r.evidenceGrade)}</p></CardHeader><CardContent className="space-y-3">
 {run.currentQualification!=="current"&&<p role="status">Current source qualification changed. This retained result requires explicit source revalidation before new reliance.</p>}
 <p>Identification: {words(r.identification.status)} · {words(r.identification.strategy)}.</p><ul className="list-disc space-y-2 pl-5">{r.identification.conditions.map((c,i)=><li key={i}>{c}</li>)}</ul>
 {r.estimate?<><p>Registered treatment minus control: <strong>{points(r.estimate.effect)}</strong>.</p><p>Conservative registered interval: {points(r.estimate.interval.lower)} to {points(r.estimate.interval.upper)} · family coverage at least {formatNumber(r.estimate.interval.familywiseCoverage*100)}%.</p><p>Original assignment intention-to-treat analysis on a native process proxy. The registered primary endpoint and interval are retained.</p></>:<p>No causal estimate is admitted. Keep this question open until the exact source and identification conditions are met.</p>}
 <p>{r.language==="conditional_assignment_effect_on_native_proxy"?"Interpretation remains conditional on randomization, complete source receipts and human assumptions.":"Causal reliance is withheld."} Execution requires separate native human authority.</p>
 </CardContent></Card><Card><CardHeader><h3 className="font-medium">Robustness and limits</h3></CardHeader><CardContent className="space-y-3"><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(r.robustness).map(([key,value])=><div key={key}><dt>{({assignmentRatio:"Assignment ratio",registeredBaselineBalance:"Registered baseline balance",completeOutcomeAndExposureReceipts:"Outcome and exposure receipts",guardrails:"Safety bounds",assumptions:"Human assumptions",sensitivity:"Sensitivity",providerRefutations:"Independent provider refutations"} as Record<string,string>)[key]}</dt><dd>{words(value)}</dd></div>)}</dl>{r.providerAnalysis&&<section aria-label="DoWhy diagnostic results" className="space-y-3"><h4 className="font-medium">DoWhy robustness diagnostics</h4><p>Anonymous binary counts · 16 simulations per method. Diagnostic p-values supplement the registered interval; sensitivity and external validity remain unknown.</p><dl className="space-y-3">{r.providerAnalysis.diagnostics.refutations.map(item=><div key={item.method}><dt>{words(item.method)} · {item.status}</dt><dd>Diagnostic effect: {points(item.effect)} · p-value: {item.pValue===null?"unknown":formatNumber(item.pValue)}.</dd></div>)}</dl></section>}<ul className="list-disc space-y-2 pl-5">{[...r.reasons,...r.limitations].map((v,i)=><li key={i}>{reasonLabel[v]??v}</li>)}</ul><p>No verified business impact or task outcome follows from this native proxy.</p></CardContent></Card><details><summary className="cursor-pointer">Inspect analysis traceability</summary><div className="space-y-2 pt-3 text-sm"><p>Completed {new Date(run.completedAt).toLocaleString()} · {run.providerKey==="dowhy"?"fixed DoWhy binary-assignment diagnostics":"one fixed registered-primary interpretation"}.</p><p className="break-all">Definition {r.definitionHash}</p><p className="break-all">Receipt {run.receiptHash}</p>{r.providerAnalysis&&<p className="break-all">Method profile {r.providerAnalysis.profile.conformanceHash} · runtime bundle {r.providerAnalysis.profile.bundleHash}</p>}</div></details></section>;
}
