import type {CausalClaimDefinition} from "@paperclipai/shared";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Textarea} from "./ui/textarea";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
type Graph=CausalClaimDefinition["graph"];
export function CausalGraphEditor({value,onChange}:{value:Graph;onChange:(graph:Graph)=>void}){
 const node=(index:number,patch:Partial<Graph["nodes"][number]>)=>onChange({...value,nodes:value.nodes.map((n,i)=>i===index?{...n,...patch}:n)});
 const edge=(index:number,patch:Partial<Graph["edges"][number]>)=>onChange({...value,edges:value.edges.map((e,i)=>i===index?{...e,...patch}:e)});
 return <section aria-label="Human causal graph" className="min-w-0 space-y-4"><h3 className="font-medium">Human causal graph</h3><p>Every arrow is a human assumption with an explicit rationale. Declare relevant pretreatment context and unobserved factors. A cycle or undeclared endpoint blocks saving.</p>
 <div className="grid gap-4 sm:grid-cols-2">{value.nodes.map((n,i)=><fieldset key={n.key} className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend className="px-1">Node {i+1} · {n.key.replaceAll("_"," ")}</legend><label className="block space-y-2">Node {i+1} label<Input aria-label={`Node ${i+1} label`} value={n.label} minLength={3} maxLength={120} required onChange={e=>node(i,{label:e.target.value})}/></label><p>Role: {n.role.replaceAll("_"," ")}</p>{!["randomized_assignment","outcome"].includes(n.role)&&<><label className="block space-y-2">Node {i+1} role<select aria-label={`Node ${i+1} role`} className={selectStyle} value={n.role} onChange={e=>node(i,{role:e.target.value as typeof n.role})}><option value="pretreatment">Pretreatment variable</option><option value="unobserved">Unobserved factor</option><option value="context">Context</option></select></label><Button type="button" variant="ghost" onClick={()=>onChange({nodes:value.nodes.filter(x=>x.key!==n.key),edges:value.edges.filter(x=>x.from!==n.key&&x.to!==n.key)})}>Remove node {i+1} and its arrows</Button></>}</fieldset>)}</div>
 {value.nodes.length<16&&<Button type="button" variant="outline" onClick={()=>{let i=1;while(value.nodes.some(n=>n.key===`context_${i}`))i++;onChange({...value,nodes:[...value.nodes,{key:`context_${i}`,label:"Context requiring review",role:"context"}]});}}>Add context or unobserved node</Button>}
 {value.edges.map((e,i)=><fieldset key={i} className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend className="px-1">Assumed arrow {i+1}</legend><div className="grid gap-3 sm:grid-cols-2">{(["from","to"] as const).map((k,j)=><label key={k} className="block space-y-2">Arrow {i+1} {j===0?"from":"to"}<select aria-label={`Arrow ${i+1} ${k}`} className={selectStyle} value={e[k]} onChange={event=>edge(i,{[k]:event.target.value})}>{value.nodes.map(n=><option key={n.key} value={n.key}>{n.label}</option>)}</select></label>)}</div><label className="block space-y-2">Arrow {i+1} human rationale<Textarea aria-label={`Arrow ${i+1} human rationale`} value={e.rationale} minLength={10} maxLength={2000} required onChange={event=>edge(i,{rationale:event.target.value})}/></label>{value.edges.length>1&&<Button type="button" variant="ghost" onClick={()=>onChange({...value,edges:value.edges.filter((_,j)=>j!==i)})}>Remove arrow {i+1}</Button>}</fieldset>)}
 {value.edges.length<32&&<Button type="button" variant="outline" onClick={()=>onChange({...value,edges:[...value.edges,{from:value.nodes[0].key,to:value.nodes[1].key,authority:"human_assumption",rationale:""}]})}>Add assumed arrow</Button>}
 </section>;
}
