import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {finishDecisionOutcomeReviewSchema,type DecisionContextVersionView,type DecisionEvidenceReference,type DecisionReviewAssessments,type FinishDecisionOutcomeReview} from "@paperclipai/shared";
import {businessMetricsApi} from "@/api/business-metrics";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
const labels={decisionProcessQuality:"Decision process quality",assumptionAccuracy:"Assumption accuracy",executionFidelity:"Execution fidelity",externalChange:"External change",observedOutcome:"Observed outcome"};
type JudgmentKey=keyof typeof labels;
type MetricRef=Extract<DecisionEvidenceReference,{type:"metric_observation"}>;
function ObservationPicker({companyId,userId,baseline,horizon,chosenAt,value,onChange}:{companyId:string;userId:string|null;baseline:MetricRef;horizon:{from:string;until:string};chosenAt:string;value:MetricRef|null;onChange:(value:MetricRef|null)=>void}) {
  const observations=useQuery({queryKey:["decision-review-observations",companyId,userId,baseline.metricId],queryFn:()=>businessMetricsApi.observations(companyId,baseline.metricId,undefined,userId??undefined),refetchInterval:30000,retry:false});
  const rows=!observations.isFetching&&!observations.isError?observations.data?.items.filter(row=>row.companyId===companyId&&row.versionId===baseline.metricVersionId&&row.from===horizon.from&&row.until===horizon.until&&Date.parse(row.asOf)>=Math.max(Date.parse(chosenAt),Date.parse(horizon.until))&&Date.parse(row.expiresAt)>Date.now()):[];
  return <div className="min-w-0 space-y-2"><label className="block space-y-2">Actual horizon observation<select aria-label="Actual horizon observation" className={selectStyle} value={value?.id??""} onChange={event=>{const row=rows?.find(row=>row.id===event.target.value);onChange(row?{type:"metric_observation",id:row.id,metricId:row.metricId,metricVersionId:row.versionId}:null);}}><option value="">No comparable observation selected</option>{value&&!rows?.some(row=>row.id===value.id)&&<option value={value.id}>Previously selected observation · current verification required</option>}{rows?.map(row=><option key={row.id} value={row.id}>{new Date(row.asOf).toLocaleString()} · {row.status} · {row.value??"unknown"}</option>)}</select></label>
    {observations.isFetching&&<p role="status">Rechecking current outcome observations…</p>}{observations.isError&&<p role="alert">{observations.error.message}</p>}
    <p className="text-sm text-muted-foreground">Bounded observations of the same metric version and exact elapsed horizon. An empty page does not prove that no evidence exists. Keep the review inconclusive when no comparable observation is available.</p>
    {value&&<Button type="button" variant="ghost" onClick={()=>onChange(null)}>Clear actual observation</Button>}
  </div>;
}
export function DecisionOutcomeReviewForm({companyId,userId,version,optionId,chosenAt,revision,busy,onSave,onCancel}:{companyId:string;userId:string|null;version:DecisionContextVersionView;optionId:string;chosenAt:string;revision:number;busy:boolean;onSave:(input:FinishDecisionOutcomeReview)=>void;onCancel:()=>void}) {
  const unknown=()=>({kind:"human_judgment" as const,assessment:"unknown" as const,explanation:"",evidenceKeys:[] as string[]});
  const [assessments,setAssessments]=useState<DecisionReviewAssessments>({decisionProcessQuality:unknown(),assumptionAccuracy:unknown(),executionFidelity:unknown(),externalChange:unknown(),observedOutcome:unknown(),causalConfidence:{assessment:"not_assessed",explanation:""}});
  const [result,setResult]=useState<FinishDecisionOutcomeReview["result"]>("inconclusive"),[lesson,setLesson]=useState("");
  const [assumptions,setAssumptions]=useState<FinishDecisionOutcomeReview["assumptionOutcomes"]>(version.definition.assumptions.map(item=>({key:item.key,kind:"human_judgment",assessment:"inconclusive",explanation:"",evidenceKeys:[]})));
  const expectations=version.definition.expectedOutcomes.map((item,index)=>({item,index})).filter(({item})=>item.optionId===optionId);
  const [qualitative,setQualitative]=useState<FinishDecisionOutcomeReview["qualitativeOutcomes"]>(expectations.filter(({item})=>item.kind==="qualitative").map(({index})=>({expectationIndex:index,kind:"human_judgment",assessment:"inconclusive",explanation:"",evidenceKeys:[]})));
  const [actual,setActual]=useState<Record<number,MetricRef|null>>({});
  const metrics=Object.entries(actual).flatMap(([index,source])=>source?[{key:`outcome_${Number(index)+1}`,source}]:[]);
  const metricOutcomes=Object.entries(actual).flatMap(([index,source])=>source?[{expectationIndex:Number(index),actualEvidenceKey:`outcome_${Number(index)+1}`}]:[]);
  const citationOptions=[{key:"native_execution",label:"Native effect execution status"},...version.evidence.map(item=>({key:`baseline:${item.key}`,label:`Frozen baseline · ${item.key}`})),...metrics.map(item=>({key:`actual:${item.key}`,label:`Actual observation · ${item.key}`}))];
  const citation=(value:string[],onChange:(value:string[])=>void,label:string)=><label className="block space-y-2">{label}<select aria-label={label} className={selectStyle} value={value[0]??""} onChange={event=>onChange(event.target.value?[event.target.value]:[])}><option value="">Human judgment without a quantitative evidence citation</option>{citationOptions.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label>;
  const input=finishDecisionOutcomeReviewSchema.safeParse({expectedRevision:revision,result,lessonSummary:lesson,assessments,actualMetrics:metrics,metricOutcomes,qualitativeOutcomes:qualitative,assumptionOutcomes:assumptions});
  const allowedCitations=new Set(citationOptions.map(item=>item.key));
  const citationsValid=[...Object.values(assessments).filter(item=>"evidenceKeys" in item),...assumptions,...qualitative].every(item=>item.evidenceKeys.every(key=>allowedCitations.has(key)));
  const completionValid=result!=="completed" || Date.parse(version.definition.timeHorizon.until)<=Date.now()&&Date.parse(version.definition.timeHorizon.until)>=Date.parse(chosenAt)&&expectations.every(({item,index})=>item.kind==="metric"?!!actual[index]:qualitative.some(value=>value.expectationIndex===index&&value.assessment!=="inconclusive"));
  const ready=input.success&&citationsValid&&completionValid;
  return <form aria-label="Decision outcome assessment" className="min-w-0 space-y-5" onSubmit={event=>{event.preventDefault();if(ready&&input.success) onSave(input.data);}}><fieldset disabled={busy} className="min-w-0 space-y-5"><legend className="font-semibold">Review the decision outcome</legend>
    <p className="text-sm text-muted-foreground">A good or bad outcome does not determine whether the original choice was good. Assess the process, assumptions, execution, external change and outcome separately.</p>
    <label className="block space-y-2">Review result<select aria-label="Review result" className={selectStyle} value={result} onChange={event=>setResult(event.target.value as typeof result)}><option value="inconclusive">Inconclusive</option><option value="completed">Completed outcome assessment</option></select></label>
    {expectations.map(({item,index})=><section key={index} aria-label={`Chosen expectation ${index+1}`} className="min-w-0 space-y-3 rounded-md border border-border p-4"><h4 className="font-medium">Expectation {index+1}</h4>
      {item.kind==="qualitative"?<><p>{item.statement}</p><label className="block space-y-2">Qualitative outcome judgment<select aria-label="Qualitative outcome judgment" className={selectStyle} value={qualitative.find(value=>value.expectationIndex===index)!.assessment} onChange={event=>setQualitative(qualitative.map(value=>value.expectationIndex===index?{...value,assessment:event.target.value as typeof value.assessment}:value))}>{["met","not_met","inconclusive"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="block space-y-2">Qualitative outcome explanation<Textarea value={qualitative.find(value=>value.expectationIndex===index)!.explanation} onChange={event=>setQualitative(qualitative.map(value=>value.expectationIndex===index?{...value,explanation:event.target.value}:value))} minLength={10} maxLength={2000} required/></label></>:<>
        <p>Human expected range: {item.expectedRange.lower} to {item.expectedRange.upper} · {item.expectedDirection??"no direction declared"}</p><p className="text-sm text-muted-foreground">{item.uncertaintySummary}</p>
        {(()=>{const baseline=version.evidence.find(value=>value.key===item.evidenceKey);return baseline?.source.type==="metric_observation"?<ObservationPicker companyId={companyId} userId={userId} baseline={baseline.source} horizon={version.definition.timeHorizon} chosenAt={chosenAt} value={actual[index]??null} onChange={value=>setActual({...actual,[index]:value})}/>:<p role="alert">The frozen measurement baseline is unavailable. A completed numeric comparison cannot be recorded.</p>;})()}
      </>}
    </section>)}
    <section aria-label="Assumption validation" className="space-y-4"><h4 className="font-medium">Validate each recorded assumption</h4>{!assumptions.length&&<p className="text-sm text-muted-foreground">No assumptions were declared before the choice.</p>}{assumptions.map((item,index)=><fieldset key={item.key} className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend>Assumption {index+1}</legend><p>{version.definition.assumptions.find(value=>value.key===item.key)!.statement}</p><label className="block space-y-2">Assumption outcome<select aria-label="Assumption outcome" className={selectStyle} value={item.assessment} onChange={event=>setAssumptions(assumptions.map((value,i)=>i===index?{...value,assessment:event.target.value as typeof value.assessment}:value))}>{["supported","contradicted","inconclusive"].map(value=><option key={value}>{value}</option>)}</select></label><label className="block space-y-2">Assumption outcome explanation<Textarea value={item.explanation} onChange={event=>setAssumptions(assumptions.map((value,i)=>i===index?{...value,explanation:event.target.value}:value))} minLength={10} maxLength={2000} required/></label>{citation(item.evidenceKeys,value=>setAssumptions(assumptions.map((current,i)=>i===index?{...current,evidenceKeys:value}:current)),"Assumption evidence")}</fieldset>)}</section>
    {(Object.keys(labels) as JudgmentKey[]).map(key=><fieldset key={key} className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend>{labels[key]}</legend><p className="text-sm text-muted-foreground">Explicit human judgment.</p><label className="block space-y-2">{labels[key]} judgment<select aria-label={`${labels[key]} judgment`} className={selectStyle} value={assessments[key].assessment} onChange={event=>setAssessments({...assessments,[key]:{...assessments[key],assessment:event.target.value as typeof assessments[typeof key]["assessment"]}})}>{["supported","mixed","not_supported","unknown"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="block space-y-2">{labels[key]} explanation<Textarea value={assessments[key].explanation} onChange={event=>setAssessments({...assessments,[key]:{...assessments[key],explanation:event.target.value}})} minLength={10} maxLength={2000} required/></label>{citation(assessments[key].evidenceKeys,value=>setAssessments({...assessments,[key]:{...assessments[key],evidenceKeys:value}}),`${labels[key]} evidence`)}</fieldset>)}
    <fieldset className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend>Causal confidence</legend><p className="text-sm text-muted-foreground">Before/after association does not establish the effect of this Decision.</p><label className="block space-y-2">Causal assessment<select aria-label="Causal assessment" className={selectStyle} value={assessments.causalConfidence.assessment} onChange={event=>setAssessments({...assessments,causalConfidence:{...assessments.causalConfidence,assessment:event.target.value as "not_assessed"|"association_only"}})}><option value="not_assessed">Not assessed</option><option value="association_only">Association only</option></select></label><label className="block space-y-2">Causal confidence explanation<Textarea value={assessments.causalConfidence.explanation} onChange={event=>setAssessments({...assessments,causalConfidence:{...assessments.causalConfidence,explanation:event.target.value}})} minLength={10} maxLength={2000} required/></label></fieldset>
    <label className="block space-y-2">Lesson summary<Textarea value={lesson} onChange={event=>setLesson(event.target.value)} minLength={10} maxLength={2000} required/></label>
    <p className="text-sm text-muted-foreground">Saving records an immutable review. It does not change the original context, choose another option or promote a Learning hypothesis.</p>{!ready&&<p className="text-sm text-muted-foreground">Explain all six assessments and every declared assumption. Completed outcomes require an elapsed prospective horizon and all chosen expectations.</p>}
    <div className="flex flex-wrap gap-2"><Button type="submit" disabled={!ready||busy}>Record outcome review</Button><Button type="button" variant="ghost" onClick={onCancel}>Cancel editing</Button></div>
  </fieldset></form>;
}
