import {useEffect,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {decisionContextDefinitionSchema,type DecisionContextDefinition,type DecisionEvidenceReference,type DecisionOption} from "@paperclipai/shared";
import {aiGovernanceApi} from "@/api/ai-governance";
import {decisionIntelligenceApi} from "@/api/decision-intelligence";
import {DecisionTemplateGuidance} from "./DecisionTemplateGuidance";
import {DecisionEvidencePicker} from "./DecisionEvidencePicker";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
const day=(value:string)=>value.slice(0,10),iso=(value:string)=>`${value}T00:00:00Z`;
type Definition=DecisionContextDefinition;
type Evidence=Omit<Definition["evidence"][number],"source">&{source:DecisionEvidenceReference|null};
export function DecisionContextForm({companyId,userId,options,initial,busy,onSave,onCancel,onAuthorityLost=onCancel}:{companyId:string;userId:string|null;options:DecisionOption[];initial?:Definition;busy:boolean;onSave:(definition:Definition)=>void;onCancel:()=>void;onAuthorityLost?:()=>void}) {
  const [question,setQuestion]=useState(initial?.question??""),[objective,setObjective]=useState(initial?.objective??"");
  const [owner,setOwner]=useState(initial?.ownerUserId??userId??"local-board"),[uncertainty,setUncertainty]=useState(initial?.uncertaintySummary??"");
  const [from,setFrom]=useState(day(initial?.timeHorizon.from??new Date().toISOString())),[until,setUntil]=useState(day(initial?.timeHorizon.until??new Date(Date.now()+90*86400000).toISOString()));
  const [revisit,setRevisit]=useState(initial?.revisitAt?day(initial.revisitAt):""),[policyId,setPolicyId]=useState(initial?.governanceObligationRefs[0]??"");
  const [retention,setRetention]=useState(String(initial?.retentionDays??30)),[sensitivity,setSensitivity]=useState<Definition["sensitivity"]>(initial?.sensitivity??"internal");
  const [scope,setScope]=useState<Definition["scope"]>(initial?.scope??{type:"company",id:null});
  const [evidence,setEvidence]=useState<Evidence[]>(initial?.evidence??[]),[assumptions,setAssumptions]=useState<Definition["assumptions"]>(initial?.assumptions??[]);
  const [criteria,setCriteria]=useState<Definition["criteria"]>(initial?.criteria??[{key:"delivery",name:"Delivery",description:"",type:"qualitative",priority:"medium",evidenceKey:null}]);
  const [outcomes,setOutcomes]=useState<Definition["expectedOutcomes"]>(initial?.expectedOutcomes??[{kind:"qualitative",optionId:options[0]?.id??"",statement:"",reviewAt:iso(day(new Date(Date.now()+91*86400000).toISOString())),uncertaintySummary:""}]);
  const policies=useQuery({queryKey:["governance-obligations",companyId,userId],queryFn:()=>aiGovernanceApi.obligations(companyId,userId??undefined)});
  const scopeProjects=useQuery({queryKey:["decision-scope",companyId,userId,"projects"],queryFn:()=>decisionIntelligenceApi.scopeSources(companyId,"project",userId??undefined),enabled:scope.type==="project",retry:false});
  const scopeIssues=useQuery({queryKey:["decision-scope",companyId,userId,"issues"],queryFn:()=>decisionIntelligenceApi.scopeSources(companyId,"issue",userId??undefined),enabled:scope.type==="issue",retry:false});
  const scopeQuery=scope.type==="project"?scopeProjects:scope.type==="issue"?scopeIssues:null;
  const authorityLost=policies.isError||scopeQuery?.isError;
  useEffect(()=>{if(authorityLost)onAuthorityLost();},[authorityLost,onAuthorityLost]);
  const valid=decisionContextDefinitionSchema.safeParse({question,objective,ownerUserId:owner,scope,timeHorizon:{from:iso(from),until:iso(until)},uncertaintySummary:uncertainty,revisitAt:revisit?iso(revisit):null,
    sensitivity,purpose:"management_intelligence",governanceObligationRefs:[policyId,...(initial?.governanceObligationRefs.slice(1)??[])],retentionDays:retention.trim()?Number(retention):NaN,evidence,assumptions,criteria,expectedOutcomes:outcomes});
  const updateEvidence=(index:number,patch:Partial<Evidence>)=>setEvidence(evidence.map((item,i)=>i===index?{...item,...patch}:item));
  const updateCriterion=(index:number,patch:Partial<Definition["criteria"][number]>)=>setCriteria(criteria.map((item,i)=>i===index?{...item,...patch}:item));
  const updateAssumption=(index:number,patch:Partial<Definition["assumptions"][number]>)=>setAssumptions(assumptions.map((item,i)=>i===index?{...item,...patch}:item));
  const updateOutcome=(index:number,item:Definition["expectedOutcomes"][number])=>setOutcomes(outcomes.map((current,i)=>i===index?item:current));
  const sourceUnavailable=!!scopeQuery&&(scopeQuery.isError||scopeQuery.isFetching);
  return <form aria-label="Decision context proposal" className="space-y-5" onSubmit={event=>{event.preventDefault();if(valid.success&&!policies.isError&&!policies.isFetching&&!sourceUnavailable) onSave(valid.data);}}>
    <fieldset disabled={busy} className="min-w-0 space-y-5"><legend className="font-semibold">Propose decision context</legend>
      <p className="text-sm text-muted-foreground">Record the question, assumptions and expected outcomes before choosing. Saving creates a proposal; preparation requires a separate human review.</p>
      <DecisionTemplateGuidance/>
      <label className="block space-y-2">Question<Textarea value={question} onChange={event=>setQuestion(event.target.value)} minLength={10} maxLength={2000} required/></label>
      <label className="block space-y-2">Objective<Textarea value={objective} onChange={event=>setObjective(event.target.value)} minLength={10} maxLength={2000} required/></label>
      <label className="block space-y-2">Human owner<Input value={owner} onChange={event=>setOwner(event.target.value)} required/></label>
      <div className="grid gap-3 sm:grid-cols-2"><label className="block space-y-2">Horizon start<Input type="date" value={from} onChange={event=>setFrom(event.target.value)} required/></label><label className="block space-y-2">Horizon end<Input type="date" value={until} onChange={event=>setUntil(event.target.value)} required/></label></div>
      <label className="block space-y-2">Decision scope<select aria-label="Decision scope" className={selectStyle} value={scope.type} onChange={event=>setScope(event.target.value==="company"?{type:"company",id:null}:{type:event.target.value as "project"|"issue",id:""})}><option value="company">Company</option><option value="project">Project</option><option value="issue">Task</option></select></label>
      {scope.type!=="company"&&<label className="block space-y-2">Scoped native object<select aria-label="Scoped native object" className={selectStyle} value={scope.id} onChange={event=>setScope({...scope,id:event.target.value})}><option value="">Choose a current native object</option>{!sourceUnavailable&&scopeQuery?.data?.items.map(row=>row.source.kind==="canonical"&&row.source.reference.type!=="foundation_section"?<option key={row.source.reference.id} value={row.source.reference.id}>{row.title}</option>:null)}{scope.id&&!scopeQuery?.data?.items.some(row=>row.source.kind==="canonical"&&row.source.reference.type!=="foundation_section"&&row.source.reference.id===scope.id)&&<option value={scope.id}>Previously selected native object · current access is rechecked</option>}</select><span className="text-sm text-muted-foreground">Showing bounded authorized choices; an empty list does not establish completeness.</span></label>}
      <p className="text-sm text-muted-foreground">Dates use UTC. Native evidence retains its own declared population; selecting a scope does not redefine a metric.</p>
      <label className="block space-y-2">Uncertainty<Textarea value={uncertainty} onChange={event=>setUncertainty(event.target.value)} minLength={10} maxLength={2000} required/></label>
      <label className="block space-y-2">Revisit date (optional)<Input type="date" value={revisit} onChange={event=>setRevisit(event.target.value)}/></label>
      <label className="block space-y-2">Sensitivity<select aria-label="Sensitivity" className={selectStyle} value={sensitivity} onChange={event=>setSensitivity(event.target.value as typeof sensitivity)}><option value="internal">Internal</option><option value="confidential">Confidential</option></select></label>
      <label className="block space-y-2">Approved decision purpose<select aria-label="Approved decision purpose" className={selectStyle} value={policyId} onChange={event=>setPolicyId(event.target.value)} required><option value="">Choose current company policy</option>{!policies.isError&&!policies.isFetching&&policies.data?.filter(row=>row.obligation.framework==="company_policy"&&row.obligation.analyticalPurpose?.status==="approved"&&row.obligation.analyticalPurpose.purpose==="management_intelligence"&&row.obligation.analyticalPurpose.capabilities.includes("decision")).map(row=><option key={row.id} value={row.id}>{row.obligation.citation}</option>)}{policyId&&!policies.data?.some(row=>row.id===policyId)&&<option value={policyId}>Previously pinned purpose · current review required</option>}</select></label>
      <label className="block space-y-2">Retention days<Input type="number" value={retention} min={1} max={3650} onChange={event=>setRetention(event.target.value)} required/></label>
      <section aria-label="Decision evidence links" className="space-y-4"><h4 className="font-medium">Evidence</h4>
        {evidence.map((item,index)=><fieldset key={index} className="min-w-0 space-y-3 rounded-md border border-border p-4"><legend>Evidence {index+1}</legend>
          <label className="block space-y-2">Evidence key<Input value={item.key} onChange={event=>updateEvidence(index,{key:event.target.value})} required/></label>
          <DecisionEvidencePicker companyId={companyId} userId={userId} value={item.source} onChange={source=>updateEvidence(index,{source})}/>
          <label className="block space-y-2">Relationship<select aria-label="Relationship" className={selectStyle} value={item.relationship} onChange={event=>{const relationship=event.target.value as Evidence["relationship"];updateEvidence(index,{relationship,optionId:["supports_option","contradicts_option"].includes(relationship)?options[0]?.id??null:null,criterionKey:relationship==="informs_criterion"?criteria[0]?.key??null:null});}}>{["supports_option","contradicts_option","informs_criterion","establishes_constraint","metric_observation","process_finding","forecast_result","scenario_result","experiment_result","causal_result","risk"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>
          {item.optionId!==null&&<label className="block space-y-2">Linked option<select aria-label="Linked option" className={selectStyle} value={item.optionId} onChange={event=>updateEvidence(index,{optionId:event.target.value})}>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
          {item.criterionKey!==null&&<label className="block space-y-2">Linked criterion<select aria-label="Linked criterion" className={selectStyle} value={item.criterionKey} onChange={event=>updateEvidence(index,{criterionKey:event.target.value})}>{criteria.map(criterion=><option key={criterion.key} value={criterion.key}>{criterion.name}</option>)}</select></label>}
          <label className="block space-y-2">Evidence rationale<Textarea value={item.rationale} onChange={event=>updateEvidence(index,{rationale:event.target.value})} minLength={10} required/></label>
          <Button type="button" variant="ghost" onClick={()=>setEvidence(evidence.filter((_,i)=>i!==index))}>Remove evidence {index+1}</Button>
        </fieldset>)}
        <Button type="button" variant="outline" disabled={evidence.length>=20} onClick={()=>setEvidence([...evidence,{key:`evidence_${evidence.length+1}`,source:null,relationship:"risk",optionId:null,criterionKey:null,rationale:""}])}>Add native evidence</Button>
      </section>
      <section aria-label="Decision assumptions" className="space-y-4"><h4 className="font-medium">Assumptions</h4><p className="text-sm text-muted-foreground">Confidence records human judgment. Validation belongs in a later review.</p>
        {assumptions.map((item,index)=><fieldset key={index} className="space-y-3 rounded-md border border-border p-4"><legend>Assumption {index+1}</legend>
          <label className="block space-y-2">Assumption key<Input value={item.key} onChange={event=>updateAssumption(index,{key:event.target.value})} required/></label>
          <label className="block space-y-2">Assumption statement<Textarea value={item.statement} onChange={event=>updateAssumption(index,{statement:event.target.value})} minLength={10} required/></label>
          <label className="block space-y-2">Assumption type<select aria-label="Assumption type" className={selectStyle} value={item.type} onChange={event=>updateAssumption(index,{type:event.target.value as typeof item.type})}>{["factual","model","delivery","financial","strategic"].map(value=><option key={value}>{value}</option>)}</select></label>
          <div className="grid gap-3 sm:grid-cols-2"><label className="block space-y-2">Human confidence<select aria-label="Human confidence" className={selectStyle} value={item.confidence.level} onChange={event=>updateAssumption(index,{confidence:{kind:"human_judgment",level:event.target.value as typeof item.confidence.level}})}>{["low","medium","high"].map(value=><option key={value}>{value}</option>)}</select></label><label className="block space-y-2">Materiality<select aria-label="Materiality" className={selectStyle} value={item.materiality} onChange={event=>updateAssumption(index,{materiality:event.target.value as typeof item.materiality})}>{["low","medium","high"].map(value=><option key={value}>{value}</option>)}</select></label></div>
          <Button type="button" variant="ghost" onClick={()=>setAssumptions(assumptions.filter((_,i)=>i!==index))}>Remove assumption {index+1}</Button>
        </fieldset>)}<Button type="button" variant="outline" disabled={assumptions.length>=20} onClick={()=>setAssumptions([...assumptions,{key:`assumption_${assumptions.length+1}`,statement:"",type:"delivery",confidence:{kind:"human_judgment",level:"medium"},materiality:"medium",status:"unverified"}])}>Add assumption</Button>
      </section>
      <section aria-label="Decision criteria" className="space-y-4"><h4 className="font-medium">Criteria</h4><p className="text-sm text-muted-foreground">Compare qualitative concerns, constraints and observations without a combined score.</p>
        {criteria.map((item,index)=><fieldset key={index} className="space-y-3 rounded-md border border-border p-4"><legend>Criterion {index+1}</legend>
          <label className="block space-y-2">Criterion key<Input value={item.key} onChange={event=>updateCriterion(index,{key:event.target.value})} required/></label>
          <label className="block space-y-2">Criterion name<Input value={item.name} onChange={event=>updateCriterion(index,{name:event.target.value})} minLength={3} required/></label>
          <label className="block space-y-2">Criterion description<Textarea value={item.description} onChange={event=>updateCriterion(index,{description:event.target.value})} minLength={10} required/></label>
          <label className="block space-y-2">Criterion type<select aria-label="Criterion type" className={selectStyle} value={item.type} onChange={event=>updateCriterion(index,{type:event.target.value as typeof item.type})}>{["qualitative","constraint","trade_off","measured"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>
          <label className="block space-y-2">Criterion priority<select aria-label="Criterion priority" className={selectStyle} value={item.priority} onChange={event=>updateCriterion(index,{priority:event.target.value as typeof item.priority})}>{["low","medium","high"].map(value=><option key={value}>{value}</option>)}</select></label>
          <label className="block space-y-2">Criterion evidence<select aria-label="Criterion evidence" className={selectStyle} value={item.evidenceKey??""} onChange={event=>updateCriterion(index,{evidenceKey:event.target.value||null})}><option value="">No measurement claim</option>{evidence.filter(link=>item.type!=="measured"||link.source?.type==="metric_observation").map(link=><option key={link.key} value={link.key}>{link.key}</option>)}</select></label>
          <Button type="button" variant="ghost" disabled={criteria.length===1} onClick={()=>setCriteria(criteria.filter((_,i)=>i!==index))}>Remove criterion {index+1}</Button>
        </fieldset>)}<Button type="button" variant="outline" disabled={criteria.length>=20} onClick={()=>setCriteria([...criteria,{key:`criterion_${criteria.length+1}`,name:"",description:"",type:"qualitative",priority:"medium",evidenceKey:null}])}>Add criterion</Button>
      </section>
      <section aria-label="Expected decision outcomes" className="space-y-4"><h4 className="font-medium">Expected outcomes</h4>
        {outcomes.map((item,index)=><fieldset key={index} className="space-y-3 rounded-md border border-border p-4"><legend>Expectation {index+1}</legend>
          <label className="block space-y-2">Expected option<select aria-label="Expected option" className={selectStyle} value={item.optionId} onChange={event=>updateOutcome(index,{...item,optionId:event.target.value})}>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>
          <label className="block space-y-2">Expectation kind<select aria-label="Expectation kind" className={selectStyle} value={item.kind} onChange={event=>updateOutcome(index,event.target.value==="qualitative"?{kind:"qualitative",optionId:item.optionId,statement:"",reviewAt:item.reviewAt,uncertaintySummary:item.uncertaintySummary}:{kind:"metric",optionId:item.optionId,evidenceKey:"",expectedRange:{lower:NaN,upper:NaN},expectedDirection:null,reviewAt:item.reviewAt,uncertaintySummary:item.uncertaintySummary})}><option value="qualitative">Qualitative outcome</option><option value="metric">Human expected metric range</option></select></label>
          {item.kind==="qualitative"?<label className="block space-y-2">Expected outcome statement<Textarea value={item.statement} onChange={event=>updateOutcome(index,{...item,statement:event.target.value})} minLength={10} required/></label>:<>
            <label className="block space-y-2">Baseline evidence<select aria-label="Baseline evidence" className={selectStyle} value={item.evidenceKey} onChange={event=>updateOutcome(index,{...item,evidenceKey:event.target.value})}><option value="">Choose a pinned metric observation</option>{evidence.filter(link=>link.source?.type==="metric_observation").map(link=><option key={link.key} value={link.key}>{link.key}</option>)}</select></label>
            <div className="grid gap-3 sm:grid-cols-2">{(["lower","upper"] as const).map(bound=><label key={bound} className="block space-y-2">{bound==="lower"?"Expected lower bound":"Expected upper bound"}<Input type="number" step="any" value={Number.isFinite(item.expectedRange[bound])?item.expectedRange[bound]:""} onChange={event=>updateOutcome(index,{...item,expectedRange:{...item.expectedRange,[bound]:event.target.value.trim()?Number(event.target.value):NaN}})} required/></label>)}</div>
            <label className="block space-y-2">Expected direction<select aria-label="Expected direction" className={selectStyle} value={item.expectedDirection??""} onChange={event=>updateOutcome(index,{...item,expectedDirection:event.target.value?event.target.value as "increase"|"decrease"|"stable":null})}><option value="">No direction claim</option>{["increase","decrease","stable"].map(value=><option key={value}>{value}</option>)}</select></label>
          </>}
          <label className="block space-y-2">Outcome review date<Input type="date" value={day(item.reviewAt)} onChange={event=>updateOutcome(index,{...item,reviewAt:iso(event.target.value)})} required/></label>
          <label className="block space-y-2">Outcome uncertainty<Textarea value={item.uncertaintySummary} onChange={event=>updateOutcome(index,{...item,uncertaintySummary:event.target.value})} minLength={10} required/></label>
          <Button type="button" variant="ghost" disabled={outcomes.length===1} onClick={()=>setOutcomes(outcomes.filter((_,i)=>i!==index))}>Remove expectation {index+1}</Button>
        </fieldset>)}<Button type="button" variant="outline" disabled={outcomes.length>=16} onClick={()=>setOutcomes([...outcomes,{kind:"qualitative",optionId:options[0]?.id??"",statement:"",reviewAt:iso(until),uncertaintySummary:""}])}>Add expected outcome</Button>
      </section>
      {policies.isError&&<p role="alert">Decision purpose could not be verified. Refresh before saving.</p>}
      {!valid.success&&<p className="text-sm text-muted-foreground">Complete all material fields, declare valid evidence pins and review dates, and keep ranges and horizons ordered.</p>}
      {scopeQuery?.isError&&<p role="alert">Scoped native objects could not be verified. Refresh before saving.</p>}
      <div className="flex flex-wrap gap-2"><Button type="submit" disabled={!valid.success||busy||policies.isError||policies.isFetching||sourceUnavailable}>Save context proposal</Button><Button type="button" variant="ghost" onClick={onCancel}>Cancel proposal</Button></div>
    </fieldset>
  </form>;
}
