import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import type {DecisionEvidenceReference} from "@paperclipai/shared";
import {businessMetricsApi} from "@/api/business-metrics";
import {processAnalysisApi} from "@/api/process-analysis";
import {businessForecastingApi} from "@/api/business-forecasting";
import {businessExperimentsApi} from "@/api/business-experiments";
import {businessScenariosApi} from "@/api/business-scenarios";
import {causalClaimsApi} from "@/api/causal-claims";
import {Button} from "@/components/ui/button";
const selectStyle="w-full min-w-0 rounded-md border border-input bg-background p-2";
export function DecisionEvidencePicker({companyId,userId,value,onChange}:{companyId:string;userId:string|null;value:DecisionEvidenceReference|null;onChange:(value:DecisionEvidenceReference|null)=>void}) {
  const [kind,setKind]=useState<DecisionEvidenceReference["type"]>(value?.type??"metric_observation");
  const [ownerId,setOwnerId]=useState(value?.type==="metric_observation"?value.metricId:value?.type==="process_finding"?value.definitionId:value?.type==="forecast_run"?value.specId:value?.type==="scenario_run"?value.scenarioId:value?.type==="experiment_analysis"?value.experimentId:value?.type==="causal_analysis"?value.claimId:"");
  const [runId,setRunId]=useState(value?.type==="process_finding"?value.runId:value?.type==="forecast_run"||value?.type==="scenario_run"?value.id:"");
  const key=["decision-evidence",companyId,userId],account=userId??undefined;
  const metrics=useQuery({queryKey:[...key,"metrics"],queryFn:()=>businessMetricsApi.list(companyId,undefined,account),enabled:kind==="metric_observation",refetchInterval:30000});
  const definitions=useQuery({queryKey:[...key,"process-definitions"],queryFn:()=>processAnalysisApi.list(companyId,undefined,account),enabled:kind==="process_finding",refetchInterval:30000});
  const observations=useQuery({queryKey:[...key,"observations",ownerId],queryFn:()=>businessMetricsApi.observations(companyId,ownerId,undefined,account),enabled:kind==="metric_observation"&&!!ownerId,refetchInterval:30000});
  const runs=useQuery({queryKey:[...key,"runs",ownerId],queryFn:()=>processAnalysisApi.listRuns(companyId,ownerId,undefined,account),enabled:kind==="process_finding"&&!!ownerId,refetchInterval:30000});
  const findings=useQuery({queryKey:[...key,"findings",ownerId,runId],queryFn:()=>processAnalysisApi.listFindings(companyId,ownerId,runId,undefined,account),enabled:kind==="process_finding"&&!!ownerId&&!!runId,refetchInterval:30000});
  const forecasts=useQuery({queryKey:[...key,"forecasts"],queryFn:()=>businessForecastingApi.list(companyId,undefined,account),enabled:kind==="forecast_run",refetchInterval:30000});
  const forecastRuns=useQuery({queryKey:[...key,"forecast-runs",ownerId],queryFn:()=>businessForecastingApi.artifacts(companyId,ownerId,"run",undefined,account),enabled:kind==="forecast_run"&&!!ownerId,refetchInterval:30000});
  const scenarios=useQuery({queryKey:[...key,"scenarios"],queryFn:()=>businessScenariosApi.list(companyId,undefined,account),enabled:kind==="scenario_run",refetchInterval:30000});
  const scenarioRuns=useQuery({queryKey:[...key,"scenario-runs",ownerId],queryFn:()=>businessScenariosApi.runs(companyId,ownerId,undefined,account),enabled:kind==="scenario_run"&&!!ownerId,refetchInterval:30000});
  const experiments=useQuery({queryKey:[...key,"experiments"],queryFn:()=>businessExperimentsApi.list(companyId,undefined,account),enabled:kind==="experiment_analysis",refetchInterval:30000});
  const experimentReceipts=useQuery({queryKey:[...key,"experiment-receipts",ownerId,experiments.data?.items.find(row=>row.experiment.id===ownerId)?.version.id],queryFn:()=>businessExperimentsApi.receipts(companyId,ownerId,experiments.data!.items.find(row=>row.experiment.id===ownerId)!.version.id,account),enabled:kind==="experiment_analysis"&&!!ownerId&&experiments.data?.items.some(row=>row.experiment.id===ownerId)===true,refetchInterval:30000});
  const causal=useQuery({queryKey:[...key,"causal-claims"],queryFn:()=>causalClaimsApi.list(companyId,undefined,account),enabled:kind==="causal_analysis",refetchInterval:30000});
  const causalDetail=useQuery({queryKey:[...key,"causal-detail",ownerId],queryFn:()=>causalClaimsApi.detail(companyId,ownerId,account),enabled:kind==="causal_analysis"&&!!ownerId,refetchInterval:30000});
  const queries=kind==="metric_observation"?[metrics,...(ownerId?[observations]:[])]:kind==="process_finding"?[definitions,...(ownerId?[runs]:[]),...(runId?[findings]:[])]:kind==="forecast_run"?[forecasts,...(ownerId?[forecastRuns]:[])]:kind==="scenario_run"?[scenarios,...(ownerId?[scenarioRuns]:[])]:kind==="causal_analysis"?[causal,...(ownerId?[causalDetail]:[])]:[experiments,...(ownerId?[experimentReceipts]:[])];
  const unavailable=queries.some(query=>query.isFetching||query.isError),error=queries.find(query=>query.isError)?.error;
  const options:{ref:DecisionEvidenceReference;label:string}[]=[];
  if(!unavailable && kind==="metric_observation") for(const row of observations.data?.items??[]) if(Date.parse(row.expiresAt)>Date.now()) options.push({ref:{type:kind,id:row.id,metricId:row.metricId,metricVersionId:row.versionId},label:`${row.from.slice(0,10)} to ${row.until.slice(0,10)} · ${row.status}`});
  if(!unavailable && kind==="process_finding") for(const row of findings.data?.items??[]) if(Date.parse(row.expiresAt)>Date.now()) options.push({ref:{type:kind,id:row.id,definitionId:row.definitionId,runId:row.analysisRunId},label:row.summary});
  if(!unavailable && kind==="forecast_run") for(const row of forecastRuns.data?.items??[]) if(row.id===runId&&row.companyId===companyId&&row.specId===ownerId&&row.currentQualification==="qualified"&&Date.parse(row.expiresAt)>Date.now()) row.result.points.forEach((point,pointIndex)=>options.push({ref:{type:kind,id:row.id,specId:row.specId,versionId:row.versionId,pointIndex},label:`${point.from.slice(0,10)} to ${point.until.slice(0,10)} · forecast point · intervals unavailable`}));
  if(!unavailable && kind==="scenario_run") for(const row of scenarioRuns.data?.items??[]) if(row.id===runId&&row.companyId===companyId&&row.scenarioId===ownerId&&row.currentQualification==="current"&&row.result.status!=="data_not_ready"&&Date.parse(row.expiresAt)>Date.now()) for(const scenarioCase of row.result.cases) for(const output of scenarioCase.outputs) options.push({ref:{type:kind,id:row.id,scenarioId:row.scenarioId,versionId:row.versionId,caseKey:scenarioCase.key,outputKey:output.key},label:`${scenarioCase.name} · ${output.key} · conditional ${row.result.status}`});
  const experiment=experiments.data?.items.find(row=>row.experiment.id===ownerId),receipt=experimentReceipts.data;
  if(!unavailable&&kind==="experiment_analysis"&&experiment?.experiment.companyId===companyId&&experiment.version.companyId===companyId&&experiment.version.experimentId===ownerId&&experiment.experiment.currentVersionId===experiment.version.id&&["decided","inconclusive","invalid"].includes(experiment.experiment.state)&&experiment.version.currentQualification==="current"&&Date.parse(experiment.version.expiresAt)>Date.now()&&receipt?.versionId===experiment.version.id&&receipt.currentQualification==="current"&&receipt.analysis?.companyId===companyId&&receipt.analysis.experimentId===ownerId&&receipt.analysis.versionId===experiment.version.id&&receipt.analysis.currentQualification==="current"&&receipt.interpretation?.analysisId===receipt.analysis.id) options.push({ref:{type:kind,id:receipt.analysis.id,experimentId:ownerId,versionId:experiment.version.id,interpretationId:receipt.interpretation.id},label:`${receipt.analysis.result.status} · human ${receipt.interpretation.conclusion.replaceAll("_"," ")} · advisory only`});
  const claim=causalDetail.data?.claim,pin=causalDetail.data?.versions.find(p=>p.version.id===claim?.currentVersionId);
  if(!unavailable&&kind==="causal_analysis"&&claim?.companyId===companyId&&claim.id===ownerId&&["supported","refuted","inconclusive"].includes(claim.status)&&pin?.version.companyId===companyId&&pin.version.claimId===ownerId&&pin.version.currentQualification==="current"&&Date.parse(pin.version.expiresAt)>Date.now()&&pin.review?.versionId===pin.version.id&&pin.run?.companyId===companyId&&pin.run.claimId===ownerId&&pin.run.versionId===pin.version.id&&pin.run.currentQualification==="current"&&claim.latestRunId===pin.run.id&&claim.status===pin.run.result.status&&claim.reviewedVersionId===pin.version.id)options.push({ref:{type:kind,id:pin.run.id,claimId:ownerId,versionId:pin.version.id,reviewId:pin.review.id},label:`${pin.run.result.status} · ${pin.run.result.evidenceGrade.replaceAll("_"," ")} · conditional advisory evidence`});
  const ownerLabel=kind==="metric_observation"?"Published metric":kind==="process_finding"?"Published process definition":kind==="forecast_run"?"Published forecast":kind==="scenario_run"?"Published scenario":kind==="causal_analysis"?"Reviewed causal claim":"Human-interpreted experiment";
  return <fieldset className="min-w-0 space-y-3"><legend className="font-medium">Native decision evidence</legend>
    <label className="block space-y-2">Evidence kind<select aria-label="Evidence kind" className={selectStyle} value={kind} onChange={event=>{setKind(event.target.value as typeof kind);setOwnerId("");setRunId("");onChange(null);}}><option value="metric_observation">Metric observation</option><option value="process_finding">Process finding</option><option value="forecast_run">Forecast point</option><option value="scenario_run">Conditional scenario output</option><option value="experiment_analysis">Human-interpreted experiment analysis</option><option value="causal_analysis">Reviewed conditional causal analysis</option></select></label>
    <label className="block space-y-2">{ownerLabel}<select aria-label={ownerLabel} className={selectStyle} value={ownerId} onChange={event=>{setOwnerId(event.target.value);setRunId("");onChange(null);}}><option value="">Choose a native definition</option>{!unavailable && (kind==="metric_observation"?metrics.data?.items.filter(row=>row.status==="published").map(row=><option key={row.id} value={row.id}>{row.key}</option>):kind==="process_finding"?definitions.data?.items.filter(row=>row.status==="published").map(row=><option key={row.id} value={row.id}>{row.definition.name}</option>):kind==="forecast_run"?forecasts.data?.items.filter(row=>row.companyId===companyId&&row.status==="published").map(row=><option key={row.id} value={row.id}>{row.key}</option>):kind==="scenario_run"?scenarios.data?.items.filter(row=>row.scenario.companyId===companyId&&row.scenario.status==="published"&&row.version.currentQualification==="current").map(row=><option key={row.scenario.id} value={row.scenario.id}>{row.version.definition.name}</option>):kind==="causal_analysis"?causal.data?.items.filter(row=>row.claim.companyId===companyId&&["supported","refuted","inconclusive"].includes(row.claim.status)&&row.version.companyId===companyId&&row.version.currentQualification==="current"&&Date.parse(row.version.expiresAt)>Date.now()).map(row=><option key={row.claim.id} value={row.claim.id}>{row.version.definition.name} · {row.claim.status}</option>):experiments.data?.items.filter(row=>row.experiment.companyId===companyId&&["decided","inconclusive","invalid"].includes(row.experiment.state)&&row.version.currentQualification==="current"&&Date.parse(row.version.expiresAt)>Date.now()).map(row=><option key={row.experiment.id} value={row.experiment.id}>{row.version.definition.name} · {row.experiment.state}</option>))}</select></label>
    {kind==="process_finding"&&ownerId&&<label className="block space-y-2">Observed process run<select aria-label="Observed process run" className={selectStyle} value={runId} onChange={event=>{setRunId(event.target.value);onChange(null);}}><option value="">Choose an authorized run</option>{!unavailable&&runs.data?.items.filter(row=>Date.parse(row.expiresAt)>Date.now()).map(row=><option key={row.id} value={row.id}>{row.from.slice(0,10)} to {row.until.slice(0,10)} · {row.result.status}</option>)}</select></label>}
    {(kind==="forecast_run"||kind==="scenario_run")&&ownerId&&<label className="block space-y-2">Retained calculation run<select aria-label="Retained calculation run" className={selectStyle} value={runId} onChange={event=>{setRunId(event.target.value);onChange(null);}}><option value="">Choose a current authorized calculation</option>{!unavailable&&(kind==="forecast_run"?forecastRuns.data?.items.filter(row=>row.companyId===companyId&&row.specId===ownerId&&row.currentQualification==="qualified"&&Date.parse(row.expiresAt)>Date.now()).map(row=><option key={row.id} value={row.id}>{new Date(row.createdAt).toLocaleString()} · qualified forecast</option>):scenarioRuns.data?.items.filter(row=>row.companyId===companyId&&row.scenarioId===ownerId&&row.currentQualification==="current"&&row.result.status!=="data_not_ready"&&Date.parse(row.expiresAt)>Date.now()).map(row=><option key={row.id} value={row.id}>{new Date(row.createdAt).toLocaleString()} · conditional {row.result.status}</option>))}</select></label>}
    <label className="block space-y-2">Pinned evidence<select aria-label="Pinned evidence" className={selectStyle} value={value?JSON.stringify(value):""} onChange={event=>onChange(options.find(option=>JSON.stringify(option.ref)===event.target.value)?.ref??null)}><option value="">Choose current native evidence</option>{value&&!options.some(option=>JSON.stringify(option.ref)===JSON.stringify(value))&&<option value={JSON.stringify(value)}>Previously pinned evidence · review current source</option>}{options.map(option=><option key={JSON.stringify(option.ref)} value={JSON.stringify(option.ref)}>{option.label}</option>)}</select></label>
    {queries.some(query=>query.isFetching)&&<p role="status">Rechecking current native sources…</p>}{error&&<p role="alert">{error.message}</p>}
    {(kind==="forecast_run"||kind==="scenario_run")&&<p className="text-sm text-muted-foreground">Choose an exact retained calculation. Forecasts and conditional scenarios are advisory evidence; they do not become measured outcomes or authorize a choice.</p>}
    {kind==="causal_analysis"&&<p className="text-sm text-muted-foreground">Pin the exact signed native interpretation and human graph review. Conditional support, refutation and abstention retain their assumptions and limits; no measured outcome or execution authority follows.</p>}
    {kind==="experiment_analysis"&&<p className="text-sm text-muted-foreground">Bind the exact signed analysis and separate human interpretation, including every registered safety gate. Human exposure and native status outcomes remain conditional proxies; this evidence grants no execution authority.</p>}
    <div className="flex flex-wrap items-center gap-2"><Button type="button" variant="ghost" onClick={()=>queries.forEach(query=>void query.refetch())}>Refresh evidence</Button><p className="text-sm text-muted-foreground">Bounded authorized choices. An empty page does not establish missing evidence.</p></div>
  </fieldset>;
}
