import { useState } from "react";
/** Optional writing guidance only. Native options, evidence, human judgments,
 * preparation and choice remain owned by the existing Decision workflow. */
const templates = [
  { key: "strategic_bet", label: "Strategic bet", prompts: ["Name the strategic objective, alternative and reversible next step.", "State the downside, material assumptions and evidence that would change the choice.", "Choose a review horizon and an observable outcome before committing."] },
  { key: "budget_allocation", label: "Budget allocation", prompts: ["Compare available resources and the opportunity cost of each alternative.", "Cite approved commitments and current actuals; keep unknown costs explicit.", "State the funding limit and later outcome review; native budget approval remains separate."] },
  { key: "vendor_selection", label: "Vendor selection", prompts: ["Compare service requirements, reliability, total cost and switching constraints.", "Declare privacy, security and contractual assumptions with current evidence.", "State acceptance criteria and the later review of actual service delivery."] },
  { key: "product_launch", label: "Product launch", prompts: ["Name the customer outcome, target scope and launch alternative.", "Assess readiness, quality, support capacity and a reversible rollout.", "Record the baseline, expected outcome and review date before the choice."] },
  { key: "market_entry", label: "Market entry", prompts: ["Specify the market, customer demand evidence and alternative use of capacity.", "Declare jurisdiction, localization, delivery and financial assumptions.", "Set a bounded commitment and review adoption separately from decision quality."] },
  { key: "project_replan", label: "Project replan", prompts: ["Identify the objective, current commitments, blockers and dependencies.", "Compare explicit capacity and deadline constraints; keep forecasts separate from actuals.", "Propose any changed dates through the native Roadmap review after the Decision."] },
  { key: "policy_change", label: "Policy change", prompts: ["Identify the policy, current control evidence and the proposed alternative.", "Explain applicability, affected business objects and unresolved governance assumptions.", "Use the native policy review for changes and assess later control evidence separately."] },
  { key: "experiment_decision", label: "Experiment decision", prompts: ["State the hypothesis, alternative and registered primary outcome with guardrails.", "Review assignment, exposure, sample size and missing evidence before interpreting results.", "Keep the native experiment's human interpretation and any conditional causal claim separate."] },
] as const;
export function DecisionTemplateGuidance() {
  const [key, setKey] = useState(""), template = templates.find(template => template.key === key);
  return <section aria-label="Optional decision template guidance" className="min-w-0 space-y-3"><label className="block space-y-2">Optional decision template<select aria-label="Optional decision template" className="w-full min-w-0 rounded-md border border-input bg-background p-2" value={key} onChange={event => setKey(event.target.value)}><option value="">Write without a template</option>{templates.map(template => <option key={template.key} value={template.key}>{template.label}</option>)}</select></label>{template && <div className="space-y-2 rounded-md border border-border p-3"><h4 className="font-medium">{template.label} guidance</h4><ul className="list-disc space-y-2 pl-5">{template.prompts.map(prompt => <li key={prompt}>{prompt}</li>)}</ul><p className="text-sm text-muted-foreground">Use these prompts to write your own context. Evidence, assumptions and expected outcomes require your review.</p></div>}</section>;
}
