import { useEffect, useState } from "react";
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { crossProjectPlanningApi } from "@/api/cross-project-planning";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Link } from "@/lib/router";
import { queryKeys } from "@/lib/queryKeys";
import { InitiativePlanningResult } from "./PortfolioPlanningPreview";
import { ProjectPlanningBasis } from "./ProjectPlanningBasis";

/** Existing native Human review states, exact revision and current Source;
 * account/source revocation and private cache lifetime belong to the parent. */
export function InitiativePlanningControls({ companyId, userId, enabled, lost, id, onSelect, onAuthorityLost, projectLabels, taskLabels, now, onSourceProjects }: { companyId: string; userId: string | null; enabled: boolean; lost: boolean; id: string; onSelect: (id: string) => void; onAuthorityLost: () => void; projectLabels: Record<string, string>; taskLabels: Record<string, string>; now: number; onSourceProjects: (ids: string[]) => void }) {
  const cache = useQueryClient(), key = ["cross-project-planning", companyId, userId];
  const [rationale, setRationale] = useState(""), [ack, setAck] = useState(false);
  const controls = useInfiniteQuery({ queryKey: [...key, "initiative-controls"], initialPageParam: undefined as string | undefined, queryFn: ({ pageParam }) => crossProjectPlanningApi.initiativeControls(companyId, pageParam, userId), getNextPageParam: page => page.nextCursor ?? undefined, retry: false });
  const detail = useQuery({ gcTime: 0, queryKey: [...key, "initiative-detail", id], queryFn: () => crossProjectPlanningApi.initiativeDetail(companyId, id, userId), enabled: !!id && enabled && !lost, retry: false, refetchInterval: 30000 });
  useEffect(() => { if (controls.isError || detail.isError) onAuthorityLost(); }, [controls.isError, detail.isError, onAuthorityLost]);
  const rows = !controls.isFetching && !controls.isError ? controls.data?.pages.flatMap(page => page.items) ?? [] : [], selected = rows.find(row => row.id === id);
  const retained = enabled && !lost && !controls.isFetching && !controls.isError && !detail.isFetching && !detail.isError && detail.data?.companyId === companyId && detail.data.id === id && Date.parse(detail.data.initiativeContext.expiresAt) > Math.max(now, Date.now()) ? detail.data : undefined;
  useEffect(() => { setRationale(""); setAck(false); }, [id, enabled]);
  useEffect(() => { setAck(false); }, [selected?.revision, retained?.contextHash]);
  useEffect(() => { onSourceProjects(retained?.initiativeContext.profile.projects.map(project => project.id) ?? []); }, [retained, onSourceProjects]);
  const review = useMutation({ gcTime: 0, mutationFn: (action: "begin_review" | "accept" | "reject" | "cancel") => crossProjectPlanningApi.reviewInitiatives(companyId, id, selected!.revision, action, rationale, userId), onSuccess: () => { onSelect(""); setRationale(""); setAck(false); void cache.invalidateQueries({ queryKey: [...key, "initiative-controls"] }); void cache.invalidateQueries({ queryKey: [...key, "initiative-detail"] }); void cache.invalidateQueries({ queryKey: [...key, "source"] }); void cache.invalidateQueries({ queryKey: queryKeys.projects.all(companyId) }); }, onError: onAuthorityLost });
  const valid = rationale.trim().length >= 10 && rationale.trim().length <= 4000, canApply = !!retained && retained.currentQualification === "current" && selected?.revision === retained.revision && ack && valid;
  return <section aria-label="Native initiative proposal controls" className="min-w-0 space-y-4"><h2 className="font-semibold">Initiative proposal controls</h2><label className="block space-y-2">Initiative proposal reference<select aria-label="Initiative proposal reference" className="w-full min-w-0 rounded-md border border-input bg-background p-2" value={id} disabled={review.isPending || controls.isFetching} onChange={event => onSelect(event.target.value)}><option value="">Choose exact native initiative proposal</option>{rows.map(row => <option key={row.id} value={row.id}>{row.status.replaceAll("_", " ")} · revision {row.revision} · {row.id}</option>)}</select></label>
    {controls.isError && <p role="alert">Current initiative control authority could not be established.</p>}{controls.hasNextPage && <Button variant="outline" disabled={controls.isFetching} onClick={() => void controls.fetchNextPage()}>Load more initiative controls</Button>}{detail.isFetching && <p role="status">Rechecking exact native initiative Sources…</p>}
    {retained && <div className="space-y-4"><p>{retained.reason}</p><InitiativePlanningResult response={{ result: retained.initiativeContext.result, currentSources: retained.initiativeContext.currentSources, capturedAt: retained.initiativeContext.capturedAt }} profile={retained.initiativeContext.profile} projectLabels={projectLabels} taskLabels={taskLabels} isCurrent={retained.currentQualification === "current"} /><ProjectPlanningBasis detail={{ contextHash: retained.contextHash, currentQualification: retained.currentQualification, context: { profile: retained.initiativeContext.profile, evidence: retained.context.evidence, capturedAt: retained.initiativeContext.capturedAt, expiresAt: retained.initiativeContext.expiresAt } }} taskLabels={taskLabels} />{retained.appliedProjectRefs.length > 0 && <ul className="list-disc space-y-2 pl-5">{retained.appliedProjectRefs.map(ref => <li key={ref.projectId}><Link className="underline" to={`/projects/${ref.projectId}`}>Open original project</Link> · {ref.disposition} · {ref.status}{ref.paused ? " · paused" : ""}</li>)}</ul>}</div>}
    {selected && ["proposed", "under_review"].includes(selected.status) && <section aria-label="Separate Human initiative review" className="space-y-3"><label className="block space-y-2">Separate Human initiative review rationale<Textarea aria-label="Initiative review rationale" minLength={10} maxLength={4000} disabled={review.isPending} value={rationale} onChange={event => { setRationale(event.target.value); setAck(false); }} /></label>{retained && <><p>Start marks a project in progress. Pause adds a manual project hold. Stop marks it cancelled and held. Continuation keeps its current state. Task dates/statuses, budgets and active runs are not changed by this approval.</p><label className="flex items-start gap-2"><input type="checkbox" checked={ack} disabled={review.isPending} onChange={event => setAck(event.target.checked)} />I reviewed this exact Source, company dimensions, costs, capacity, protected commitments and each proposed project change.</label></>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={review.isPending || !valid} onClick={() => review.mutate("reject")}>Reject initiative proposal</Button><Button variant="ghost" disabled={review.isPending || !valid} onClick={() => review.mutate("cancel")}>Cancel initiative proposal</Button>{retained && <Button disabled={review.isPending || !canApply} onClick={() => review.mutate(selected.status === "proposed" ? "begin_review" : "accept")}>{selected.status === "proposed" ? "Begin separate initiative review" : "Approve initiative project changes"}</Button>}</div></section>}
  </section>;
}
