// @vitest-environment jsdom
import { withV7AccountScope } from "@/context/V7AccountScope";
vi.mock("@/api/companies-query", () => ({ useAccountIdentity: () => ({ userId: "fixture-user", settled: true, failed: false }) }));
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, expect, it, vi } from "vitest";
import { roadmapPolicySchema } from "@paperclipai/shared";
import { LearningPolicyReview } from "./LearningPolicyReview";
import { learningApi } from "@/api/learning";
vi.mock("@/api/learning", () => { const learningApi = { policies: vi.fn(), reviewPolicy: vi.fn() }; return { learningApi, createLearningApi: () => learningApi }; });
vi.mock("@/context/CompanyContext", () => ({ useCompany: () => ({ selectedCompanyId: "company" }) }));
let root: Root | undefined, container: HTMLDivElement | undefined;
afterEach(async () => { await act(async () => root?.unmount()); container?.remove(); vi.clearAllMocks(); });
it("requires a separate rationale and acknowledgment for each policy and resets consent on a version change", async () => {
  const policy = roadmapPolicySchema.parse({ allowAgentForecast: false });
  const proposal = { policyType: "project_roadmap" as const, expectedProjectUpdatedAt: "2026-10-05T00:00:00.000Z", policy: { ...policy, allowAgentForecast: true } };
  const rows = ["one", "two"].map(id => ({ id, companyId: "company", targetId: "project", version: 1, status: "pending", policyType: proposal.policyType, proposal, baseline: { ...proposal, policy }, reason: "Allow bounded forecasting", reviewedBy: null, reviewRationale: null }));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: Infinity } } });
  vi.mocked(learningApi.policies).mockResolvedValue(rows);
  client.setQueryData(["learning-policies", "company", "user:fixture-user"], rows);
  container = document.createElement("div"); document.body.append(container); root = createRoot(container);
  const Scoped = withV7AccountScope(() => <LearningPolicyReview companyId="company" />);
  await act(async () => root!.render(<QueryClientProvider client={client}><Scoped /></QueryClientProvider>));
  const buttons = () => Array.from(container!.querySelectorAll("button")).filter(button => button.textContent === "Accept policy change");
  expect(container.textContent).toContain("Disabled → Allowed");
  expect(buttons().every(button => button.disabled)).toBe(true);
  await act(async () => {
    const input = container!.querySelector("input:not([type=checkbox])")!;
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "Reviewed the exact proposed policy and its safety implications.");
    input.dispatchEvent(new Event("input", { bubbles: true }));
    (container!.querySelector("input[type=checkbox]") as HTMLInputElement).click();
  });
  expect(buttons()[0]!.disabled).toBe(false);
  expect(buttons()[1]!.disabled).toBe(true);
  vi.mocked(learningApi.reviewPolicy).mockResolvedValue(rows[0]!);
  await act(async () => buttons()[0]!.click());
  expect(learningApi.reviewPolicy).toHaveBeenCalledWith("company", "one", expect.objectContaining({ expectedVersion: 1, acknowledgeApprovalOrSecurityChange: true, decision: "accept" }));
  await act(async () => { await client.cancelQueries({ queryKey: ["learning-policies", "company", "user:fixture-user"] }); client.setQueryData(["learning-policies", "company", "user:fixture-user"], [{ ...rows[0], version: 2 }, rows[1]]); await new Promise(resolve => setTimeout(resolve, 10)); });
  expect(buttons()[0]!.disabled).toBe(true);
  expect((container.querySelector("input[type=checkbox]") as HTMLInputElement).checked).toBe(false);
});
