import type { ManagementReviewView } from "@paperclipai/shared";
import { BusinessExperimentResult } from "./BusinessExperimentResult";
import { CausalClaimResult } from "./CausalClaimResult";
const human = (value: string) => value.replace(/([a-z])([A-Z])/g, "$1 $2").replaceAll("_", " ");
const grades = { native_observation: "Observed native measure", native_current_state: "Current native state", predictive: "Prediction", conditional_scenario: "Conditional scenario", human_interpreted_experiment: "Human-interpreted experiment", conditional_causal: "Conditional causal interpretation", native_outcome_review: "Native outcome review", native_learning_cycle: "Verified-task Learning cycle" };
export function ManagementReviewResult({ review }: { review: ManagementReviewView }) {
  const stale = review.currentQualification !== "current";
  return <section aria-label="Cited management review" className="min-w-0 space-y-5">
    <header className="space-y-2"><h2 className="text-lg font-semibold">{review.definition.name}</h2><p>{human(review.definition.reviewType)} · {review.status} · captured {new Date(review.packet.asOf).toLocaleString()}</p><p>Review period: {review.packet.period.from} to {review.packet.period.until}.</p></header>
    {stale && <p role="status">Retained historical review: current sources changed. Original facts remain visible; capture and review a fresh packet before publication or current reliance.</p>}
    <p>Coverage: explicitly selected native sources. The agenda and hypotheses are human declarations; these citations do not establish a complete company review.</p>
    <section aria-label="Cited evidence" className="min-w-0 space-y-4"><h3 className="font-semibold">Cited evidence</h3>{review.packet.claims.map(claim => { const source = review.sources.find(source => claim.sourceKeys.includes(source.key)), analytical = source?.analytical; return <article id={`management-source-${source?.key ?? claim.key}`} key={claim.key} className="min-w-0 space-y-3 rounded-md border p-3">
      <h4 className="font-medium">{human(source?.key ?? claim.key)} · {grades[claim.grade]}</h4><dl className="space-y-2">{Object.entries(claim.facts).filter(([key]) => !/(Id|Hash)$/.test(key)).map(([key, value]) => <div key={key}><dt className="text-muted-foreground">{human(key)}</dt><dd className="break-words">{value === null ? "Unknown / not established" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value)}</dd></div>)}</dl>
      {analytical?.causal && <details><summary className="cursor-pointer">Original causal model and human review</summary><div className="space-y-3 pt-3"><p>{analytical.causal.definition.question}</p><p>Human hypothesis: {analytical.causal.definition.humanHypothesis}</p><p>Human graph review: {analytical.causal.review.rationale}</p><CausalClaimResult run={stale ? { ...analytical.causal.run, currentQualification: "needs_revalidation" } : analytical.causal.run} /><ul className="list-disc space-y-2 pl-5">{Object.entries(analytical.causal.definition.assumptions).map(([key, assumption]) => <li key={key}>{human(key)}: {assumption.status}. {assumption.rationale}</li>)}</ul></div></details>}
      {analytical?.experiment && <details><summary className="cursor-pointer">Original registered experiment and interpretation</summary><div className="pt-3"><BusinessExperimentResult analysis={analytical.experiment.analysis} definition={analytical.experiment.registeredMetrics} interpretation={analytical.experiment.interpretation} /></div></details>}
      <ul className="list-disc space-y-2 pl-5">{claim.limitations.map(limit => <li key={limit}>{limit}</li>)}</ul>
      {source && <details><summary className="cursor-pointer">Inspect source provenance</summary><div className="space-y-2 pt-3 text-sm"><p>Source kind: {human(source.source.kind)}{source.source.kind === "analytical" || source.source.kind === "canonical" ? ` · ${human(source.source.reference.type)}` : ""}</p><p>Captured {source.capturedAt}; retention until {source.expiresAt}.</p><p className="break-all">Source hash {source.sourceHash}</p></div></details>}
    </article>; })}</section>
    <section aria-label="Human decision agenda" className="space-y-3"><h3 className="font-semibold">Human decision agenda</h3><ol className="list-decimal space-y-4 pl-5">{review.packet.agenda.map(item => <li key={item.key} className="min-w-0 space-y-2"><h4 className="font-medium">{human(item.category)} · {human(item.key)}</h4><p>Owner: {item.ownerUserId} · due {new Date(item.dueAt).toLocaleString()}.</p><p>Human proposed next action: {item.nextAction}</p><p>Evidence: {item.sourceKeys.map((key, index) => <span key={key}>{index ? ", " : ""}<a className="underline" href={`#management-source-${key}`}>{human(key)}</a></span>)}</p>{item.hypothesis && <p>Human hypothesis, unverified: {item.hypothesis}</p>}</li>)}</ol></section>
    {!!review.events.length && <section aria-label="Reported review events" className="space-y-3"><h3 className="font-semibold">Reported review events</h3><p>These signed human reports do not verify an intervention, result or executive performance.</p><ol className="list-decimal space-y-3 pl-5">{review.events.map(event => <li key={event.id}>{human(event.event)} · {human(event.itemKey)}. {event.rationale}<p>Reported by {event.recordedBy} · {new Date(event.recordedAt).toLocaleString()}.</p></li>)}</ol></section>}
    <ul className="list-disc space-y-2 pl-5">{review.packet.limitations.map(limit => <li key={limit}>{limit}</li>)}</ul>
    <details><summary className="cursor-pointer">Inspect review provenance and retention</summary><div className="space-y-2 pt-3 text-sm"><p>Created by {review.createdBy}; retention until {review.expiresAt}. Classification: {review.definition.sensitivity}.</p>{review.publishedAt && <p>Published by {review.publishedBy} · {review.publishedAt}.</p>}<p className="break-all">Content hash {review.packet.contentHash}</p><p className="break-all">Input hash {review.packet.inputHash}</p></div></details>
  </section>;
}
