import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { managementReviewDefinitionSchema, type ManagementReviewDefinition, type ManagementReviewSource } from "@paperclipai/shared";
import { aiGovernanceApi } from "@/api/ai-governance";
import { ManagementReviewSourcePicker } from "./ManagementReviewSourcePicker";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
const selectStyle = "w-full min-w-0 rounded-md border border-input bg-background p-2";
const utc = (value: string) => value && Number.isFinite(Date.parse(`${value}Z`)) ? new Date(`${value}Z`).toISOString() : "";
export function ManagementReviewDefinitionForm({ companyId, userId, busy, onSave, onCancel, onAuthorityLost }: { companyId: string; userId: string | null; busy: boolean; onSave: (definition: ManagementReviewDefinition) => void; onCancel: () => void; onAuthorityLost: () => void }) {
  const [definition, setDefinition] = useState<Omit<ManagementReviewDefinition, "sources">>(() => ({ name: "", reviewType: "ad_hoc", period: { from: "", until: "" }, purpose: "management_intelligence", sensitivity: "internal", retentionDays: 30, governanceObligationRefs: [], agenda: [{ key: "agenda_1", category: "INVESTIGATE", ownerUserId: userId ?? "local-board", dueAt: "", sourceKeys: ["source_1"], nextAction: "", hypothesis: null }] }));
  const [sources, setSources] = useState<Array<{ key: string; source: ManagementReviewSource | null; valid: boolean }>>([{ key: "source_1", source: null, valid: false }]), [sequence, setSequence] = useState(2);
  const policies = useQuery({ queryKey: ["management-definition-sources", companyId, userId, "purpose"], queryFn: () => aiGovernanceApi.obligations(companyId, userId ?? undefined), retry: false, refetchInterval: 30000 });
  useEffect(() => { if (policies.isError) onAuthorityLost(); }, [policies.isError, onAuthorityLost]);
  const unavailable = policies.isFetching || policies.isPending || policies.isError, approved = !unavailable ? policies.data?.filter(policy => policy.companyId === companyId && policy.obligation.framework === "company_policy" && policy.obligation.analyticalPurpose?.status === "approved" && policy.obligation.analyticalPurpose.purpose === "management_intelligence" && policy.obligation.analyticalPurpose.capabilities.includes("reviews")) ?? [] : [];
  const parsed = managementReviewDefinitionSchema.safeParse({ ...definition, sources: sources.map(({ key, source }) => ({ key, source })) }), valid = !unavailable && sources.every(source => !!source.source && source.valid) && parsed.success && definition.governanceObligationRefs.every(id => approved.some(policy => policy.id === id));
  const update = <K extends keyof typeof definition>(key: K, value: typeof definition[K]) => setDefinition(previous => ({ ...previous, [key]: value }));
  const agenda = (index: number, value: Partial<ManagementReviewDefinition["agenda"][number]>) => update("agenda", definition.agenda.map((item, i) => i === index ? { ...item, ...value } : item));
  return <form aria-label="Cited management review proposal" className="min-w-0 space-y-5" onSubmit={event => { event.preventDefault(); if (valid && parsed.success) onSave(parsed.data); }}><fieldset disabled={busy} className="min-w-0 space-y-5"><legend className="text-lg font-semibold">Capture a cited review draft</legend><p>Choose exact current native sources and an explicit human agenda. Saving captures historical evidence; publication requires a separate human review.</p>
    <label className="block space-y-2">Review name<Input aria-label="Review name" value={definition.name} minLength={3} maxLength={200} required onChange={event => update("name", event.target.value)} /></label>
    <label className="block space-y-2">Review type<select aria-label="Review type" className={selectStyle} value={definition.reviewType} onChange={event => update("reviewType", event.target.value as typeof definition.reviewType)}>{["daily_operational", "weekly_leadership", "monthly_business", "quarterly_strategy", "ad_hoc"].map(type => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><p className="text-sm text-muted-foreground">Review type describes this packet. Scheduling uses an explicitly configured Routine.</p>
    {(["from", "until"] as const).map((key, index) => <label key={key} className="block space-y-2">{index ? "Review period end (UTC)" : "Review period start (UTC)"}<Input aria-label={index ? "Review period end (UTC)" : "Review period start (UTC)"} type="datetime-local" step="1" required value={definition.period[key].replace(/Z$/, "")} onChange={event => update("period", { ...definition.period, [key]: utc(event.target.value) })} /></label>)}
    <section aria-label="Declared review sources" className="min-w-0 space-y-4"><h3 className="font-semibold">Native source citations</h3>{sources.map((source, index) => <div key={source.key} className="min-w-0 space-y-3 rounded-md border p-3"><ManagementReviewSourcePicker companyId={companyId} userId={userId} name={`Source ${index + 1}`} value={source.source} onChange={value => setSources(rows => rows.map(row => row.key === source.key ? { ...row, source: value, valid: false } : row))} onValidity={valid => setSources(rows => rows.some(row => row.key === source.key && row.valid !== valid) ? rows.map(row => row.key === source.key ? { ...row, valid } : row) : rows)} onAuthorityLost={onAuthorityLost} /><p>Citation label: {source.key}</p>{sources.length > 1 && <Button type="button" variant="ghost" onClick={() => { setSources(rows => rows.filter(row => row.key !== source.key)); update("agenda", definition.agenda.map(item => ({ ...item, sourceKeys: item.sourceKeys.filter(key => key !== source.key) }))); }}>Remove source {index + 1}</Button>}</div>)}<Button type="button" variant="outline" disabled={sources.length >= 20} onClick={() => { setSources(rows => [...rows, { key: `source_${sequence}`, source: null, valid: false }]); setSequence(sequence + 1); }}>Add native source</Button></section>
    <section aria-label="Declared human review agenda" className="min-w-0 space-y-4"><h3 className="font-semibold">Human decision agenda</h3><p>Order is your declaration. Each action needs a current human owner, due date and source citation.</p>{definition.agenda.map((item, index) => <fieldset key={item.key} className="min-w-0 space-y-3 rounded-md border p-3"><legend className="font-medium">Agenda {index + 1}</legend><label className="block space-y-2">Category<select aria-label={`Agenda ${index + 1} category`} className={selectStyle} value={item.category} onChange={event => agenda(index, { category: event.target.value as typeof item.category })}>{["DECISION_REQUIRED", "INVESTIGATE", "APPROVAL_REQUIRED", "AT_RISK", "NO_ACTION"].map(category => <option key={category} value={category}>{category.replaceAll("_", " ")}</option>)}</select></label>
      <label className="block space-y-2">Human owner<Input aria-label={`Agenda ${index + 1} human owner`} value={item.ownerUserId} required maxLength={300} onChange={event => agenda(index, { ownerUserId: event.target.value })} /></label><label className="block space-y-2">Due date (UTC)<Input aria-label={`Agenda ${index + 1} due date (UTC)`} type="datetime-local" step="1" value={item.dueAt.replace(/Z$/, "")} required onChange={event => agenda(index, { dueAt: utc(event.target.value) })} /></label>
      <fieldset className="space-y-2"><legend>Evidence citations</legend>{sources.map(source => <label key={source.key} className="flex items-start gap-2"><input type="checkbox" checked={item.sourceKeys.includes(source.key)} onChange={event => agenda(index, { sourceKeys: event.target.checked ? [...item.sourceKeys, source.key] : item.sourceKeys.filter(key => key !== source.key) })} />{source.key}</label>)}</fieldset>
      <label className="block space-y-2">Proposed next action<Textarea aria-label={`Agenda ${index + 1} proposed next action`} value={item.nextAction} minLength={10} maxLength={2000} required onChange={event => agenda(index, { nextAction: event.target.value })} /></label><label className="block space-y-2">Optional unverified human hypothesis<Textarea aria-label={`Agenda ${index + 1} human hypothesis`} value={item.hypothesis ?? ""} maxLength={2000} onChange={event => agenda(index, { hypothesis: event.target.value || null })} /></label>
      {definition.agenda.length > 1 && <Button type="button" variant="ghost" onClick={() => update("agenda", definition.agenda.filter((_, i) => i !== index))}>Remove agenda {index + 1}</Button>}</fieldset>)}<Button type="button" variant="outline" disabled={definition.agenda.length >= 10} onClick={() => { update("agenda", [...definition.agenda, { key: `agenda_${sequence}`, category: "INVESTIGATE", ownerUserId: userId ?? "local-board", dueAt: "", sourceKeys: [], nextAction: "", hypothesis: null }]); setSequence(sequence + 1); }}>Add human agenda item</Button></section>
    <section aria-label="Explicit native metric comparisons" className="space-y-3"><h3 className="font-semibold">Optional cited metric comparisons</h3><p>Choose the exact target and observation, or two observations in consecutive equal windows. Open, missing or incompatible measurements stay unknown; forecasts cannot substitute for actuals.</p>{(definition.comparisons ?? []).map((comparison, index) => <fieldset key={comparison.key} className="min-w-0 space-y-3 rounded-md border p-3"><legend>Comparison {index + 1}</legend><label className="block space-y-2">Comparison kind<select aria-label={`Comparison ${index + 1} kind`} className={selectStyle} value={comparison.kind} onChange={event => update("comparisons", definition.comparisons!.map((item, i) => i === index ? { ...item, kind: event.target.value as typeof item.kind, leftSourceKey: "", rightSourceKey: "" } : item))}><option value="target_actual">Actual against approved commitment</option><option value="metric_change">Descriptive change between two cited windows</option></select></label>{(["leftSourceKey", "rightSourceKey"] as const).map((key, position) => <label key={key} className="block space-y-2">{position ? "Actual / later observation" : comparison.kind === "target_actual" ? "Approved target" : "Earlier observation"}<select aria-label={`Comparison ${index + 1} ${position ? "right" : "left"} source`} className={selectStyle} value={comparison[key]} onChange={event => update("comparisons", definition.comparisons!.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item))}><option value="">Choose an exact declared citation</option>{sources.filter(source => { const ref = source.source?.kind === "analytical" || source.source?.kind === "canonical" ? source.source.reference : null; return position === 0 && comparison.kind === "target_actual" ? source.source?.kind === "canonical" && ref?.type === "metric_target" : ref?.type === "metric_observation"; }).map(source => <option key={source.key} value={source.key}>{source.key}</option>)}</select></label>)}<Button type="button" variant="ghost" onClick={() => update("comparisons", definition.comparisons!.filter((_, i) => i !== index))}>Remove comparison {index + 1}</Button></fieldset>)}<Button type="button" variant="outline" disabled={(definition.comparisons?.length ?? 0) >= 20} onClick={() => { update("comparisons", [...(definition.comparisons ?? []), { key: `measure_${sequence}`, kind: "target_actual", leftSourceKey: "", rightSourceKey: "" }]); setSequence(sequence + 1); }}>Add cited metric comparison</Button></section>
    <label className="block space-y-2">Approved review purpose<select aria-label="Approved review purpose" className={selectStyle} value={definition.governanceObligationRefs[0] ?? ""} required onChange={event => update("governanceObligationRefs", event.target.value ? [event.target.value] : [])}><option value="">Choose a current company policy</option>{approved.map(policy => <option key={policy.id} value={policy.id}>{policy.obligation.citation}</option>)}</select></label>
    <label className="block space-y-2">Sensitivity<select aria-label="Review sensitivity" className={selectStyle} value={definition.sensitivity} onChange={event => update("sensitivity", event.target.value as "internal" | "confidential")}><option value="internal">Internal</option><option value="confidential">Confidential</option></select></label><label className="block space-y-2">Retention (days)<Input aria-label="Review retention (days)" type="number" min={1} max={365} required value={definition.retentionDays} onChange={event => update("retentionDays", event.target.value ? Number(event.target.value) : NaN)} /></label>
  </fieldset>{unavailable && <p role="status">Rechecking approved review purpose…</p>}{!valid && <p>Complete the review period, current native sources and every cited human agenda item. Unknown or unavailable sources cannot be saved.</p>}<div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy || !valid}>Capture management review draft</Button><Button type="button" variant="ghost" disabled={busy} onClick={onCancel}>Cancel review draft</Button></div></form>;
}
