// @vitest-environment jsdom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { instanceExperimentalSettingsSchema } from "@paperclipai/shared";
import { ProjectAdaptivePlanning } from "./ProjectAdaptivePlanning";
import { adaptivePlanningApi } from "@/api/adaptive-planning";
import { instanceSettingsApi } from "@/api/instanceSettings";
import { aiGovernanceApi } from "@/api/ai-governance";
import { planningFixture } from "../../storybook/stories/project-planning-fixtures";
const identity=vi.hoisted(()=>({userId:"human",settled:true,failed:false}));
vi.mock("@/api/companies-query",()=>({useAccountIdentity:()=>identity}));
vi.mock("@/api/adaptive-planning",()=>({adaptivePlanningApi:{source:vi.fn(),preview:vi.fn(),propose:vi.fn(),controls:vi.fn(),detail:vi.fn(),review:vi.fn(),recordOutcome:vi.fn(),outcome:vi.fn()}}));
vi.mock("@/lib/router",()=>({Link:({children,to,...props}:{children:React.ReactNode;to:string})=><a href={to} {...props}>{children}</a>}));
vi.mock("@/api/instanceSettings",()=>({instanceSettingsApi:{getExperimental:vi.fn()}}));
vi.mock("@/api/ai-governance",()=>({aiGovernanceApi:{obligations:vi.fn()}}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const flush=async()=>{await act(async()=>{await new Promise(resolve=>setTimeout(resolve,30));});};
async function mount(){const f=planningFixture(),client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),container=document.createElement("div");document.body.append(container);const root=createRoot(container);const render=async()=>{await act(async()=>root.render(<QueryClientProvider client={client}><ProjectAdaptivePlanning companyId={f.companyId} projectId={f.projectId}/></QueryClientProvider>));await flush();};await render();return {client,container,render,cleanup:async()=>{await act(async()=>root.unmount());client.clear();container.remove();}};}
async function click(node:HTMLElement,label:string){const find=()=>[...node.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label);for(let i=0;i<25&&(!find()||find()!.disabled);i++)await flush();expect(find(),label).toBeDefined();expect(find()!.disabled,label).toBe(false);await act(async()=>find()!.click());await flush();}
async function field(node:HTMLElement,label:string,value:string){await act(async()=>{const input=node.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(input,label).toBeDefined();if(input instanceof HTMLSelectElement){input.value=value;input.dispatchEvent(new Event("change",{bubbles:true}));}else {Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));}});await flush();}
async function declarations(node:HTMLElement){const f=planningFixture();await click(node,"Declare a project planning problem");await field(node,"Demand for Prepare source evidence","120");await field(node,"Declaration rationale for Prepare source evidence","Human supplies explicit assumptions with remaining uncertainty");await field(node,"Approved planning purpose",f.policy.id);}
beforeEach(()=>{vi.resetAllMocks();const f=planningFixture();identity.userId=f.userId;identity.settled=true;identity.failed=false;vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(f.flags);vi.mocked(aiGovernanceApi.obligations).mockResolvedValue([f.policy]);vi.mocked(adaptivePlanningApi.source).mockResolvedValue(f.roadmap);vi.mocked(adaptivePlanningApi.controls).mockResolvedValue({proposals:[{id:f.id,status:"pending"}],nextCursor:null,hasMore:false});vi.mocked(adaptivePlanningApi.detail).mockResolvedValue(f.detail);vi.mocked(adaptivePlanningApi.preview).mockResolvedValue(f.response);vi.mocked(adaptivePlanningApi.propose).mockResolvedValue(f.detail);vi.mocked(adaptivePlanningApi.review).mockResolvedValue({id:f.id,companyId:f.companyId,projectId:f.projectId,status:"accepted",updatedAt:"2026-10-07T00:00:00Z"});});
describe("Native planning operator authority",()=>{
 it("records completion for an accepted baseline and withholds feedback during a denied source recheck",async()=>{
  const f=planningFixture(),manifestId="00000000-0000-4000-8000-000000007010";
  vi.mocked(adaptivePlanningApi.controls).mockResolvedValue({proposals:[{id:f.id,status:"accepted"}],nextCursor:null,hasMore:false});
  vi.mocked(adaptivePlanningApi.detail).mockResolvedValue({...f.detail,status:"accepted",currentQualification:"needs_revalidation"});
  const outcome={companyId:f.companyId,projectId:f.projectId,proposalId:f.id,contextHash:f.detail.contextHash,recordedBy:f.userId,recordedAt:new Date().toISOString(),expiresAt:f.detail.context.expiresAt,rationale:"Reviewed actual native completion; causal impact remains unknown",tasks:[{issueId:f.taskId,updatedAt:new Date().toISOString(),completedAt:new Date().toISOString(),plannedEndAt:"2099-10-10T00:00:00.000Z",completionDeltaDays:-1}],authority:"supplemental_descriptive_signal" as const,causalClaimRef:null};
  vi.mocked(adaptivePlanningApi.recordOutcome).mockResolvedValue({manifestId,outcome});vi.mocked(adaptivePlanningApi.outcome).mockResolvedValue({manifestId,outcome});
  const app=await mount();try{
   await field(app.container,"Planning proposal reference",f.id);
   expect(app.container.textContent).toContain("Review observed plan completion");
   await field(app.container,"Planning outcome review rationale",outcome.rationale);await click(app.container,"Record observed planning outcome");await flush();
   expect(adaptivePlanningApi.recordOutcome).toHaveBeenCalledWith(f.companyId,f.projectId,f.id,outcome.rationale,f.userId);
   expect(app.container.querySelector<HTMLAnchorElement>('a[href*="planningManifestId"]')!.href).toContain(manifestId);
   vi.mocked(adaptivePlanningApi.outcome).mockRejectedValue(new Error("Current source denied"));
   await act(async()=>{await app.client.invalidateQueries({queryKey:["project-adaptive-planning",f.companyId,f.projectId,f.userId,"outcome"]});});await flush();
   expect(app.container.textContent).not.toContain(outcome.rationale);expect(app.container.querySelector('a[href*="planningManifestId"]')).toBeNull();
  }finally{await app.cleanup();}
 });
 it("keeps unknown durations and capacity explicit and never invents zero task demand",async()=>{const f=planningFixture();vi.mocked(adaptivePlanningApi.preview).mockResolvedValue({...f.response,result:{...f.result,status:"inconclusive",schedule:[],criticalPath:null,diagnostics:[{code:"unknown_duration",taskKeys:[f.taskId],poolKeys:[]}]}});const app=await mount();try{await click(app.container,"Declare a project planning problem");await field(app.container,"Declaration rationale for Prepare source evidence","Human supplies explicit assumptions with remaining uncertainty");await field(app.container,"Approved planning purpose",f.policy.id);const inspect=()=>[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Inspect constraints and proposed schedule")!;expect(inspect().disabled).toBe(true);await field(app.container,"Demand for Prepare source evidence","120");await click(app.container,"Inspect constraints and proposed schedule");expect(adaptivePlanningApi.preview).toHaveBeenCalledWith(f.companyId,f.projectId,expect.objectContaining({tasks:[expect.objectContaining({key:f.taskId,durationDays:null,demands:[{poolKey:"declared_project_capacity",minutesPerDay:120}]})],pools:[expect.objectContaining({days:expect.arrayContaining([{availableMinutes:null,committedMinutes:null}])})]}),f.userId);expect(app.container.textContent).toContain("Inconclusive");expect([...app.container.querySelectorAll("button")].some(button=>button.textContent==="Create pending planning proposal")).toBe(false);expect(adaptivePlanningApi.propose).not.toHaveBeenCalled();expect(adaptivePlanningApi.review).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("pins the exact inspected profile and invalidates the proposal after a human amendment",async()=>{const f=planningFixture(),app=await mount();try{await declarations(app.container);await field(app.container,"Duration for Prepare source evidence","2");await field(app.container,"Available minutes per day (empty = unknown)","480");await field(app.container,"Already committed minutes per day (empty = unknown)","60");await click(app.container,"Inspect constraints and proposed schedule");await field(app.container,"Duration for Prepare source evidence","3");expect(app.container.querySelector('[aria-label="Declared planning constraint result"]')).toBeNull();await click(app.container,"Inspect constraints and proposed schedule");await field(app.container,"Reason for this pending Roadmap proposal","Human proposes these exact assumptions for independent review");await click(app.container,"Create pending planning proposal");const profile=vi.mocked(adaptivePlanningApi.preview).mock.calls.at(-1)![2];expect(adaptivePlanningApi.propose).toHaveBeenCalledWith(f.companyId,f.projectId,{profile,expectedSnapshotHash:f.response.snapshotHash,reason:expect.any(String)},f.userId);expect(adaptivePlanningApi.review).not.toHaveBeenCalled();}finally{await app.cleanup();}});
 it("requires a separate exact human acknowledgement before canonical acceptance",async()=>{const f=planningFixture(),app=await mount();try{await field(app.container,"Planning proposal reference",f.id);const approve=()=>[...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Approve committed planning dates")!;expect(approve().disabled).toBe(true);await field(app.container,"Separate human planning review rationale","Human independently reviews the original source and proposed intervals");expect(approve().disabled).toBe(true);await act(async()=>app.container.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await click(app.container,"Approve committed planning dates");expect(adaptivePlanningApi.review).toHaveBeenCalledWith(f.companyId,f.projectId,f.id,true,expect.any(String),f.userId);}finally{await app.cleanup();}});
 it("preserves changed-source calculation numbers while withholding current acceptance",async()=>{const f=planningFixture(true);vi.mocked(adaptivePlanningApi.detail).mockResolvedValue(f.detail);const app=await mount();try{await field(app.container,"Planning proposal reference",f.id);expect(app.container.textContent).toContain("Retained feasible calculation");expect(app.container.textContent).toContain("2099-10-10");expect([...app.container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Approve committed planning dates")!.disabled).toBe(true);}finally{await app.cleanup();}});
 it("allows metadata-only rejection with the feature disabled without fetching inherited source",async()=>{const f=planningFixture();vi.mocked(instanceSettingsApi.getExperimental).mockResolvedValue(instanceExperimentalSettingsSchema.parse({}));const app=await mount();try{expect(adaptivePlanningApi.source).not.toHaveBeenCalled();await field(app.container,"Planning proposal reference",f.id);await field(app.container,"Separate human planning review rationale","Human rejects this pending proposal while planning is disabled");await click(app.container,"Reject this planning proposal");expect(adaptivePlanningApi.review).toHaveBeenCalledWith(f.companyId,f.projectId,f.id,false,expect.any(String),f.userId);expect(adaptivePlanningApi.detail).not.toHaveBeenCalled();expect(app.container.textContent).not.toContain(f.detail.reason);}finally{await app.cleanup();}});
 it("withholds human assumptions and clears source caches on Memory access loss",async()=>{const f=planningFixture(),app=await mount();try{await declarations(app.container);await field(app.container,"Declaration rationale for Prepare source evidence","Private human planning rationale must disappear");app.client.setQueryData(["decision-evidence",f.companyId,f.userId,"private"],{text:"private source"});await act(async()=>window.dispatchEvent(new Event("memory-access-changed")));await flush();expect(app.container.querySelector('[aria-label="Declared project planning assumptions"]')).toBeNull();expect(app.container.textContent).not.toContain("Prepare source evidence");expect(app.client.getQueriesData({queryKey:["decision-evidence",f.companyId,f.userId]})).toHaveLength(0);}finally{await app.cleanup();}});
 it("clears the old account proposal when the verified human account changes",async()=>{const f=planningFixture(),app=await mount();try{await field(app.container,"Planning proposal reference",f.id);identity.userId="different-human";vi.mocked(adaptivePlanningApi.source).mockRejectedValue(new Error("Current account denied"));await app.render();await flush();expect(app.container.textContent).not.toContain(f.detail.reason);expect(app.container.querySelector('[aria-label="Declared planning constraint result"]')).toBeNull();}finally{await app.cleanup();}});
});
