import type { ProjectPlanningDetail } from "@/api/adaptive-planning";
import { CausalClaimResult } from "./CausalClaimResult";
import { BusinessExperimentResult } from "./BusinessExperimentResult";
const humanLabel=(name:string)=>name.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ");
export function ProjectPlanningBasis({detail,taskLabels}:{detail:Pick<ProjectPlanningDetail,"currentQualification"|"contextHash"> & {context:Pick<ProjectPlanningDetail["context"],"profile"|"evidence"|"capturedAt"|"expiresAt">};taskLabels:Record<string,string>}){
 const {profile,evidence}=detail.context;
 return <details className="min-w-0 space-y-3"><summary className="cursor-pointer font-medium">Original human declarations and evidence</summary>
  <p>Captured {detail.context.capturedAt}; retention until {detail.context.expiresAt}. Classification: {profile.sensitivity}.</p>
  <section aria-label="Original declared task assumptions" className="space-y-3"><h4 className="font-medium">Original declared task assumptions</h4><ul className="list-disc space-y-3 pl-5">{profile.tasks.map(task=><li key={task.key}>{taskLabels[task.key]??"Retained task reference"} · duration {task.durationDays??"unknown"} days · release offset {task.releaseDay} · completion offset {task.deadlineDay??"horizon"} · {task.mandatoryCommitment?"mandatory commitment":"required task"}. {task.rationale}{!task.demands.length&&<p>Explicitly declared no demand on supplied pools.</p>}<ul className="list-disc pl-5">{task.demands.map(demand=><li key={demand.poolKey}>{humanLabel(demand.poolKey)}: {demand.minutesPerDay} minutes per day</li>)}</ul><dl>{Object.entries(task.dimensions).map(([key,value])=><div key={key}><dt>{humanLabel(key)}</dt><dd>{value??"Unknown"}</dd></div>)}</dl></li>)}</ul></section>
  <section aria-label="Original declared daily capacity" className="space-y-3"><h4 className="font-medium">Original declared daily capacity</h4>{profile.pools.map(pool=><div key={pool.key} className="overflow-x-auto rounded-md border"><table className="w-full text-left text-sm"><caption className="p-2 text-left">{humanLabel(pool.key)} · UTC day offsets from {profile.horizon.start}; capacity declarations do not grant execution budget.</caption><thead><tr><th className="p-2">Day offset</th><th className="p-2">Available minutes</th><th className="p-2">Committed minutes</th></tr></thead><tbody>{pool.days.map((day,index)=><tr key={index} className="border-t"><th className="p-2 font-normal">{index}</th><td className="p-2">{day.availableMinutes??"Unknown"}</td><td className="p-2">{day.committedMinutes??"Unknown"}</td></tr>)}</tbody></table></div>)}</section>
  <section aria-label="Captured planning evidence" className="min-w-0 space-y-3"><h4 className="font-medium">Captured planning evidence</h4>{!evidence.length&&<p>No quantitative source evidence was declared. The plan uses explicit human assumptions.</p>}{evidence.map(item=><div className="min-w-0 space-y-3 rounded-md border p-3" key={item.key}><p>{item.source.type.replaceAll("_"," ")} · {profile.evidence.find(ref=>ref.key===item.key)?.rationale}</p><p>Captured {item.capturedAt}; source retention until {item.expiresAt}.</p>
  {item.causal?<section className="space-y-3"><p>{item.causal.definition.question}</p><p>{item.causal.definition.humanHypothesis}</p><p>Human graph review: {item.causal.review.rationale}</p><CausalClaimResult run={detail.currentQualification==="current"?item.causal.run:{...item.causal.run,currentQualification:"needs_revalidation"}}/><details><summary className="cursor-pointer">Captured human graph and assumptions</summary><ul className="list-disc space-y-2 pl-5">{item.causal.definition.graph.edges.map((edge,index)=><li key={index}>{item.causal!.definition.graph.nodes.find(node=>node.key===edge.from)?.label} → {item.causal!.definition.graph.nodes.find(node=>node.key===edge.to)?.label} · human assumption. {edge.rationale}</li>)}</ul><ul className="list-disc space-y-2 pl-5">{Object.entries(item.causal.definition.assumptions).map(([key,assumption])=><li key={key}>{humanLabel(key)} · {assumption.status}: {assumption.rationale}</li>)}</ul></details></section>:item.experiment?<BusinessExperimentResult analysis={item.experiment.analysis} definition={item.experiment.registeredMetrics} interpretation={item.experiment.interpretation}/>:<dl className="space-y-2">{Object.entries(item.facts).filter(([key])=>!/(Id|Hash)$/.test(key)).map(([key,value])=><div key={key}><dt className="text-muted-foreground">{humanLabel(key)}</dt><dd className="break-words">{value??"Not established"}</dd></div>)}</dl>}
  <ul className="list-disc space-y-2 pl-5">{item.limitations.map(limit=><li key={limit}>{limit}</li>)}</ul><details><summary className="cursor-pointer">Inspect captured planning provenance</summary><p className="break-all">Native source {item.source.id}</p><p className="break-all">Source hash {item.sourceHash}</p><p className="break-all">Planning context {detail.contextHash}</p></details></div>)}</section>
 </details>;
}
