import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "@/api/client";
import { v5Api } from "@/api/v5";
import { useCompany } from "@/context/CompanyContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { V5Error } from "@/components/V5Gate";

interface Report { checks: Record<string, boolean>; requiredChecks: string[]; runIds: string[]; spentCents: number | null; failure: string | null; binding: { status: string } }
export function ProviderConformanceControls({ companyId, agentId, identityId, onTested }: { companyId: string; agentId: string; identityId: string; onTested: () => void }) {
  const { companies } = useCompany(), [peerCompanyId, setPeerCompanyId] = useState(""), [costCeiling, setCostCeiling] = useState("100"), [acknowledged, setAcknowledged] = useState(false);
  const peers = useQuery({ queryKey: ["v5-conformance-peer", peerCompanyId], queryFn: () => v5Api.identities(peerCompanyId), enabled: Boolean(peerCompanyId) }), peer = peers.data?.find((entry) => entry.id === identityId);
  const run = useMutation({ mutationFn: () => api.post<Report>(`/companies/${companyId}/agents/${agentId}/provider-binding/conformance`, { acknowledgeProviderRuns: true, maximumCostCents: Number(costCeiling), isolationPeer: peer ? { companyId: peerCompanyId, agentId: peer.agentId } : null }), onSuccess: onTested });
  return <details className="space-y-3 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Test provider behavior and profile isolation</summary><V5Error error={peers.error ?? run.error} /><p className="text-sm text-muted-foreground">This starts and cancels synthetic provider runs, retains their traces and records reported costs. Isolation tests require another configured profile of this identity on the same endpoint. Unknown costs stop further probes; a single provider call may exceed the ceiling before its cost is reported.</p><div className="flex flex-wrap gap-3"><label className="space-y-1 text-sm"><span className="block">Explicit isolation peer company</span><select className="rounded-md border bg-background p-2" value={peerCompanyId} onChange={(event) => setPeerCompanyId(event.target.value)}><option value="">No peer (isolation remains unproven)</option>{companies.filter((company) => company.id !== companyId).map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Stop further probes at reported cost (cents)</span><Input type="number" min={1} max={10000} value={costCeiling} onChange={(event) => setCostCeiling(event.target.value)} /></label></div>{peerCompanyId && !peers.isPending && !peer && <p role="status" className="text-sm">This company has no accessible local presence of the selected identity.</p>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} />I authorize these provider test runs and possible charges</label><div className="flex justify-end"><Button variant="outline" disabled={run.isPending || !acknowledged || Number(costCeiling) < 1 || Boolean(peerCompanyId && !peer)} onClick={() => run.mutate()}>{run.isPending ? "Testing provider…" : "Run retained conformance probes"}</Button></div>{run.data && <div className="space-y-2 text-sm"><Badge variant={run.data.binding.status === "active" ? "outline" : "destructive"}>Binding {run.data.binding.status}</Badge>{run.data.failure && <p role="status">{run.data.failure}</p>}<p>Reported total: {run.data.spentCents === null ? "unknown" : `${run.data.spentCents} cents`}</p><ul className="space-y-1">{run.data.requiredChecks.map((check) => <li key={check}>{check}: {run.data!.checks[check] === true ? "pass" : "unproven / failed"}</li>)}</ul><details><summary className="cursor-pointer">Retained probe run IDs</summary><ul className="mt-2 break-all text-xs">{run.data.runIds.map((id) => <li key={id}>{id}</li>)}</ul></details></div>}</details>;
}
