import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import type { RoadmapPolicy as Policy } from "@paperclipai/shared";
import { api } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { V5Error } from "@/components/V5Gate";

export function RoadmapPolicy({ companyId, projectId, policy, onSaved }: { companyId: string; projectId: string; policy: Policy; onSaved: () => Promise<unknown> }) {
  const [value, setValue] = useState(policy);
  const save = useMutation({ mutationFn: () => api.put(`/companies/${companyId}/projects/${projectId}/roadmap/policy`, value), onSuccess: onSaved });
  return <details className="space-y-4 rounded-lg border p-4"><summary className="cursor-pointer font-medium">Planning policy and authoritative fields</summary><p className="text-sm text-muted-foreground">A project administrator owns this policy. Autonomous schedule changes are off by default. External ownership prevents internal writes to the selected fields.</p><V5Error error={save.error} /><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.allowAgentForecast} onChange={(event) => setValue({ ...value, allowAgentForecast: event.target.checked })} />Allow agent forecast updates</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.allowLowRiskAgentScheduleUpdates} onChange={(event) => setValue({ ...value, allowLowRiskAgentScheduleUpdates: event.target.checked })} />Allow low risk agent schedule changes within tolerance</label><label className="space-y-1 text-sm"><span className="block">Schedule tolerance in days</span><Input type="number" min={0} max={14} value={value.scheduleToleranceDays} onChange={(event) => setValue({ ...value, scheduleToleranceDays: Number(event.target.value) })} /></label></div><div className="grid gap-3 md:grid-cols-2">{(Object.keys(value.fieldOwnership) as Array<keyof Policy["fieldOwnership"]>).map((field) => <label key={field} className="space-y-1 text-sm"><span className="block">Owner of {field === "plannedDates" ? "planned dates" : field}</span><select className="w-full rounded-md border bg-background p-2" value={value.fieldOwnership[field]} onChange={(event) => setValue({ ...value, fieldOwnership: { ...value.fieldOwnership, [field]: event.target.value } })}>{(["internal", "external_readonly", "external_authoritative"] as const).map((owner) => <option key={owner} value={owner}>{owner.replaceAll("_", " ")}</option>)}</select></label>)}</div><label className="block space-y-1 text-sm"><span>External source reference</span><Input value={value.externalSourceRef ?? ""} onChange={(event) => setValue({ ...value, externalSourceRef: event.target.value || null })} required={Object.values(value.fieldOwnership).some((owner) => owner !== "internal")} placeholder="jira:project-key" /></label><div className="flex justify-end"><Button disabled={save.isPending}>Save planning policy</Button></div></form></details>;
}
