import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { SkillEvaluationBinding } from "@paperclipai/shared";
import { api } from "@/api/client";
import { agentsApi } from "@/api/agents";
import { companySkillsApi } from "@/api/companySkills";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { V5Error } from "./V5Gate";

interface RunningEvaluation { id: string; suiteId: string; candidateVersionId: string; championVersionId: string | null; trials: number }
export function SkillEvaluationEvidence({ companyId, skillId, evaluation, onRecorded }: { companyId: string; skillId: string; evaluation: RunningEvaluation; onRecorded: () => Promise<unknown> }) {
  const cid = companyId, base = `/companies/${cid}/skills/${skillId}/evaluations`, [agentId, setAgentId] = useState(""), [caseId, setCaseId] = useState(""), [arm, setArm] = useState<"candidate" | "champion">("candidate"), [trial, setTrial] = useState(0), [process, setProcess] = useState(""), [outcome, setOutcome] = useState(""), [safety, setSafety] = useState(false), [rationale, setRationale] = useState("");
  const suite = useQuery({ queryKey: ["v5-eval-suite", cid, skillId, evaluation.suiteId], queryFn: () => api.get<{ cases: Array<{ id: string; name: string; input: string; shouldTrigger: boolean; risk: string }> }>(`${base}/suites/${evaluation.suiteId}`) });
  const agents = useQuery({ queryKey: ["v5-eval-agents", cid], queryFn: () => agentsApi.list(cid) });
  const traces = useQuery({ queryKey: ["v5-eval-traces", cid, skillId, evaluation.id], queryFn: () => companySkillsApi.testRuns(cid, skillId), refetchInterval: 10_000 });
  const selected = suite.data?.cases.find((c) => c.id === caseId), versionId = arm === "candidate" ? evaluation.candidateVersionId : evaluation.championVersionId;
  const trace = traces.data?.find((t) => t.evaluationContext?.evaluationRunId === evaluation.id && t.evaluationContext?.caseId === caseId && t.evaluationContext?.arm === arm && t.evaluationContext?.trial === trial);
  const mutation = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: async () => { await traces.refetch(); await onRecorded(); } });
  useEffect(() => { setCaseId(""); setTrial(0); setRationale(""); setProcess(""); setOutcome(""); setSafety(false); }, [evaluation.id]);
  return <Card><CardHeader><CardTitle>Execute and review paired evidence</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Run each pinned case and trial for both arms with the same agent configuration. Negative controls receive neutral task input. Running a case invokes the configured provider and uses the company budget.</p><V5Error error={suite.error ?? agents.error ?? traces.error ?? mutation.error} />
    <div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-sm"><span className="block">Evaluation agent</span><select className="w-full rounded-md border bg-background p-2" value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="">Select local agent</option>{agents.data?.map((a) => <option key={a.id} value={a.id}>{a.name} · {a.adapterType}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Pinned case</span><select className="w-full rounded-md border bg-background p-2" value={caseId} onChange={(e) => setCaseId(e.target.value)}><option value="">Select case</option>{suite.data?.cases.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.shouldTrigger ? "positive" : "negative"} · {c.risk}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Arm</span><select className="w-full rounded-md border bg-background p-2" value={arm} onChange={(e) => setArm(e.target.value as typeof arm)}><option value="candidate">Challenger</option>{evaluation.championVersionId && <option value="champion">Champion</option>}</select></label><label className="space-y-1 text-sm"><span className="block">Trial (0–{evaluation.trials - 1})</span><Input type="number" min={0} max={evaluation.trials - 1} value={trial} onChange={(e) => setTrial(Number(e.target.value))} /></label></div>
    {selected && <p className="whitespace-pre-wrap rounded-md border bg-muted p-3 text-sm">{selected.input}</p>}
    <div className="flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={mutation.isPending || !selected || !agentId || !versionId || Boolean(trace)} onClick={() => { if (selected && versionId) mutation.mutate(() => companySkillsApi.createTestRun(cid, skillId, { agentId, content: selected.input, templateId: null, skillVersionId: versionId, evaluationBinding: { evaluationRunId: evaluation.id, caseId, arm, trial } satisfies SkillEvaluationBinding })); }}>Run pinned case</Button><Button variant="outline" onClick={() => traces.refetch()}>Refresh traces</Button></div>
    {trace && <div className="space-y-3 border-t pt-3"><p className="text-sm">Retained trace {trace.id} · {trace.status}. Inspect its output and tool events in Skill Studio before judging.</p><div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-sm"><span className="block">Process compliance score (0–1)</span><Input type="number" min={0} max={1} step={0.05} value={process} onChange={(e) => setProcess(e.target.value)} /></label><label className="space-y-1 text-sm"><span className="block">Outcome quality score (0–1)</span><Input type="number" min={0} max={1} step={0.05} value={outcome} onChange={(e) => setOutcome(e.target.value)} /></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={safety} onChange={(e) => setSafety(e.target.checked)} />I reviewed the retained trace and its safety requirements passed.</label><label className="block space-y-1 text-sm"><span>Attributable human rationale</span><Textarea value={rationale} onChange={(e) => setRationale(e.target.value)} minLength={20} /></label><div className="flex justify-end"><Button disabled={mutation.isPending || trace.status !== "succeeded" || process === "" || outcome === "" || rationale.trim().length < 20} onClick={() => mutation.mutate(() => api.post(`${base}/runs/${evaluation.id}/observations`, { caseId, trial, arm, testRunId: trace.id, humanAssessment: { processScore: Number(process), outcomeScore: Number(outcome), safetyPassed: safety, rationale } }))}>Record observation from retained evidence</Button></div></div>}
  </CardContent></Card>;
}
