import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { SkillPromotionPolicy, SkillReviewPolicy } from "@paperclipai/shared";
import { agentsApi } from "@/api/agents";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function SkillGovernancePolicy({ companyId, ownerAgentId, reviewPolicy, promotionPolicy, busy, onSave }: { companyId: string; ownerAgentId: string | null; reviewPolicy: SkillReviewPolicy; promotionPolicy: SkillPromotionPolicy; busy: boolean; onSave: (input: { ownerAgentId: string | null; reviewPolicy: SkillReviewPolicy; promotionPolicy: SkillPromotionPolicy }) => void }) {
  const agents = useQuery({ queryKey: ["v5-governance-agents", companyId], queryFn: () => agentsApi.list(companyId) });
  const [owner, setOwner] = useState(ownerAgentId ?? ""), [review, setReview] = useState(reviewPolicy), [promotion, setPromotion] = useState(promotionPolicy);
  return <form className="space-y-3 border-t pt-4" onSubmit={(event) => { event.preventDefault(); onSave({ ownerAgentId: owner || null, reviewPolicy: review, promotionPolicy: promotion }); }}><h2 className="text-sm font-semibold">Owner and review policy</h2><div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-sm"><span className="block">Local owner</span><select className="w-full rounded-md border bg-background p-2" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">No agent owner</option>{agents.data?.filter((agent) => agent.status !== "terminated").map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label><label className="space-y-1 text-sm"><span className="block">Human steward member ID (optional)</span><Input value={review.stewardUserId ?? ""} onChange={(event) => setReview({ ...review, stewardUserId: event.target.value || null })} /></label><label className="space-y-1 text-sm"><span className="block">Review interval in days</span><Input type="number" min={1} max={365} value={review.reviewIntervalDays} onChange={(event) => setReview({ ...review, reviewIntervalDays: Number(event.target.value) })} /></label><label className="space-y-1 text-sm"><span className="block">Minimum paired trials</span><Input type="number" min={2} max={20} value={promotion.minimumPairedTrials} onChange={(event) => setPromotion({ ...promotion, minimumPairedTrials: Number(event.target.value) })} /></label><label className="space-y-1 text-sm"><span className="block">Minimum outcome score</span><Input type="number" min={0} max={1} step={0.05} value={promotion.minimumOutcomeScore} onChange={(event) => setPromotion({ ...promotion, minimumOutcomeScore: Number(event.target.value) })} /></label><label className="space-y-1 text-sm"><span className="block">Maximum cost regression ratio</span><Input type="number" min={1} max={5} step={0.05} value={promotion.maximumCostRegressionRatio} onChange={(event) => setPromotion({ ...promotion, maximumCostRegressionRatio: Number(event.target.value) })} /></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={promotion.requireHumanReview} onChange={(event) => setPromotion({ ...promotion, requireHumanReview: event.target.checked })} />Require human review</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={promotion.allowAutonomousPromotion} onChange={(event) => setPromotion({ ...promotion, allowAutonomousPromotion: event.target.checked })} />Allow autonomous promotion under explicit company policy</label><p className="text-xs text-muted-foreground">Autonomous promotion also requires a company rule, feature flags, a local owner and every evaluation gate. High-risk and critical cases require human review.</p><div className="flex justify-end"><Button variant="outline" disabled={busy}>Save governance policy</Button></div></form>;
}
