import { z } from "zod";
export const SUPERVISION_ACTIONS = ["CONTINUE", "STEER", "PAUSE", "RETRY", "REASSIGN", "SPAWN_WORKER", "START_VERIFIER", "REQUEST_INPUT", "REQUEST_APPROVAL", "ESCALATE_HUMAN", "STOP", "FINISH"] as const;
export const SUPERVISION_SIGNALS = ["progress", "no_progress", "stuck_loop", "repeated_failure", "off_track", "requirement_missing", "requirement_satisfied", "verification_needed", "verification_failed", "budget_warning", "budget_exceeded", "permission_changed", "readiness_degraded", "external_dependency_wait", "human_input_needed", "policy_violation", "possible_completion"] as const;
export const supervisionPolicySchema = z.object({ repeatedFailureThreshold: z.number().int().min(2).max(20).default(3), noProgressSeconds: z.number().int().min(30).max(86400).nullable().default(null), minCheckIntervalSeconds: z.number().int().min(5).max(3600).default(30), maxSupervisorChecks: z.number().int().min(1).max(10000).default(100), maxVerifierCalls: z.number().int().min(0).max(10).default(1), maxVerificationDepth: z.number().int().min(0).max(3).default(1) }).strict();
export const supervisionInterventionSchema = z.object({ expectedPlanVersion: z.number().int().positive(), action: z.enum(SUPERVISION_ACTIONS), rationale: z.string().trim().min(20).max(2000), signalIds: z.array(z.string().uuid()).max(32).default([]), workerId: z.string().uuid().nullable().default(null), reassignToAgentId: z.string().uuid().nullable().default(null) }).strict().superRefine((value, ctx) => { if (value.action === "REASSIGN" && (!value.workerId || !value.reassignToAgentId)) ctx.addIssue({ code: "custom", message: "Reassignment requires a worker and its new canonical agent" }); if (value.action !== "REASSIGN" && value.reassignToAgentId) ctx.addIssue({ code: "custom", message: "Only reassignment can select a new agent" }); });
export type SupervisionPolicy = z.infer<typeof supervisionPolicySchema>;
export type SupervisionAction = typeof SUPERVISION_ACTIONS[number];
export type SupervisionSignalType = typeof SUPERVISION_SIGNALS[number];
export type SupervisionInterventionInput = z.input<typeof supervisionInterventionSchema>;
export interface SupervisionSignalView { modelReservationId?: string | null; id: string; planId: string; signalType: SupervisionSignalType; severity: string; sourceRef: string; facts: Record<string, unknown>; observedAt: string; expiresAt: string | null; }
export interface SupervisionInterventionView { id: string; planId: string; recommendation: SupervisionAction; decisionAction: SupervisionAction; reasonCode: string; status: string; expectedPlanVersion: number; requestedByType: string; requestedById: string | null; rationale: string | null; createdAt: string; }
export interface SupervisionView { sessions: Array<{ id: string; status: string; lastObservedAt: string | null; policy: SupervisionPolicy }>; signals: SupervisionSignalView[]; interventions: SupervisionInterventionView[]; }
