import { z } from "zod";
import type { OrchestrationCompletion } from "./orchestration.js";
const judgement = z.object({ index: z.number().int().min(0).max(15), satisfied: z.boolean(), evidenceRefs: z.array(z.string().min(1).max(200)).max(32).default([]) }).strict();
export const verificationReviewSchema = z.object({ expectedPlanVersion: z.number().int().positive(), workerId: z.string().uuid().nullable().default(null), expectedResultHash: z.string().regex(/^[a-f0-9]{64}$/), result: z.enum(["pass","fail","inconclusive","needs_human"]), rationale: z.string().trim().min(20).max(2000), objectiveSatisfied: z.boolean(), businessInvariants: z.array(judgement).max(16), evidenceRequirements: z.array(judgement).max(16).default([]), prohibitedOutcomes: z.array(judgement).max(16).default([]), uncertainties: z.array(z.string().trim().min(5).max(500)).max(16).default([]), explicitHighImpactApproval: z.boolean().default(false) }).strict();
export type VerificationReviewInput = z.input<typeof verificationReviewSchema>;
export interface VerificationEvidenceRef { ref: string; type: "task_document" | "tool_receipt" | "task_state" | "memory"; sourceId: string; sourceVersion: string; hash: string | null; }
export interface VerificationPacket { planId: string; planVersion: number; workerId: string | null; issueId: string; contractId: string; contractHash: string; contract: OrchestrationCompletion; resultHash: string; evidence: VerificationEvidenceRef[]; deterministicFailures: string[]; liveAttempts: number; riskClass: string; policy: { independentRequired: boolean; humanRequired: boolean; workerSelfCertification: false }; }
export interface VerificationRunView { modelReservationId?: string | null; id: string; planId: string; workerId: string | null; result: "pass" | "fail" | "inconclusive" | "needs_human"; resultHash: string; reviewerType: string; reviewerId: string; failedInvariants: string[]; uncertainties: string[]; createdAt: string; erasedAt: string | null; }
export const trajectoryReviewSchema = z.object({ expectedPlanVersion: z.number().int().positive(), workerId: z.string().uuid().nullable().default(null), expectedResultHash: z.string().regex(/^[a-f0-9]{64}$/), verdict: z.enum(["on_track","off_track","uncertain","possible_completion"]), reasonCode: z.enum(["aligned_with_objective","wrong_objective","missing_requirement","insufficient_evidence","result_ready_for_review"]), evidenceRefs: z.array(z.string().min(1).max(200)).min(1).max(32), rationale: z.string().trim().min(20).max(2000) }).strict();
export type TrajectoryReviewInput = z.input<typeof trajectoryReviewSchema>;
