import { sql } from "drizzle-orm";
import { pgTable, uuid, text, timestamp, integer, jsonb, unique, foreignKey, check, index } from "drizzle-orm/pg-core";
import type { LearningHypothesisInput, LearningEvaluationInput, LearningPolicyPayload } from "@paperclipai/shared";
import { companies } from "./companies.js";
import { memoryRecords } from "./memory.js";
const times = () => ({ createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const learningCycles = pgTable("learning_cycles", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  scopeType: text("scope_type").notNull(), scopeId: text("scope_id"), purpose: text("purpose").notNull(), trigger: text("trigger").notNull(), status: text("status").notNull().default("hypothesizing"), version: integer("version").notNull().default(1),
  maxHypotheses: integer("max_hypotheses").notNull(), maxEvaluations: integer("max_evaluations").notNull(), outcomeVersions: jsonb("outcome_versions").$type<Record<string, string>>().notNull(), createdBy: text("created_by").notNull(), erasedAt: timestamp("erased_at", { withTimezone: true }), ...times(),
}, (t) => ({ tenantUq: unique("learning_cycles_tenant_uq").on(t.companyId, t.id), scopeCheck: check("learning_cycle_scope_check", sql`(${t.scopeType}='company' and ${t.scopeId} is null) or (${t.scopeType}='project' and ${t.scopeId} is not null)`),
  statusCheck: check("learning_cycle_status_check", sql`${t.status} in ('hypothesizing','evaluating','proposing','completed','failed','cancelled')`), limits: check("learning_cycle_limits_check", sql`${t.version}>0 and ${t.maxHypotheses} between 1 and 20 and ${t.maxEvaluations} between 1 and 40`), companyIdx: index("learning_cycles_company_idx").on(t.companyId, t.createdAt) }));
export const learningEvidence = pgTable("learning_evidence", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), cycleId: uuid("cycle_id").notNull(), memoryRecordId: uuid("memory_record_id").notNull(), sourceVersion: text("source_version").notNull(),
}, (t) => ({ cycleFk: foreignKey({ name: "learning_evidence_cycle_fk", columns: [t.companyId, t.cycleId], foreignColumns: [learningCycles.companyId, learningCycles.id] }).onDelete("cascade"), memoryFk: foreignKey({ name: "learning_evidence_memory_fk", columns: [t.companyId, t.memoryRecordId], foreignColumns: [memoryRecords.companyId, memoryRecords.id] }).onDelete("cascade"), rootUq: unique("learning_evidence_root_uq").on(t.cycleId, t.memoryRecordId) }));
export const learningHypotheses = pgTable("learning_hypotheses", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), cycleId: uuid("cycle_id").notNull(), claim: text("claim").notNull(), predictedEffect: text("predicted_effect").notNull(), targetDomain: text("target_domain").notNull(), targetId: uuid("target_id").notNull(), riskClass: text("risk_class").notNull(), status: text("status").notNull().default("candidate"), version: integer("version").notNull().default(1),
  evaluationContract: jsonb("evaluation_contract").$type<LearningHypothesisInput["evaluationContract"] | null>(), erasedAt: timestamp("erased_at", { withTimezone: true }), ...times(),
}, (t) => ({ tenantUq: unique("learning_hypotheses_tenant_uq").on(t.companyId, t.id), cycleFk: foreignKey({ name: "learning_hypothesis_cycle_fk", columns: [t.companyId, t.cycleId], foreignColumns: [learningCycles.companyId, learningCycles.id] }).onDelete("cascade"), statusCheck: check("learning_hypothesis_status_check", sql`${t.status} in ('candidate','supported','not_supported','inconclusive','proposal_created','rejected')`), riskCheck: check("learning_hypothesis_risk_check", sql`${t.riskClass} in ('low','material','high','critical')`), targetCheck: check("learning_hypothesis_target_check", sql`${t.targetDomain} in ('foundation','skill','playbook','project','policy','workflow','role_pack','automation_artifact','agent_package')`), versionCheck: check("learning_hypothesis_version_check", sql`${t.version}>0`) }));
export const learningEvaluations = pgTable("learning_evaluations", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), hypothesisId: uuid("hypothesis_id").notNull(), method: text("method").notNull(), result: text("result").notNull(),
  cases: jsonb("cases").$type<LearningEvaluationInput["cases"]>().notNull(), outcomeVersions: jsonb("outcome_versions").$type<Record<string, string>>().notNull(), metrics: jsonb("metrics").$type<Record<string, unknown>>().notNull(), limitations: jsonb("limitations").$type<string[]>().notNull(), reviewedBy: text("reviewed_by").notNull(), erasedAt: timestamp("erased_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ tenantUq: unique("learning_evaluations_tenant_uq").on(t.companyId, t.id), hypothesisFk: foreignKey({ name: "learning_eval_hypothesis_fk", columns: [t.companyId, t.hypothesisId], foreignColumns: [learningHypotheses.companyId, learningHypotheses.id] }).onDelete("cascade"), resultCheck: check("learning_eval_result_check", sql`${t.result} in ('passed','failed','inconclusive')`), methodCheck: check("learning_eval_method_check", sql`${t.method}='manual_review'`) }));
export const learningDomainCandidates = pgTable("learning_domain_candidates", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), hypothesisId: uuid("hypothesis_id").notNull(), evaluationId: uuid("evaluation_id").notNull(), targetDomain: text("target_domain").notNull(), targetId: uuid("target_id").notNull(), candidateId: uuid("candidate_id").notNull(), candidateHash: text("candidate_hash").notNull(), invalidatedAt: timestamp("invalidated_at", { withTimezone: true }), erasedAt: timestamp("erased_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ tenantUq: unique("learning_candidate_tenant_uq").on(t.companyId, t.id), hypothesisFk: foreignKey({ name: "learning_candidate_hypothesis_fk", columns: [t.companyId, t.hypothesisId], foreignColumns: [learningHypotheses.companyId, learningHypotheses.id] }).onDelete("cascade"), evalFk: foreignKey({ name: "learning_candidate_eval_fk", columns: [t.companyId, t.evaluationId], foreignColumns: [learningEvaluations.companyId, learningEvaluations.id] }), oneUq: unique("learning_candidate_hypothesis_uq").on(t.hypothesisId), candidateUq: unique("learning_candidate_domain_uq").on(t.companyId, t.targetDomain, t.candidateId) }));
export const learningRetainedAssets = pgTable("learning_retained_assets", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), candidateLinkId: uuid("candidate_link_id").notNull(), assetType: text("asset_type").notNull(), assetId: uuid("asset_id").notNull(), erasedAt: timestamp("erased_at", { withTimezone: true }),
}, (t) => ({ linkFk: foreignKey({ name: "learning_retained_asset_link_fk", columns: [t.companyId, t.candidateLinkId], foreignColumns: [learningDomainCandidates.companyId, learningDomainCandidates.id] }).onDelete("cascade"), assetUq: unique("learning_retained_asset_uq").on(t.candidateLinkId, t.assetType, t.assetId), assetCheck: check("learning_retained_asset_type_check", sql`${t.assetType} in ('document_revision','skill_version','workflow_revision','role_pack_version','automation_artifact_version','agent_package_installation')`) }));
export const policyChangeProposals = pgTable("policy_change_proposals", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }), targetId: uuid("target_id").notNull(), policyType: text("policy_type").notNull(), version: integer("version").notNull().default(1), proposal: jsonb("proposal").$type<LearningPolicyPayload | null>(), reason: text("reason").notNull(), status: text("status").notNull().default("pending"), reviewedBy: text("reviewed_by"), reviewRationale: text("review_rationale"), erasedAt: timestamp("erased_at", { withTimezone: true }), ...times(),
}, (t) => ({ statusCheck: check("policy_proposal_status_check", sql`${t.status} in ('pending','accepted','rejected','stale')`), versionCheck: check("policy_proposal_version_check", sql`${t.version}>0`) }));
