import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { documents } from "./documents.js";
import { documentRevisions } from "./document_revisions.js";
import { agents } from "./agents.js";
import { companySkills, companySkillVersions } from "./company_skills.js";

export const playbookDocuments = pgTable("playbook_documents", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }), documentId: uuid("document_id").notNull(),
  key: text("playbook_key").notNull(), category: text("category").notNull(), status: text("status").notNull().default("draft"), sensitivity: text("sensitivity").notNull().default("internal"),
  approvedRevisionId: uuid("approved_revision_id"), ownerUserId: text("owner_user_id"), ownerAgentId: uuid("owner_agent_id"), reviewFrequencyDays: integer("review_frequency_days").notNull().default(90),
  lastReviewedAt: timestamp("last_reviewed_at", { withTimezone: true }), nextReviewAt: timestamp("next_review_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ companyIdUq: unique("playbook_documents_company_id_uq").on(t.companyId, t.id), companyKeyUq: unique("playbook_documents_company_key_uq").on(t.companyId, t.key), companyDocumentUq: unique("playbook_documents_company_document_uq").on(t.companyId, t.documentId), documentFk: foreignKey({ columns: [t.companyId, t.documentId], foreignColumns: [documents.companyId, documents.id] }).onDelete("cascade"), revisionFk: foreignKey({ columns: [t.companyId, t.documentId, t.approvedRevisionId], foreignColumns: [documentRevisions.companyId, documentRevisions.documentId, documentRevisions.id] }), ownerFk: foreignKey({ columns: [t.companyId, t.ownerAgentId], foreignColumns: [agents.companyId, agents.id] }), stateCheck: check("playbook_documents_state_check", sql`${t.status} in ('draft','in_review','approved','superseded','archived')`), approvedCheck: check("playbook_documents_approved_check", sql`${t.status} <> 'approved' or ${t.approvedRevisionId} is not null`), sensitivityCheck: check("playbook_documents_sensitivity_check", sql`${t.sensitivity} in ('public','internal','confidential','restricted')`), reviewCheck: check("playbook_documents_review_check", sql`${t.reviewFrequencyDays} between 1 and 3650`), statusIdx: index("playbook_documents_status_idx").on(t.companyId, t.status) }));

export const playbookSkillLinks = pgTable("playbook_skill_links", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), playbookId: uuid("playbook_id").notNull(), playbookRevisionId: uuid("playbook_revision_id").notNull(), skillId: uuid("skill_id").notNull(), skillVersionId: uuid("skill_version_id").notNull(),
  relationType: text("relation_type").notNull(), syncPolicy: text("sync_policy").notNull().default("notify_on_change"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ revisionFk: foreignKey({ columns: [t.companyId, t.playbookRevisionId], foreignColumns: [documentRevisions.companyId, documentRevisions.id] }), playbookFk: foreignKey({ columns: [t.companyId, t.playbookId], foreignColumns: [playbookDocuments.companyId, playbookDocuments.id] }).onDelete("cascade"), versionFk: foreignKey({ columns: [t.companyId, t.skillId, t.skillVersionId], foreignColumns: [companySkillVersions.companyId, companySkillVersions.companySkillId, companySkillVersions.id] }), relationCheck: check("playbook_skill_links_relation_check", sql`${t.relationType} in ('implements','refers_to','derived_from')`), syncCheck: check("playbook_skill_links_sync_check", sql`${t.syncPolicy} in ('manual','notify_on_change','auto_generate_candidate')`), uniqueLink: unique("playbook_skill_links_version_uq").on(t.companyId, t.playbookId, t.playbookRevisionId, t.skillVersionId, t.relationType) }));

export const playbookChangeProposals = pgTable("playbook_change_proposals", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), playbookId: uuid("playbook_id").notNull(), baseApprovedRevisionId: uuid("base_approved_revision_id"), baseDraftRevisionId: uuid("base_draft_revision_id").notNull(), title: text("title").notNull(), markdown: text("markdown").notNull(), reason: text("reason").notNull(),
  sourceSkillId: uuid("source_skill_id"), sourceSkillVersionId: uuid("source_skill_version_id"), status: text("status").notNull().default("pending"), createdByUserId: text("created_by_user_id"), createdByAgentId: uuid("created_by_agent_id"), reviewedByUserId: text("reviewed_by_user_id"), reviewRationale: text("review_rationale"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ playbookFk: foreignKey({ columns: [t.companyId, t.playbookId], foreignColumns: [playbookDocuments.companyId, playbookDocuments.id] }).onDelete("cascade"), sourceVersionFk: foreignKey({ columns: [t.companyId, t.sourceSkillId, t.sourceSkillVersionId], foreignColumns: [companySkillVersions.companyId, companySkillVersions.companySkillId, companySkillVersions.id] }), authorFk: foreignKey({ columns: [t.companyId, t.createdByAgentId], foreignColumns: [agents.companyId, agents.id] }), stateCheck: check("playbook_change_proposals_state_check", sql`${t.status} in ('pending','accepted','rejected','stale')`), statusIdx: index("playbook_change_proposals_status_idx").on(t.companyId, t.playbookId, t.status) }));
