import { sql } from "drizzle-orm";
import { check, foreignKey, index, jsonb, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import type { PortfolioCapabilitySnapshot } from "@paperclipai/shared";
import { companies } from "./companies.js";
import { companySkills } from "./company_skills.js";
import { playbookDocuments } from "./playbooks.js";

export const portfolioCapabilityPublications = pgTable("portfolio_capability_publications", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }), assetType: text("asset_type").notNull(), assetId: uuid("asset_id").notNull(), versionId: uuid("version_id").notNull(),
  recipientCompanyIds: uuid("recipient_company_ids").array().notNull(), classification: text("classification").notNull(), releaseNotes: text("release_notes").notNull(), snapshot: jsonb("snapshot").$type<PortfolioCapabilitySnapshot>().notNull(), hash: text("hash").notNull(), status: text("status").notNull().default("published"), publishedByUserId: text("published_by_user_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ assetIdx: index("portfolio_capability_publications_asset_idx").on(t.companyId, t.assetType, t.assetId, t.createdAt), stateCheck: check("portfolio_capability_publications_state_check", sql`${t.status} in ('published','withdrawn')`), classificationCheck: check("portfolio_capability_publications_classification_check", sql`${t.classification} in ('public','internal')`), assetTypeCheck: check("portfolio_capability_publications_type_check", sql`${t.assetType} in ('skill','playbook')`) }));

export const portfolioCapabilitySubscriptions = pgTable("portfolio_capability_subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }), publicationId: uuid("publication_id").notNull().references(() => portfolioCapabilityPublications.id), sourceCompanyId: uuid("source_company_id").notNull().references(() => companies.id), assetType: text("asset_type").notNull(), sourceAssetId: uuid("source_asset_id").notNull(), pinnedSourceVersionId: uuid("pinned_source_version_id").notNull(), localSkillId: uuid("local_skill_id"), localPlaybookId: uuid("local_playbook_id"), mode: text("mode").notNull(), createdByUserId: text("created_by_user_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ localSkillFk: foreignKey({ columns: [t.companyId, t.localSkillId], foreignColumns: [companySkills.companyId, companySkills.id] }), localPlaybookFk: foreignKey({ columns: [t.companyId, t.localPlaybookId], foreignColumns: [playbookDocuments.companyId, playbookDocuments.id] }), localSkillUq: unique("portfolio_capability_subscriptions_skill_uq").on(t.localSkillId), localPlaybookUq: unique("portfolio_capability_subscriptions_playbook_uq").on(t.localPlaybookId), modeCheck: check("portfolio_capability_subscriptions_mode_check", sql`${t.mode} in ('install','subscribe','fork')`), localTypeCheck: check("portfolio_capability_subscriptions_local_type_check", sql`(${t.assetType} = 'skill' and ${t.localSkillId} is not null and ${t.localPlaybookId} is null) or (${t.assetType} = 'playbook' and ${t.localPlaybookId} is not null and ${t.localSkillId} is null)`), sourceIdx: index("portfolio_capability_subscriptions_source_idx").on(t.companyId, t.sourceCompanyId, t.sourceAssetId) }));
