import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { SUPERVISION_ACTIONS, SUPERVISION_SIGNALS, type SupervisionPolicy, type SupervisionAction, type SupervisionSignalType } from "@paperclipai/shared";
import { agents } from "./agents.js";
import { orchestrationPlans, orchestrationWorkerAttempts, orchestrationWorkers } from "./orchestration.js";
import { orchestrationModelReservations } from "./orchestration.js";
export const supervisionSessions = pgTable("supervision_sessions", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), planId: uuid("plan_id").notNull(), status: text("status").notNull().default("active"), policy: jsonb("policy").$type<SupervisionPolicy>().notNull(),
  progressHash: text("progress_hash"), lastProgressAt: timestamp("last_progress_at", { withTimezone: true }), checksUsed: integer("checks_used").notNull().default(0), verifierCallsUsed: integer("verifier_calls_used").notNull().default(0), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), lastObservedAt: timestamp("last_observed_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, t => ({ tenantUq: unique("supervision_session_tenant_uq").on(t.companyId, t.id), planSessionUq: unique("supervision_plan_session_uq").on(t.companyId, t.planId, t.id), planFk: foreignKey({ columns: [t.companyId, t.planId], foreignColumns: [orchestrationPlans.companyId, orchestrationPlans.id] }).onDelete("cascade"), livePlanUq: uniqueIndex("supervision_session_live_plan_uq").on(t.planId).where(sql`${t.status}='active'`), statusCheck: check("supervision_session_status_check", sql`${t.status} in ('active','paused','completed','failed')`), countersCheck: check("supervision_session_counters_check", sql`${t.checksUsed}>=0 and ${t.verifierCallsUsed}>=0`) }));
export const supervisionSignals = pgTable("supervision_signals", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), planId: uuid("plan_id").notNull(), sessionId: uuid("session_id").notNull(), workerAttemptId: uuid("worker_attempt_id"), modelReservationId: uuid("model_reservation_id"), signalType: text("signal_type").$type<SupervisionSignalType>().notNull(), severity: text("severity").notNull(), sourceType: text("source_type").notNull(), sourceRef: text("source_ref").notNull(), facts: jsonb("facts").$type<Record<string, unknown>>().notNull(), snapshotHash: text("snapshot_hash").notNull(), dedupKey: text("dedup_key").notNull(), observedAt: timestamp("observed_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }),
}, t => ({ tenantUq: unique("supervision_signal_tenant_uq").on(t.companyId, t.id), modelReservationFk: foreignKey({ columns: [t.companyId,t.modelReservationId], foreignColumns: [orchestrationModelReservations.companyId,orchestrationModelReservations.id] }), modelReservationUq: unique("supervision_signal_model_reservation_uq").on(t.modelReservationId), modelSourceCheck: check("supervision_signal_model_source_check",sql`(${t.sourceType}='read_only_model_trajectory')=(${t.modelReservationId} is not null)`), dedupUq: unique("supervision_signal_dedup_uq").on(t.companyId, t.planId, t.dedupKey), sessionFk: foreignKey({ columns: [t.companyId, t.planId, t.sessionId], foreignColumns: [supervisionSessions.companyId, supervisionSessions.planId, supervisionSessions.id] }), attemptFk: foreignKey({ columns: [t.companyId,t.planId,t.workerAttemptId], foreignColumns: [orchestrationWorkerAttempts.companyId,orchestrationWorkerAttempts.planId,orchestrationWorkerAttempts.id] }), typeCheck: check("supervision_signal_type_check", sql`${t.signalType} in (${sql.raw(SUPERVISION_SIGNALS.map(v => "'"+v+"'").join(","))})`), severityCheck: check("supervision_signal_severity_check", sql`${t.severity} in ('info','warning','blocking')`), planIdx: index("supervision_signal_plan_idx").on(t.companyId, t.planId, t.observedAt) }));
export const supervisionInterventions = pgTable("supervision_interventions", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), planId: uuid("plan_id").notNull(), sessionId: uuid("session_id").notNull(), signalIds: jsonb("signal_ids").$type<string[]>().notNull().default([]), recommendation: text("recommendation").$type<SupervisionAction>().notNull(), decisionAction: text("decision_action").$type<SupervisionAction>().notNull(), reasonCode: text("reason_code").notNull(), policySnapshotHash: text("policy_snapshot_hash").notNull(), expectedPlanVersion: integer("expected_plan_version").notNull(), requestedByType: text("requested_by_type").notNull(), requestedById: text("requested_by_id"), rationale: text("rationale"), targetWorkerId: uuid("target_worker_id"), targetAgentId: uuid("target_agent_id"), targetAttemptIds: jsonb("target_attempt_ids").$type<string[]>().notNull().default([]), idempotencyKey: text("idempotency_key").notNull(), status: text("status").notNull(), attempts: integer("attempts").notNull().default(0), leaseOwner: text("lease_owner"), leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }), lastErrorCode: text("last_error_code"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }),
}, t => ({ tenantUq: unique("supervision_intervention_tenant_uq").on(t.companyId, t.id), sessionFk: foreignKey({ columns: [t.companyId, t.planId, t.sessionId], foreignColumns: [supervisionSessions.companyId, supervisionSessions.planId, supervisionSessions.id] }), workerFk: foreignKey({ columns: [t.companyId,t.planId,t.targetWorkerId], foreignColumns: [orchestrationWorkers.companyId,orchestrationWorkers.planId,orchestrationWorkers.id] }), agentFk: foreignKey({ columns: [t.companyId,t.targetAgentId], foreignColumns: [agents.companyId,agents.id] }), idempotencyUq: unique("supervision_intervention_idempotency_uq").on(t.companyId, t.idempotencyKey), actionCheck: check("supervision_intervention_action_check", sql`${t.recommendation} in (${sql.raw(SUPERVISION_ACTIONS.map(v => "'"+v+"'").join(","))}) and ${t.decisionAction} in (${sql.raw(SUPERVISION_ACTIONS.map(v => "'"+v+"'").join(","))})`), stateCheck: check("supervision_intervention_state_check", sql`${t.status} in ('pending','running','applied','blocked','failed')`), actorCheck: check("supervision_intervention_actor_check", sql`${t.requestedByType} in ('user','agent','system')`), leaseCheck: check("supervision_intervention_lease_check", sql`(${t.leaseOwner} is null)=(${t.leaseExpiresAt} is null) and (${t.status}='running')=(${t.leaseOwner} is not null)`), counterCheck: check("supervision_intervention_counter_check", sql`${t.attempts}>=0 and ${t.expectedPlanVersion}>0`), queueIdx: index("supervision_intervention_queue_idx").on(t.status, t.leaseExpiresAt, t.createdAt) }));
