import { sql } from "drizzle-orm";
import { pgTable, uuid, text, jsonb, integer, timestamp, unique, foreignKey, check, index } from "drizzle-orm/pg-core";
import type { VerificationEvidenceRef, VerificationReviewInput } from "@paperclipai/shared";
import { orchestrationPlans, orchestrationWorkers, orchestrationWorkerAttempts } from "./orchestration.js";
import { completionContracts } from "./completion_contracts.js";
import { issues } from "./issues.js";
export const verificationRuns = pgTable("verification_runs", {
  id: uuid("id").primaryKey().defaultRandom(), companyId: uuid("company_id").notNull(), planId: uuid("plan_id").notNull(), workerId: uuid("worker_id"), workerAttemptId: uuid("worker_attempt_id"), issueId: uuid("issue_id").notNull(), completionContractId: uuid("completion_contract_id").notNull(), completionContractHash: text("completion_contract_hash").notNull(), expectedPlanVersion: integer("expected_plan_version").notNull(), resultHash: text("result_hash").notNull(), inputArtifactRefs: jsonb("input_artifact_refs").$type<VerificationEvidenceRef[]>().notNull(), evidenceRefs: jsonb("evidence_refs").$type<string[]>().notNull(), reviewerType: text("reviewer_type").notNull(), reviewerId: text("reviewer_id").notNull(), result: text("result").$type<"pass"|"fail"|"inconclusive"|"needs_human">().notNull(), failedInvariants: jsonb("failed_invariants").$type<string[]>().notNull(), uncertainties: jsonb("uncertainties").$type<string[]>().notNull(), review: jsonb("review").$type<VerificationReviewInput|null>(), recommendation: text("recommendation").notNull(), erasedAt: timestamp("erased_at",{ withTimezone: true }), createdAt: timestamp("created_at",{ withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at",{ withTimezone: true }).notNull().defaultNow(),
}, t => ({ tenantUq: unique("verification_run_tenant_uq").on(t.companyId,t.id), planFk: foreignKey({ columns: [t.companyId,t.planId], foreignColumns: [orchestrationPlans.companyId,orchestrationPlans.id] }), workerFk: foreignKey({ columns: [t.companyId,t.planId,t.workerId], foreignColumns: [orchestrationWorkers.companyId,orchestrationWorkers.planId,orchestrationWorkers.id] }), attemptFk: foreignKey({ columns: [t.companyId,t.planId,t.workerAttemptId], foreignColumns: [orchestrationWorkerAttempts.companyId,orchestrationWorkerAttempts.planId,orchestrationWorkerAttempts.id] }), issueFk: foreignKey({ columns: [t.companyId,t.issueId], foreignColumns: [issues.companyId,issues.id] }), contractFk: foreignKey({ columns: [t.companyId,t.issueId,t.completionContractId], foreignColumns: [completionContracts.companyId,completionContracts.issueId,completionContracts.id] }), resultCheck: check("verification_result_check",sql`${t.result} in ('pass','fail','inconclusive','needs_human')`), reviewerCheck: check("verification_reviewer_check",sql`${t.reviewerType}='human'`), versionCheck: check("verification_plan_version_check",sql`${t.expectedPlanVersion}>0`), planIdx: index("verification_plan_idx").on(t.companyId,t.planId,t.createdAt) }));
