import { businessScenarioDefinitionSchema, type BusinessScenarioView, type BusinessScenarioVersionView, type BusinessScenarioRunView, type NativeBusinessScenarioResult } from "@paperclipai/shared";
import { forecastFixture } from "./business-forecast-fixtures";
/** Synthetic presentation fixtures only; hashes and future retention dates
 * never establish actual source admission, execution or model calibration. */
export function scenarioFixture(published = false, monteCarlo = false) {
  const f = forecastFixture(), scenarioId = "00000000-0000-4000-8000-000000000501", versionId = "00000000-0000-4000-8000-000000000502", runId = "00000000-0000-4000-8000-000000000503";
  const policy = { ...f.policy, obligation: { ...f.policy.obligation, analyticalPurpose: { ...f.policy.obligation.analyticalPurpose!, capabilities: ["metrics", "forecast", "scenario"] as NonNullable<typeof f.policy.obligation.analyticalPurpose>["capabilities"] } } };
  const definition = businessScenarioDefinitionSchema.parse({ name: "Conditional delivery capacity", objective: "Compare explicit conditional capacity assumptions for human review", decisionUse: "Prepare advisory evidence for a separate human capacity decision", ownerUserId: f.userId,
    scope: { type: "company", id: null }, calculationType: monteCarlo ? "bounded_monte_carlo" : "formula",
    inputs: [{ kind: "metric_observation", key: "objects", metricId: f.metric.id, metricVersionId: f.metricVersion.id, observationId: f.observations[0].id, unit: { issue: 1 } }],
    assumptions: [{ key: "factor", name: "Human conditional capacity factor", type: "numeric", unit: {}, nominal: 2, range: { minimum: 1, maximum: 3 }, evidence: [{ kind: "human_statement", rationale: "Illustrative human assumption; no causal calibration has been performed" }], confidence: "human_asserted", uncertaintyRationale: "Demand responses and external changes may invalidate this assumption", ownerUserId: f.userId, controllable: true,
      distribution: monteCarlo ? { kind: "uniform", minimum: 1, maximum: 3, rationale: "Explicit illustrative conditional distribution with no empirical calibration claim" } : null }],
    formula: [{ key: "source", operation: "input", inputKey: "objects" }, { key: "factor", operation: "input", inputKey: "factor" }, { key: "scaled", operation: "multiply", left: "source", right: "factor" }],
    outputs: [{ key: "capacity", name: "Conditional modeled capacity", nodeKey: "scaled", unit: { issue: 1 }, constraints: { minimum: 2, maximum: null, rationale: "Illustrative human numerical bound for a review, not complete feasibility" } }],
    cases: [{ key: "base", name: "Base case", kind: "base", changes: [] }, { key: "option", name: "Capacity option", kind: "option", changes: [{ kind: "intervention", assumptionKey: "factor", value: 3, rationale: "Consider this human-proposed conditional intervention" }] }, { key: "stress", name: "Demand stress", kind: "stress", changes: [{ kind: "hypothetical_condition", assumptionKey: "factor", value: 1, rationale: "Consider the declared lower-bound assumption as a stress condition" }] }],
    uncertaintyPolicy: monteCarlo ? { kind: "bounded_monte_carlo", samples: 1000, independenceRationale: "One uncertain input only; no empirical correlations are inferred", stabilityAbsoluteTolerance: { capacity: 0.2 } } : { kind: "deterministic", rationale: "Nominal conditional arithmetic; ranges have not been propagated" },
    nonModeledEffects: ["Execution fidelity, market responses and external shocks are unmodeled"], sensitivity: "internal", purpose: "management_intelligence", governanceObligationRefs: [policy.id], retentionDays: 30,
  });
  const scenario: BusinessScenarioView = { id: scenarioId, companyId: f.companyId, key: "conditional_capacity", revision: published ? 2 : 1, status: published ? "published" : "draft", publishedVersionId: published ? versionId : null, createdAt: "2026-10-07T00:00:00Z", updatedAt: "2026-10-07T00:00:00Z" };
  const version: BusinessScenarioVersionView = { id: versionId, companyId: f.companyId, scenarioId, revision: 1, definition, contentHash: "a".repeat(64), inputHash: "b".repeat(64), inputs: [{ key: "objects", kind: "metric_observation", sourceId: f.observations[0].id, versionId: f.metricVersion.id, pointIndex: null, value: 1, unit: { issue: 1 }, contentHash: "c".repeat(64) }], createdAt: "2026-10-07T00:00:00Z", expiresAt: "2099-01-01T00:00:00Z", currentQualification: "current" };
  const result: NativeBusinessScenarioResult = { engineVersion: "aw-native-business-scenario-v1", status: "calculated", definitionHash: version.contentHash, inputHash: version.inputHash, seed: monteCarlo ? 0 : null, reasons: [],
    cases: definition.cases.map((item, index) => ({ key: item.key, name: item.name, kind: item.kind, changes: item.changes, outputs: [{ key: "capacity", unit: { issue: 1 }, nominal: [2, 3, 1][index], differenceFromBase: [0, 1, -1][index], constraint: index === 2 ? "violated" : "satisfied", simulation: monteCarlo ? { samples: 1000, minimum: index === 0 ? 1 : [2, 3, 1][index], p10: index === 0 ? 1.2 : [2, 3, 1][index], median: [2, 3, 1][index], p90: index === 0 ? 2.8 : [2, 3, 1][index], maximum: index === 0 ? 3 : [2, 3, 1][index], constraintViolations: index === 0 ? 500 : index === 2 ? 1000 : 0, halfSampleMaximumDifference: index === 0 ? 0.08 : 0, stabilityAbsoluteTolerance: 0.2 } : null }] })),
    uncertainty: { method: monteCarlo ? "independent_assumption_monte_carlo" : "deterministic", seedAlgorithm: monteCarlo ? "sha256-counter-48-v1" : null, coverageLevel: null, qualification: monteCarlo ? "stable_for_declared_tolerance" : "not_assessed", unstableOutputs: [] },
    limitations: ["Results are conditional implications, not causal effects or execution authority.", "Numerical constraint satisfaction does not establish complete organizational feasibility.", "Human-declared distributions have not been empirically calibrated.", ...definition.nonModeledEffects] };
  const run: BusinessScenarioRunView = { id: runId, companyId: f.companyId, scenarioId, versionId, result, contentHash: "d".repeat(64), createdAt: "2026-10-07T00:00:00Z", expiresAt: version.expiresAt, currentQualification: "current" };
  return { ...f, policy, scenario, version, run };
}
