import {businessForecastDefinitionSchema,businessMetricDefinitionSchema,governanceObligationSchema,type BusinessForecastArtifactView,type BusinessForecastSpecView,type BusinessForecastVersionView,type BusinessMetricResult,type GovernanceObligationView} from "@paperclipai/shared";
export const forecastId=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
/** Presentation fixtures only; they do not establish collected history,
 * source access, provider execution or release qualification. */
export function forecastFixture(published=false) {
 const companyId=forecastId(1),userId="reviewer",specId=forecastId(2),versionId=forecastId(3),policyId=forecastId(4),metricId=forecastId(6),metricVersionId=forecastId(7),expiresAt="2099-01-01T00:00:00Z",createdAt="2026-10-07T00:00:00Z";
 const definition=businessForecastDefinitionSchema.parse({name:"Daily delivery volume",businessQuestion:"Which workload should the human capacity review consider?",decisionUse:"Review capacity before making a separate human commitment",ownerUserId:userId,metricId,metricVersionId,scope:{type:"company",id:null},frequency:"daily_utc",horizon:2,provider:"aw_native",candidate:{kind:"naive"},baselines:[{kind:"naive"}],minimumHistory:10,captureLatencySeconds:3600,backtest:{minimumTrainingPoints:3,minimumOrigins:3,gapPeriods:1,maximumMAE:1,minimumRelativeMAEImprovement:0.05},knownFailureModes:["Presentation fixture: a steady historical series cannot establish future stability","Native completion counts do not establish useful outcomes or causal effects"],sensitivity:"internal",purpose:"management_intelligence",governanceObligationRefs:[policyId],retentionDays:30});
 const spec:BusinessForecastSpecView={id:specId,companyId,key:"delivery_volume",revision:published?2:1,status:published?"published":"draft",publishedVersionId:published?versionId:null,createdAt,updatedAt:createdAt};
 const version:BusinessForecastVersionView={id:versionId,companyId,specId,revision:1,definition,contentHash:"a".repeat(64),createdAt,expiresAt};
 const metricDefinition=businessMetricDefinitionSchema.parse({name:"Created task throughput",description:"Count native tasks created in a UTC window and complete at capture",businessQuestion:"How many created tasks are currently complete?",decisionUse:"Human capacity review",populationDescription:"Company tasks created in the chosen window",inclusions:["Created tasks"],exclusions:[],authorityMode:"aw_native",valueType:"count",unit:"objects",currency:null,grain:"issue",timeGrain:"window",timezone:"UTC",timeSemantics:"created_in_window_current_state",dimensions:[],calculation:{kind:"native_count",population:{entity:"issue",statuses:["done"],projectId:null}},ownerUserId:userId,reviewFrequencyDays:30,freshnessSeconds:2592000,missingPolicy:"explicit_unknown",goodhartRisk:"Task volume does not establish valuable outcomes",purpose:"management_intelligence",sensitivity:"internal",governanceObligationRefs:[policyId],retentionDays:30});
 const metric={id:metricId,companyId,key:"task_throughput",revision:2,status:"published" as const,publishedVersionId:metricVersionId,createdAt,updatedAt:createdAt};
 const metricVersion={id:metricVersionId,companyId,metricId,revision:1,definition:metricDefinition,contentHash:"b".repeat(64),createdAt};
 const cutoff=new Date(Math.floor(Date.now()/86400000)*86400000).toISOString();
 const observations:BusinessMetricResult[]=Array.from({length:10},(_,index)=>{const from=new Date(Date.parse(cutoff)-(10-index)*86400000).toISOString(),until=new Date(Date.parse(from)+86400000).toISOString();return {id:forecastId(20+index),companyId,metricId,versionId:metricVersionId,from,until,asOf:until,expiresAt,status:"observed",value:1,reason:null,groups:[],inputHash:"c".repeat(64),definitionHash:metricVersion.contentHash,engineVersion:"aw-native-metric-v1",lineageManifestId:forecastId(40+index),sourceWatermark:until};});
 const loss={mae:0,bias:0,wape:0,mase:null,zeroActualDenominator:false,zeroNaiveScale:true,byHorizon:[{horizon:1,cases:3,mae:0,bias:0},{horizon:2,cases:3,mae:0,bias:0}]};
 const artifact:BusinessForecastArtifactView={id:forecastId(5),companyId,specId,versionId,kind:"backtest",series:observations.map(value=>({observationId:value.id,metricId,metricVersionId,sourceHash:"c".repeat(64),from:value.from,until:value.until,asOf:value.asOf,value:value.value,status:value.status,unit:"objects"})),contentHash:"d".repeat(64),cutoff,createdAt,expiresAt,currentQualification:"qualified",reviewReason:null,
  result:{engineVersion:"aw-native-business-forecast-v1",status:"qualified",reasons:[],inputHash:"e".repeat(64),definitionHash:version.contentHash,unit:"objects",trainingObservationIds:observations.map(value=>value.id),backtests:[{origin:5,trainingObservationIds:observations.slice(0,5).map(value=>value.id),trainingCutoff:observations[4].asOf,testObservationIds:observations.slice(6,8).map(value=>value.id),gapPeriods:1,predictions:[{model:{kind:"naive"},values:[1,1],actual:[1,1],loss}]}],comparisons:[{model:{kind:"naive"},loss}],selectedReason:"Declared last-value baseline meets the human loss limit; intervals remain unavailable.",points:Array.from({length:2},(_,index)=>({from:new Date(Date.parse(cutoff)+index*86400000).toISOString(),until:new Date(Date.parse(cutoff)+(index+1)*86400000).toISOString(),value:1,interval:null})),uncertainty:{method:"unavailable",coverageLevel:null,reason:"Native point baselines have no qualified prediction intervals."},limitations:definition.knownFailureModes}};
 const policy:GovernanceObligationView={id:policyId,companyId,obligationHash:"f".repeat(64),ownerUserId:userId,lastReviewedAt:createdAt,nextReviewAt:expiresAt,obligation:governanceObligationSchema.parse({framework:"company_policy",authority:"Sample board",citation:"Approved advisory forecast purpose",jurisdictionOrScope:"Native business objects",applicabilityFacts:"Human review of forecast evidence",applicabilityState:"applicable",effectiveFrom:createdAt,effectiveUntil:null,requiredControl:"Current native source authority",evidenceRequired:["Native version and source pins"],controlRefs:["Separate human publication"],nextReviewAt:expiresAt,reviewTrigger:"Purpose or source change",sourceVersionOrDate:"storybook/v1",sourceUrl:"https://example.test/forecast-policy",analyticalPurpose:{status:"approved",purpose:"management_intelligence",capabilities:["metrics","forecast"],populationUnits:"business_objects",peopleImpact:"none",decisionBoundary:"advisory_only",maxRetentionDays:30,permittedSensitivity:["internal"],prohibitedUses:["Employee ranking"],approvalRationale:"Presentation-only advisory fixture"}})};
 return {companyId,userId,spec,version,metric,metricVersion,observations,policy,backtest:artifact,run:{...artifact,id:forecastId(8),kind:"run" as const}};
}
