import {causalClaimDefinitionSchema,type CausalClaimView,type CausalClaimVersionView,type CausalAnalysisRunView,type NativeCausalResult} from "@paperclipai/shared";
import {emptyCausalClaimDefinition} from "@/components/causal-claim-draft";
import {experimentFixture} from "./business-experiment-fixtures";
import {forecastId} from "./business-forecast-fixtures";
/** Synthetic presentation only: copied display intervals are not newly admitted
 * source evidence, a collected experiment or verified causal impact. */
export function causalFixture(state:"draft"|"reviewed"|"supported"|"refuted"|"inconclusive"|"revoked"="draft",stale=false){
 const f=experimentFixture("decided",state==="refuted"?"fail":"pass"),id=forecastId(1101),versionId=forecastId(1102),runId=forecastId(1103),interpretationId=forecastId(1104),at="2026-10-07T00:00:00Z",prose="Synthetic human presentation rationale only; this is not operational evidence.";
 const policy={...f.policy,obligation:{...f.policy.obligation,citation:"Approved advisory causal purpose",analyticalPurpose:{...f.policy.obligation.analyticalPurpose!,capabilities:["metrics","experiment","causal"] as NonNullable<typeof f.policy.obligation.analyticalPurpose>["capabilities"]}}};
 const initial=emptyCausalClaimDefinition(f.userId),assumption={status:"assumed" as const,rationale:prose};
 const definition=causalClaimDefinitionSchema.parse({...initial,name:"Earlier review and native completion",question:"Does earlier human review improve the registered native completion proxy?",humanHypothesis:"The registered earlier review may improve completion within the original safety bounds.",outcomeMetricId:f.measurements[0].metric.id,outcomeMetricVersionId:f.measurements[0].version.id,population:{scope:f.version.definition.scope,unit:"issue",eligibilityStatement:prose,externalValidityLimits:prose},horizon:{from:f.version.definition.sampleOrDurationPlan.from,until:f.version.definition.sampleOrDurationPlan.until},estimand:{...initial.estimand,minimumMeaningfulEffect:f.version.definition.primaryMetric.minimumMeaningfulEffect},graph:{...initial.graph,edges:[{...initial.graph.edges[0],rationale:prose}]},assumptions:{noInterference:assumption,stableOutcomeMeasurement:assumption,registeredPopulationValidity:assumption},experimentEvidence:{type:"experiment_analysis",id:f.analysis.id,experimentId:f.experiment.id,versionId:f.version.id,interpretationId},governanceObligationRefs:[policy.id]});
 const analyzed=!["draft","reviewed"].includes(state),status=state==="supported"||state==="refuted"?state:"inconclusive";
 const claim:CausalClaimView={id,companyId:f.companyId,key:"earlier_review_completion",revision:analyzed?3:state==="reviewed"?2:1,status:state==="revoked"?"revoked":analyzed?status:"hypothesis",currentVersionId:versionId,reviewedVersionId:state==="draft"?null:versionId,latestRunId:analyzed?runId:null,createdAt:at,updatedAt:at};
 const version:CausalClaimVersionView={id:versionId,companyId:f.companyId,claimId:id,revision:1,definition,contentHash:"a".repeat(64),sourceHash:"b".repeat(64),createdAt:at,expiresAt:"2099-01-01T00:00:00Z",currentQualification:stale?"needs_revalidation":"current"};
 const result:NativeCausalResult={engineVersion:"aw-native-causal-registered-primary-v1",definitionHash:version.contentHash,inputHash:"c".repeat(64),evidenceGrade:"randomized_experiment",status,stages:["question","human_model_and_assumptions","identification","estimation_or_abstention","robustness","conditional_interpretation"],identification:{status:status==="inconclusive"?"source_not_qualified":"conditional_identified",strategy:"registered_randomized_assignment",conditions:["Exact registered randomization and source identity remain required."]},estimate:status==="inconclusive"?null:{effect:0.3,interval:{lower:0.1,upper:0.5,method:"bonferroni_clopper_pearson_difference_v1",familywiseCoverage:0.95},unit:"fraction_difference",estimand:"assignment_intention_to_treat_native_binary_outcome",derivedFromRegisteredAnalysis:true},robustness:{assignmentRatio:"passed",registeredBaselineBalance:"passed",completeOutcomeAndExposureReceipts:status==="inconclusive"?"unavailable":"passed",guardrails:"excluded_within_registered_bounds",assumptions:"human_assumed",sensitivity:"unknown",providerRefutations:"not_run"},language:status==="inconclusive"?"causal_reliance_withheld":"conditional_assignment_effect_on_native_proxy",limitations:["Human exposure reports and model assumptions are not verified intervention delivery.","This is synthetic display data; no independent refutation or verified business impact."],reasons:[status==="supported"?"registered_meaningful_primary_and_safety_bounds_conditionally_supported":status==="refuted"?"registered_minimum_meaningful_primary_benefit_not_supported_within_bounds":"registered_source_quality_or_current_authority_does_not_admit_estimation"],executionAuthority:"advisory_only"};
 const run:CausalAnalysisRunView={id:runId,companyId:f.companyId,claimId:id,versionId,providerKey:"aw_native_registered_randomization",providerVersion:"1",methodKey:"registered_primary_itt",analysisPlanHash:"d".repeat(64),assumptionsSnapshotHash:"e".repeat(64),sourceHash:version.sourceHash,result,receiptHash:"f".repeat(64),startedAt:at,completedAt:at,currentQualification:version.currentQualification};
 const review=state==="draft"?null:{id:forecastId(1105),versionId,rationale:prose,reviewedBy:f.userId,reviewedAt:at,receiptHash:"9".repeat(64)};
 const receipts={...f.receipts,analysis:f.analysis,interpretation:{id:interpretationId,analysisId:f.analysis.id,conclusion:"ship_candidate" as const,rationale:prose,executionAuthority:"advisory_only" as const,receiptHash:"8".repeat(64),interpretedBy:f.userId,interpretedAt:at}};
 return {...f,policy,claim,causalVersion:version,run,review,causalReceipts:receipts};
}

export const doWhyPresentationProfile={provider:"dowhy" as const,version:"0.14" as const,python:"3.12.14" as const,bundleHash:"a".repeat(64),conformanceHash:"b".repeat(64)};
/** Strict synthetic presentation DTOs, not signed native/provider evidence. */
export function doWhyPresentationRun(status:"passed"|"failed"|"unknown"="passed"){
 const run=causalFixture("supported").run,profile=doWhyPresentationProfile;
 run.providerKey="dowhy";run.providerVersion="0.14";run.methodKey="backdoor.linear_regression";
 run.result.providerAnalysis={profile,nativeResultHash:"c".repeat(64),diagnostics:{provider:"dowhy",version:"0.14",python:"3.12.14",bundleHash:profile.bundleHash,method:"backdoor.linear_regression",identification:"identified_under_registered_randomization",adjustmentSet:[],effect:run.result.estimate!.effect,representation:"anonymous_binary_sufficient_counts",simulations:16,seed:1729,refutations:(["random_common_cause","placebo_treatment_refuter","data_subset_refuter"] as const).map((method,index)=>({method,effect:method==="placebo_treatment_refuter"?0:0.3,pValue:index===1?(status==="unknown"?null:status==="failed"?0.01:0.5):0.5,status:index===1?status:"passed"})),sensitivity:"unknown",uncertainty:"native_registered_interval_required"}};
 run.result.robustness.providerRefutations=status;run.result.limitations=["Synthetic presentation data; no collected trial, calibrated refutation or verified business impact."];
 if(status!=="passed"){run.result.status="inconclusive";run.result.language="causal_reliance_withheld";run.result.reasons=["optional_provider_refutations_do_not_admit_causal_reliance"];}
 return run;
}
