import type {DecisionOutcomeReviewState,DecisionOutcomeReviewView,FinishDecisionOutcomeReview,DecisionContextDefinition} from "@paperclipai/shared";
// Synthetic presentation fixtures, never live/provider/rollout evidence.
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
export function outcomeFixture(state:DecisionOutcomeReviewState,definition:DecisionContextDefinition):DecisionOutcomeReviewView {
  const companyId=id(1),decisionId=id(2),versionId=id(3),userId="reviewer",expiresAt="2099-01-01T00:00:00Z";
  const judgment={kind:"human_judgment" as const,assessment:"unknown" as const,explanation:"The native observation alone cannot establish this judgment",evidenceKeys:[]};
  const assessment:FinishDecisionOutcomeReview={expectedRevision:2,result:state==="completed"?"completed":"inconclusive",lessonSummary:"Better observed completion does not prove the decision's causal effect or process quality",
    assessments:{decisionProcessQuality:{...judgment,assessment:"supported",explanation:"The human considered uncertainty and recorded the expected range before choosing"},assumptionAccuracy:judgment,executionFidelity:{...judgment,assessment:"supported",explanation:"The native effects completed; that alone is not business success",evidenceKeys:["native_execution"]},externalChange:judgment,observedOutcome:{...judgment,assessment:"supported",explanation:"The later native observation is above the human expected range",evidenceKeys:["actual:outcome_1"]},causalConfidence:{assessment:"association_only",explanation:"No identification design isolates the effect of this decision"}},
    actualMetrics:[{key:"outcome_1",source:{type:"metric_observation",id:id(11),metricId:id(6),metricVersionId:id(7)}}],metricOutcomes:[{expectationIndex:0,actualEvidenceKey:"outcome_1"}],qualitativeOutcomes:[],assumptionOutcomes:[{key:"capacity",kind:"human_judgment",assessment:"inconclusive",explanation:"Delivery capacity was not independently validated against external change",evidenceKeys:[]}]};
  const initial={revision:1,action:"schedule" as const,fromState:null,toState:"scheduled" as const,rationale:"The human schedules assessment of the frozen chosen expectations",recordedBy:userId,recordedAt:"2026-10-07T01:05:00Z",contextHash:"a".repeat(64),contentHash:"d".repeat(64),assessment:null,actualEvidence:[],comparisons:[],nativeExecution:null,expiresAt};
  const begun={...initial,revision:2,action:"begin" as const,fromState:"scheduled" as const,toState:"in_review" as const,rationale:"The human begins the separate outcome review",recordedAt:"2027-01-02T00:00:00Z"};
  const terminal=["completed","inconclusive"].includes(state);
  const finalReceipt=terminal?{...initial,revision:3,action:"finish" as const,fromState:"in_review" as const,toState:state as "completed"|"inconclusive",rationale:assessment.lessonSummary,recordedAt:"2027-01-02T00:05:00Z",assessment,nativeExecution:{status:"succeeded",capturedAt:"2027-01-02T00:05:00Z"},
    actualEvidence:[{key:"outcome_1",source:assessment.actualMetrics[0].source,sourceHash:"e".repeat(64),capturedAt:"2027-01-02T00:05:00Z",expiresAt,facts:{value:1,status:"observed",unit:"ratio",from:definition.timeHorizon.from,until:definition.timeHorizon.until,asOf:"2027-01-02T00:00:00Z"},limitations:["Presentation fixture only; no live measurement qualification"]}],
    comparisons:[{expectationIndex:0,baselineEvidenceKey:"baseline",actualEvidenceKey:"outcome_1",metricId:id(6),metricVersionId:id(7),unit:"ratio",baselineValue:0.5,actualValue:1,expectedRange:{lower:0.6,upper:0.8},rangePosition:"above" as const,observedDirection:"increase" as const,expectedDirection:"increase" as const,limitations:["Human expected range, not a calibrated prediction interval","Before/after association does not identify this decision's effect","Native created-object cohorts can differ between windows"]}]}:null;
  const cancelled={...initial,revision:2,action:"cancel" as const,fromState:"scheduled" as const,toState:"cancelled" as const,rationale:"The human explicitly cancels this outcome review"};
  const receipts=finalReceipt?[finalReceipt,begun,initial]:state==="in_review"?[begun,initial]:state==="cancelled"?[cancelled,initial]:[initial];
  return {id:id(12),companyId,decisionId,contextVersionId:versionId,contextHash:"a".repeat(64),optionId:"extend",revision:receipts.length,status:state,reviewDueAt:"2027-01-02T00:00:00Z",reviewedAt:terminal?"2027-01-02T00:05:00Z":null,reviewedByUserId:terminal?userId:null,receipts,causalClaimRef:null,learningCycleId:null,authorizationCheckedAt:"2026-10-07T00:00:00Z"};
}
