import type { PortfolioPlanningPreview, PortfolioPlanningProfile } from "@paperclipai/shared";
import type { InitiativePlanningControls, InitiativePlanningDetail } from "@/api/cross-project-planning";
import { jointPlanningFixture } from "./cross-project-planning-fixtures";
// Synthetic presentation prerequisites only. Native owner/browser evidence is separate.
export function initiativePlanningFixture(stale = false) {
  const f = jointPlanningFixture(), id = "00000000-0000-4000-8000-000000002404";
  const profile: PortfolioPlanningProfile = { ...f.profile, initiatives: f.sources.map((source, index) => ({ projectId: source.projectId, mandatoryCommitment: false, protectedCommitment: false, preference: "eligible", dimensions: { strategic_alignment: 10 - index, declared_value: null, declared_risk: null }, estimatedBilledCostCents: 40, rationale: "Human declares uncertain initiative dimensions and costs for independent review" })), initiativePolicy: { mandatoryCommitmentsFirst: true, orderBy: [{ key: "strategic_alignment", direction: "maximize" }], minimumDimensions: [{ key: "strategic_alignment", minimum: 5 }], requireActiveGoal: true, maxSelectedActiveProjects: 2 } };
  const response: PortfolioPlanningPreview = { snapshotHash: "3".repeat(64), capturedAt: f.detail.context.capturedAt, expiresAt: f.response.expiresAt, authority: "human_initiative_review_required", currentSources: { projects: f.sources.map(source => ({ id: source.projectId, status: "backlog", paused: false, taskKeys: source.tasks.map(task => task.id), activeGoalIds: [] })), budgets: [] }, result: { provider: { key: "aw_native_constraints", version: "1" }, optimality: "not_proven", candidates: f.sources.map(source => ({ projectId: source.projectId, disposition: "start", reasons: ["native_constraints_feasible"] })), selectedProjectIds: f.sources.map(source => source.projectId), schedule: f.result, resultHash: "4".repeat(64), authority: "human_initiative_review_required", limitations: ["Synthetic software presentation fixture; no native authority or trial claimed"] } };
  const detail: InitiativePlanningDetail = { id, companyId: f.companyId, status: "proposed", revision: 1, context: f.detail.context, initiativeContext: { ...response, profile, jointSnapshotHash: f.response.snapshotHash, sourcePins: { goalIds: [], goalsHash: "5".repeat(64), associationsHash: "6".repeat(64), accountingHash: "7".repeat(64) } }, contextHash: "8".repeat(64), reason: "Human proposes the exact initiative assumptions for separate native review", appliedProjectRefs: [], currentQualification: stale ? "needs_revalidation" : "current" };
  const controls: InitiativePlanningControls = { items: [{ id, status: "proposed", revision: 1 }], nextCursor: null, coverage: "bounded_native_initiative_proposal_metadata" };
  return { ...f, id, profile, response, detail, controls };
}
