import { instanceExperimentalSettingsSchema, type ManagementReviewDefinition, type ManagementReviewView, type CapturedManagementSource, type Goal } from "@paperclipai/shared";
import { causalFixture } from "./causal-claim-fixtures";
/** Cached synthetic presentation only. These hashes and facts are not owner
 * receipts, collected management evidence or a business-impact qualification. */
export function managementFixture(stale = false, published = false) {
  const f = causalFixture(), id = "00000000-0000-4000-8000-000000002301", goalId = "00000000-0000-4000-8000-000000002302", at = "2026-10-07T00:00:00.000Z", expiry = "2099-10-08T00:00:00.000Z";
  const policy = structuredClone(f.policy); policy.obligation.citation = "Approved synthetic review purpose"; policy.obligation.analyticalPurpose!.capabilities = ["reviews"];
  const goal: Goal = { id: goalId, companyId: f.companyId, title: "Review onboarding evidence", description: null, level: "company", status: "active", parentId: null, ownerAgentId: null, createdAt: new Date(at), updatedAt: new Date(at) };
  const definition: ManagementReviewDefinition = { name: "Weekly onboarding evidence review", reviewType: "weekly_leadership", period: { from: "2026-10-01T00:00:00.000Z", until: at }, purpose: "management_intelligence", sensitivity: "internal", retentionDays: 30, governanceObligationRefs: [policy.id], sources: [{ key: "source_1", source: { kind: "canonical", reference: { type: "goal", id: goalId } } }], agenda: [{ key: "agenda_1", category: "INVESTIGATE", ownerUserId: f.userId, dueAt: "2099-10-08T00:00:00.000Z", sourceKeys: ["source_1"], nextAction: "Inspect the current onboarding blockers before proposing any canonical change.", hypothesis: "The handoff delay may relate to review timing; this is an unverified human hypothesis." }] };
  const sources: CapturedManagementSource[] = [{ key: "source_1", source: definition.sources[0].source, sourceHash: "a".repeat(64), capturedAt: at, expiresAt: expiry, grade: "native_current_state", facts: { title: goal.title, status: "active", level: "company", measuredEffect: null }, limitations: ["Synthetic presentation only; no collected source evidence or measured business impact."] }];
  const review: ManagementReviewView = { id, companyId: f.companyId, status: published ? "published" : "draft", definition, sources, packet: { engineVersion: "aw-native-management-skeleton-v1", definitionHash: "b".repeat(64), inputHash: "c".repeat(64), contentHash: "d".repeat(64), asOf: at, period: definition.period, claims: sources.map(source => ({ key: `claim_${source.key}`, sourceKeys: [source.key], grade: source.grade, facts: source.facts, limitations: source.limitations })), agenda: definition.agenda.map(item => ({ ...item, interpretation: "human_declared_agenda", hypothesisAuthority: "human_hypothesis" })), coverage: "explicit_selected_native_sources", limitations: ["Human proposed actions grant no execution or approval authority."], executionAuthority: "read_only_historical_review" }, createdBy: f.userId, createdAt: at, expiresAt: expiry, publishedBy: published ? f.userId : null, publishedAt: published ? at : null, currentQualification: stale ? "needs_revalidation" : "current", events: published ? [{ id: "00000000-0000-4000-8000-000000002303", itemKey: "agenda_1", event: "false_alarm", rationale: "Human reports a corrected interpretation of the synthetic review item.", recordedBy: f.userId, recordedAt: at, ordinal: 1, interpretation: "human_reported_event" }] : [] };
  const controls = { items: [{ id, status: review.status, createdAt: at, expiresAt: expiry }], nextCursor: null, coverage: "bounded_native_review_metadata" as const };
  const flags = instanceExperimentalSettingsSchema.parse({ enableFoundationV1: true, analytical_lineage_v8: true, business_metrics_v8: true, management_reviews_v8: true, ai_use_cases_v7: true, governance_evidence_v7: true });
  return { companyId: f.companyId, userId: f.userId, id, goal, policy, definition, review, controls, flags };
}
