import { roadmapPolicySchema, instanceExperimentalSettingsSchema, type ProjectRoadmap, type ProjectPlanningProfile, type NativePlanningResult } from "@paperclipai/shared";
import type { ProjectPlanningDetail } from "@/api/adaptive-planning";
import { causalFixture } from "./causal-claim-fixtures";
export function planningFixture(stale = false) {
 const f = causalFixture(), projectId = "00000000-0000-4000-8000-000000002201", id = "00000000-0000-4000-8000-000000002202", taskId = "00000000-0000-4000-8000-000000002203", updatedAt = "2026-10-07T00:00:00.000Z";
 const roadmap: ProjectRoadmap = {companyId:f.companyId,projectId,projectName:"Synthetic planning presentation",projectUpdatedAt:updatedAt,policy:roadmapPolicySchema.parse({}),tasks:[{id:taskId,title:"Prepare source evidence",identifier:"SYN-1",status:"todo",updatedAt,assigneeAgentId:null,assigneeUserId:null,milestoneId:null,plannedStartAt:null,plannedEndAt:null,forecastStartAt:null,forecastEndAt:null,forecastConfidence:null,forecastReason:null,startedAt:null,completedAt:null,estimatedEffortMinutes:null}],milestones:[],dependencies:[],baselines:[],proposals:[],health:{status:"unknown",facts:[],observedAt:updatedAt}};
 const policy = structuredClone(f.policy); policy.obligation.analyticalPurpose!.capabilities = ["planning"];
 const profile: ProjectPlanningProfile = {purpose:"management_intelligence",sensitivity:"internal",retentionDays:1,governanceObligationRefs:[policy.id],horizon:{start:"2099-10-08",days:14},pools:[{key:"declared_project_capacity",days:Array.from({length:14},()=>({availableMinutes:480,committedMinutes:60}))}],policy:{mandatoryCommitmentsFirst:false,orderBy:[],paretoDimensions:[]},tasks:[{key:taskId,expectedUpdatedAt:updatedAt,durationDays:2,releaseDay:0,deadlineDay:null,demands:[{poolKey:"declared_project_capacity",minutesPerDay:120}],mandatoryCommitment:false,dimensions:{declared_order:null,declared_learning_value:null,declared_effort:240},rationale:"Human supplied synthetic assumptions; no business-impact claim"}],evidence:[]};
 const result: NativePlanningResult = {provider:{key:"aw_native_constraints",version:"1"},status:"feasible_best_known",optimality:"not_proven",inputHash:"1".repeat(64),resultHash:"2".repeat(64),schedule:[{taskKey:taskId,startDay:0,endDay:2}],criticalPath:{taskKeys:[taskId],earliestCompletionDay:2},pareto:{status:"not_requested",taskKeys:[]},diagnostics:[],objective:profile.policy,limits:{tasks:200,dependencies:2000,horizonDays:366,pools:32,paretoCandidates:32,operations:5000000},limitations:["Synthetic cached presentation only; no collected evidence or business impact."]};
 const response={snapshotHash:"3".repeat(64),result,runtimeMs:1,capturedAt:updatedAt,expiresAt:"2099-10-09T00:00:00.000Z",authority:"human_roadmap_review_required" as const};
 const detail: ProjectPlanningDetail = {id,companyId:f.companyId,projectId,status:"pending",reason:"Human proposes synthetic UTC dates for independent review",contextHash:"4".repeat(64),currentQualification:stale?"needs_revalidation":"current",context:{...response,profile,sourceSnapshot:{projectId,projectUpdatedAt:updatedAt,roadmapPolicy:roadmap.policy,tasks:roadmap.tasks.map(t=>({id:t.id,updatedAt:t.updatedAt,status:t.status,plannedStartAt:t.plannedStartAt,plannedEndAt:t.plannedEndAt,estimatedEffortMinutes:t.estimatedEffortMinutes,milestoneId:t.milestoneId,assigneeAgentId:t.assigneeAgentId,assigneeUserId:t.assigneeUserId})),dependencies:[],satisfiedDependencies:[]},evidence:[]}};
 const flags=instanceExperimentalSettingsSchema.parse({enableFoundationV1:true,analytical_lineage_v8:true,business_metrics_v8:true,strategy_execution_v8:true,adaptive_planning_v8:true,planning_optimizer_v8:true,ai_use_cases_v7:true,governance_evidence_v7:true});
 return {companyId:f.companyId,userId:f.userId,projectId,id,taskId,roadmap,policy,profile,result,response,detail,flags};
}
